"use server";
import{revalidatePath}from"next/cache";import{addFavorite}from"@/lib/studio/quick-access/quick-access-repository";import{listEntityTags,setEntityTags}from"@/lib/studio/tags/tag-assignment-repository";import{attachRenderFile,createRenderCategory,setHeroRender,setRenderFlags,updateRender,updateRenderCategory}from"@/lib/studio/renders/render-repository";import{sendRenderWhatsApp}from"@/lib/studio/renders/render-whatsapp-service";
const path=(id:string)=>`/studio/projects/${id}/renders`;async function run(projectId:string,work:()=>Promise<unknown>,message:string){try{await work();revalidatePath(path(projectId));return{success:true,message};}catch(error){return{success:false,message:error instanceof Error&&error.message==="whatsapp_opt_in_required"?"WhatsApp bildirim izni bulunmuyor.":error instanceof Error&&error.message==="customer_phone_missing"?"WhatsApp telefon numarası bulunmuyor.":"İşlem şu anda tamamlanamadı."};}}
export async function createRenderCategoryAction(projectId:string,formData:FormData){await run(projectId,()=>createRenderCategory(projectId,String(formData.get("name")??"")),"Kategori eklendi.");}
export async function updateRenderCategoryAction(projectId:string,id:string,formData:FormData){return run(projectId,()=>updateRenderCategory(projectId,id,String(formData.get("name")??""),formData.get("archived")==="1"),"Kategori güncellendi.");}
export async function attachRenderFileAction(projectId:string,formData:FormData){const category=String(formData.get("categoryId")??"");await run(projectId,()=>attachRenderFile(projectId,String(formData.get("fileId")??""),category||null),"Render arşive eklendi.");}
export async function updateRenderAction(projectId:string,id:string,formData:FormData){const number=(key:string)=>{const value=String(formData.get(key)??"");return value?Number(value):null};return run(projectId,()=>updateRender(projectId,id,{title:String(formData.get("title")??""),description:String(formData.get("description")??""),categoryId:String(formData.get("categoryId")??"")||null,width:number("width"),height:number("height")}),"Render güncellendi.");}
export async function setHeroRenderAction(projectId:string,id:string){return run(projectId,()=>setHeroRender(projectId,id),"Kapak renderı güncellendi.");}
export async function setRenderFlagsAction(projectId:string,ids:string[],input:{clientVisible?:boolean;presented?:boolean;archived?:boolean}){return run(projectId,()=>setRenderFlags(projectId,ids,input),"Seçili renderlar güncellendi.");}
export async function favoriteRenderFilesAction(projectId:string,fileIds:string[]){return run(projectId,()=>Promise.all([...new Set(fileIds)].slice(0,50).map(id=>addFavorite("file",id))),"Seçili renderlar favorilere eklendi.");}
export async function tagRenderFilesAction(projectId:string,fileIds:string[],tagIds:string[]){return run(projectId,()=>Promise.all([...new Set(fileIds)].slice(0,50).map(async id=>{const current=await listEntityTags("file",id);await setEntityTags("file",id,[...new Set([...current.map(tag=>tag.id),...tagIds])]);})),"Etiketler güncellendi.");}
export async function sendRenderWhatsAppAction(projectId:string,id:string,message:string){return run(projectId,()=>sendRenderWhatsApp(projectId,id,message),"Render WhatsApp ile gönderildi.");}
export async function sendRenderBulkWhatsAppAction(projectId:string,items:Array<{id:string;message:string}>){const safe=items.slice(0,10);let sent=0,failed=0;for(const item of safe){try{await sendRenderWhatsApp(projectId,item.id,item.message);sent++}catch{failed++}}revalidatePath(path(projectId));return{success:failed===0,message:failed?`${sent} render gönderildi, ${failed} render gönderilemedi.`:`${sent} render WhatsApp ile gönderildi.`};}
