import Link from "next/link";
import StudioLeadArchiveControl from "@/components/studio/crm/StudioLeadArchiveControl";
import {StudioLeadStageBadge,StudioLeadStatusBadge} from "@/components/studio/crm/StudioLeadBadge";
import type {StudioLead} from "@/lib/studio/crm/lead-types";
import type {StudioQuote} from "@/lib/studio/quotes/quote-types";

function budget(lead:StudioLead){return lead.budgetAmount?new Intl.NumberFormat("tr-TR",{style:"currency",currency:lead.budgetCurrency}).format(Number(lead.budgetAmount)):"Belirtilmedi";}
function Item({label,value}:{label:string;value:string}){return <div className="min-w-0"><dt className="text-[8px] uppercase tracking-[.12em] text-[#aaa79f]">{label}</dt><dd className="mt-1.5 break-words text-[11px] text-[#414a4f]">{value||"Belirtilmedi"}</dd></div>;}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><h2 className="border-b border-[#ece9e3] pb-4 text-[13px] font-semibold text-[#2d353b]">{title}</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{children}</dl></section>;}
export default function StudioLeadDetail({lead,quotes}:{lead:StudioLead;quotes:StudioQuote[]}){return <section className="mx-auto min-w-0 max-w-[1280px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8 lg:py-9">
 <header className="rounded-xl border border-[#d9d4ca] bg-white p-5 shadow-[0_5px_24px_rgba(30,38,45,.04)] sm:p-7"><Link href="/studio/crm" className="text-[9px] font-medium uppercase tracking-[.14em] text-[#8e784d] outline-none focus-visible:ring-2 focus-visible:ring-[#a58a56]/25">← CRM’e Dön</Link><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="min-w-0"><div className="flex flex-wrap gap-2"><StudioLeadStageBadge stage={lead.stage}/><StudioLeadStatusBadge status={lead.status}/>{lead.isArchived?<span className="rounded-full border border-[#dfcbc0] bg-[#f8f0ec] px-2.5 py-1 text-[9px] text-[#8c604e]">Arşiv</span>:null}</div><h1 className="mt-4 break-words text-[28px] font-semibold tracking-[-.04em] text-[#1f2930]">{lead.fullName}</h1><p className="mt-2 text-[11px] text-[#777b78]">{lead.companyName||"Bireysel müşteri"} · {lead.serviceType}</p></div>{lead.canManage?<div className="flex flex-wrap gap-2">{!lead.isArchived?<><Link href={`/studio/quotes/new?leadId=${lead.id}`} className="grid h-10 place-items-center rounded-lg border border-[#d5d0c6] px-4 text-[10px] text-[#555e61]">Teklif Oluştur</Link><Link href={`/studio/crm/${lead.id}/edit`} className="grid h-10 place-items-center rounded-lg bg-[#18222d] px-4 text-[10px] font-semibold text-white outline-none focus-visible:ring-2 focus-visible:ring-[#9e8452]/40">Düzenle</Link></>:null}<StudioLeadArchiveControl leadId={lead.id} archived={lead.isArchived}/></div>:null}</div></header>
 <div className="mt-5 grid min-w-0 gap-5 lg:grid-cols-2"><Card title="İletişim"><Item label="Telefon" value={lead.phone}/><Item label="E-posta" value={lead.email}/></Card><Card title="Konum"><Item label="Şehir" value={lead.city}/><Item label="İlçe" value={lead.district}/></Card><Card title="Hizmet"><Item label="Hizmet Tipi" value={lead.serviceType}/><Item label="Tahmini Bütçe" value={budget(lead)}/><Item label="Kaynak" value={lead.source}/></Card><Card title="Süreç"><Item label="Sorumlu" value={lead.assignedUser?.name||""}/><Item label="Son Görüşme" value={lead.lastContactLabel}/><Item label="Sonraki Takip" value={lead.nextFollowUpLabel}/></Card>
 <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6 lg:col-span-2"><h2 className="text-[13px] font-semibold text-[#2d353b]">Notlar</h2><p className="mt-4 whitespace-pre-wrap break-words text-[11px] leading-6 text-[#5f6666]">{lead.notes||"Bu lead için not eklenmemiş."}</p></section>
 <Card title="Kayıt Bilgileri"><Item label="Oluşturulma" value={lead.createdAtLabel}/><Item label="Güncellenme" value={lead.updatedAtLabel}/></Card><section className="rounded-xl border border-[#dedad1] bg-white p-6"><h2 className="text-[13px] font-semibold text-[#30393f]">Bu Lead’e Ait Teklifler</h2>{quotes.length?<div className="mt-4 space-y-2">{quotes.slice(0,4).map(quote=><Link key={quote.id} href={`/studio/quotes/${quote.id}`} className="flex items-center justify-between gap-3 rounded-lg border border-[#e7e3dc] px-3 py-2 text-[9px]"><span className="truncate">{quote.quoteNumber} · {quote.title}</span><span>{quote.status}</span></Link>)}</div>:<p className="mt-3 text-[10px] text-[#7d817d]">Bu lead için henüz teklif oluşturulmadı.</p>}</section></div>
 </section>;}
