"use client";

import Link from "next/link";
import {useActionState,useState} from "react";
import StudioAiWritingDialog from "@/components/studio/ai/StudioAiWritingDialog";
import {DEFAULT_LEAD_VALUES,LEAD_CURRENCIES,LEAD_SERVICE_TYPES,LEAD_SOURCES,LEAD_STAGES,LEAD_STATUSES} from "@/lib/studio/crm/lead-constants";
import type {LeadFormState,LeadFormValues,StudioLeadMember} from "@/lib/studio/crm/lead-types";
import {StudioPendingLabel,studioButtonClass} from "@/components/studio/StudioButton";

type Action=(state:LeadFormState,formData:FormData)=>Promise<LeadFormState>;
const emptyValues:LeadFormValues={firstName:"",lastName:"",companyName:"",phone:"",email:"",city:"",district:"",
 serviceType:DEFAULT_LEAD_VALUES.serviceType,budgetAmount:"",budgetCurrency:DEFAULT_LEAD_VALUES.budgetCurrency,source:DEFAULT_LEAD_VALUES.source,
 stage:DEFAULT_LEAD_VALUES.stage,status:DEFAULT_LEAD_VALUES.status,notes:"",assignedUserId:"",lastContactAt:"",nextFollowUpAt:""};
const inputClass="studio-field mt-2 w-full min-w-0 rounded-lg border border-[#ddd8ce] bg-[#fbfaf7] px-4 text-[#343b40] outline-none placeholder:text-[#92958f] focus:border-[#a58a56] focus:ring-2 focus:ring-[#a58a56]/15 aria-[invalid=true]:border-[#a56650]";
function Field({name,label,state,type="text",required,placeholder,min,step}:{name:keyof LeadFormValues;label:string;state:LeadFormState;type?:string;required?:boolean;placeholder?:string;min?:string;step?:string}){
 const error=state.fieldErrors?.[name]?.[0];return <label className="block min-w-0"><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">{label}{required?" *":""}</span><input name={name} type={type} required={required} placeholder={placeholder} min={min} step={step} defaultValue={state.values?.[name]??emptyValues[name]} aria-invalid={Boolean(error)} aria-describedby={error?`${name}-error`:undefined} className={inputClass}/>{error?<span id={`${name}-error`} className="mt-1.5 block text-[9px] text-[#9b5d48]">{error}</span>:null}</label>;
}
function Select({name,label,state,options,empty}:{name:keyof LeadFormValues;label:string;state:LeadFormState;options:readonly string[];empty?:string}){
 const error=state.fieldErrors?.[name]?.[0];return <label className="block min-w-0"><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">{label}</span><select name={name} defaultValue={state.values?.[name]??emptyValues[name]} aria-invalid={Boolean(error)} aria-describedby={error?`${name}-error`:undefined} className={inputClass}>{empty?<option value="">{empty}</option>:null}{options.map(value=><option key={value} value={value}>{value}</option>)}</select>{error?<span id={`${name}-error`} className="mt-1.5 block text-[9px] text-[#9b5d48]">{error}</span>:null}</label>;
}
function Section({title,description,children}:{title:string;description?:string;children:React.ReactNode}){return <section className="studio-card"><div className="border-b border-[#ece9e3] pb-4"><h2 className="studio-section-title">{title}</h2>{description?<p className="studio-helper-text mt-2">{description}</p>:null}</div><div className="mt-6 grid gap-6 sm:grid-cols-2">{children}</div></section>;}
export default function StudioLeadForm({action,initialValues,members,mode,leadId}:{action:Action;initialValues?:LeadFormValues;members:StudioLeadMember[];mode:"create"|"edit";leadId?:string}){
 const[state,formAction,pending]=useActionState(action,{success:false,values:initialValues??emptyValues});
 const[notes,setNotes]=useState(initialValues?.notes??"");
 return <form action={formAction} className="space-y-5">
  {state.message?<div role="alert" className="rounded-lg border border-[#decfc7] bg-[#f8f1ee] px-4 py-3 text-[10px] text-[#875b4b]">{state.message}</div>:null}
  <Section title="Kişisel Bilgiler" description="Lead ile doğrudan iletişim kurmak için temel bilgiler"><Field name="firstName" label="Ad" state={state} required/><Field name="lastName" label="Soyad" state={state}/><Field name="phone" label="Telefon" state={state} required/><Field name="email" label="E-posta" state={state} type="email"/><Field name="companyName" label="Firma Adı" state={state}/></Section>
  <Section title="Konum"><Field name="city" label="Şehir" state={state}/><Field name="district" label="İlçe" state={state}/></Section>
  <Section title="Hizmet ve Bütçe"><Select name="serviceType" label="Hizmet Tipi" state={state} options={LEAD_SERVICE_TYPES}/><Select name="source" label="Lead Kaynağı" state={state} options={LEAD_SOURCES}/><Field name="budgetAmount" label="Tahmini Bütçe" state={state} type="number" min="0" step="0.01"/><Select name="budgetCurrency" label="Para Birimi" state={state} options={LEAD_CURRENCIES}/></Section>
  <Section title="Süreç" description="Kapandı durumu yalnız Kazanıldı veya Kaybedildi aşamasıyla kullanılabilir."><Select name="stage" label="Aşama" state={state} options={LEAD_STAGES}/><Select name="status" label="Durum" state={state} options={LEAD_STATUSES}/><label className="block min-w-0"><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">Sorumlu Kullanıcı</span><select name="assignedUserId" defaultValue={state.values?.assignedUserId??""} aria-invalid={Boolean(state.fieldErrors?.assignedUserId)} aria-describedby={state.fieldErrors?.assignedUserId?"assignedUserId-error":undefined} className={inputClass}><option value="">Atanmadı</option>{members.map(member=><option key={member.id} value={member.id}>{member.name} · {member.role}</option>)}</select>{state.fieldErrors?.assignedUserId?.[0]?<span id="assignedUserId-error" className="mt-1.5 block text-[9px] text-[#9b5d48]">{state.fieldErrors.assignedUserId[0]}</span>:null}</label><Field name="lastContactAt" label="Son Görüşme" state={state} type="datetime-local"/><Field name="nextFollowUpAt" label="Sonraki Takip" state={state} type="datetime-local"/></Section>
  <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-sm font-semibold uppercase tracking-[.08em] text-[#777a75]">Notlar</span><StudioAiWritingDialog operation="crm_ai_meeting_note" title="AI Görüşme Notu" triggerLabel="AI ile Görüşme Notu Oluştur" currentText={notes} allowFormat context={{customerName:[initialValues?.firstName,initialValues?.lastName].filter(Boolean).join(" "),companyName:initialValues?.companyName??"",serviceType:initialValues?.serviceType??"",nextFollowUpAt:initialValues?.nextFollowUpAt??"",responsibleUser:initialValues?.assignedUserId??"",currentNote:notes}} onUse={setNotes}/></div><label className="mt-3 block"><span className="sr-only">Notlar</span><textarea name="notes" rows={6} maxLength={10000} value={notes} onChange={event=>setNotes(event.target.value)} aria-invalid={Boolean(state.fieldErrors?.notes)} aria-describedby={state.fieldErrors?.notes?"notes-error":undefined} className="mt-2 w-full resize-y rounded-lg border border-[#ddd8ce] bg-[#fbfaf7] px-3 py-3 text-[15px] leading-6 text-[#343b40] outline-none focus:border-[#a58a56] focus:ring-2 focus:ring-[#a58a56]/15"/>{state.fieldErrors?.notes?.[0]?<span id="notes-error" className="mt-1.5 block text-[9px] text-[#9b5d48]">{state.fieldErrors.notes[0]}</span>:null}</label></section>
  <div className="flex flex-col-reverse gap-3 border-t border-[#dcd7cd] pt-5 sm:flex-row sm:justify-end"><Link href={leadId?`/studio/crm/${leadId}`:"/studio/crm"} className={studioButtonClass("outline")}>Vazgeç</Link><button type="submit" disabled={pending} aria-busy={pending} className={studioButtonClass("primary")}><StudioPendingLabel pending={pending} pendingLabel={mode==="create"?"Lead Oluşturuluyor...":"Değişiklikler Kaydediliyor..."}>{mode==="create"?"Lead Oluştur":"Değişiklikleri Kaydet"}</StudioPendingLabel></button></div>
 </form>;
}
