import "server-only";
import {getStudioContext}from"@/lib/studio/auth/get-studio-context";
import {createStudioServerClient}from"@/lib/studio/supabase/server";
import {OFFICIAL_PROCESS_STATUSES,RESPONSIBLE_PARTIES,STATUS_LABELS,type OfficialProcess,type OfficialProcessStatus,type ResponsibleParty}from"./official-process-types";
const select="id,project_id,entity_type,fee_type,title,status,amount,due_date,responsible_party,description,is_client_visible,client_notified_at,assessment_file_id,receipt_file_id,received_document_file_id,created_at,updated_at";
async function context(owner=false){const c=await getStudioContext();if(!c?.user||!c.membership)throw new Error("unauthorized");if(owner&&c.membership.role!=="owner")throw new Error("forbidden");return{userId:c.user.id,organizationId:c.membership.organization_id};}
function map(row:Record<string,unknown>):OfficialProcess{return{id:String(row.id),projectId:String(row.project_id),entityType:row.entity_type as OfficialProcess["entityType"],feeType:row.fee_type as string|null,title:String(row.title),status:row.status as OfficialProcessStatus,amount:row.amount===null?null:Number(row.amount),dueDate:row.due_date as string|null,responsibleParty:row.responsible_party as ResponsibleParty,description:row.description as string|null,isClientVisible:Boolean(row.is_client_visible),clientNotifiedAt:row.client_notified_at as string|null,assessmentFileId:row.assessment_file_id as string|null,receiptFileId:row.receipt_file_id as string|null,receivedDocumentFileId:row.received_document_file_id as string|null,createdAt:String(row.created_at),updatedAt:String(row.updated_at),isOverdue:Boolean(row.due_date)&&!['paid','document_received','cancelled'].includes(String(row.status))&&String(row.due_date)<new Date().toISOString().slice(0,10),events:[]};}
export async function listOfficialProcesses(projectId:string){const c=await context();const db=await createStudioServerClient();const{data,error}=await db.from("studio_project_obligations").select(select).eq("organization_id",c.organizationId).eq("project_id",projectId).eq("is_archived",false).order("entity_type").order("created_at");if(error)throw error;const items=(data??[]).map(row=>map(row as Record<string,unknown>));if(!items.length)return items;const{data:events}=await db.from("studio_project_obligation_events").select("id,obligation_id,title,created_at").eq("organization_id",c.organizationId).eq("project_id",projectId).order("created_at",{ascending:false});for(const item of items)item.events=(events??[]).filter(e=>e.obligation_id===item.id).slice(0,5).map(e=>({id:e.id,title:e.title,createdAt:e.created_at}));return items;}
export async function listOfficialProcessDocuments(projectId:string){const c=await context();const db=await createStudioServerClient();const{data,error}=await db.from("studio_project_files").select("id,display_name,extension").eq("organization_id",c.organizationId).eq("project_id",projectId).eq("status","ready").eq("is_archived",false).in("extension",["pdf","jpg","jpeg","png"]).order("display_name");if(error)throw error;return(data??[]).map(row=>({id:row.id as string,name:row.display_name as string}));}
export async function initializeOfficialProcesses(projectId:string){await context(true);const db=await createStudioServerClient();const{error}=await db.rpc("studio_initialize_project_obligations",{target_project_id:projectId});if(error)throw error;}
export async function updateOfficialProcess(id:string,input:{status:string;amount:string;dueDate:string;responsibleParty:string;description:string;isClientVisible:boolean;assessmentFileId:string|null;receiptFileId:string|null;receivedDocumentFileId:string|null}){const c=await context(true);if(!OFFICIAL_PROCESS_STATUSES.includes(input.status as OfficialProcessStatus)||!RESPONSIBLE_PARTIES.includes(input.responsibleParty as ResponsibleParty))throw new Error("validation");if(input.status==="document_received"&&!input.receivedDocumentFileId)throw new Error("document_required");const db=await createStudioServerClient();const{data,error}=await db.from("studio_project_obligations").update({status:input.status,amount:input.amount?Number(input.amount):null,due_date:input.dueDate||null,responsible_party:input.responsibleParty,description:input.description.trim()||null,is_client_visible:input.isClientVisible,assessment_file_id:input.assessmentFileId,receipt_file_id:input.receiptFileId,received_document_file_id:input.receivedDocumentFileId,updated_by:c.userId}).eq("organization_id",c.organizationId).eq("id",id).select("project_id").single();if(error)throw error;return data.project_id as string;}
export async function createCustomFee(projectId:string,title:string){const c=await context(true);if(!title.trim()||title.trim().length>160)throw new Error("validation");const db=await createStudioServerClient();const{error}=await db.from("studio_project_obligations").insert({organization_id:c.organizationId,project_id:projectId,entity_type:"fee",fee_type:"custom",title:title.trim(),created_by:c.userId,updated_by:c.userId});if(error)throw error;}
export async function archiveCustomFee(id:string){const c=await context(true);const db=await createStudioServerClient();const{data,error}=await db.from("studio_project_obligations").update({is_archived:true,updated_by:c.userId}).eq("organization_id",c.organizationId).eq("id",id).eq("fee_type","custom").select("project_id").single();if(error)throw error;return data.project_id as string;}
export async function notifyOfficialProcess(id:string){const c=await context(true);const db=await createStudioServerClient();const{data:item,error}=await db.from("studio_project_obligations").select("id,project_id,title,due_date,assessment_file_id").eq("organization_id",c.organizationId).eq("id",id).single();if(error)throw error;if(!item.assessment_file_id)throw new Error("assessment_required");const date=item.due_date?new Intl.DateTimeFormat("tr-TR").format(new Date(item.due_date)):"Belirtilmedi";const message=`Merhaba.\n\nProjenize ait ${item.title} tahakkuku hazırlanmıştır.\n\nSon ödeme tarihi:\n${date}\n\nTahakkuk belgesi sisteme yüklenmiştir.\n\nÖdeme tamamlandıktan sonra dekont paylaşabilirsiniz.\n\nARZ Mimarlık`;const{error:notificationError}=await db.from("studio_project_obligation_notifications").insert({organization_id:c.organizationId,project_id:item.project_id,obligation_id:id,message_snapshot:message,created_by:c.userId});if(notificationError)throw notificationError;const{error:updateError}=await db.from("studio_project_obligations").update({status:"client_notified",client_notified_at:new Date().toISOString(),updated_by:c.userId}).eq("id",id).eq("organization_id",c.organizationId);if(updateError)throw updateError;return item.project_id as string;}
export function summarizeOfficialProcesses(items:OfficialProcess[]){const fees=items.filter(i=>i.entityType==="fee");const app=items.find(i=>i.entityType==="application");const clean=items.find(i=>i.entityType==="clean_application");return{pendingFees:fees.filter(i=>!['paid','document_received','cancelled'].includes(i.status)).length,paidFees:fees.filter(i=>['paid','document_received'].includes(i.status)).length,receivedDocuments:items.filter(i=>i.receivedDocumentFileId).length,pendingDocuments:items.filter(i=>i.status==='paid'&&!i.receivedDocumentFileId).length,overdue:items.filter(i=>i.isOverdue).length,applicationStatus:app?STATUS_LABELS[app.status]:"—",cleanApplicationStatus:clean?STATUS_LABELS[clean.status]:"—"};}
