"use server";import{revalidatePath}from"next/cache";import{createCustomProjectStage,sendStageNotification}from"@/lib/studio/notifications/notification-repository";import{archiveStage,attachStageFile,duplicateStage,reorderStage,updateFlexibleStage,updateStageFile}from"@/lib/studio/notifications/stage-flex-repository";import type{NotificationActionState}from"@/lib/studio/notifications/notification-types";const ok=(message:string)=>({success:true,message}),fail=(message="İşlem tamamlanamadı.")=>({success:false,message}),route=(id:string)=>`/studio/projects/${id}/stages`;async function run(projectId:string,fn:()=>Promise<unknown>,message:string){try{await fn();revalidatePath(route(projectId));return ok(message)}catch{return fail()}}
export async function createStageAction(projectId:string,_:NotificationActionState,f:FormData){return run(projectId,()=>createCustomProjectStage(projectId,String(f.get("title")??"")),"Aşama eklendi.")}
export async function updateStageAction(projectId:string,id:string,_:NotificationActionState,f:FormData){try{await updateFlexibleStage(id,{title:String(f.get("title")??""),description:String(f.get("description")??""),status:String(f.get("status")??"waiting"),startedAt:String(f.get("startedAt")??""),completedAt:String(f.get("completedAt")??""),responsibleUserId:String(f.get("responsibleUserId")??""),note:String(f.get("note")??""),isActive:f.get("isActive")==="on",isClientVisible:f.get("isClientVisible")==="on"});revalidatePath(route(projectId));return ok("Aşama güncellendi.")}catch(error){const code=error instanceof Error?error.message:"";const messages:Record<string,string>={stage_start_date_invalid:"Başlangıç tarihi geçersiz.",stage_completion_date_invalid:"Tamamlanma tarihi geçersiz.",stage_date_order_invalid:"Tamamlanma tarihi başlangıç tarihinden önce olamaz."};return fail(messages[code]??"Aşama güncellenemedi.")}}
export async function duplicateStageAction(projectId:string,id:string){return run(projectId,()=>duplicateStage(id),"Aşama çoğaltıldı.")}
export async function archiveStageAction(projectId:string,id:string,archived:boolean){return run(projectId,()=>archiveStage(id,archived),archived?"Aşama arşivlendi.":"Aşama geri alındı.")}
export async function deleteStageAction(projectId:string,id:string,title:string){return run(projectId,()=>import("@/lib/studio/notifications/stage-flex-repository").then(({deleteCustomStage})=>deleteCustomStage(id,title)),"Özel aşama kalıcı olarak silindi.")}
export async function reorderStageAction(projectId:string,id:string,direction:-1|1){return run(projectId,()=>reorderStage(id,direction),"Sıra güncellendi.")}
export async function attachStageFileAction(projectId:string,id:string,_:NotificationActionState,f:FormData){return run(projectId,()=>attachStageFile(id,String(f.get("fileId")),String(f.get("role")??"other"),f.get("customerVisible")==="on"),"Dosya bağlandı.")}
export async function removeStageFileAction(projectId:string,id:string){return run(projectId,()=>updateStageFile(id,true,false),"Dosya bağlantısı kaldırıldı.")}
export async function toggleStageFileVisibilityAction(projectId:string,id:string,visible:boolean){return run(projectId,()=>updateStageFile(id,false,visible),"Dosya görünürlüğü güncellendi.")}
export async function generateStageDescriptionAction(id:string,currentDescription:string){try{const{generateAiStageDescription}=await import("@/lib/studio/notifications/stage-ai-description-service");return{success:true,...await generateAiStageDescription(id,currentDescription)}}catch{return{success:false,description:"",generatedBy:"template" as const,message:"AI açıklaması şu anda oluşturulamadı."}}}
export async function sendStageNotificationAction(projectId:string,id:string){try{const{sendStageWhatsAppDocuments}=await import("@/lib/studio/notifications/stage-whatsapp-service");const documents=await sendStageWhatsAppDocuments(id);const result=documents.sent>0?{ok:true as const}:await sendStageNotification(id);revalidatePath(route(projectId));return result.ok?ok("WhatsApp bildirimi gönderildi."):fail(result.errorCode==="whatsapp_not_configured"?"WhatsApp yapılandırılmadı.":"WhatsApp bildirimi gönderilemedi.")}catch(error){const code=error instanceof Error?error.message:"";const messages:Record<string,string>={stage_archived:"Arşivlenmiş aşamalar için WhatsApp bildirimi gönderilemez.",stage_not_sendable:"Arşivlenmiş, pasif veya tamamlanmamış aşamalar için WhatsApp bildirimi gönderilemez.",stage_not_completed:"Aşama henüz tamamlanmadı.",whatsapp_opt_in_required:"WhatsApp bildirim izni bulunmuyor.",customer_phone_missing:"WhatsApp telefon numarası bulunmuyor.",whatsapp_not_configured:"WhatsApp henüz yapılandırılmadı."};return fail(messages[code]??"WhatsApp bildirimi gönderilemedi.")}}
