"use server";import{revalidatePath}from"next/cache";import{createCustomProjectStage,sendStageNotification}from"@/lib/studio/notifications/notification-repository";import{archiveStage,attachStageFile,duplicateStage,reorderStage,updateFlexibleStage,updateStageFile}from"@/lib/studio/notifications/stage-flex-repository";import type{NotificationActionState}from"@/lib/studio/notifications/notification-types";const ok=(message:string)=>({success:true,message}),fail=(message="İşlem tamamlanamadı.")=>({success:false,message}),route=(id:string)=>`/studio/projects/${id}/stages`;async function run(projectId:string,fn:()=>Promise<unknown>,message:string){try{await fn();revalidatePath(route(projectId));return ok(message)}catch{return fail()}}
export async function createStageAction(projectId:string,_:NotificationActionState,f:FormData){return run(projectId,()=>createCustomProjectStage(projectId,String(f.get("title")??"")),"Aşama eklendi.")}
export async function updateStageAction(projectId:string,id:string,_:NotificationActionState,f:FormData){return run(projectId,()=>updateFlexibleStage(id,{title:String(f.get("title")??""),description:String(f.get("description")??""),status:String(f.get("status")??"waiting"),startedAt:String(f.get("startedAt")??""),completedAt:String(f.get("completedAt")??""),responsibleUserId:String(f.get("responsibleUserId")??""),note:String(f.get("note")??""),isActive:f.get("isActive")==="on",isClientVisible:f.get("isClientVisible")==="on"}),"Aşama güncellendi.")}
export async function duplicateStageAction(projectId:string,id:string){return run(projectId,()=>duplicateStage(id),"Aşama çoğaltıldı.")}
export async function archiveStageAction(projectId:string,id:string,archived:boolean){return run(projectId,()=>archiveStage(id,archived),archived?"Aşama arşivlendi.":"Aşama geri alındı.")}
export async function reorderStageAction(projectId:string,id:string,direction:-1|1){return run(projectId,()=>reorderStage(id,direction),"Sıra güncellendi.")}
export async function attachStageFileAction(projectId:string,id:string,_:NotificationActionState,f:FormData){return run(projectId,()=>attachStageFile(id,String(f.get("fileId")),String(f.get("role")??"other"),f.get("customerVisible")==="on"),"Dosya bağlandı.")}
export async function removeStageFileAction(projectId:string,id:string){return run(projectId,()=>updateStageFile(id,true,false),"Dosya bağlantısı kaldırıldı.")}
export async function toggleStageFileVisibilityAction(projectId:string,id:string,visible:boolean){return run(projectId,()=>updateStageFile(id,false,visible),"Dosya görünürlüğü güncellendi.")}
export async function sendStageNotificationAction(projectId:string,id:string){try{const result=await sendStageNotification(id);const{sendStageWhatsAppDocuments}=await import("@/lib/studio/notifications/stage-whatsapp-service");await sendStageWhatsAppDocuments(id);revalidatePath(route(projectId));return result.ok?ok("WhatsApp bildirimi gönderildi."):fail(result.errorCode==="whatsapp_not_configured"?"WhatsApp yapılandırılmadı.":"Bildirim gönderilemedi.")}catch(error){return fail(error instanceof Error&&error.message==="whatsapp_opt_in_required"?"WhatsApp bildirim izni bulunmuyor.":"Bildirim gönderilemedi.")}}
