"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {z} from "zod";
import {StudioFileError} from "@/lib/studio/files/file-errors";
import {createStudioProjectFolder,finalizeStudioProjectFile,finalizeGoogleDriveProjectFile,markStudioProjectFileFailed,moveStudioProjectFolder,renameStudioProjectFolder,reserveGoogleDriveProjectFile,setStudioProjectFileArchived,setStudioProjectFolderArchived,updateStudioProjectFileMetadata} from "@/lib/studio/files/file-repository";
import {fileMetadataSchema,folderSchema,validateUploadFile} from "@/lib/studio/files/file-validation";
import {initializeStudioProjectDriveStorage} from "@/lib/studio/files/storage/google-drive-mapping";
export async function initializeProjectDriveStorageAction(projectId:string){const path=`/studio/projects/${projectId}/files`;try{await initializeStudioProjectDriveStorage(projectId);}catch{redirect(`${path}?error=project_drive_initialization_failed`);}revalidatePath(path);redirect(path);}
type State={success:boolean;message?:string};
function message(error:unknown){return error instanceof StudioFileError?error.message:"Dosya işlemi tamamlanamadı. Lütfen yeniden deneyin.";}
export async function createFolderAction(projectId:string,_state:State,formData:FormData):Promise<State>{const parsed=folderSchema.safeParse({name:String(formData.get("name")??""),parentFolderId:String(formData.get("parentFolderId")??"")});if(!parsed.success)return{success:false,message:z.flattenError(parsed.error).formErrors[0]??Object.values(z.flattenError(parsed.error).fieldErrors)[0]?.[0]};try{await createStudioProjectFolder(projectId,parsed.data);revalidatePath(`/studio/projects/${projectId}/files`);return{success:true,message:"Klasör oluşturuldu."};}catch(error){return{success:false,message:message(error)};}}
export async function renameFolderAction(projectId:string,folderId:string,formData:FormData){const parsed=folderSchema.pick({name:true}).safeParse({name:String(formData.get("name")??"")});if(!parsed.success)throw new StudioFileError("invalid_folder","Geçerli bir klasör adı girin.");await renameStudioProjectFolder(projectId,folderId,parsed.data.name);revalidatePath(`/studio/projects/${projectId}/files`);}
export async function moveFolderAction(projectId:string,folderId:string,formData:FormData){await moveStudioProjectFolder(projectId,folderId,String(formData.get("parentFolderId")??""));revalidatePath(`/studio/projects/${projectId}/files`);}
export async function archiveFolderAction(projectId:string,folderId:string,archived:boolean){await setStudioProjectFolderArchived(projectId,folderId,archived);revalidatePath(`/studio/projects/${projectId}/files`);}
export async function reserveFileUploadAction(input:{projectId:string;folderId:string;name:string;type:string;size:number;category:string}){const category=z.enum(["general","drawing","model","document","image","render","video","archive","spreadsheet","other"]).parse(input.category);const file=validateUploadFile({name:input.name,type:input.type,size:input.size,category});if(!file.success)throw new StudioFileError("invalid_file",file.message);return reserveGoogleDriveProjectFile({projectId:input.projectId,folderId:input.folderId,originalFileName:input.name,mimeType:file.mimeType,fileSize:input.size,category,extension:file.extension});}
export async function finalizeFileUploadAction(projectId:string,fileId:string){await finalizeStudioProjectFile(projectId,fileId);revalidatePath(`/studio/projects/${projectId}/files`);}
export async function finalizeGoogleDriveFileUploadAction(projectId:string,fileId:string,externalFileId:string){await finalizeGoogleDriveProjectFile(projectId,fileId,externalFileId);revalidatePath(`/studio/projects/${projectId}/files`);revalidatePath(`/studio/projects/${projectId}/files/${fileId}`);}
export async function failFileUploadAction(projectId:string,fileId:string){await markStudioProjectFileFailed(projectId,fileId);revalidatePath(`/studio/projects/${projectId}/files`);}
export async function updateFileMetadataAction(projectId:string,fileId:string,_state:State,formData:FormData):Promise<State>{const parsed=fileMetadataSchema.safeParse({displayName:String(formData.get("displayName")??""),description:String(formData.get("description")??""),category:String(formData.get("category")??""),folderId:String(formData.get("folderId")??"")});if(!parsed.success)return{success:false,message:"İşaretli dosya bilgilerini kontrol edin."};try{await updateStudioProjectFileMetadata(projectId,fileId,parsed.data);}catch(error){return{success:false,message:message(error)};}revalidatePath(`/studio/projects/${projectId}/files`);redirect(`/studio/projects/${projectId}/files/${fileId}`);}
export async function archiveFileAction(projectId:string,fileId:string,archived:boolean){await setStudioProjectFileArchived(projectId,fileId,archived);revalidatePath(`/studio/projects/${projectId}/files`);revalidatePath(`/studio/projects/${projectId}/files/${fileId}`);}
