"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {z} from "zod";
import {StudioFileError} from "@/lib/studio/files/file-errors";
import {createStudioProjectFolder,finalizeStudioProjectFile,markStudioProjectFileFailed,moveStudioProjectFile,moveStudioProjectFolder,renameStudioProjectFile,renameStudioProjectFolder,reserveGoogleDriveProjectFile,setStudioProjectFileArchived,setStudioProjectFolderArchived,updateStudioProjectFileMetadata,verifyStudioProjectFile,verifyStudioProjectFolder} from "@/lib/studio/files/file-repository";
import {fileMetadataSchema,fileMoveSchema,fileRenameSchema,folderSchema,validateUploadFile} from "@/lib/studio/files/file-validation";
import {initializeStudioProjectDriveStorage} from "@/lib/studio/files/storage/google-drive-mapping";
import {finalizeInitialStudioFileVersion,finalizeStudioFileVersion,findSameNameStudioFile,markStudioFileVersionFailed,promoteStudioFileVersion,repairStudioFileVersion,reserveStudioFileVersion} from "@/lib/studio/files/versions/version-repository";
import {versionRevisionSchema} from "@/lib/studio/files/versions/version-validation";

type State={success:boolean;message?:string};
const routePath=(projectId:string)=>`/studio/projects/${projectId}/files`;
function message(error:unknown){return error instanceof StudioFileError?error.message:"Dosya işlemi tamamlanamadı. Lütfen yeniden deneyin.";}
function refresh(projectId:string,fileId?:string){const path=routePath(projectId);revalidatePath(path);if(fileId)revalidatePath(`${path}/${fileId}`);}

export async function initializeProjectDriveStorageAction(projectId:string){const path=routePath(projectId);try{await initializeStudioProjectDriveStorage(projectId);}catch{redirect(`${path}?error=project_drive_initialization_failed`);}revalidatePath(path);redirect(path);}
export async function createFolderAction(projectId:string,_state:State,formData:FormData):Promise<State>{void _state;const parsed=folderSchema.safeParse({name:String(formData.get("name")??""),parentFolderId:String(formData.get("parentFolderId")??"")});if(!parsed.success)return{success:false,message:z.flattenError(parsed.error).formErrors[0]??Object.values(z.flattenError(parsed.error).fieldErrors)[0]?.[0]};try{await createStudioProjectFolder(projectId,parsed.data);refresh(projectId);return{success:true,message:"Klasör oluşturuldu."};}catch(error){return{success:false,message:message(error)};}}
export async function renameFolderAction(projectId:string,folderId:string,formData:FormData){const parsed=folderSchema.pick({name:true}).safeParse({name:String(formData.get("name")??"")});if(!parsed.success)throw new StudioFileError("invalid_folder","Geçerli bir klasör adı girin.");await renameStudioProjectFolder(projectId,folderId,parsed.data.name);refresh(projectId);}
export async function moveFolderAction(projectId:string,folderId:string,formData:FormData){await moveStudioProjectFolder(projectId,folderId,String(formData.get("parentFolderId")??""));refresh(projectId);}
export async function archiveFolderAction(projectId:string,folderId:string,archived:boolean){await setStudioProjectFolderArchived(projectId,folderId,archived);refresh(projectId);}
export async function reserveFileUploadAction(input:{projectId:string;folderId:string;name:string;type:string;size:number;category:string}){const category=z.enum(["general","drawing","model","document","image","render","video","archive","spreadsheet","other"]).parse(input.category);const file=validateUploadFile({name:input.name,type:input.type,size:input.size,category});if(!file.success)throw new StudioFileError("invalid_file",file.message);return reserveGoogleDriveProjectFile({projectId:input.projectId,folderId:input.folderId,originalFileName:input.name,mimeType:file.mimeType,fileSize:input.size,category,extension:file.extension});}
export async function finalizeFileUploadAction(projectId:string,fileId:string){await finalizeStudioProjectFile(projectId,fileId);refresh(projectId);}
export async function finalizeGoogleDriveFileUploadAction(projectId:string,fileId:string,externalFileId:string){await finalizeInitialStudioFileVersion(projectId,fileId,externalFileId);refresh(projectId,fileId);}
export async function failFileUploadAction(projectId:string,fileId:string){await markStudioProjectFileFailed(projectId,fileId);refresh(projectId);}
export async function updateFileMetadataAction(projectId:string,fileId:string,_state:State,formData:FormData):Promise<State>{void _state;const parsed=fileMetadataSchema.safeParse({displayName:String(formData.get("displayName")??""),description:String(formData.get("description")??""),category:String(formData.get("category")??""),folderId:String(formData.get("folderId")??"")});if(!parsed.success)return{success:false,message:"İşaretli dosya bilgilerini kontrol edin."};try{await updateStudioProjectFileMetadata(projectId,fileId,parsed.data);refresh(projectId,fileId);return{success:true,message:"Dosya bilgileri kaydedildi."};}catch(error){return{success:false,message:message(error)};}}
export async function archiveFileAction(projectId:string,fileId:string,archived:boolean){const result=await setStudioProjectFileArchived(projectId,fileId,archived);refresh(projectId,fileId);return result;}
export async function renameFileAction(projectId:string,fileId:string,_state:State,formData:FormData):Promise<State>{void _state;const parsed=fileRenameSchema.safeParse({name:String(formData.get("name")??"")});if(!parsed.success)return{success:false,message:"Geçerli bir dosya adı girin."};try{await renameStudioProjectFile(projectId,fileId,parsed.data.name);refresh(projectId,fileId);return{success:true,message:"Dosya yeniden adlandırıldı."};}catch(error){return{success:false,message:message(error)};}}
export async function moveFileAction(projectId:string,fileId:string,_state:State,formData:FormData):Promise<State>{void _state;const parsed=fileMoveSchema.safeParse({folderId:String(formData.get("folderId")??"")});if(!parsed.success)return{success:false,message:"Geçerli bir hedef klasör seçin."};try{await moveStudioProjectFile(projectId,fileId,parsed.data.folderId);refresh(projectId,fileId);return{success:true,message:"Dosya yeni klasöre taşındı."};}catch(error){return{success:false,message:message(error)};}}
export async function verifyFileAction(projectId:string,fileId:string,_state:State):Promise<State>{void _state;try{await verifyStudioProjectFile(projectId,fileId);refresh(projectId,fileId);return{success:true,message:"Google Drive dosya durumu doğrulandı."};}catch(error){return{success:false,message:message(error)};}}
export async function verifyFolderAction(projectId:string,folderId:string,_state:State):Promise<State>{void _state;try{await verifyStudioProjectFolder(projectId,folderId);refresh(projectId);return{success:true,message:"Google Drive klasör eşlemesi doğrulandı."};}catch(error){return{success:false,message:message(error)};}}
export async function reserveFileVersionUploadAction(input:{projectId:string;fileId:string;name:string;type:string;size:number;revisionCode:string;revisionTitle:string;revisionReason:string;revisionNote:string}){const revision=versionRevisionSchema.safeParse(input);if(!revision.success)throw new StudioFileError("invalid_file",revision.error.issues[0]?.message??"Revizyon bilgilerini kontrol edin.");return reserveStudioFileVersion({projectId:input.projectId,fileId:input.fileId,originalFileName:input.name,mimeType:input.type,fileSize:input.size,...revision.data});}
export async function finalizeFileVersionUploadAction(projectId:string,fileId:string,versionId:string,externalFileId:string){await finalizeStudioFileVersion(projectId,fileId,versionId,externalFileId);refresh(projectId,fileId);}
export async function failFileVersionUploadAction(projectId:string,fileId:string,versionId:string){await markStudioFileVersionFailed(projectId,fileId,versionId);refresh(projectId,fileId);}
export async function promoteFileVersionAction(projectId:string,fileId:string,versionId:string){await promoteStudioFileVersion(projectId,fileId,versionId);refresh(projectId,fileId);}
export async function repairFileVersionAction(projectId:string,fileId:string,versionId:string){await repairStudioFileVersion(projectId,fileId,versionId);refresh(projectId,fileId);}
export async function findSameNameFileAction(projectId:string,folderId:string,name:string){return findSameNameStudioFile(projectId,folderId,name);}
