/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase relation rows are mapped at this boundary. */
import "server-only";
import {getStudioContext} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {financeEntrySchema,financePaymentSchema} from "./finance-validation";
import type {FinanceDashboard,FinanceEntry} from "./finance-types";

async function scope(owner=false){const c=await getStudioContext();if(!c?.user||!c.membership)throw new Error("unauthorized");if(owner&&c.membership.role!=="owner")throw new Error("forbidden");return{db:await createStudioServerClient(),organizationId:c.membership.organization_id,userId:c.user.id,canManage:c.membership.role==="owner"};}
const empty=(canManage:boolean):FinanceDashboard=>({available:false,canManage,entries:[],projects:[],quotes:[],customers:[],files:[],summary:{income:0,expense:0,collected:0,monthCollected:0,outstanding:0,profit:0,cash:0,pendingProgress:0,bestProject:null},profitability:[]});

export async function getFinanceDashboard():Promise<FinanceDashboard>{
 const s=await scope();
 const [entryResult,paymentResult,projectResult,feeResult,fileResult,quoteResult,customerResult]=await Promise.all([
  s.db.from("studio_finance_entries").select("id,project_id,entry_type,title,description,category,status,amount,tax_rate,currency,entry_date,due_date,invoice_number,document_file_id,is_client_visible,created_at,studio_projects(name)").eq("organization_id",s.organizationId).eq("is_archived",false).order("entry_date",{ascending:false}).limit(1000),
  s.db.from("studio_finance_payments").select("income_id,amount,payment_date").eq("organization_id",s.organizationId).eq("is_archived",false),
  s.db.from("studio_projects").select("id,name").eq("organization_id",s.organizationId).eq("is_archived",false).order("name"),
  s.db.from("studio_project_obligations").select("project_id,amount,status").eq("organization_id",s.organizationId).eq("entity_type","fee").eq("is_archived",false),
  s.db.from("studio_project_files").select("id,project_id,display_name").eq("organization_id",s.organizationId).eq("status","ready").eq("is_archived",false).order("display_name").limit(500),
  s.db.from("studio_quotes").select("id,title,converted_project_id,lead_id").eq("organization_id",s.organizationId).eq("is_archived",false).order("created_at",{ascending:false}).limit(200),
  s.db.from("studio_leads").select("id,company,contact_name").eq("organization_id",s.organizationId).eq("is_archived",false).order("company").limit(300),
 ]);
 if(entryResult.error||paymentResult.error){const error=entryResult.error??paymentResult.error;if(["42P01","PGRST205"].includes(error?.code??""))return empty(s.canManage);throw error;}
 const paid=new Map<string,number>();for(const p of paymentResult.data??[])paid.set(p.income_id,(paid.get(p.income_id)??0)+Number(p.amount));
 const entries=(entryResult.data??[]).map((r:any):FinanceEntry=>{const project=Array.isArray(r.studio_projects)?r.studio_projects[0]:r.studio_projects,collected=paid.get(r.id)??0,amount=Number(r.amount),taxRate=Number(r.tax_rate);return{id:r.id,projectId:r.project_id,projectName:project?.name??null,type:r.entry_type,title:r.title,description:r.description??"",category:r.category,status:r.status,amount,taxRate,grossAmount:amount*(1+taxRate/100),currency:r.currency,entryDate:r.entry_date,dueDate:r.due_date,invoiceNumber:r.invoice_number,documentFileId:r.document_file_id,clientVisible:r.is_client_visible,createdAt:r.created_at,collected,remaining:Math.max(0,amount-collected)}});
 const projects=projectResult.data??[],fees=feeResult.data??[];
 const profitability=projects.map(p=>{const own=entries.filter(x=>x.projectId===p.id),expected=own.filter(x=>x.type==="income"||x.type==="progress_payment").reduce((n,x)=>n+x.amount,0),feeTotal=fees.filter(f=>f.project_id===p.id&&f.status!=="cancelled").reduce((n,f)=>n+Number(f.amount??0),0),expense=own.filter(x=>x.type==="expense").reduce((n,x)=>n+x.amount,0)+feeTotal,collected=own.reduce((n,x)=>n+x.collected,0),profit=collected-expense;return{projectId:p.id,projectName:p.name,expected,income:collected,expense,fees:feeTotal,collected,remaining:Math.max(0,expected-collected),profit,roi:expense>0?profit/expense*100:null}}).sort((a,b)=>b.profit-a.profit);
 const income=entries.filter(x=>x.type==="income"||x.type==="progress_payment").reduce((n,x)=>n+x.amount,0),expense=entries.filter(x=>x.type==="expense").reduce((n,x)=>n+x.amount,0),collected=entries.reduce((n,x)=>n+x.collected,0),month=new Date().toISOString().slice(0,7),monthCollected=(paymentResult.data??[]).filter(p=>p.payment_date.startsWith(month)).reduce((n,p)=>n+Number(p.amount),0);
 return{available:true,canManage:s.canManage,entries,projects,quotes:(quoteResult.data??[]).map(q=>({id:q.id,name:q.title,projectId:q.converted_project_id,crmLeadId:q.lead_id})),customers:(customerResult.data??[]).map(l=>({id:l.id,name:l.company||l.contact_name})),files:(fileResult.data??[]).map(f=>({id:f.id,projectId:f.project_id,name:f.display_name})),summary:{income,expense,collected,monthCollected,outstanding:Math.max(0,income-collected),profit:collected-expense,cash:collected-expense,pendingProgress:entries.filter(x=>x.type==="progress_payment"&&!['collected','cancelled'].includes(x.status)).reduce((n,x)=>n+x.remaining,0),bestProject:profitability[0]?.projectName??null},profitability};
}
export async function createFinanceEntry(raw:unknown){const s=await scope(true),v=financeEntrySchema.parse(raw);let projectId=v.projectId,crmLeadId=v.crmLeadId;if(v.sourceType==="quote"){if(!v.quoteId)throw new Error("quote_required");const{data:quote,error:quoteError}=await s.db.from("studio_quotes").select("converted_project_id,lead_id").eq("organization_id",s.organizationId).eq("id",v.quoteId).single();if(quoteError)throw quoteError;projectId=projectId??quote.converted_project_id;crmLeadId=crmLeadId??quote.lead_id;}if(v.documentFileId&&!projectId)throw new Error("document_project_required");const{error}=await s.db.from("studio_finance_entries").insert({organization_id:s.organizationId,project_id:projectId,quote_id:v.quoteId,crm_lead_id:crmLeadId,entry_type:v.type,source_type:v.sourceType,title:v.title,description:v.description||null,category:v.category,status:"waiting",amount:v.amount,tax_rate:v.taxRate,currency:v.currency,entry_date:v.entryDate,due_date:v.dueDate,invoice_number:v.type==="invoice"?v.invoiceNumber||null:null,document_file_id:v.documentFileId,is_client_visible:v.clientVisible,created_by:s.userId,updated_by:s.userId});if(error)throw error;}
export async function createFinancePayment(raw:unknown){const s=await scope(true),v=financePaymentSchema.parse(raw);const{error}=await s.db.from("studio_finance_payments").insert({organization_id:s.organizationId,income_id:v.incomeId,amount:v.amount,payment_date:v.paymentDate,method:v.method,note:v.note||null,receipt_file_id:v.receiptFileId,is_client_visible:v.clientVisible,created_by:s.userId,updated_by:s.userId});if(error)throw error;}
export async function archiveFinanceEntry(id:string){const s=await scope(true);const{error}=await s.db.from("studio_finance_entries").update({is_archived:true,updated_by:s.userId}).eq("organization_id",s.organizationId).eq("id",id);if(error)throw error;}
