import "server-only";
import {z}from"zod";
import {getStudioContext}from"@/lib/studio/auth/get-studio-context";
import {createStudioServerClient}from"@/lib/studio/supabase/server";
import {PAYMENT_REQUEST_TYPES,type StudioPaymentRequest}from"@/lib/payments/payment-request-types";
import{createClient}from"@supabase/supabase-js";

const amount=z.string().trim().regex(/^\d{1,12}(?:[.,]\d{1,2})?$/).transform(value=>value.replace(",","."));
const inputSchema=z.object({title:z.string().trim().min(2).max(180),paymentType:z.enum(PAYMENT_REQUEST_TYPES),amount,currency:z.enum(["TRY","USD","EUR","GBP"]),description:z.string().trim().max(4000),dueDate:z.union([z.literal(""),z.iso.date()]).transform(value=>value||null)});

async function scope(projectId:string,owner=false){const context=await getStudioContext();if(!context?.user||!context.membership)throw new Error("unauthorized");if(owner&&context.membership.role!=="owner")throw new Error("forbidden");const db=await createStudioServerClient();const{data:project,error}=await db.from("studio_projects").select("id").eq("organization_id",context.membership.organization_id).eq("id",projectId).eq("is_archived",false).maybeSingle();if(error||!project)throw new Error("project_not_found");return{db,userId:context.user.id,organizationId:context.membership.organization_id};}
const unavailable=(code:string|undefined)=>["42P01","PGRST202","PGRST204","PGRST205"].includes(code??"");

export async function getStudioPaymentRequests(projectId:string):Promise<StudioPaymentRequest[]>{const s=await scope(projectId);const result=await s.db.rpc("studio_list_client_payment_requests_v2",{p_project_id:projectId});let rows:Record<string,unknown>[];if(result.error&&unavailable(result.error.code)){const legacy=await s.db.from("studio_client_payment_requests").select("id,title,description,payment_type,amount,currency,due_date,status,payment_provider,paid_at,created_at").eq("organization_id",s.organizationId).eq("project_id",projectId).order("created_at",{ascending:false});if(legacy.error&&unavailable(legacy.error.code))return[];if(legacy.error)throw legacy.error;rows=(legacy.data??[])as Record<string,unknown>[]}else{if(result.error)throw result.error;rows=(result.data??[])as Record<string,unknown>[];}const requests=rows.map(row=>map(row))as StudioPaymentRequest[],pending=requests.filter(item=>item.status==="pending").map(item=>item.id),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!pending.length||!url||!key)return requests;const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),{data}=await admin.from("studio_client_payment_attempts").select("payment_request_id").eq("project_id",projectId).eq("organization_id",s.organizationId).eq("checkout_source","public_link").eq("status","awaiting_payment").in("payment_request_id",pending);const recoverable=new Set((data??[]).map(row=>String(row.payment_request_id)));return requests.map(item=>({...item,canReconcile:recoverable.has(item.id)}));}
function map(row:Record<string,unknown>){return{id:String(row.id),title:String(row.title),description:String(row.description??""),paymentType:row.payment_type,amount:String(row.amount),currency:String(row.currency),dueDate:row.due_date?String(row.due_date):null,status:row.status,paymentProvider:row.payment_provider?String(row.payment_provider):null,paidAt:row.paid_at?String(row.paid_at):null,createdAt:String(row.created_at),installment:row.installment?Number(row.installment):null,paidPrice:row.paid_price?String(row.paid_price):null,merchantCommissionRate:row.merchant_commission_rate?String(row.merchant_commission_rate):null,merchantCommissionRateAmount:row.merchant_commission_rate_amount?String(row.merchant_commission_rate_amount):null,iyziCommissionRateAmount:row.iyzi_commission_rate_amount?String(row.iyzi_commission_rate_amount):null,iyziCommissionFee:row.iyzi_commission_fee?String(row.iyzi_commission_fee):null,paymentEnvironment:row.environment?String(row.environment):null,refundStatus:row.refund_status?String(row.refund_status):null};}

export async function createStudioPaymentRequest(projectId:string,raw:unknown){const s=await scope(projectId,true),value=inputSchema.parse(raw);const{error}=await s.db.rpc("studio_create_client_payment_request",{p_project_id:projectId,p_title:value.title,p_description:value.description||null,p_payment_type:value.paymentType,p_amount:value.amount,p_currency:value.currency,p_due_date:value.dueDate});if(error)throw error;}

export async function cancelStudioPaymentRequest(projectId:string,paymentRequestId:string){const s=await scope(projectId,true),id=z.uuid().parse(paymentRequestId);const{data,error}=await s.db.rpc("studio_cancel_client_payment_request",{p_project_id:projectId,p_payment_request_id:id});if(error)throw error;if(!data)throw new Error("payment_request_not_found");}
