/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase rows are normalized at this repository boundary. */
import "server-only";
import {getStudioContext} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {z} from "zod";
import {PROJECT_EXPENSE_CATEGORIES} from "./project-finance-constants";
export const projectExpenseSchema=z.object({category:z.enum(PROJECT_EXPENSE_CATEGORIES),amount:z.coerce.number().positive().max(999999999999),paidAmount:z.coerce.number().min(0).default(0),status:z.enum(["waiting","partial","paid","cancelled"]).default("waiting"),entryDate:z.iso.date(),description:z.string().trim().max(4000),documentFileId:z.union([z.literal(""),z.uuid()]).transform(value=>value||null),receiptFileId:z.union([z.literal(""),z.uuid()]).transform(value=>value||null),invoiceFileId:z.union([z.literal(""),z.uuid()]).transform(value=>value||null)}).superRefine((value,ctx)=>{if(value.paidAmount>value.amount)ctx.addIssue({code:"custom",path:["paidAmount"],message:"Ödenen gider tutarı toplamı aşamaz."})});
async function scope(projectId:string,owner=false){const context=await getStudioContext();if(!context?.user||!context.membership)throw new Error("unauthorized");if(owner&&context.membership.role!=="owner")throw new Error("forbidden");const db=await createStudioServerClient();const{data:project,error}=await db.from("studio_projects").select("id,name,code,category").eq("organization_id",context.membership.organization_id).eq("id",projectId).eq("is_archived",false).single();if(error||!project)throw new Error("project_not_found");return{db,organizationId:context.membership.organization_id,userId:context.user.id,canManage:context.membership.role==="owner",project};}
export async function getProjectFinanceWorkspace(projectId:string){const s=await scope(projectId);const[profileResult,entryResult,fileResult,eventResult]=await Promise.all([s.db.from("studio_project_finance_profiles").select("id,agreed_amount,currency,contract_date,description,contract_file_id").eq("organization_id",s.organizationId).eq("project_id",projectId).maybeSingle(),s.db.from("studio_finance_entries").select("id,category,title,description,status,amount,paid_amount,entry_date,document_file_id,receipt_file_id,invoice_file_id").eq("organization_id",s.organizationId).eq("project_id",projectId).eq("entry_type","expense").eq("is_archived",false).order("entry_date",{ascending:false}),s.db.from("studio_project_files").select("id,display_name,extension,mime_type,file_size").eq("organization_id",s.organizationId).eq("project_id",projectId).eq("status","ready").eq("is_archived",false).order("display_name").limit(500),s.db.from("studio_finance_events").select("id,title,event_type,created_at,entry_id").eq("organization_id",s.organizationId).eq("project_id",projectId).order("created_at",{ascending:false}).limit(100)]);if(profileResult.error&&!['42P01','PGRST205'].includes(profileResult.error.code??''))throw profileResult.error;if(entryResult.error)throw entryResult.error;const expenses=(entryResult.data??[]).map((row:any)=>({id:row.id,category:row.category,description:row.description??row.title,status:row.status,amount:Number(row.amount),paidAmount:Number(row.paid_amount??(row.status==="paid"?row.amount:0)),entryDate:row.entry_date,documentFileId:row.document_file_id,receiptFileId:row.receipt_file_id,invoiceFileId:row.invoice_file_id}));const profile=profileResult.data?{agreedAmount:Number(profileResult.data.agreed_amount),currency:profileResult.data.currency,contractDate:profileResult.data.contract_date,description:profileResult.data.description??"",contractFileId:profileResult.data.contract_file_id}:{agreedAmount:0,currency:"TRY",contractDate:null,description:"",contractFileId:null};const totalExpense=expenses.filter(x=>x.status!=="cancelled").reduce((n,x)=>n+x.amount,0),paidExpense=expenses.filter(x=>x.status!=="cancelled").reduce((n,x)=>n+Math.min(x.amount,x.paidAmount),0);return{project:s.project,canManage:s.canManage,profile,expenses,files:fileResult.data??[],events:eventResult.data??[],summary:{agreedAmount:profile.agreedAmount,totalExpense,paidExpense,pendingExpense:Math.max(0,totalExpense-paidExpense),netExpected:profile.agreedAmount-totalExpense,margin:profile.agreedAmount>0?(profile.agreedAmount-totalExpense)/profile.agreedAmount*100:null}};}
export async function saveProjectFinanceProfile(projectId:string,raw:unknown){const s=await scope(projectId,true);const value=z.object({agreedAmount:z.coerce.number().min(0).max(999999999999),currency:z.enum(["TRY","USD","EUR","GBP"]),contractDate:z.union([z.literal(""),z.iso.date()]).transform(v=>v||null),description:z.string().trim().max(4000),contractFileId:z.union([z.literal(""),z.uuid()]).transform(v=>v||null)}).parse(raw);const payload={organization_id:s.organizationId,project_id:projectId,agreed_amount:value.agreedAmount,currency:value.currency,contract_date:value.contractDate,description:value.description||null,contract_file_id:value.contractFileId,updated_by:s.userId};const{error}=await s.db.from("studio_project_finance_profiles").upsert({...payload,created_by:s.userId},{onConflict:"organization_id,project_id"});if(error)throw error;}
export async function createProjectExpense(projectId:string,raw:unknown){const s=await scope(projectId,true);const value=projectExpenseSchema.parse(raw);const{error}=await s.db.from("studio_finance_entries").insert({organization_id:s.organizationId,project_id:projectId,entry_type:"expense",source_type:"project",title:value.description.slice(0,180)||"Proje gideri",description:value.description||null,category:value.category,status:value.status,amount:value.amount,paid_amount:value.paidAmount,entry_date:value.entryDate,document_file_id:value.documentFileId,receipt_file_id:value.receiptFileId,invoice_file_id:value.invoiceFileId,currency:"TRY",tax_rate:0,is_client_visible:false,created_by:s.userId,updated_by:s.userId});if(error)throw error;}
