/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars -- Supabase rows are normalized at this boundary. */
import "server-only";
import {getStudioContext} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {z} from "zod";
import {PROJECT_EXPENSE_CATEGORIES} from "./project-finance-constants";

export const projectExpenseSchema=z.object({category:z.enum(PROJECT_EXPENSE_CATEGORIES),amount:z.coerce.number().positive().max(999999999999),paidAmount:z.coerce.number().min(0).default(0),status:z.enum(["waiting","partial","paid","cancelled"]).default("waiting"),entryDate:z.iso.date(),description:z.string().trim().max(4000),documentFileId:z.union([z.literal(""),z.uuid()]).transform(value=>value||null),receiptFileId:z.union([z.literal(""),z.uuid()]).transform(value=>value||null),invoiceFileId:z.union([z.literal(""),z.uuid()]).transform(value=>value||null)}).superRefine((value,ctx)=>{if(value.paidAmount>value.amount)ctx.addIssue({code:"custom",path:["paidAmount"],message:"Ödenen gider tutarı toplamı aşamaz."})});
const workTypes=["Modelleme","Kaplama / Materyal","Işıklandırma","Render Ayarları","Render Süresi","Photoshop / Post-prodüksiyon","Animasyon","Video Montaj","Revize","Toplantı","Diğer"] as const;
const revisionStatuses=["requested","completed","cancelled"] as const;

async function scope(projectId:string,owner=false){const context=await getStudioContext();if(!context?.user||!context.membership)throw new Error("unauthorized");if(owner&&context.membership.role!=="owner")throw new Error("forbidden");const db=await createStudioServerClient();const{data:project,error}=await db.from("studio_projects").select("id,name,code,category,stage").eq("organization_id",context.membership.organization_id).eq("id",projectId).eq("is_archived",false).single();if(error||!project)throw new Error("project_not_found");return{db,organizationId:context.membership.organization_id,userId:context.user.id,canManage:context.membership.role==="owner",project};}
const unavailable=(error:any)=>["42P01","PGRST204","PGRST205"].includes(error?.code??"");
const visualizationProject=(project:any)=>[project?.category,project?.stage].some(value=>String(value??"").trim().toLocaleLowerCase("tr-TR")==="görselleştirme");

async function profileFor(s:any,projectId:string){let result=await s.db.from("studio_project_finance_profiles").select("id,agreed_amount,currency,contract_date,description,contract_file_id,included_revision_count,extra_revision_unit_price").eq("organization_id",s.organizationId).eq("project_id",projectId).maybeSingle();if(result.error&&result.error.code==="PGRST204")result=await s.db.from("studio_project_finance_profiles").select("id,agreed_amount,currency,contract_date,description,contract_file_id").eq("organization_id",s.organizationId).eq("project_id",projectId).maybeSingle();if(result.error&&!unavailable(result.error))throw result.error;const row=result.data;return row?{agreedAmount:Number(row.agreed_amount),currency:row.currency,contractDate:row.contract_date,description:row.description??"",contractFileId:row.contract_file_id,includedRevisionCount:Number(row.included_revision_count??0),extraRevisionUnitPrice:Number(row.extra_revision_unit_price??0)}:{agreedAmount:0,currency:"TRY",contractDate:null,description:"",contractFileId:null,includedRevisionCount:0,extraRevisionUnitPrice:0};}
async function optionalRows(query:any){const result=await query;return result.error&&unavailable(result.error)?[]:(result.error?(()=>{throw result.error})():result.data??[]);}

export async function getProjectFinanceWorkspace(projectId:string){
 const s=await scope(projectId),profile=await profileFor(s,projectId),isVisualization=visualizationProject(s.project);
 const [entryResult,fileResult,eventResult,paymentRows]=await Promise.all([
  s.db.from("studio_finance_entries").select("id,entry_type,category,title,description,status,amount,paid_amount,entry_date,document_file_id,receipt_file_id,invoice_file_id").eq("organization_id",s.organizationId).eq("project_id",projectId).eq("is_archived",false).order("entry_date",{ascending:false}),
  s.db.from("studio_project_files").select("id,display_name,extension,mime_type,file_size").eq("organization_id",s.organizationId).eq("project_id",projectId).eq("status","ready").eq("is_archived",false).order("display_name").limit(500),
  s.db.from("studio_finance_events").select("id,title,event_type,created_at,entry_id").eq("organization_id",s.organizationId).eq("project_id",projectId).order("created_at",{ascending:false}).limit(100),
  s.db.from("studio_finance_payments").select("income_id,amount,payment_date").eq("organization_id",s.organizationId).eq("is_archived",false),
 ]);
 if(entryResult.error)throw entryResult.error;if(fileResult.error)throw fileResult.error;if(eventResult.error)throw eventResult.error;
 const rows=entryResult.data??[],expenses=rows.filter((row:any)=>row.entry_type==="expense").map((row:any)=>({id:row.id,category:row.category,description:row.description??row.title,status:row.status,amount:Number(row.amount),paidAmount:Number(row.paid_amount??(row.status==="paid"?row.amount:0)),entryDate:row.entry_date,documentFileId:row.document_file_id,receiptFileId:row.receipt_file_id,invoiceFileId:row.invoice_file_id}));
 const totalExpense=expenses.filter(x=>x.status!=="cancelled").reduce((n,x)=>n+x.amount,0),paidExpense=expenses.filter(x=>x.status!=="cancelled").reduce((n,x)=>n+Math.min(x.amount,x.paidAmount),0),incomeIds=new Set(rows.filter((row:any)=>["income","progress_payment"].includes(row.entry_type)).map((row:any)=>row.id)),collected=(paymentRows.data??[]).filter((row:any)=>incomeIds.has(row.income_id)).reduce((n,row:any)=>n+Number(row.amount),0);
 let visualization=null as any;
 if(isVisualization){
  const [times,revisions,renders]=await Promise.all([
   optionalRows(s.db.from("studio_visualization_time_entries").select("id,user_id,work_type,duration_minutes,work_date,description,render_id").eq("organization_id",s.organizationId).eq("project_id",projectId).is("archived_at",null).order("work_date",{ascending:false}).limit(500)),
   optionalRows(s.db.from("studio_visualization_revisions").select("id,revision_number,requested_at,description,is_included,amount,status,render_id,file_version_id,finance_entry_id").eq("organization_id",s.organizationId).eq("project_id",projectId).is("archived_at",null).order("revision_number",{ascending:false}).limit(200)),
   optionalRows(s.db.from("studio_project_renders").select("id,logical_file_id,presented_at,is_client_visible").eq("organization_id",s.organizationId).eq("project_id",projectId).is("archived_at",null).limit(500)),
  ]);
  const renderIds=renders.map((row:any)=>row.logical_file_id).filter(Boolean),versions=renderIds.length?await optionalRows(s.db.from("studio_project_file_versions").select("file_id").eq("organization_id",s.organizationId).in("file_id",renderIds)):[];
  const hours=times.reduce((n:any,row:any)=>n+Number(row.duration_minutes??0),0)/60,delivered=renders.filter((row:any)=>Boolean(row.presented_at)).length,used=revisions.filter((row:any)=>row.status!=="cancelled").length,included=profile.includedRevisionCount,paidRevisions=revisions.filter((row:any)=>!row.is_included&&row.status!=="cancelled"),totalRenderCost=totalExpense;
  visualization={times,revisions,renders,totalMinutes:hours*60,totalHours:hours,deliveredRenders:delivered,renderCount:renders.length,renderVersionCount:versions.length,includedRevisionCount:included,usedRevisionCount:used,remainingIncludedRevisions:Math.max(0,included-used),paidRevisionCount:paidRevisions.length,extraRevisionIncome:paidRevisions.reduce((n:any,row:any)=>n+Number(row.amount??0),0),hourlyEarnings:hours>0?(profile.agreedAmount-totalExpense)/hours:null,costPerDeliveredRender:delivered>0?totalRenderCost/delivered:null,netProfit:profile.agreedAmount-totalExpense,collected,remainingCollection:Math.max(profile.agreedAmount-collected,0),timeline:[...(eventResult.data??[]),...revisions.map((row:any)=>({id:`revision-${row.id}`,title:"Revize oluşturuldu",event_type:"revision_created",created_at:row.requested_at,entry_id:null}))].sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at)))};
 }
 return{project:s.project,canManage:s.canManage,profile,expenses,files:fileResult.data??[],events:eventResult.data??[],summary:{agreedAmount:profile.agreedAmount,totalExpense,paidExpense,pendingExpense:Math.max(0,totalExpense-paidExpense),netExpected:profile.agreedAmount-totalExpense,margin:profile.agreedAmount>0?(profile.agreedAmount-totalExpense)/profile.agreedAmount*100:null,collected,remainingCollection:Math.max(profile.agreedAmount-collected,0)},isVisualization,visualization};
}

export async function saveProjectFinanceProfile(projectId:string,raw:unknown){const s=await scope(projectId,true),value=z.object({agreedAmount:z.coerce.number().min(0).max(999999999999),currency:z.enum(["TRY","USD","EUR","GBP"]),contractDate:z.union([z.literal(""),z.iso.date()]).transform(v=>v||null),description:z.string().trim().max(4000),contractFileId:z.union([z.literal(""),z.uuid()]).transform(v=>v||null),includedRevisionCount:z.coerce.number().int().min(0).max(1000).default(0),extraRevisionUnitPrice:z.coerce.number().min(0).max(999999999999).default(0)}).parse(raw);const payload={organization_id:s.organizationId,project_id:projectId,agreed_amount:value.agreedAmount,currency:value.currency,contract_date:value.contractDate,description:value.description||null,contract_file_id:value.contractFileId,included_revision_count:value.includedRevisionCount,extra_revision_unit_price:value.extraRevisionUnitPrice,updated_by:s.userId};let result=await s.db.from("studio_project_finance_profiles").upsert({...payload,created_by:s.userId},{onConflict:"organization_id,project_id"});if(result.error?.code==="PGRST204"){const{included_revision_count,extra_revision_unit_price,...legacy}=payload;result=await s.db.from("studio_project_finance_profiles").upsert({...legacy,created_by:s.userId},{onConflict:"organization_id,project_id"});}if(result.error)throw result.error;}
export async function createProjectExpense(projectId:string,raw:unknown){const s=await scope(projectId,true),value=projectExpenseSchema.parse(raw),{error}=await s.db.from("studio_finance_entries").insert({organization_id:s.organizationId,project_id:projectId,entry_type:"expense",source_type:"project",title:value.description.slice(0,180)||"Proje gideri",description:value.description||null,category:value.category,status:value.status,amount:value.amount,paid_amount:value.paidAmount,entry_date:value.entryDate,document_file_id:value.documentFileId,receipt_file_id:value.receiptFileId,invoice_file_id:value.invoiceFileId,currency:"TRY",tax_rate:0,is_client_visible:false,created_by:s.userId,updated_by:s.userId});if(error)throw error;}
export async function createVisualizationTimeEntry(projectId:string,raw:unknown){const s=await scope(projectId,true),value=z.object({workType:z.enum(workTypes),durationMinutes:z.coerce.number().int().positive().max(1440),workDate:z.iso.date(),description:z.string().trim().max(2000),renderId:z.union([z.literal(""),z.uuid()]).transform(v=>v||null)}).parse(raw),{error}=await s.db.from("studio_visualization_time_entries").insert({organization_id:s.organizationId,project_id:projectId,user_id:s.userId,work_type:value.workType,duration_minutes:value.durationMinutes,work_date:value.workDate,description:value.description||null,render_id:value.renderId});if(error)throw error;}
export async function createVisualizationRevision(projectId:string,raw:unknown){const s=await scope(projectId,true),value=z.object({revisionNumber:z.coerce.number().int().positive().max(10000),requestedAt:z.iso.date(),description:z.string().trim().min(2).max(3000),isIncluded:z.coerce.boolean(),amount:z.coerce.number().min(0).max(999999999999),status:z.enum(revisionStatuses),renderId:z.union([z.literal(""),z.uuid()]).transform(v=>v||null),fileVersionId:z.union([z.literal(""),z.uuid()]).transform(v=>v||null)}).parse(raw),{error}=await s.db.from("studio_visualization_revisions").insert({organization_id:s.organizationId,project_id:projectId,revision_number:value.revisionNumber,requested_at:value.requestedAt,description:value.description,is_included:value.isIncluded,amount:value.amount,status:value.status,render_id:value.renderId,file_version_id:value.fileVersionId,created_by:s.userId});if(error)throw error;}
