"use client";

import Image from "next/image";
import Link from "next/link";
import {useEffect,useMemo,useState,useTransition} from "react";

import {favoriteRenderFilesAction,sendRenderBulkWhatsAppAction,sendRenderWhatsAppAction,setHeroRenderAction,setRenderFlagsAction,updateRenderAction} from "@/app/studio/(protected)/projects/[projectId]/renders/actions";
import StudioAiWritingDialog from "@/components/studio/ai/StudioAiWritingDialog";
import StudioFavoriteButton from "@/components/studio/quick-access/StudioFavoriteButton";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioIcon} from "@/components/studio/StudioIcons";
import {StudioBadge,StudioDrawer,StudioEmptyState,StudioIconSurface,StudioSectionHeader} from "@/components/studio/ui";
import type {StudioRenderArchive,StudioRenderItem} from "@/lib/studio/renders/render-types";

function WhatsAppDialog({archive,render,text,onClose,onResult}:{archive:StudioRenderArchive;render:StudioRenderItem;text:string;onClose:()=>void;onResult:(value:string)=>void}){
 const[message,setMessage]=useState(text),[pending,start]=useTransition();
 return <div role="dialog" aria-modal="true" aria-labelledby={`render-whatsapp-${render.id}`} className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/55 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-xl"><h3 id={`render-whatsapp-${render.id}`} className="text-xl font-semibold">WhatsApp Önizlemesi</h3><p className="mt-2 text-sm text-[#68706f]">{render.title} · {render.file.extension.toUpperCase()} güvenli medya eki</p><label className="mt-4 block text-sm font-semibold">Müşteri mesajı<textarea value={message} onChange={event=>setMessage(event.target.value)} maxLength={3000} className="studio-field mt-2 min-h-48 w-full"/></label><p className="mt-2 text-right text-xs text-[#68706f]">{message.length} karakter</p><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={onClose} className={studioButtonClass("ghost","sm")}>İptal</button><button type="button" disabled={pending||message.trim().length<10} onClick={()=>start(async()=>{const result=await sendRenderWhatsAppAction(archive.project.id,render.id,message);onResult(result.message);if(result.success)onClose();})} className={studioButtonClass("primary","sm")}>{pending?"Gönderiliyor…":"WhatsApp ile Gönder"}</button></div></div></div>;
}

function RenderCard({render,archive,selected,toggle,openPresent,openDetail}:{render:StudioRenderItem;archive:StudioRenderArchive;selected:boolean;toggle:()=>void;openPresent:()=>void;openDetail:()=>void}){
 const[description,setDescription]=useState(render.description),[editing,setEditing]=useState(false),[whatsapp,setWhatsapp]=useState(false),[pending,start]=useTransition(),[message,setMessage]=useState("");
 const action=updateRenderAction.bind(null,archive.project.id,render.id);
 const defaultMessage=description||`${archive.project.name} projesine ait ${render.title} render çalışması sunuma hazırdır.`;
 return <article className={`studio-render-card group ${selected?"is-selected":""}`}>
  <div className="studio-render-card__preview"><Image src={render.thumbnailUrl} alt={`${render.title} render önizlemesi`} fill sizes="(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 420px" unoptimized className="object-cover transition duration-300 group-hover:scale-[1.025]"/><label className="studio-render-card__select"><input type="checkbox" checked={selected} onChange={toggle}/><span className="sr-only">{render.title} renderını seç</span></label><div className="studio-render-card__favorite"><StudioFavoriteButton entityType="file" entityId={render.fileId} initialFavorite={render.isFavorite} compact/></div>{render.isHero?<StudioBadge variant="info" icon="star">Kapak</StudioBadge>:null}<div className="studio-render-card__overlay"><Link href={`/studio/projects/${archive.project.id}/renders/${render.id}`} className={studioButtonClass("outline","sm")}><StudioIcon name="search"/>Önizle</Link><a href={`/studio/projects/${archive.project.id}/files/${render.fileId}/download`} className={studioButtonClass("outline","sm")}><StudioIcon name="download"/>İndir</a><button type="button" onClick={openPresent} className={studioButtonClass("outline","sm")}><StudioIcon name="image"/>Sunum</button><button type="button" onClick={openDetail} className={studioButtonClass("outline","sm")}><StudioIcon name="sliders"/>Detay</button></div></div>
  <div className="studio-render-card__body"><div className="flex min-w-0 items-start justify-between gap-2"><div className="min-w-0"><h3>{render.title}</h3><p>{archive.project.name} · {render.categoryName}</p></div><div className="flex shrink-0 gap-1">{render.presentedAt?<StudioBadge variant="success" icon="check">Sunuldu</StudioBadge>:null}</div></div>
   <div className="studio-render-card__facts"><span>{render.file.extension.toUpperCase()}</span><span>{render.width&&render.height?`${render.width} × ${render.height}`:render.aspectRatio}</span><span>{render.file.fileSizeLabel}</span><span>V{render.file.versionNumber}</span></div>
   <p className="studio-render-card__description">{description||"Açıklama eklenmedi."}</p>
   <div className="studio-render-card__tags">{render.tags.slice(0,3).map(tag=><StudioBadge key={tag} variant="outline">{tag}</StudioBadge>)}{render.tags.length>3?<small>+{render.tags.length-3}</small>:null}</div>
   <footer><span><StudioIcon name="user"/>{render.file.uploadedByName}</span><span><StudioIcon name="revision"/>{render.file.versionCount} sürüm</span></footer>
   {archive.canManage?<div className="studio-render-card__manage"><button type="button" onClick={()=>setEditing(value=>!value)} className={studioButtonClass("ghost","sm")}>Özellikler</button><button type="button" disabled={pending||render.isHero} onClick={()=>start(async()=>setMessage((await setHeroRenderAction(archive.project.id,render.id)).message))} className={studioButtonClass("ghost","sm")}>Kapak Yap</button><button type="button" onClick={()=>setWhatsapp(true)} className={studioButtonClass("ghost","sm")}>WhatsApp</button></div>:null}
   {archive.canManage&&editing?<form action={async formData=>{const result=await action(formData);setMessage(result.message);if(result.success)setEditing(false);}} className="studio-render-card__edit"><label>Başlık<input name="title" defaultValue={render.title} className="studio-field" required/></label><label>Kategori<select name="categoryId" defaultValue={render.categoryId??""} className="studio-field"><option value="">Diğer</option>{archive.categories.filter(item=>!item.isArchived).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label>Genişlik<input name="width" type="number" min="1" defaultValue={render.width??""} className="studio-field"/></label><label>Yükseklik<input name="height" type="number" min="1" defaultValue={render.height??""} className="studio-field"/></label></div><div className="flex items-center justify-between gap-2"><span>Açıklama</span><StudioAiWritingDialog operation="render_description" title="AI Render Açıklaması" triggerLabel="AI ile Oluştur" currentText={description} context={{projectName:archive.project.name,category:render.categoryName,tags:render.tags,userNote:description}} onUse={setDescription}/></div><textarea name="description" value={description} onChange={event=>setDescription(event.target.value)} maxLength={3000} className="studio-field min-h-28 w-full"/><button className={studioButtonClass("primary","sm")}>Kaydet</button></form>:null}
   {message?<p role="status" className="studio-render-message">{message}</p>:null}
  </div>{whatsapp?<WhatsAppDialog archive={archive} render={render} text={defaultMessage} onClose={()=>setWhatsapp(false)} onResult={setMessage}/>:null}
 </article>;
}

function RenderDetailDrawer({archive,render,onClose,openPresent}:{archive:StudioRenderArchive;render:StudioRenderItem|null;onClose:()=>void;openPresent:()=>void}){
 if(!render)return null;
 return <StudioDrawer open title={render.title} onClose={onClose}><div className="studio-render-detail"><div className="studio-render-detail__preview"><Image src={render.thumbnailUrl} alt={render.title} fill unoptimized className="object-contain"/></div><div className="flex flex-wrap gap-2">{render.isHero?<StudioBadge variant="info" icon="star">Kapak Renderı</StudioBadge>:null}{render.presentedAt?<StudioBadge variant="success" icon="check">Sunuldu</StudioBadge>:null}{render.isClientVisible?<StudioBadge variant="info" icon="clients">Müşteriye Açık</StudioBadge>:null}</div><dl><div><dt>İlgili proje</dt><dd>{archive.project.name}</dd></div><div><dt>Kategori</dt><dd>{render.categoryName}</dd></div><div><dt>Çözünürlük</dt><dd>{render.width&&render.height?`${render.width} × ${render.height}`:"Belirtilmedi"}</dd></div><div><dt>Format / Boyut</dt><dd>{render.file.extension.toUpperCase()} · {render.file.fileSizeLabel}</dd></div><div><dt>Oluşturan</dt><dd>{render.file.uploadedByName}</dd></div><div><dt>Revizyon</dt><dd>{render.file.versionCount} sürüm</dd></div></dl><section><h3>Versiyon Geçmişi</h3><div className="studio-render-versions">{Array.from({length:render.file.versionCount},(_,index)=><span key={index} className={index===render.file.versionNumber-1?"is-current":""}>V{index+1}</span>)}</div></section><section><h3>Notlar</h3><p>{render.description||"Bu render için not eklenmedi."}</p></section><div className="studio-render-detail__actions"><button type="button" onClick={openPresent} className={studioButtonClass("secondary","sm")}><StudioIcon name="image"/>Sunum</button><a href={`/studio/projects/${archive.project.id}/files/${render.fileId}/download`} className={studioButtonClass("primary","sm")}><StudioIcon name="download"/>İndir</a><Link href={`/studio/projects/${archive.project.id}/files/${render.fileId}`} className={studioButtonClass("outline","sm")}><StudioIcon name="upload"/>Yeni Revizyon</Link><Link href={`/studio/projects/${archive.project.id}/renders/${render.id}`} className={studioButtonClass("outline","sm")}>Tam Detay</Link></div></div></StudioDrawer>;
}

function Compare({items,onClose}:{items:StudioRenderItem[];onClose:()=>void}){const[position,setPosition]=useState(50);return <div role="dialog" aria-modal="true" aria-label="Render karşılaştırması" className="fixed inset-0 z-50 bg-[#111]/95 p-4 text-white"><button onClick={onClose} className={studioButtonClass("outline","sm")}>Kapat</button><div className="relative mx-auto mt-5 aspect-video max-h-[80vh] max-w-6xl overflow-hidden rounded-xl"><Image src={items[0].thumbnailUrl} alt={`Önce: ${items[0].title}`} fill unoptimized className="object-contain"/><div className="absolute inset-0 overflow-hidden" style={{clipPath:`inset(0 ${100-position}% 0 0)`}}><Image src={items[1].thumbnailUrl} alt={`Sonra: ${items[1].title}`} fill unoptimized className="object-contain"/></div><input aria-label="Önce sonra karşılaştırma konumu" type="range" min="0" max="100" value={position} onChange={event=>setPosition(Number(event.target.value))} className="absolute bottom-5 left-[10%] w-[80%]"/></div></div>;}
function Presentation({items,start,onClose}:{items:StudioRenderItem[];start:number;onClose:()=>void}){const[index,setIndex]=useState(start);useEffect(()=>{function key(event:KeyboardEvent){if(event.key==="Escape")onClose();if(event.key==="ArrowRight")setIndex(value=>(value+1)%items.length);if(event.key==="ArrowLeft")setIndex(value=>(value-1+items.length)%items.length);}document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key);},[items.length,onClose]);const item=items[index];return <div role="dialog" aria-modal="true" aria-label="Render sunumu" className="fixed inset-0 z-50 grid bg-black text-white"><header className="flex items-center justify-between p-4"><strong className="tracking-[.2em]">ARZ MİMARLIK</strong><button onClick={onClose} className={studioButtonClass("outline","sm")}>Esc · Kapat</button></header><div className="relative min-h-0"><Image src={item.thumbnailUrl} alt={item.title} fill unoptimized className="object-contain"/></div><footer className="flex flex-wrap items-center justify-between gap-3 p-4"><div><h2 className="text-xl font-semibold">{item.title}</h2><p className="text-sm text-white/70">{item.description}</p></div><div className="flex gap-2"><button onClick={()=>setIndex(value=>(value-1+items.length)%items.length)} className={studioButtonClass("outline","sm")}>←</button><span>{index+1}/{items.length}</span><button onClick={()=>setIndex(value=>(value+1)%items.length)} className={studioButtonClass("outline","sm")}>→</button></div></footer></div>;}

export default function StudioRenderArchiveView({archive}:{archive:StudioRenderArchive}){
 const[selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false),[present,setPresent]=useState<number|null>(null),[detail,setDetail]=useState<StudioRenderItem|null>(null),[view,setView]=useState<"grid"|"masonry">("grid"),[pending,start]=useTransition(),[message,setMessage]=useState("");
 const selectedItems=useMemo(()=>archive.renders.filter(item=>selected.includes(item.id)),[archive.renders,selected]);
 function bulk(input:{clientVisible?:boolean;presented?:boolean;archived?:boolean}){start(async()=>setMessage((await setRenderFlagsAction(archive.project.id,selected,input)).message));}
 const presentItem=(item:StudioRenderItem)=>{const index=archive.renders.findIndex(render=>render.id===item.id);if(index>=0)setPresent(index);};
 return <section className="studio-render-gallery"><div className="studio-render-gallery__header"><StudioIconSurface icon="image" tone="blue" size="sm"/><StudioSectionHeader title="Render Koleksiyonları" description="Görsel sunumlar, revizyonlar ve proje teslimleri" count={`${archive.renders.length} render`} action={<div className="studio-render-view-toggle" role="group" aria-label="Galeri görünümü"><button type="button" aria-pressed={view==="grid"} onClick={()=>setView("grid")}><StudioIcon name="dashboard"/>Grid</button><button type="button" aria-pressed={view==="masonry"} onClick={()=>setView("masonry")}><StudioIcon name="files"/>Masonry</button></div>}/></div>
  {selected.length?<div className="studio-render-selection"><strong>{selected.length} render seçildi</strong><button disabled={selected.length!==2} onClick={()=>setCompare(true)} className={studioButtonClass("outline","sm")}>Karşılaştır</button><button disabled={pending} onClick={()=>start(async()=>setMessage((await favoriteRenderFilesAction(archive.project.id,selectedItems.map(item=>item.fileId))).message))} className={studioButtonClass("outline","sm")}>Favorile</button><button disabled={pending} onClick={()=>bulk({presented:true})} className={studioButtonClass("outline","sm")}>Sunuldu</button><button disabled={pending} onClick={()=>bulk({clientVisible:true})} className={studioButtonClass("outline","sm")}>Müşteriye Aç</button><button disabled={pending} onClick={()=>start(async()=>setMessage((await sendRenderBulkWhatsAppAction(archive.project.id,selectedItems.map(item=>({id:item.id,message:item.description||`${archive.project.name} · ${item.title}`})))).message))} className={studioButtonClass("outline","sm")}>WhatsApp</button><button disabled={pending} onClick={()=>bulk({archived:true})} className={studioButtonClass("danger","sm")}>Arşivle</button><button type="button" onClick={()=>setSelected([])} className={studioButtonClass("ghost","sm")}>Seçimi Temizle</button></div>:null}
  {message?<p role="status" className="studio-render-message">{message}</p>:null}
  {archive.renders.length?<div className={view==="grid"?"studio-render-grid grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-3":"studio-render-masonry"}>{archive.renders.map((render,index)=><RenderCard key={render.id} render={render} archive={archive} selected={selected.includes(render.id)} toggle={()=>setSelected(values=>values.includes(render.id)?values.filter(id=>id!==render.id):[...values,render.id])} openPresent={()=>setPresent(index)} openDetail={()=>setDetail(render)}/>)}</div>:<StudioEmptyState icon="image" title="Henüz render yüklenmedi" description="İlk renderınızı arşive ekleyerek görsel koleksiyonunuzu oluşturmaya başlayın." action={archive.canManage?<a href="#render-add" className={studioButtonClass("primary","sm")}>Render Ekle</a>:undefined}/>}
  <RenderDetailDrawer archive={archive} render={detail} onClose={()=>setDetail(null)} openPresent={()=>{if(detail)presentItem(detail);}}/>{compare&&selectedItems.length===2?<Compare items={selectedItems} onClose={()=>setCompare(false)}/>:null}{present!==null?<Presentation items={archive.renders} start={present} onClose={()=>setPresent(null)}/>:null}
 </section>;
}
