"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useMemo,useState,useTransition} from "react";
import StudioAiWritingDialog from "@/components/studio/ai/StudioAiWritingDialog";
import StudioFavoriteButton from "@/components/studio/quick-access/StudioFavoriteButton";
import {studioButtonClass} from "@/components/studio/StudioButton";
import type {StudioRenderArchive,StudioRenderItem} from "@/lib/studio/renders/render-types";
import {favoriteRenderFilesAction,sendRenderBulkWhatsAppAction,sendRenderWhatsAppAction,setHeroRenderAction,setRenderFlagsAction,updateRenderAction} from "@/app/studio/(protected)/projects/[projectId]/renders/actions";

function WhatsAppDialog({archive,render,text,onClose,onResult}:{archive:StudioRenderArchive;render:StudioRenderItem;text:string;onClose:()=>void;onResult:(value:string)=>void}){
  const[message,setMessage]=useState(text),[pending,start]=useTransition();
  return <div role="dialog" aria-modal="true" aria-labelledby={`render-whatsapp-${render.id}`} className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/55 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-5 shadow-xl"><h3 id={`render-whatsapp-${render.id}`} className="text-xl font-semibold">WhatsApp Önizlemesi</h3><p className="mt-2 text-sm text-[#68706f]">{render.title} · {render.file.extension.toUpperCase()} güvenli medya eki</p><label className="mt-4 block text-sm font-semibold">Müşteri mesajı<textarea value={message} onChange={event=>setMessage(event.target.value)} maxLength={3000} className="studio-field mt-2 min-h-48 w-full"/></label><p className="mt-2 text-right text-xs text-[#68706f]">{message.length} karakter</p><div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={onClose} className={studioButtonClass("ghost","sm")}>İptal</button><button type="button" disabled={pending||message.trim().length<10} onClick={()=>start(async()=>{const result=await sendRenderWhatsAppAction(archive.project.id,render.id,message);onResult(result.message);if(result.success)onClose()})} className={studioButtonClass("primary","sm")}>{pending?"Gönderiliyor…":"WhatsApp ile Gönder"}</button></div></div></div>;
}

function RenderCard({render,archive,selected,toggle,openPresent}:{render:StudioRenderItem;archive:StudioRenderArchive;selected:boolean;toggle:()=>void;openPresent:()=>void}){
  const[description,setDescription]=useState(render.description),[editing,setEditing]=useState(false),[whatsapp,setWhatsapp]=useState(false),[pending,start]=useTransition(),[message,setMessage]=useState("");
  const action=updateRenderAction.bind(null,archive.project.id,render.id);
  const defaultMessage=description||`${archive.project.name} projesine ait ${render.title} render çalışması sunuma hazırdır.`;
  return <article className="group min-w-0 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="relative aspect-[4/3] overflow-hidden bg-[#e6e2da]"><Image src={render.thumbnailUrl} alt={`${render.title} render önizlemesi`} fill sizes="(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 400px" unoptimized className="object-cover transition duration-300 group-hover:scale-[1.02]"/><label className="absolute left-3 top-3 rounded-lg bg-white/95 px-2 py-1 text-sm font-semibold"><input type="checkbox" checked={selected} onChange={toggle} className="mr-2"/>Seç</label><div className="absolute right-3 top-3"><StudioFavoriteButton entityType="file" entityId={render.fileId} initialFavorite={render.isFavorite} compact/></div>{render.isHero?<span className="absolute bottom-3 left-3 rounded-full bg-[#1f2930] px-3 py-1 text-xs font-bold text-white">Kapak Renderı</span>:null}</div>
    <div className="p-4 sm:p-5"><div className="flex min-w-0 flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h3 className="break-words text-lg font-semibold">{render.title}</h3><p className="mt-1 text-sm text-[#6d7472]">{render.categoryName} · V{render.file.versionNumber} · {render.file.fileSizeLabel}</p></div><div className="flex flex-wrap gap-1">{render.presentedAt?<span className="rounded-full border border-emerald-300 bg-emerald-50 px-2 py-1 text-xs font-semibold">Sunuldu</span>:null}{description?<span className="rounded-full border bg-[#f5efe2] px-2 py-1 text-xs font-semibold">AI açıklaması var</span>:null}</div></div>
      <div className="mt-3 flex flex-wrap gap-1.5">{render.tags.slice(0,4).map(tag=><span key={tag} className="rounded-full border px-2 py-1 text-xs">{tag}</span>)}</div><p className="mt-3 line-clamp-3 text-sm leading-6 text-[#59615f]">{description||"Açıklama eklenmedi."}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-xs text-[#69706e]"><div><dt className="font-semibold">Çözünürlük</dt><dd>{render.width&&render.height?`${render.width} × ${render.height}`:"Belirtilmedi"}</dd></div><div><dt className="font-semibold">Oran</dt><dd>{render.aspectRatio}</dd></div><div><dt className="font-semibold">Format</dt><dd>{render.file.extension.toUpperCase()}</dd></div><div><dt className="font-semibold">Sürüm</dt><dd>{render.file.versionCount} sürüm</dd></div></dl>
      <div className="mt-4 flex flex-wrap gap-2"><Link href={`/studio/projects/${archive.project.id}/renders/${render.id}`} className={studioButtonClass("outline","sm")}>Önizle</Link><button type="button" onClick={openPresent} className={studioButtonClass("ghost","sm")}>Sunum</button>{archive.canManage?<><button type="button" onClick={()=>setEditing(value=>!value)} className={studioButtonClass("ghost","sm")}>Özellikler</button><button type="button" disabled={pending||render.isHero} onClick={()=>start(async()=>setMessage((await setHeroRenderAction(archive.project.id,render.id)).message))} className={studioButtonClass("outline","sm")}>Kapak Yap</button></>:null}</div>
      {archive.canManage&&editing?<form action={async formData=>{const result=await action(formData);setMessage(result.message);if(result.success)setEditing(false)}} className="mt-4 grid gap-3 border-t pt-4"><label className="text-sm font-semibold">Başlık<input name="title" defaultValue={render.title} className="studio-field mt-1 w-full" required/></label><label className="text-sm font-semibold">Kategori<select name="categoryId" defaultValue={render.categoryId??""} className="studio-field mt-1 w-full"><option value="">Diğer</option>{archive.categories.filter(item=>!item.isArchived).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-sm font-semibold">Genişlik<input name="width" type="number" min="1" defaultValue={render.width??""} className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Yükseklik<input name="height" type="number" min="1" defaultValue={render.height??""} className="studio-field mt-1 w-full"/></label></div><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">Açıklama</span><StudioAiWritingDialog operation="render_description" title="AI Render Açıklaması" triggerLabel="AI ile Oluştur" currentText={description} context={{projectName:archive.project.name,category:render.categoryName,tags:render.tags,userNote:description}} onUse={setDescription}/></div><textarea name="description" value={description} onChange={event=>setDescription(event.target.value)} maxLength={3000} className="studio-field min-h-32 w-full"/><button className={studioButtonClass("primary","sm")}>Kaydet</button></form>:null}
      {archive.canManage?<div className="mt-4 border-t pt-4"><button type="button" onClick={()=>setWhatsapp(true)} className={studioButtonClass("primary","sm")}>WhatsApp ile Gönder</button></div>:null}{message?<p role="status" className="mt-3 text-sm">{message}</p>:null}
    </div>{whatsapp?<WhatsAppDialog archive={archive} render={render} text={defaultMessage} onClose={()=>setWhatsapp(false)} onResult={setMessage}/>:null}</article>;
}

function Compare({items,onClose}:{items:StudioRenderItem[];onClose:()=>void}){const[position,setPosition]=useState(50);return <div role="dialog" aria-modal="true" aria-label="Render karşılaştırması" className="fixed inset-0 z-50 bg-[#111]/95 p-4 text-white"><button onClick={onClose} className={studioButtonClass("outline","sm")}>Kapat</button><div className="relative mx-auto mt-5 aspect-video max-h-[80vh] max-w-6xl overflow-hidden rounded-xl"><Image src={items[0].thumbnailUrl} alt={`Önce: ${items[0].title}`} fill unoptimized className="object-contain"/><div className="absolute inset-0 overflow-hidden" style={{clipPath:`inset(0 ${100-position}% 0 0)`}}><Image src={items[1].thumbnailUrl} alt={`Sonra: ${items[1].title}`} fill unoptimized className="object-contain"/></div><input aria-label="Önce sonra karşılaştırma konumu" type="range" min="0" max="100" value={position} onChange={event=>setPosition(Number(event.target.value))} className="absolute bottom-5 left-[10%] w-[80%]"/></div></div>}
function Presentation({items,start,onClose}:{items:StudioRenderItem[];start:number;onClose:()=>void}){const[index,setIndex]=useState(start);useEffect(()=>{function key(event:KeyboardEvent){if(event.key==="Escape")onClose();if(event.key==="ArrowRight")setIndex(value=>(value+1)%items.length);if(event.key==="ArrowLeft")setIndex(value=>(value-1+items.length)%items.length)}document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[items.length,onClose]);const item=items[index];return <div role="dialog" aria-modal="true" aria-label="Render sunumu" className="fixed inset-0 z-50 grid bg-black text-white"><header className="flex items-center justify-between p-4"><strong className="tracking-[.2em]">ARZ MİMARLIK</strong><button onClick={onClose} className={studioButtonClass("outline","sm")}>Esc · Kapat</button></header><div className="relative min-h-0"><Image src={item.thumbnailUrl} alt={item.title} fill unoptimized className="object-contain"/></div><footer className="flex flex-wrap items-center justify-between gap-3 p-4"><div><h2 className="text-xl font-semibold">{item.title}</h2><p className="text-sm text-white/70">{item.description}</p></div><div className="flex gap-2"><button onClick={()=>setIndex(value=>(value-1+items.length)%items.length)} className={studioButtonClass("outline","sm")}>←</button><span>{index+1}/{items.length}</span><button onClick={()=>setIndex(value=>(value+1)%items.length)} className={studioButtonClass("outline","sm")}>→</button></div></footer></div>}

export default function StudioRenderArchiveView({archive}:{archive:StudioRenderArchive}){
  const[selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false),[present,setPresent]=useState<number|null>(null),[pending,start]=useTransition(),[message,setMessage]=useState("");
  const selectedItems=useMemo(()=>archive.renders.filter(item=>selected.includes(item.id)),[archive.renders,selected]);
  function bulk(input:{clientVisible?:boolean;presented?:boolean;archived?:boolean}){start(async()=>setMessage((await setRenderFlagsAction(archive.project.id,selected,input)).message))}
  return <section className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">Render Koleksiyonları</h2><p className="mt-1 text-sm text-[#68706f]">{archive.renders.length} render · {archive.categories.filter(item=>!item.isArchived).length} kategori</p></div>{selected.length?<div className="flex flex-wrap gap-2 rounded-xl border bg-white p-2"><button disabled={selected.length!==2} onClick={()=>setCompare(true)} className={studioButtonClass("outline","sm")}>Karşılaştır</button><button disabled={pending} onClick={()=>start(async()=>setMessage((await favoriteRenderFilesAction(archive.project.id,selectedItems.map(item=>item.fileId))).message))} className={studioButtonClass("outline","sm")}>Favorile</button><button disabled={pending} onClick={()=>bulk({presented:true})} className={studioButtonClass("outline","sm")}>Sunuldu</button><button disabled={pending} onClick={()=>bulk({clientVisible:true})} className={studioButtonClass("outline","sm")}>Müşteriye Aç</button><button disabled={pending} onClick={()=>start(async()=>setMessage((await sendRenderBulkWhatsAppAction(archive.project.id,selectedItems.map(item=>({id:item.id,message:item.description||`${archive.project.name} · ${item.title}`})))).message))} className={studioButtonClass("outline","sm")}>WhatsApp</button><button disabled={pending} onClick={()=>bulk({archived:true})} className={studioButtonClass("danger","sm")}>Arşivle</button></div>:null}</div>{message?<p role="status" className="mt-3 rounded-lg border bg-white p-3 text-sm">{message}</p>:null}{archive.renders.length?<div className="mt-5 grid min-w-0 gap-5 sm:grid-cols-2 xl:grid-cols-3">{archive.renders.map((render,index)=><RenderCard key={render.id} render={render} archive={archive} selected={selected.includes(render.id)} toggle={()=>setSelected(values=>values.includes(render.id)?values.filter(id=>id!==render.id):[...values,render.id])} openPresent={()=>setPresent(index)}/>)}</div>:<p className="mt-5 rounded-xl border border-dashed p-10 text-center">Render arşivinde kayıt bulunmuyor.</p>}{compare&&selectedItems.length===2?<Compare items={selectedItems} onClose={()=>setCompare(false)}/>:null}{present!==null?<Presentation items={archive.renders} start={present} onClose={()=>setPresent(null)}/>:null}</section>;
}
