"use client";
import {useState} from "react";
import {StudioCard,StudioInput,StudioSectionHeader} from "@/components/studio/ui";
import {studioButtonClass} from "@/components/studio/StudioButton";
export default function StudioClientInvitationLink({projectId,defaultEmail}:{projectId:string;defaultEmail:string}){
 const[email,setEmail]=useState(defaultEmail);const[url,setUrl]=useState("");const[message,setMessage]=useState("");const[pending,setPending]=useState(false);
 async function create(){setPending(true);setMessage("");setUrl("");try{const response=await fetch(`/api/studio/projects/${projectId}/client-invitations`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,expiresAt:new Date(Date.now()+7*86400000).toISOString()})});const result=await response.json() as{error?:string;invitationUrl?:string};if(!response.ok||!result.invitationUrl)throw new Error(result.error||"Davet oluşturulamadı.");setUrl(result.invitationUrl);setMessage("Davet bağlantısı oluşturuldu. Sayfa yenilendiğinde tekrar gösterilmez.");}catch(caught){setMessage(caught instanceof Error?caught.message:"Davet oluşturulamadı.");}finally{setPending(false);}}
 async function copy(){if(!url)return;try{await navigator.clipboard.writeText(url);setMessage("Davet bağlantısı panoya kopyalandı.");}catch{setMessage("Bağlantı kopyalanamadı. Metni seçerek kopyalayın.");}}
 return <StudioCard as="section" className="p-4"><StudioSectionHeader title="Müşteri Portalı Daveti" description="Tek kullanımlık güvenli portal bağlantısı" icon="messages"/><div className="mt-4 grid gap-3 md:grid-cols-[minmax(0,1fr)_auto]"><StudioInput id="client-invite-email" label="Müşteri e-postası" type="email" required value={email} onChange={event=>setEmail(event.target.value)}/><button type="button" disabled={pending||!email} onClick={create} className={`${studioButtonClass("primary","sm")} self-end`}>{pending?"Oluşturuluyor…":"Davet Linki Oluştur"}</button></div>{url?<div className="mt-4 rounded-xl border border-[#dce5ec] bg-[#f7f9fc] p-3"><label className="block text-[11px] font-semibold text-[#64748b]">Yalnız şimdi gösterilen bağlantı<input readOnly value={url} onFocus={event=>event.currentTarget.select()} className="mt-2 h-10 w-full rounded-lg border border-[#dce5ec] bg-white px-3 text-xs text-[#334155]"/></label><button type="button" onClick={copy} className={`${studioButtonClass("outline","sm")} mt-3`}>Kopyala</button></div>:null}{message?<p role="status" className="mt-3 text-sm text-[#64748b]">{message}</p>:null}</StudioCard>;
}
