"use client";

import {useRouter} from "next/navigation";
import {useState} from "react";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioBadge,StudioCard,StudioEmptyState,StudioModal,StudioSectionHeader} from "@/components/studio/ui";
import type {ClientAccessEvent,ClientInvitation,ClientProjectAccess} from "@/lib/studio/client-access/client-access-repository";

const date=(value:string|null)=>value?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
const invitationLabels={pending:"Bekliyor",accepted:"Kabul edildi",expired:"Süresi doldu",revoked:"İptal edildi"} as const;
const invitationVariants={pending:"warning",accepted:"success",expired:"archived",revoked:"danger"} as const;
const eventLabels:Record<string,string>={client_invitation_created:"Davet oluşturuldu",client_invitation_revoked:"Davet iptal edildi",client_invitation_accepted:"Davet kabul edildi",client_project_access_granted:"Proje erişimi verildi",client_project_access_revoked:"Proje erişimi kaldırıldı"};
type Action={kind:"revoke-invitation"|"renew-invitation"|"revoke-access";id:string;label:string}|null;

export default function StudioClientAccessManager({projectId,invitations,accesses,events}:{projectId:string;invitations:ClientInvitation[];accesses:ClientProjectAccess[];events:ClientAccessEvent[]}){
 const router=useRouter();const[action,setAction]=useState<Action>(null);const[pending,setPending]=useState(false);const[message,setMessage]=useState("");const[renewedUrl,setRenewedUrl]=useState("");
 async function execute(){if(!action)return;setPending(true);setMessage("");setRenewedUrl("");try{const path=action.kind==="revoke-access"?`/api/studio/projects/${projectId}/client-access/${action.id}`:`/api/studio/projects/${projectId}/client-invitations/${action.id}${action.kind==="renew-invitation"?"/renew":""}`;const response=await fetch(path,{method:action.kind==="renew-invitation"?"POST":"DELETE"});const result=await response.json() as{error?:string;invitationUrl?:string;emailDelivery?:string};if(!response.ok)throw new Error(result.error||"İşlem tamamlanamadı.");if(result.invitationUrl){setRenewedUrl(result.invitationUrl);setMessage(result.emailDelivery==="sent"?"Yeni davet oluşturuldu ve e-posta gönderildi.":"Yeni davet oluşturuldu. Bağlantı yalnız şimdi gösterilir; e-posta gönderilemedi veya yapılandırılmadı.");}else setMessage(action.kind==="revoke-access"?"Müşteri erişimi kaldırıldı.":"Davet iptal edildi.");setAction(null);router.refresh();}catch(caught){setMessage(caught instanceof Error?caught.message:"İşlem tamamlanamadı.");}finally{setPending(false);}}
 async function copy(){try{await navigator.clipboard.writeText(renewedUrl);setMessage("Yeni davet bağlantısı panoya kopyalandı.");}catch{setMessage("Bağlantı kopyalanamadı.");}}
 return <div className="grid gap-4">
  {renewedUrl?<StudioCard className="p-4"><p className="text-sm font-semibold text-[#17232e]">Yenilenen davet bağlantısı</p><input readOnly value={renewedUrl} onFocus={event=>event.currentTarget.select()} className="mt-2 h-10 w-full rounded-lg border border-[#dce5ec] bg-white px-3 text-xs text-[#334155]"/><button type="button" onClick={copy} className={`${studioButtonClass("outline","sm")} mt-3`}>Kopyala</button></StudioCard>:null}
  {message?<p role="status" className="text-sm text-[#64748b]">{message}</p>:null}
  <StudioCard as="section" className="p-4"><StudioSectionHeader title="Proje Erişimleri" description="Kabul edilmiş müşteri hesapları ve erişim durumu" icon="clients" count={accesses.length}/><div className="mt-4 grid gap-3">{accesses.length?accesses.map(item=><div key={item.accessId} className="flex flex-col gap-3 rounded-xl border border-[#e3e9ee] p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-[#17232e]">{item.fullName||item.email||"Müşteri"}</p><StudioBadge variant={item.revokedAt?"danger":"success"}>{item.revokedAt?"Erişim kaldırıldı":"Aktif erişim"}</StudioBadge></div><p className="mt-1 truncate text-xs text-[#64748b]">{item.email||"E-posta bilgisi yok"}</p><p className="mt-1 text-xs text-[#94a3b8]">Verildi: {date(item.grantedAt)}{item.revokedAt?` · Kaldırıldı: ${date(item.revokedAt)}`:""}</p></div>{!item.revokedAt?<button type="button" onClick={()=>setAction({kind:"revoke-access",id:item.userId,label:item.email||item.fullName||"müşteri"})} className={studioButtonClass("danger","sm")}>Erişimi Kaldır</button>:null}</div>):<StudioEmptyState title="Henüz müşteri erişimi yok" description="Davet kabul edildiğinde erişim burada görünür." icon="clients"/>}</div></StudioCard>
  <StudioCard as="section" className="p-4"><StudioSectionHeader title="Davet Geçmişi" description="Bekleyen, kabul edilen, süresi dolan ve iptal edilen davetler" icon="messages" count={invitations.length}/><div className="mt-4 grid gap-3">{invitations.length?invitations.map(item=><div key={item.id} className="flex flex-col gap-3 rounded-xl border border-[#e3e9ee] p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-[#17232e]">{item.invitedUserName||item.invitedEmail}</p><StudioBadge variant={invitationVariants[item.status]}>{invitationLabels[item.status]}</StudioBadge></div><p className="mt-1 truncate text-xs text-[#64748b]">{item.invitedEmail}</p><p className="mt-1 text-xs text-[#94a3b8]">Oluşturuldu: {date(item.createdAt)} · Son kullanım: {date(item.expiresAt)}{item.acceptedAt?` · Kabul: ${date(item.acceptedAt)}`:""}</p></div>{item.status==="pending"?<div className="flex gap-2"><button type="button" onClick={()=>setAction({kind:"renew-invitation",id:item.id,label:item.invitedEmail})} className={studioButtonClass("outline","sm")}>Yenile</button><button type="button" onClick={()=>setAction({kind:"revoke-invitation",id:item.id,label:item.invitedEmail})} className={studioButtonClass("danger","sm")}>İptal Et</button></div>:null}</div>):<StudioEmptyState title="Henüz davet yok" description="Yeni müşteri davetleri burada listelenir." icon="messages"/>}</div></StudioCard>
  <StudioCard as="section" className="p-4"><StudioSectionHeader title="Erişim Hareketleri" description="Davet ve proje erişimi yaşam döngüsü" icon="activity" count={events.length}/><div className="mt-4 grid gap-3">{events.length?events.map(item=><div key={item.id} className="border-b border-[#edf1f4] pb-3 last:border-0 last:pb-0"><p className="text-sm font-medium text-[#334155]">{eventLabels[item.action]||item.summary}</p><p className="mt-1 text-xs text-[#94a3b8]">{item.actorName||"Sistem"} · {date(item.createdAt)}</p></div>):<StudioEmptyState title="Henüz erişim hareketi yok" description="Davet ve erişim işlemleri burada görünür." icon="activity"/>}</div></StudioCard>
  <StudioModal open={Boolean(action)} title={action?.kind==="renew-invitation"?"Daveti yenile":action?.kind==="revoke-access"?"Müşteri erişimini kaldır":"Daveti iptal et"} onClose={()=>!pending&&setAction(null)} footer={<><button type="button" disabled={pending} onClick={()=>setAction(null)} className={studioButtonClass("outline","sm")}>Vazgeç</button><button type="button" disabled={pending} onClick={execute} className={studioButtonClass(action?.kind==="renew-invitation"?"primary":"danger","sm")}>{pending?"İşleniyor…":action?.kind==="renew-invitation"?"Yenile":"Onayla"}</button></>}><p className="text-sm leading-6 text-[#64748b]">{action?.kind==="renew-invitation"?`${action.label} için mevcut bekleyen davet iptal edilip yeni 7 günlük bağlantı oluşturulacak.`:action?.kind==="revoke-access"?`${action?.label} için portal proje erişimi ve güvenli dosya/önizleme yetkileri hemen kesilecek.`:`${action?.label} adresine ait bekleyen davet kullanılamaz hale gelecek.`}</p></StudioModal>
 </div>;
}
