"use client";

import {useState,useTransition} from "react";
import {preparePermanentProjectDeletionAction,permanentlyDeleteProjectAction} from "@/app/studio/(protected)/projects/actions";
import {StudioIcon} from "@/components/studio/StudioIcons";

const reasons=["Test projesi","Yanlış oluşturuldu","Mükerrer","Müşteri iptal etti","Diğer"] as const;
export default function StudioPermanentDeleteDialog({projectId,projectName}:{projectId:string;projectName:string}){
 const[open,setOpen]=useState(false);const[step,setStep]=useState<1|2>(1);const[name,setName]=useState("");const[reason,setReason]=useState("");const[token,setToken]=useState("");const[error,setError]=useState("");const[pending,startTransition]=useTransition();
 const matches=name.trim().toLocaleLowerCase("tr-TR")===projectName.trim().toLocaleLowerCase("tr-TR");
 function close(){if(pending)return;setOpen(false);setStep(1);setName("");setReason("");setToken("");setError("");}
 function continueToFinal(){setError("");startTransition(async()=>{const result=await preparePermanentProjectDeletionAction(projectId,projectName);if(result.ok){setToken(result.token);setStep(2);}else setError(result.message);});}
 function confirm(){setError("");startTransition(async()=>{const result=await permanentlyDeleteProjectAction(projectId,token,reason);if(result?.ok===false)setError(result.message);});}
 return <>
  <button type="button" onClick={()=>setOpen(true)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-[#d9a7a7] bg-[#fff7f7] px-4 py-2 text-[10px] font-semibold text-[#9a3030] transition hover:bg-[#ffecec] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9a3030]/40" aria-haspopup="dialog"><StudioIcon name="close" className="h-3.5 w-3.5"/>Kalıcı Sil</button>
  {open?<div className="fixed inset-0 z-50 grid place-items-center bg-[#17222c]/55 p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="permanent-delete-title" className="w-full max-w-lg rounded-2xl border border-[#e2d8d0] bg-[#fffdfa] p-6 shadow-2xl">
   <div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#fff0f0] text-[#a53030]"><StudioIcon name="close" className="h-4 w-4"/></div><div><h2 id="permanent-delete-title" className="text-lg font-semibold text-[#2d3438]">Kalıcı Sil</h2><p className="mt-1 text-[12px] text-[#9a3030]">Bu işlem geri alınamaz.</p></div></div>
   {step===1?<><p className="mt-5 text-[12px] text-[#555d60]">Aşağıdaki proje ilişkileri kalıcı olarak kaldırılacaktır:</p><ul className="mt-3 grid gap-1 text-[11px] text-[#62686a] sm:grid-cols-2">{["Proje","Dosyalar ve versiyonları","Render Arşivi","Finans ve tahsilatlar","Resmî süreçler","Görevler ve kilometre taşları","AI kullanım ilişkileri","Timeline, favoriler ve son açılanlar","Thumbnail kayıtları","Projeye bağlı diğer ilişkiler"].map(item=><li key={item}>• {item}</li>)}</ul><label className="mt-5 block text-[11px] font-semibold text-[#41494c]">Devam etmek için proje adını yazın<input autoFocus value={name} onChange={event=>setName(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#d8d1c7] bg-white px-3 text-[12px] outline-none focus:border-[#a53030] focus:ring-2 focus:ring-[#a53030]/15" aria-describedby="delete-name-help"/><span id="delete-name-help" className="mt-1 block text-[10px] font-normal text-[#85898a]">Birebir eşleşme gerekir: {projectName}</span></label><label className="mt-4 block text-[11px] font-semibold text-[#41494c]">Silme nedeni (isteğe bağlı)<select value={reason} onChange={event=>setReason(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-[#d8d1c7] bg-white px-3 text-[12px]"><option value="">Belirtilmedi</option>{reasons.map(value=><option key={value}>{value}</option>)}</select></label>{error?<p role="alert" className="mt-3 text-[11px] text-[#a53030]">{error}</p>:null}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={close} className="min-h-10 rounded-lg border border-[#d8d1c7] px-4 text-[11px] text-[#4f5659]">Vazgeç</button><button type="button" onClick={continueToFinal} disabled={!matches||pending} className="min-h-10 rounded-lg bg-[#9a3030] px-4 text-[11px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45">{pending?"Hazırlanıyor…":"Devam Et"}</button></div></>:<><p className="mt-6 text-[13px] leading-6 text-[#343b3e]">“{projectName}” projesi ve bağlı tüm kayıtlar kalıcı olarak silinecek. Bu işlem geri alınamaz.</p>{error?<p role="alert" className="mt-3 text-[11px] text-[#a53030]">{error}</p>:null}<div className="mt-7 flex justify-end gap-2"><button type="button" onClick={close} disabled={pending} className="min-h-10 rounded-lg border border-[#d8d1c7] px-4 text-[11px] text-[#4f5659]">Vazgeç</button><button type="button" onClick={confirm} disabled={pending} className="min-h-10 rounded-lg bg-[#9a3030] px-4 text-[11px] font-semibold text-white disabled:opacity-50">{pending?"Siliniyor…":"Kalıcı Olarak Sil"}</button></div></>}
  </section></div>:null}
 </>;
}
