import {StudioIcon} from "@/components/studio/StudioIcons";
import {projectStages,projectStatuses} from "@/components/studio/projects/StudioProjectData";
import type {ProjectArchiveFilter} from "@/lib/studio/projects/project-types";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioFilterBar} from "@/components/studio/ui";
export type ProjectFilters={query?:string;status?:string;stage?:string;archive?:ProjectArchiveFilter;favoritesOnly?:boolean};
export default function StudioProjectsFilters({filters}:{filters:ProjectFilters}){
 return <form method="get" action="/studio/projects" className="mt-5"><StudioFilterBar><label className="relative min-w-0 flex-1 basis-56"><span className="sr-only">Projelerde ara</span><StudioIcon name="search" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#92948f]"/><input name="q" defaultValue={filters.query} type="search" placeholder="Proje, müşteri, kod veya konum ara..." className="studio-filter-input pl-10"/></label><label><span className="sr-only">Arşiv filtresi</span><select name="archive" defaultValue={filters.archive||"active"} className="studio-filter-select"><option value="active">Aktif Projeler</option><option value="archived">Arşiv</option><option value="all">Tümü</option></select></label><label><span className="sr-only">Durum filtresi</span><select name="status" defaultValue={filters.status||""} className="studio-filter-select"><option value="">Tüm durumlar</option>{projectStatuses.map((status)=><option key={status} value={status}>{status}</option>)}</select></label><label><span className="sr-only">Aşama filtresi</span><select name="stage" defaultValue={filters.stage||""} className="studio-filter-select"><option value="">Tüm aşamalar</option>{projectStages.map((stage)=><option key={stage} value={stage}>{stage}</option>)}</select></label><label className="studio-checkbox"><input type="checkbox" name="favorites" value="1" defaultChecked={filters.favoritesOnly}/><span>Sadece Favoriler</span></label><button type="submit" className={studioButtonClass("primary","sm")}>Filtrele</button></StudioFilterBar></form>;
}
