import {NextResponse} from "next/server";
import {createStudioFileVersionDownload} from "@/lib/studio/files/versions/version-repository";

export const dynamic="force-dynamic";

function disposition(name:string,inline=false){const ascii=name.normalize("NFKD").replace(/[^\x20-\x7E]/g,"_").replace(/["\\]/g,"-");return`${inline?"inline":"attachment"}; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(name)}`;}
function streamed(response:Response,fileName:string,inline:boolean){const headers=new Headers({"Content-Type":response.headers.get("content-type")??"application/octet-stream","Content-Disposition":disposition(fileName,inline),"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"});if(inline&&headers.get("content-type")?.toLowerCase().includes("image/svg"))headers.set("Content-Security-Policy","default-src 'none'; sandbox");const length=response.headers.get("content-length");if(length)headers.set("Content-Length",length);return new Response(response.body,{status:response.status,headers});}

export async function GET(request:Request,{params}:{params:Promise<{projectId:string;fileId:string;versionId:string}>}){try{const{projectId,fileId,versionId}=await params;const preview=new URL(request.url).searchParams.get("preview")==="1";const result=await createStudioFileVersionDownload(projectId,fileId,versionId);if(result.kind==="stream")return streamed(result.response,result.fileName,preview);if(preview){const privateResponse=await fetch(result.url,{cache:"no-store"});if(!privateResponse.ok)throw new Error("private preview stream failed");return streamed(privateResponse,result.fileName,true);}return NextResponse.redirect(result.url,{status:303});}catch{return new NextResponse("Sürüm dosyası bulunamadı veya erişim reddedildi.",{status:404,headers:{"Cache-Control":"private, no-store","Content-Type":"text/plain; charset=utf-8"}});}}
