"use client";
import{useEffect,useRef,useState,useTransition}from"react";
import{generateStudioFormTextAction}from"@/app/studio/(protected)/ai-writing-actions";
import{studioButtonClass}from"@/components/studio/StudioButton";
import type{StudioAiOperation,StudioAiOutputFormat}from"@/lib/studio/ai/ai-writing-types";
type Props={operation:StudioAiOperation;title:string;triggerLabel:string;currentText:string;context:Record<string,string|string[]|null>;onUse:(text:string)=>void;allowFormat?:boolean};
export default function StudioAiWritingDialog({operation,title,triggerLabel,currentText,context,onUse,allowFormat=false}:Props){
 const[open,setOpen]=useState(false),[text,setText]=useState(""),[message,setMessage]=useState(""),[format,setFormat]=useState<StudioAiOutputFormat>("paragraph");const[pending,start]=useTransition();const closeRef=useRef<HTMLButtonElement>(null),dialogRef=useRef<HTMLDivElement>(null);
 function generate(){setMessage("");start(async()=>{const result=await generateStudioFormTextAction(operation,context,currentText,format);if(!result.success){setMessage(result.message??"AI metni şu anda oluşturulamadı.");return}setText(result.text);setMessage(result.message??"");setOpen(true);});}
 useEffect(()=>{if(!open)return;closeRef.current?.focus();function key(event:KeyboardEvent){if(event.key==="Escape")setOpen(false);if(event.key==="Tab"){const nodes=dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),textarea,select');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[open]);
 return <><button type="button" disabled={pending} onClick={generate} className={studioButtonClass("outline","sm")}>{pending?"Oluşturuluyor…":`✨ ${triggerLabel}`}</button>{open?<div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby={`ai-${operation}`} className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/50 p-4"><div className="w-full max-w-2xl rounded-xl bg-white p-5 shadow-xl sm:p-6"><h3 id={`ai-${operation}`} className="text-xl font-semibold">{title}</h3>{allowFormat?<label className="mt-4 block text-sm font-semibold">Biçim<select value={format} onChange={event=>setFormat(event.target.value as StudioAiOutputFormat)} className="studio-field mt-2 w-full"><option value="paragraph">Kısa paragraf</option><option value="bullets">Maddeli özet</option></select></label>:null}<label className="mt-4 block text-sm font-semibold">AI çıktısı<textarea value={text} onChange={event=>setText(event.target.value)} maxLength={10000} className="mt-2 min-h-56 w-full rounded-lg border p-3 text-[15px] leading-6"/></label><p className="mt-2 text-right text-sm text-slate-600" aria-live="polite">{text.length} karakter</p>{message?<p role="status" aria-live="polite" className="mt-2 text-sm text-amber-700">{message}</p>:null}<div className="mt-5 flex flex-wrap justify-end gap-2"><button ref={closeRef} type="button" onClick={()=>setOpen(false)} className={studioButtonClass("ghost","sm")}>İptal</button><button type="button" disabled={pending} onClick={generate} className={studioButtonClass("outline","sm")}>Yeniden Oluştur</button><button type="button" disabled={!text.trim()} onClick={()=>{onUse(text);setOpen(false)}} className={studioButtonClass("primary","sm")}>Kullan</button></div></div></div>:null}</>;
}
