import Link from "next/link";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioIcon} from "@/components/studio/StudioIcons";
import {STUDIO_CATEGORY_LABELS,STUDIO_FILE_CATEGORIES} from "@/lib/studio/files/file-constants";
import type {StudioFileWorkspace} from "@/lib/studio/files/file-types";
import StudioFileTypeIcon from "./StudioFileTypeIcon";
import StudioFileUpload from "./StudioFileUpload";
import StudioFolderActions from "./StudioFolderActions";
import StudioFolderForm from "./StudioFolderForm";
import StudioSyncStatus from "./StudioSyncStatus";

export default function StudioProjectFilesPage({workspace}:{workspace:StudioFileWorkspace}){
 const folderId=workspace.currentFolder?.id??"";
 return <section className="mx-auto min-w-0 max-w-[1540px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8 lg:py-9">
  <header className="flex flex-col justify-between gap-5 border-b border-[#ddd8ce] pb-6 lg:flex-row lg:items-end"><div><Link href={`/studio/projects/${workspace.project.id}`} className="text-[13px] font-semibold uppercase tracking-[.1em] text-[#8e784d]">← {workspace.project.code} · {workspace.project.name}</Link><h1 className="mt-3 text-[30px] font-semibold tracking-[-.04em] text-[#1e272f]">Dosyalar</h1><p className="mt-2 text-sm leading-6 text-[#68706f]">Projenin kontrollü klasör ve dosya çalışma alanı.</p></div><dl className="grid grid-cols-3 gap-3"><div className="rounded-lg border bg-white px-4 py-3"><dt className="text-[13px] text-[#707674]">Dosya</dt><dd className="mt-1 text-base font-semibold">{workspace.summary.fileCount}</dd></div><div className="rounded-lg border bg-white px-4 py-3"><dt className="text-[13px] text-[#707674]">Klasör</dt><dd className="mt-1 text-base font-semibold">{workspace.summary.folderCount}</dd></div><div className="rounded-lg border bg-white px-4 py-3"><dt className="text-[13px] text-[#707674]">Kullanım</dt><dd className="mt-1 text-base font-semibold">{workspace.summary.storageLabel}</dd></div></dl></header>
  <nav aria-label="Dosya klasör yolu" className="mt-5 flex flex-wrap items-center gap-2 text-sm"><Link href={`/studio/projects/${workspace.project.id}/files`} className="font-semibold text-[#806b45]">Kök</Link>{workspace.breadcrumbs.map(folder=><span key={folder.id} className="flex items-center gap-2"><span aria-hidden="true">/</span><span aria-current="page">{folder.name}</span></span>)}</nav>
  <form className="mt-4 grid gap-3 rounded-xl border border-[#dedad1] bg-white p-4 sm:grid-cols-2 lg:grid-cols-[minmax(220px,1fr)_180px_140px_auto]"><input type="hidden" name="folder" value={folderId}/><input name="q" aria-label="Dosyalarda ara" placeholder="Dosya adı ara" className="h-11 min-w-0 rounded-lg border bg-[#fbfaf7] px-3 text-sm"/><select name="category" aria-label="Kategori" className="h-11 rounded-lg border bg-white px-3 text-sm"><option value="">Tüm kategoriler</option>{STUDIO_FILE_CATEGORIES.map(value=><option key={value} value={value}>{STUDIO_CATEGORY_LABELS[value]}</option>)}</select><select name="archive" aria-label="Arşiv görünümü" className="h-11 rounded-lg border bg-white px-3 text-sm"><option value="active">Aktif</option><option value="archived">Arşiv</option><option value="all">Tümü</option></select><button className={studioButtonClass("primary","sm")}>Filtrele</button></form>
  {workspace.canManage?<div className="mt-5 space-y-3"><StudioFileUpload projectId={workspace.project.id} folderId={folderId}/><StudioFolderForm projectId={workspace.project.id} parentFolderId={folderId}/></div>:null}
  <section className="mt-7" aria-labelledby="folders-title"><h2 id="folders-title" className="text-lg font-semibold">Klasörler</h2>{workspace.folders.length?<div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{workspace.folders.map(folder=><article key={folder.id} className="rounded-xl border border-[#dedad1] bg-white p-4 shadow-[0_4px_18px_rgba(32,39,46,.03)]"><Link href={`/studio/projects/${workspace.project.id}/files?folder=${folder.id}${folder.isArchived?"&archive=all":""}`} className="flex min-w-0 items-center gap-3 rounded-md focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#9b8253]"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-[#f2eee5] text-[#8d7548]"><StudioIcon name="folder" className="h-5 w-5"/></span><div className="min-w-0"><h3 className="truncate text-base font-semibold">{folder.name}</h3><p className="mt-1 text-[13px] text-[#707674]">{folder.isArchived?"Arşivlenmiş klasör":folder.isSystem?"Sistem klasörü":"Özel klasör"}</p></div></Link><div className="mt-3"><StudioSyncStatus status={folder.syncStatus}/></div>{workspace.canManage?<div className="mt-4 border-t pt-4"><StudioFolderActions projectId={workspace.project.id} folder={folder} folders={workspace.availableFolders}/></div>:null}</article>)}</div>:<p className="mt-3 rounded-xl border border-dashed bg-white/60 p-8 text-center text-sm text-[#69716f]">Bu konumda klasör bulunmuyor.</p>}</section>
  <section className="mt-7" aria-labelledby="files-title"><h2 id="files-title" className="text-lg font-semibold">Dosyalar</h2>{workspace.files.length?<div className="mt-3 overflow-hidden rounded-xl border border-[#dedad1] bg-white"><ul>{workspace.files.map(file=><li key={file.id} className="border-b last:border-b-0"><Link href={`/studio/projects/${workspace.project.id}/files/${file.id}`} className="grid min-w-0 gap-3 p-4 hover:bg-[#faf8f4] focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#9b8253] sm:grid-cols-[auto_minmax(0,1fr)_140px_120px_170px] sm:items-center"><StudioFileTypeIcon extension={file.extension}/><div className="min-w-0"><p className="truncate text-[15px] font-semibold">{file.displayName}</p><p className="mt-1 truncate text-[13px] text-[#707674]">{file.originalFileName}</p></div><span className="text-sm">{STUDIO_CATEGORY_LABELS[file.category]}</span><span className="text-sm text-[#69716f]">{file.fileSizeLabel}</span><div className="flex flex-col items-start gap-1.5"><StudioSyncStatus status={file.syncStatus}/><span className="text-[13px] text-[#69716f]">{file.createdAtLabel}</span></div></Link></li>)}</ul></div>:<div className="mt-3 rounded-xl border border-dashed bg-white/60 px-6 py-10 text-center"><h3 className="text-lg font-semibold">{workspace.currentFolder?"Bu klasör henüz boş.":"Henüz dosya yüklenmemiş."}</h3><p className="mt-2 text-sm leading-6 text-[#6f7674]">{workspace.canManage?"Yukarıdaki güvenli yükleme alanından ilk dosyayı ekleyin.":"Dosya yüklendiğinde burada görüntülenecek."}</p></div>}</section>
 </section>;
}
