"use client";
import Link from "next/link";
import {useActionState,useState} from "react";
import {moveFileAction,renameFileAction,updateFileMetadataAction,verifyFileAction} from "@/app/studio/(protected)/projects/[projectId]/files/actions";
import {studioButtonClass,StudioPendingLabel} from "@/components/studio/StudioButton";
import {STUDIO_CATEGORY_LABELS,STUDIO_FILE_CATEGORIES} from "@/lib/studio/files/file-constants";
import type {StudioProjectFile,StudioProjectFolder} from "@/lib/studio/files/file-types";
import StudioFileArchiveControl from "./StudioFileArchiveControl";
import StudioFileTypeIcon from "./StudioFileTypeIcon";
import StudioSyncStatus from "./StudioSyncStatus";
import StudioFileVersionUpload from "./StudioFileVersionUpload";
import StudioVersionPromoteButton from "./StudioVersionPromoteButton";
import StudioVersionRepairButton from "./StudioVersionRepairButton";
import StudioInitialUploadRecoveryButton from "./StudioInitialUploadRecoveryButton";
import type {StudioFileVersion} from "@/lib/studio/files/versions/version-types";
import {STUDIO_REVISION_REASON_LABELS} from "@/lib/studio/files/versions/version-types";
import StudioFilePreview from "./preview/StudioFilePreview";

function Item({label,children}:{label:string;children:React.ReactNode}){return <div><dt className="text-sm font-semibold text-[#707674]">{label}</dt><dd className="mt-1.5 break-words text-[15px] leading-6 text-[#374147]">{children}</dd></div>;}
function Feedback({state}:{state:{success:boolean;message?:string}}){return state.message?<p role="status" aria-live="polite" className={`text-[13px] ${state.success?"text-[#41745d]":"text-[#8b5141]"}`}>{state.message}</p>:null;}

export default function StudioFileDetail({file,folders,versions}:{file:StudioProjectFile;folders:StudioProjectFolder[];versions:StudioFileVersion[]}){
 const[selectedVersionId,setSelectedVersionId]=useState(versions.find(version=>version.isCurrent&&version.status==="ready")?.id??versions.find(version=>version.status==="ready")?.id??"");
 const[metadataState,metadataAction,metadataPending]=useActionState(updateFileMetadataAction.bind(null,file.projectId,file.id),{success:false});
 const[renameState,renameAction,renamePending]=useActionState(renameFileAction.bind(null,file.projectId,file.id),{success:false});
 const[moveState,moveAction,movePending]=useActionState(moveFileAction.bind(null,file.projectId,file.id),{success:false});
 const[verifyState,verifyAction,verifyPending]=useActionState(verifyFileAction.bind(null,file.projectId,file.id),{success:false});
 return <section className="mx-auto min-w-0 max-w-[1100px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
  <header className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-7"><Link href={`/studio/projects/${file.projectId}/files${file.folderId?`?folder=${file.folderId}`:""}`} className="text-[13px] font-semibold uppercase tracking-[.1em] text-[#8e784d]">← Dosyalara Dön</Link><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex min-w-0 gap-4"><StudioFileTypeIcon extension={file.extension}/><div className="min-w-0"><h1 className="break-words text-2xl font-semibold tracking-[-.03em]">{file.displayName}</h1><div className="mt-3 flex flex-wrap items-center gap-2 text-sm text-[#6e7573]"><span>{file.extension.toUpperCase()} · {file.fileSizeLabel} · {file.status}{file.isArchived?" · Arşiv":""}</span><StudioSyncStatus status={file.syncStatus}/></div></div></div><div className="flex flex-wrap gap-2"><a href={`/studio/projects/${file.projectId}/files/${file.id}/download`} className={studioButtonClass("primary","sm")}>İndir</a>{file.canManage?<StudioFileArchiveControl projectId={file.projectId} fileId={file.id} archived={file.isArchived}/>:null}</div></div></header>
  <StudioFilePreview file={file} versions={versions} selectedVersionId={selectedVersionId} onSelectVersion={setSelectedVersionId}/>
  <div className="mt-5 grid gap-5 lg:grid-cols-2">
   <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><h2 className="text-xl font-semibold">Dosya Bilgileri</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Item label="Orijinal ad">{file.originalFileName}</Item><Item label="MIME">{file.mimeType}</Item><Item label="Kategori">{STUDIO_CATEGORY_LABELS[file.category]}</Item><Item label="Boyut">{file.fileSizeLabel}</Item><Item label="Yükleyen">{file.uploadedBy.name}</Item><Item label="Yüklenme">{file.createdAtLabel}</Item><Item label="Durum">{file.status}</Item><Item label="Güncellenme">{new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(file.updatedAt))}</Item></dl><div className="mt-6 border-t pt-5"><p className="text-sm font-semibold text-[#707674]">Açıklama</p><p className="mt-2 whitespace-pre-wrap text-[15px] leading-7 text-[#596260]">{file.description||"Açıklama eklenmemiş."}</p></div></section>
   <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><h2 className="text-xl font-semibold">Dosya İşlemleri</h2>{file.canManage?<div className="mt-5 space-y-6">
    {file.storageProvider==="google_drive"?<><form action={renameAction} className="space-y-3"><label className="block text-sm font-semibold text-[#707674]">Yeni dosya adı<input name="name" required maxLength={240} defaultValue={file.displayName} className="mt-2 h-11 w-full rounded-lg border bg-[#fbfaf7] px-3 text-sm"/></label><button disabled={renamePending} className={studioButtonClass("secondary")}><StudioPendingLabel pending={renamePending} pendingLabel="Adlandırılıyor…">Yeniden Adlandır</StudioPendingLabel></button><Feedback state={renameState}/></form><form action={moveAction} className="space-y-3"><label className="block text-sm font-semibold text-[#707674]">Hedef klasör<select name="folderId" required defaultValue={file.folderId} className="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm">{folders.filter(folder=>!folder.isArchived).map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><button disabled={movePending} className={studioButtonClass("outline")}><StudioPendingLabel pending={movePending} pendingLabel="Taşınıyor…">Klasöre Taşı</StudioPendingLabel></button><Feedback state={moveState}/></form></>:null}
    <form action={metadataAction} className="space-y-4"><input type="hidden" name="displayName" value={file.displayName}/><input type="hidden" name="folderId" value={file.folderId}/><label className="block text-sm font-semibold text-[#707674]">Kategori<select name="category" defaultValue={file.category} className="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm">{STUDIO_FILE_CATEGORIES.map(value=><option key={value} value={value}>{STUDIO_CATEGORY_LABELS[value]}</option>)}</select></label><label className="block text-sm font-semibold text-[#707674]">Açıklama<textarea name="description" rows={5} maxLength={5000} defaultValue={file.description} className="mt-2 w-full rounded-lg border bg-[#fbfaf7] p-3 text-sm"/></label><Feedback state={metadataState}/><button disabled={metadataPending} className={studioButtonClass("primary")}><StudioPendingLabel pending={metadataPending} pendingLabel="Kaydediliyor…">Bilgileri Kaydet</StudioPendingLabel></button></form>
    {file.storageProvider==="google_drive"?<form action={verifyAction} className="border-t pt-5"><button disabled={verifyPending} className={studioButtonClass("ghost")}><StudioPendingLabel pending={verifyPending} pendingLabel="Doğrulanıyor…">Drive Durumunu Doğrula</StudioPendingLabel></button><div className="mt-3"><Feedback state={verifyState}/></div></form>:null}
   </div>:<p className="mt-4 text-[15px] leading-6 text-[#69716f]">Dosya değişiklikleri yalnızca Studio sahibine açıktır. Güvenli indirme üyeler tarafından kullanılabilir.</p>}</section>
  </div>
  {file.canManage&&!file.isArchived&&file.storageProvider==="google_drive"?<div className="mt-5"><StudioFileVersionUpload projectId={file.projectId} fileId={file.id} extension={file.extension} nextVersion={(versions[0]?.versionNumber??0)+1}/></div>:null}
  {file.canManage&&file.storageProvider==="google_drive"&&file.status!=="ready"?<section className="mt-5 rounded-xl border border-[#d9c39c] bg-[#fffaf0] p-5"><h2 className="text-lg font-semibold">Yükleme tamamlanmayı bekliyor</h2><p className="mt-2 text-sm leading-6">Drive’a ulaşmış olabilecek dosya yeniden yüklenmeden reservation kimliğiyle doğrulanır.</p><div className="mt-4"><StudioInitialUploadRecoveryButton projectId={file.projectId} fileId={file.id}/></div></section>:null}
  {file.canManage&&versions.some(version=>version.status==="action_required"||version.status==="failed")?<section className="mt-5 rounded-xl border border-[#d9c39c] bg-[#fffaf0] p-5" aria-labelledby="version-repair-title"><h2 id="version-repair-title" className="text-lg font-semibold">Sürüm onarımı gerekli</h2><p className="mt-2 text-sm leading-6 text-[#6f654f]">Drive’a ulaşmış olabilecek mevcut sürüm yeniden yüklenmeden reservation kimliğiyle doğrulanır.</p><div className="mt-4 flex flex-wrap gap-2">{versions.filter(version=>version.status==="action_required"||version.status==="failed").map(version=><StudioVersionRepairButton key={version.id} projectId={file.projectId} fileId={file.id} versionId={version.id}/>)}</div></section>:null}
  <section className="mt-5 rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6" aria-labelledby="version-history-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="version-history-title" className="text-xl font-semibold">Sürüm Geçmişi</h2><p className="mt-1 text-sm text-[#69716f]">Her sürüm ayrı bir fiziksel dosya olarak korunur.</p></div><span className="text-sm font-semibold text-[#806b45]">{versions.length} sürüm</span></div>{versions.length?<ol className="mt-6 space-y-4">{versions.map(version=><li key={version.id} className="rounded-xl border border-[#e1ddd4] p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/studio/projects/${file.projectId}/files/${file.id}/versions/${version.id}`} className="text-base font-semibold text-[#202b33] hover:text-[#8b6b31]">V{version.versionNumber}{version.revisionCode?` · ${version.revisionCode}`:""}</Link>{version.isCurrent?<span className="rounded-full border border-[#b9d2c3] bg-[#edf6f0] px-2.5 py-1 text-[13px] font-semibold text-[#315c45]">✓ Güncel</span>:null}<StudioSyncStatus status={version.syncStatus}/></div><p className="mt-2 break-words text-[15px] font-semibold">{version.revisionTitle||STUDIO_REVISION_REASON_LABELS[version.revisionReason]}</p><p className="mt-1 line-clamp-3 break-words text-sm leading-6 text-[#69716f]">{version.revisionNote||STUDIO_REVISION_REASON_LABELS[version.revisionReason]}</p><p className="mt-2 text-[13px] text-[#747b79]">{version.createdAtLabel} · {version.uploadedBy.name} · {version.fileSizeLabel}</p></div><div className="flex shrink-0 flex-wrap gap-2"><a href={`/studio/projects/${file.projectId}/files/${file.id}/versions/${version.id}/download`} className={studioButtonClass("ghost","sm")} aria-label={`V${version.versionNumber} sürümünü indir`}>İndir</a>{file.canManage&&!version.isCurrent&&version.status==="ready"?<StudioVersionPromoteButton projectId={file.projectId} fileId={file.id} versionId={version.id} versionNumber={version.versionNumber}/>:null}</div></div></li>)}</ol>:<div className="mt-6 rounded-xl border border-dashed p-8 text-center"><h3 className="text-lg font-semibold">Sürüm geçmişi henüz hazır değil.</h3><p className="mt-2 text-sm text-[#69716f]">Migration 009 sonrasında mevcut ready dosyalar V1 olarak görünür.</p></div>}</section>
 </section>;
}
