"use client";
import {useActionState,useState,useTransition} from "react";
import {archiveFolderAction,moveFolderAction,renameFolderAction,verifyFolderAction} from "@/app/studio/(protected)/projects/[projectId]/files/actions";
import {studioButtonClass,StudioPendingLabel} from "@/components/studio/StudioButton";
import type {StudioProjectFolder} from "@/lib/studio/files/file-types";

export default function StudioFolderActions({projectId,folder,folders=[]}:{projectId:string;folder:StudioProjectFolder;folders?:StudioProjectFolder[]}){
 const[editing,setEditing]=useState(false);const[pending,start]=useTransition();const[error,setError]=useState("");const[verifyState,verifyAction,verifyPending]=useActionState(verifyFolderAction.bind(null,projectId,folder.id),{success:false});
 if(folder.isSystem)return <div className="flex flex-wrap items-center gap-2"><span className="text-[13px] font-semibold uppercase tracking-[.08em] text-[#9b8253]">Sistem</span>{folder.storageProvider==="google_drive"?<form action={verifyAction}><button disabled={verifyPending} className={studioButtonClass("ghost","sm")}><StudioPendingLabel pending={verifyPending} pendingLabel="Doğrulanıyor…">Klasör Eşlemesini Doğrula</StudioPendingLabel></button></form>:null}{verifyState.message?<p role="status" className={`w-full text-[13px] ${verifyState.success?"text-[#41745d]":"text-[#8b5141]"}`}>{verifyState.message}</p>:null}</div>;
 if(editing)return <div className="space-y-3">
  <form action={form=>start(async()=>{setError("");try{await renameFolderAction(projectId,folder.id,form);setEditing(false);}catch(value){setError(value instanceof Error?value.message:"Klasör yeniden adlandırılamadı.");}})} className="flex min-w-0 gap-2"><input name="name" defaultValue={folder.name} maxLength={120} aria-label="Yeni klasör adı" className="h-11 min-w-0 flex-1 rounded-md border px-3 text-sm"/><button disabled={pending} className={studioButtonClass("secondary","sm")}>Kaydet</button></form>
  <form action={form=>start(async()=>{setError("");try{await moveFolderAction(projectId,folder.id,form);setEditing(false);}catch(value){setError(value instanceof Error?value.message:"Klasör taşınamadı.");}})} className="flex min-w-0 gap-2"><label className="sr-only" htmlFor={`move-${folder.id}`}>Üst klasör</label><select id={`move-${folder.id}`} name="parentFolderId" defaultValue={folder.parentFolderId} className="h-11 min-w-0 flex-1 rounded-md border bg-white px-3 text-sm"><option value="">Proje kökü</option>{folders.filter(value=>value.id!==folder.id&&!value.isArchived).map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select><button disabled={pending} className={studioButtonClass("outline","sm")}>Taşı</button></form>
  <button type="button" onClick={()=>setEditing(false)} className={studioButtonClass("ghost","sm")}>Vazgeç</button>{error?<p role="alert" className="text-[13px] text-[#8b5141]">{error}</p>:null}
 </div>;
 return <div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setEditing(true)} className={studioButtonClass("ghost","sm")}>Yeniden Adlandır / Taşı</button><button type="button" disabled={pending} onClick={()=>{if(window.confirm(folder.isArchived?"Klasör arşivden geri alınsın mı?":"Klasör 08 Arşiv altına taşınsın mı? İçeriği silinmez."))start(async()=>{setError("");try{await archiveFolderAction(projectId,folder.id,!folder.isArchived);}catch(value){setError(value instanceof Error?value.message:"Klasör işlemi tamamlanamadı.");}});}} className={studioButtonClass("danger","sm")}>{folder.isArchived?"Geri Al":"Arşivle"}</button>{folder.storageProvider==="google_drive"?<form action={verifyAction}><button disabled={verifyPending} className={studioButtonClass("outline","sm")}><StudioPendingLabel pending={verifyPending} pendingLabel="Doğrulanıyor…">Drive Durumunu Doğrula</StudioPendingLabel></button></form>:null}{error?<p role="alert" className="w-full text-[13px] text-[#8b5141]">{error}</p>:null}{verifyState.message?<p role="status" className={`w-full text-[13px] ${verifyState.success?"text-[#41745d]":"text-[#8b5141]"}`}>{verifyState.message}</p>:null}</div>;
}
