"use client";
import {useRef,useState} from "react";
import {failFileVersionUploadAction,finalizeFileVersionUploadAction,reserveFileVersionUploadAction} from "@/app/studio/(protected)/projects/[projectId]/files/actions";
import {studioButtonClass,StudioButtonSpinner} from "@/components/studio/StudioButton";
import {uploadToGoogleDriveSession} from "@/lib/studio/files/uploads/google-drive-resumable-upload";
import {STUDIO_REVISION_REASON_LABELS,type StudioRevisionReason} from "@/lib/studio/files/versions/version-types";

const reasons=Object.entries(STUDIO_REVISION_REASON_LABELS).filter(([value])=>value!=="initial"&&value!=="rollback") as [StudioRevisionReason,string][];
export default function StudioFileVersionUpload({projectId,fileId,extension,nextVersion}:{projectId:string;fileId:string;extension:string;nextVersion:number}){
 const inputRef=useRef<HTMLInputElement>(null);const abortRef=useRef<AbortController|null>(null);const[file,setFile]=useState<File|null>(null);const[revisionCode,setRevisionCode]=useState("");const[revisionTitle,setRevisionTitle]=useState("");const[revisionReason,setRevisionReason]=useState<StudioRevisionReason>("design_change");const[revisionNote,setRevisionNote]=useState("");const[state,setState]=useState({pending:false,message:"",error:false,percent:0});
 async function submit(){if(!file||state.pending)return;let versionId="";const controller=new AbortController();abortRef.current=controller;setState({pending:true,message:"Sürüm ayrılıyor…",error:false,percent:0});try{const reservation=await reserveFileVersionUploadAction({projectId,fileId,name:file.name,type:file.type,size:file.size,revisionCode,revisionTitle,revisionReason,revisionNote});versionId=reservation.id;setState(value=>({...value,message:"Google Drive'a yükleniyor…"}));const metadata=await uploadToGoogleDriveSession(file,reservation.sessionUrl,progress=>setState(value=>({...value,percent:Math.floor(progress.uploaded/progress.total*100)})),controller.signal);setState(value=>({...value,message:"Güncel sürüm işaretleniyor…",percent:100}));await finalizeFileVersionUploadAction(projectId,fileId,versionId,metadata.id);setState({pending:false,message:`V${reservation.versionNumber} başarıyla yüklendi.`,error:false,percent:100});setFile(null);setRevisionCode("");setRevisionTitle("");setRevisionNote("");if(inputRef.current)inputRef.current.value="";}catch(error){if(versionId)await failFileVersionUploadAction(projectId,fileId,versionId).catch(()=>undefined);setState(value=>({...value,pending:false,error:true,message:error instanceof DOMException?"Yükleme iptal edildi.":error instanceof Error?error.message:"Sürüm yüklenemedi."}));}finally{abortRef.current=null;}}
 return <section className="rounded-xl border border-[#d8cfbd] bg-[#faf8f3] p-5" aria-labelledby="version-upload-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="version-upload-title" className="text-lg font-semibold">Yeni Sürüm Yükle</h2><p className="mt-1 text-sm text-[#6f7674]">Sıradaki sürüm: V{nextVersion} · Beklenen uzantı: .{extension}</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-[#707674]">Dosya<input ref={inputRef} type="file" disabled={state.pending} onChange={event=>setFile(event.target.files?.[0]??null)} className="mt-2 block w-full text-sm file:mr-3 file:rounded-md file:border-0 file:bg-[#17232e] file:px-3 file:py-2 file:font-semibold file:text-white"/></label><label className="text-sm font-semibold text-[#707674]">Revizyon kodu<input value={revisionCode} onChange={event=>setRevisionCode(event.target.value)} maxLength={40} placeholder="R02" className="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm"/></label><label className="text-sm font-semibold text-[#707674] sm:col-span-2">Revizyon başlığı<input value={revisionTitle} onChange={event=>setRevisionTitle(event.target.value)} required maxLength={160} className="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm"/></label><label className="text-sm font-semibold text-[#707674]">Revizyon nedeni<select value={revisionReason} onChange={event=>setRevisionReason(event.target.value as StudioRevisionReason)} className="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-sm">{reasons.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold text-[#707674] sm:col-span-2">Revizyon notu<textarea value={revisionNote} onChange={event=>setRevisionNote(event.target.value)} maxLength={4000} rows={4} className="mt-2 w-full rounded-lg border bg-white p-3 text-sm"/></label></div>{state.pending?<div className="mt-4" aria-live="polite"><div className="flex justify-between text-sm"><span>{state.message}</span><span>%{state.percent}</span></div><div role="progressbar" aria-label="Yeni sürüm yükleme ilerlemesi" aria-valuemin={0} aria-valuemax={100} aria-valuenow={state.percent} className="mt-2 h-2 overflow-hidden rounded-full bg-[#e6dfd3]"><div className="h-full bg-[#a77936]" style={{width:`${state.percent}%`}}/></div></div>:null}<div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={()=>void submit()} disabled={!file||!revisionTitle.trim()||state.pending} className={studioButtonClass("primary")} >{state.pending?<><StudioButtonSpinner/>Yükleniyor…</>:"Yeni Sürümü Yükle"}</button>{state.pending?<button type="button" onClick={()=>abortRef.current?.abort()} className={studioButtonClass("outline")}>İptal</button>:null}</div><p role="status" aria-live="polite" className={`mt-3 min-h-5 text-sm ${state.error?"text-[#8b5141]":"text-[#41745d]"}`}>{state.message}</p></section>;
}
