"use client";

import {useState} from "react";
import type {OfficialProcess} from "@/lib/studio/official-processes/official-process-types";
import {STATUS_LABELS} from "@/lib/studio/official-processes/official-process-types";
import {StudioActivityIcon,StudioBadge,StudioCard,StudioEmptyState,StudioIconSurface,StudioKpiCard,StudioSectionHeader} from "@/components/studio/ui";
import StudioOfficialProcessMilestoneCard from "./StudioOfficialProcessMilestoneCard";

type Props={items:OfficialProcess[];documents:Array<{id:string;name:string}>;canManage:boolean;whatsappConfigured:boolean;projectName:string;customerName:string;customerPhone:string};
const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0});
const date=new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric"});
const completed=(item:OfficialProcess)=>item.status==="paid"||item.status==="document_received";
const badge=(item:OfficialProcess)=>item.isOverdue?{label:"Gecikti",variant:"danger" as const}:item.status==="cancelled"?{label:"İptal",variant:"archived" as const}:completed(item)?{label:STATUS_LABELS[item.status],variant:"success" as const}:{label:STATUS_LABELS[item.status],variant:"warning" as const};
const formattedDate=(value:string|null)=>value?date.format(new Date(`${value.length===10?`${value}T12:00:00`:value}`)):"—";

export default function StudioOfficialProcessesWorkspace(props:Props){
 const{items}=props;const[selected,setSelected]=useState<OfficialProcess|null>(null);const active=items.filter(item=>!item.isArchived&&item.status!=="cancelled");const fees=active.filter(item=>item.entityType==="fee");const documents=active.filter(item=>item.entityType!=="fee");const now=new Date();const month=now.getMonth();const year=now.getFullYear();const inThisMonth=(value:string)=>{const current=new Date(value);return current.getMonth()===month&&current.getFullYear()===year;};
 const metrics=[
  {label:"Bekleyen Harç",value:fees.filter(item=>!completed(item)).length,detail:"Ödeme aksiyonu bekliyor",icon:"receipt" as const,tone:"orange" as const,target:"fees"},
  {label:"Bekleyen Evrak",value:active.filter(item=>!item.receivedDocumentFileId).length,detail:"Belge bağlantısı bekliyor",icon:"file-text" as const,tone:"purple" as const,target:"documents"},
  {label:"Geciken Süreç",value:active.filter(item=>item.isOverdue).length,detail:"Son tarihi geçen kayıt",icon:"warning" as const,tone:"red" as const,target:"upcoming"},
  {label:"Bu Ay Tahsil Edilen",value:fees.filter(item=>completed(item)&&inThisMonth(item.updatedAt)).length,detail:"Bu ay ödenen harç",icon:"wallet" as const,tone:"green" as const,target:"fees"},
  {label:"Bu Ay Başvuru",value:documents.filter(item=>inThisMonth(item.createdAt)).length,detail:"Yeni resmî başvuru",icon:"calendar" as const,tone:"blue" as const,target:"documents"},
  {label:"Tamamlanan Süreç",value:active.filter(completed).length,detail:"Sonuçlanan kayıt",icon:"check" as const,tone:"green" as const,target:"history"},
 ];
 const upcoming=[...active].filter(item=>item.dueDate).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).slice(0,6);const events=items.flatMap(item=>item.events.map(event=>({...event,process:item}))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,10);
 return <div className="mt-5 space-y-5">
  <section aria-labelledby="official-kpis"><h2 id="official-kpis" className="sr-only">Resmî süreç özetleri</h2><div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 min-[1280px]:grid-cols-6">{metrics.map(metric=><a key={metric.label} href={`#${metric.target}`} className="group min-w-0 rounded-[18px] outline-none focus-visible:ring-2 focus-visible:ring-[#2d7ef7]/30"><StudioKpiCard {...metric} className="h-full min-h-[132px] transition duration-180 group-hover:-translate-y-0.5 group-hover:shadow-[0_10px_28px_rgba(40,57,73,.08)]"/><span className="pointer-events-none absolute sr-only">Detay</span></a>)}</div></section>
  <section className="grid min-w-0 items-stretch gap-4 xl:grid-cols-[1.35fr_1fr_1fr]">
   <StudioCard className="flex h-[430px] min-w-0 flex-col overflow-hidden p-0" as="section"><div className="border-b border-[var(--studio-border)] p-4"><StudioSectionHeader title="Harç Süreçleri" description="Ödeme ve tahakkuk operasyonları" icon="receipt" count={fees.length}/></div><div id="fees" className="min-h-0 flex-1 overflow-auto">{fees.length?<div className="min-w-[680px]"><div className="grid grid-cols-[minmax(160px,1.3fr)_minmax(130px,1fr)_110px_110px_110px_72px] gap-3 border-b border-[var(--studio-border)] bg-[var(--studio-surface-muted)] px-4 py-2 text-[11px] font-semibold text-slate-500"><span>Proje</span><span>Harç Türü</span><span>Durum</span><span>Son Tarih</span><span>Tutar</span><span>İşlem</span></div>{fees.map(item=>{const state=badge(item);return <button type="button" key={item.id} onClick={()=>setSelected(item)} className="grid min-h-[58px] w-full grid-cols-[minmax(160px,1.3fr)_minmax(130px,1fr)_110px_110px_110px_72px] items-center gap-3 border-b border-[var(--studio-border)] px-4 text-left text-[12px] transition hover:bg-[var(--studio-surface-muted)]"><span className="truncate font-semibold text-slate-800">{props.projectName}</span><span className="truncate text-slate-600">{item.title}</span><StudioBadge variant={state.variant}>{state.label}</StudioBadge><span className="text-slate-500">{formattedDate(item.dueDate)}</span><span className="font-semibold text-slate-700">{item.amount===null?"—":money.format(item.amount)}</span><span className="font-semibold text-[#2d6f95]">Detay →</span></button>})}</div>:<div className="p-4"><StudioEmptyState icon="receipt" title="Harç süreci bulunmuyor" description="Bu proje için aktif bir harç kaydı yok."/></div>}</div></StudioCard>
   <div id="documents" className="min-w-0"><StudioCard className="flex h-[430px] min-w-0 flex-col overflow-hidden p-0" as="section"><div className="border-b border-[var(--studio-border)] p-4"><StudioSectionHeader title="Resmî Evraklar" description="Başvuru ve teslim belgeleri" icon="file-text" count={documents.length}/></div><div className="min-h-0 flex-1 overflow-y-auto px-4">{documents.length?documents.map(item=>{const state=badge(item);return <button type="button" key={item.id} onClick={()=>setSelected(item)} className="flex min-h-[64px] w-full items-center gap-3 border-b border-[var(--studio-border)] py-2 text-left transition hover:bg-[var(--studio-surface-muted)]"><StudioIconSurface icon="file-text" tone={completed(item)?"green":"blue"} size="sm"/><span className="min-w-0 flex-1"><strong className="block truncate text-[13px] text-slate-800">{item.title}</strong><span className="block truncate text-[11px] text-slate-500">{props.projectName} · {formattedDate(item.dueDate)}</span></span><StudioBadge variant={state.variant}>{state.label}</StudioBadge></button>}):<StudioEmptyState icon="file-text" title="Resmî evrak bulunmuyor" description="Bu projeye bağlı aktif evrak kaydı yok."/>}</div></StudioCard></div>
   <div id="upcoming" className="min-w-0"><StudioCard className="flex h-[430px] min-w-0 flex-col overflow-hidden p-0" as="section"><div className="border-b border-[var(--studio-border)] p-4"><StudioSectionHeader title="Yaklaşan Süreçler" description="Son tarih sırasına göre" icon="calendar" count={upcoming.length}/></div><div className="min-h-0 flex-1 overflow-y-auto px-4">{upcoming.length?<ol>{upcoming.map(item=>{const state=badge(item);return <li key={item.id} className="relative flex min-h-[62px] gap-3 border-b border-[var(--studio-border)] py-2.5"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${item.isOverdue?"bg-red-500":completed(item)?"bg-emerald-500":"bg-blue-500"}`}/><button type="button" onClick={()=>setSelected(item)} className="min-w-0 flex-1 text-left"><strong className="block truncate text-[13px] text-slate-800">{item.title}</strong><span className="mt-0.5 block text-[11px] text-slate-500">{formattedDate(item.dueDate)} · {state.label}</span></button></li>})}</ol>:<StudioEmptyState icon="calendar" title="Yaklaşan süreç yok" description="Tarihi yaklaşan aktif kayıt bulunmuyor."/>}</div></StudioCard></div>
  </section>
  <div id="history"><StudioCard className="min-w-0 overflow-hidden p-0" as="section"><div className="border-b border-[var(--studio-border)] p-4"><StudioSectionHeader title="İşlem Geçmişi" description="Projede yapılan son resmî süreç işlemleri" icon="activity" count={events.length}/></div>{events.length?<div className="divide-y divide-[var(--studio-border)] px-4">{events.map(event=><button type="button" key={event.id} onClick={()=>setSelected(event.process)} className="grid min-h-[58px] w-full grid-cols-[36px_minmax(0,1fr)_auto] items-center gap-3 py-2 text-left transition hover:bg-[var(--studio-surface-muted)]"><StudioActivityIcon variant={event.process.isOverdue?"warning":completed(event.process)?"success":"notification"} size="sm"/><span className="min-w-0"><strong className="block truncate text-[13px] text-slate-800">{event.title}</strong><span className="block truncate text-[11px] text-slate-500">{props.projectName} · {event.process.title}</span></span><time className="text-[11px] text-slate-500">{formattedDate(event.createdAt)}</time></button>)}</div>:<div className="p-4"><StudioEmptyState icon="activity" title="İşlem geçmişi boş" description="Bu projede henüz kaydedilmiş bir süreç hareketi yok."/></div>}</StudioCard></div>
  {selected?<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-0 sm:items-center sm:p-6" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)setSelected(null);}}><div role="dialog" aria-modal="true" aria-label={`${selected.title} işlemleri`} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-[20px] bg-white p-4 shadow-2xl sm:rounded-[20px] sm:p-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-base font-semibold text-slate-800">Süreç Detayı</h2><button type="button" onClick={()=>setSelected(null)} className="rounded-lg border border-[var(--studio-border)] bg-white px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-[var(--studio-surface-muted)]">Kapat</button></div><StudioOfficialProcessMilestoneCard item={selected} documents={props.documents} canManage={props.canManage} whatsappConfigured={props.whatsappConfigured} projectName={props.projectName} customerName={props.customerName} customerPhone={props.customerPhone}/></div></div>:null}
 </div>;
}
