"use client";
import {useState} from "react";
import StudioOfficialProcessCard from "./StudioOfficialProcessCard";
import StudioOfficialProcessStatusBadge from "./StudioOfficialProcessStatusBadge";
import type {OfficialProcess} from "@/lib/studio/official-processes/official-process-types";
const money=new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"});
export default function StudioOfficialProcessMilestoneCard({item,documents,canManage,whatsappConfigured,projectName,customerName,customerPhone}:{item:OfficialProcess;documents:Array<{id:string;name:string}>;canManage:boolean;whatsappConfigured:boolean;projectName:string;customerName:string;customerPhone:string}){
 const[open,setOpen]=useState(false);const paid=item.status==="paid"||item.status==="document_received"?item.amount??0:0;const remaining=Math.max((item.amount??0)-paid,0);const date=item.updatedAt?new Intl.DateTimeFormat("tr-TR").format(new Date(item.updatedAt)):"Belirtilmedi";
 return <><article className="flex min-h-[210px] min-w-0 flex-col rounded-xl border border-[#dedad1] bg-white p-4 shadow-[0_4px_18px_rgba(32,39,46,.035)]"><div className="flex min-w-0 items-start justify-between gap-3"><h3 className="min-w-0 break-words text-base font-semibold leading-6 text-[#202b34]">{item.title}</h3><button type="button" onClick={()=>setOpen(true)} className="shrink-0 rounded-lg border border-[#d8d1c7] px-2.5 py-1.5 text-xs font-semibold text-[#4f5659] hover:bg-[#f8f5ef] focus-visible:outline-2 focus-visible:outline-offset-2" aria-label={`${item.title} detaylarını aç`}>Detay</button></div><div className="mt-3"><StudioOfficialProcessStatusBadge status={item.status}/></div><dl className="mt-4 grid grid-cols-3 gap-2 text-xs"><div className="min-w-0 rounded-lg bg-[#f8f6f1] p-2"><dt className="text-[#747b78]">Tahakkuk</dt><dd className="mt-1 break-words font-semibold">{item.amount===null?"—":money.format(item.amount)}</dd></div><div className="min-w-0 rounded-lg bg-[#f8f6f1] p-2"><dt className="text-[#747b78]">Ödenen</dt><dd className="mt-1 break-words font-semibold">{money.format(paid)}</dd></div><div className="min-w-0 rounded-lg bg-[#f8f6f1] p-2"><dt className="text-[#747b78]">Kalan</dt><dd className="mt-1 break-words font-semibold">{money.format(remaining)}</dd></div></dl><p className="mt-auto pt-4 text-xs text-[#68716f]">Son işlem: <span className="font-semibold text-[#41494c]">{date}</span></p></article>{open?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-0 sm:items-center sm:p-6"><div role="dialog" aria-modal="true" aria-label={`${item.title} detayları`} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl bg-[#faf8f3] p-4 sm:rounded-2xl sm:p-6"><div className="mb-3 flex justify-end"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border border-[#d8d1c7] px-3 py-2 text-sm font-semibold focus-visible:outline-2" aria-label="Detay penceresini kapat">Kapat</button></div><StudioOfficialProcessCard item={item} documents={documents} canManage={canManage} whatsappConfigured={whatsappConfigured} projectName={projectName} customerName={customerName} customerPhone={customerPhone}/></div></div>:null}</>;
}
