import {notFound} from "next/navigation";
import StudioCustomFeeForm from "@/components/studio/official-processes/StudioCustomFeeForm";
import StudioOfficialProcessMilestoneCard from "@/components/studio/official-processes/StudioOfficialProcessMilestoneCard";
import StudioOfficialProcessSummaryGrid from "@/components/studio/official-processes/StudioOfficialProcessSummaryGrid";
import StudioProjectTabs from "@/components/studio/projects/StudioProjectTabs";
import {initializeOfficialProcesses,listOfficialProcessDocuments,listOfficialProcesses} from "@/lib/studio/official-processes/official-process-repository";
import {isWhatsAppConfigured} from "@/lib/studio/notifications/whatsapp-adapter";
import {getStudioProjectAccess,getStudioProjectById} from "@/lib/studio/projects/project-repository";
export const dynamic="force-dynamic";
export default async function OfficialProcessesPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const{projectId}=await params;const query=await searchParams;const archiveView=query.view==="archive";const[project,access]=await Promise.all([getStudioProjectById(projectId),getStudioProjectAccess()]);if(!project)notFound();let payload:Awaited<ReturnType<typeof loadOfficialProcesses>>|null=null;try{if(access.canManage&&!archiveView)await initializeOfficialProcesses(projectId);payload=await loadOfficialProcesses(projectId,archiveView);}catch{payload=null;}
 if(!payload)return <main className="mx-auto max-w-[1540px] px-4 py-6 sm:px-6 lg:px-8"><PageHeader code={project.code} name={project.name} projectId={projectId}/><section role="status" className="mt-5 rounded-xl border border-dashed bg-[#faf8f3] p-6"><h2 className="text-xl font-semibold">Modül henüz hazırlanmadı</h2><p className="mt-2 text-[15px] leading-6 text-[#68716f]">Harç ve Evraklar veri yapısı henüz bu ortamda etkin değil.</p></section></main>;
 const{items,documents}=payload;const cardProps={documents,canManage:access.canManage,whatsappConfigured:isWhatsAppConfigured(),projectName:project.name,customerName:project.client.name,customerPhone:project.client.phone};const milestones=buildMilestones(items);const visible=archiveView?items:milestones.filter((item):item is NonNullable<typeof item>=>Boolean(item));
 return <main className="mx-auto min-w-0 max-w-[1540px] px-4 py-6 sm:px-6 lg:px-8"><PageHeader code={project.code} name={project.name} projectId={projectId}/><nav className="mt-5 flex flex-wrap gap-2" aria-label="Harç görünümü"><a href={`/studio/projects/${projectId}/official-processes`} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${!archiveView?"bg-[#17222c] text-white":"bg-white text-[#41494c]"}`}>Aktif</a><a href={`/studio/projects/${projectId}/official-processes?view=archive`} className={`rounded-lg border px-3 py-2 text-sm font-semibold ${archiveView?"bg-[#17222c] text-white":"bg-white text-[#41494c]"}`}>Arşivlenmiş</a></nav>{!archiveView?<><StudioOfficialProcessSummaryGrid items={items}/><section aria-labelledby="fee-milestone-title" className="mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="fee-milestone-title" className="text-xl font-semibold text-[#202b34]">Harç Milestone</h2><p className="mt-1 text-sm leading-6 text-[#68716f]">Projeye ait resmi harç süreçlerini tek ekrandan takip edin.</p></div>{access.canManage?<StudioCustomFeeForm projectId={projectId}/>:null}</div><div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{milestones.map((item,index)=>item?<StudioOfficialProcessMilestoneCard key={item.id} item={item} {...cardProps}/>:<article key={`missing-${index}`} className="flex min-h-[210px] items-center rounded-xl border border-dashed border-[#dedad1] bg-[#faf8f3] p-4 text-sm text-[#747b78]">Süreç henüz oluşturulmadı.</article>)}</div></section></>:<section aria-labelledby="archive-title" className="mt-6"><h2 id="archive-title" className="text-xl font-semibold">Harç Arşivi</h2><p className="mt-1 text-sm text-[#68716f]">Arşivlenen süreçler burada salt okunur olarak korunur.</p><div className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map(item=><StudioOfficialProcessMilestoneCard key={item.id} item={item} {...cardProps}/>)}{!visible.length?<p className="rounded-xl border border-dashed p-6 text-sm text-[#68716f]">Arşivlenmiş süreç bulunmuyor.</p>:null}</div></section>}</main>;
}
async function loadOfficialProcesses(projectId:string,includeArchived=false){const[items,documents]=await Promise.all([listOfficialProcesses(projectId,{includeArchived}),listOfficialProcessDocuments(projectId)]);return{items,documents};}
function buildMilestones(items:Awaited<ReturnType<typeof listOfficialProcesses>>){const find=(match:(item:typeof items[number])=>boolean)=>items.find(match);const title=(item:typeof items[number])=>item.title.toLocaleLowerCase("tr-TR");return[find(item=>item.entityType==="application"),find(item=>item.entityType==="fee"&&title(item).includes("imar durum")),find(item=>item.entityType==="fee"&&(title(item).includes("istikamet")||title(item).includes("kot kesit"))),find(item=>item.entityType==="fee"&&title(item).includes("mikroböl")),find(item=>item.entityType==="fee"&&title(item).includes("proje har"))];}
function PageHeader({code,name,projectId}:{code:string;name:string;projectId:string}){return <><div><p className="text-sm font-semibold text-[#9a7b40]">{code}</p><h1 className="mt-1 break-words text-3xl font-semibold text-[#202b34]">Harç ve Evraklar</h1><p className="mt-2 text-[15px] leading-6 text-[#68716f]">{name} için belediye harçları ve resmî süreçler.</p></div><StudioProjectTabs projectId={projectId} active="official-processes"/></>;}
