import "server-only";
import {createHash,randomUUID} from "node:crypto";
import {createClient} from "@supabase/supabase-js";
import {createStudioServerClient} from "@/lib/studio/supabase/server";

export type CheckoutPayment={id:string;organization_id:string;project_id:string;project_name:string;title:string;amount:string;currency:string;status:"pending"|"paid"|"cancelled";buyer_id:string;buyer_full_name:string|null;buyer_identity_number:string|null;buyer_email:string|null;buyer_gsm_number:string|null;buyer_registration_address:string|null;buyer_city:string|null;buyer_country:string|null;buyer_zip_code:string|null};
export type PaymentAttempt={id:string;payment_request_id:string;conversation_id:string;basket_id:string;amount:string;currency:string;status:string;provider_checkout_url:string|null;expires_at:string|null};

function admin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("PAYMENT_DATABASE_NOT_CONFIGURED");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export const tokenHash=(token:string)=>createHash("sha256").update(token,"utf8").digest("hex");

export async function authenticatedPayment(id:string){const db=await createStudioServerClient(),{data:{user}}=await db.auth.getUser();if(!user)return{kind:"unauthorized"} as const;const{data,error}=await db.rpc("client_portal_get_payment_request_for_checkout",{p_payment_request_id:id});if(error)throw new Error("PAYMENT_LOOKUP_FAILED");const row=(Array.isArray(data)?data[0]:data) as CheckoutPayment|undefined;return row?{kind:"ok",userId:user.id,payment:row} as const:{kind:"not_found"} as const;}
export async function createOrReuseAttempt(paymentRequestId:string,userId:string){const db=admin(),conversationId=`arz-${randomUUID()}`,basketId=`arz-${randomUUID()}`,expiresAt=new Date(Date.now()+30*60*1000).toISOString();const{data,error}=await db.rpc("iyzico_create_payment_attempt",{p_payment_request_id:paymentRequestId,p_initiated_by:userId,p_environment:"sandbox",p_conversation_id:conversationId,p_basket_id:basketId,p_expires_at:expiresAt});if(error)throw new Error(error.message.includes("already_paid")?"PAYMENT_ALREADY_PAID":error.message.includes("cancelled")?"PAYMENT_CANCELLED":"PAYMENT_ATTEMPT_FAILED");return(Array.isArray(data)?data[0]:data) as PaymentAttempt;}
export async function claimAttemptInitialization(id:string){const{data,error}=await admin().from("studio_client_payment_attempts").update({error_code:"INITIALIZING",updated_at:new Date().toISOString()}).eq("id",id).eq("status","created").is("error_code",null).select("id").maybeSingle();if(error)throw new Error("PAYMENT_ATTEMPT_CLAIM_FAILED");return Boolean(data);}
export async function markAwaiting(attemptId:string,token:string,url:string){const{error}=await admin().from("studio_client_payment_attempts").update({status:"awaiting_payment",provider_token_hash:tokenHash(token),provider_checkout_url:url,error_code:null,updated_at:new Date().toISOString()}).eq("id",attemptId).eq("status","created");if(error)throw new Error("PAYMENT_ATTEMPT_UPDATE_FAILED");}
export async function attemptForToken(token:string){const{data,error}=await admin().from("studio_client_payment_attempts").select("id,payment_request_id,conversation_id,basket_id,amount,currency,status").eq("provider_token_hash",tokenHash(token)).maybeSingle();if(error)throw new Error("PAYMENT_ATTEMPT_LOOKUP_FAILED");return data as (PaymentAttempt&{payment_request_id:string})|null;}
export async function markAttemptFailed(id:string,code:string){await admin().from("studio_client_payment_attempts").update({status:"failed",error_code:code.slice(0,100),error_message:"Payment verification failed.",updated_at:new Date().toISOString()}).eq("id",id).neq("status","succeeded");}
export async function finalizeAttempt(id:string,paymentId:string,amount:string,currency:string){const{data,error}=await admin().rpc("iyzico_finalize_payment",{p_attempt_id:id,p_provider_payment_id:paymentId,p_amount:amount,p_currency:currency});if(error||!data)throw new Error("PAYMENT_FINALIZATION_FAILED");}
