import "server-only";
import {createHash,randomUUID} from "node:crypto";
import {createClient} from "@supabase/supabase-js";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import{decryptCheckoutPaymentIdentity}from"@/lib/payments/payment-profile-encryption";
import type{IyzicoEnvironment}from"@/lib/payments/iyzico/config";
import type{VerifiedPaymentMetadata}from"@/lib/payments/iyzico/verification";

export type CheckoutPayment={id:string;organization_id:string;project_id:string;project_name:string;title:string;amount:string;currency:string;status:"pending"|"paid"|"cancelled"|"refunded";buyer_id:string;buyer_full_name:string|null;buyer_identity_number:string|null;buyer_email:string|null;buyer_gsm_number:string|null;buyer_registration_address:string|null;buyer_city:string|null;buyer_country:string|null;buyer_zip_code:string|null};
export type PaymentAttempt={id:string;payment_request_id:string;conversation_id:string;basket_id:string;amount:string;currency:string;environment:IyzicoEnvironment;status:string;provider_token_hash:string|null;provider_checkout_url:string|null;expires_at:string|null;checkout_source?:"client_portal"|"public_link";public_payment_link_id?:string|null;wasCreated?:boolean};

function admin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("PAYMENT_DATABASE_NOT_CONFIGURED");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export const tokenHash=(token:string)=>createHash("sha256").update(token,"utf8").digest("hex");
export class PaymentProfileLoadError extends Error{constructor(public code:"PAYMENT_PROFILE_LOOKUP_FAILED"|"PAYMENT_PROFILE_ENCRYPTION_KEY_MISSING"|"PAYMENT_PROFILE_ENCRYPTION_KEY_INVALID"|"PAYMENT_PROFILE_DECRYPT_FAILED"){super(code);this.name="PaymentProfileLoadError";}}

export async function authenticatedPayment(id:string){const db=await createStudioServerClient(),{data:{user}}=await db.auth.getUser();if(!user)return{kind:"unauthorized"} as const;const{data,error}=await db.rpc("client_portal_get_payment_request_for_checkout",{p_payment_request_id:id});if(error)throw new Error("PAYMENT_LOOKUP_FAILED");const row=(Array.isArray(data)?data[0]:data) as CheckoutPayment|undefined;if(!row)return{kind:"not_found"}as const;const{data:profile,error:profileError}=await admin().from("studio_client_payment_billing_profiles").select("identity_number,identity_number_encrypted,identity_number_last_two").eq("user_id",user.id).maybeSingle();if(profileError)throw new PaymentProfileLoadError("PAYMENT_PROFILE_LOOKUP_FAILED");const encrypted=profile?.identity_number_encrypted as string|null|undefined,legacy=profile?.identity_number as string|null|undefined,lastTwo=profile?.identity_number_last_two as string|null|undefined;let identity:string|null=legacy??null;if(encrypted){try{identity=decryptCheckoutPaymentIdentity(encrypted,lastTwo);}catch(error){const code=error instanceof Error&&["PAYMENT_PROFILE_ENCRYPTION_KEY_MISSING","PAYMENT_PROFILE_ENCRYPTION_KEY_INVALID","PAYMENT_PROFILE_DECRYPT_FAILED"].includes(error.message)?error.message as PaymentProfileLoadError["code"]:"PAYMENT_PROFILE_DECRYPT_FAILED";throw new PaymentProfileLoadError(code);}}const payment:CheckoutPayment={...row,buyer_identity_number:identity};return{kind:"ok",userId:user.id,payment}as const;}
export async function createOrReuseAttempt(paymentRequestId:string,userId:string,environment:IyzicoEnvironment){const db=admin(),conversationId=`arz-${randomUUID()}`,basketId=`arz-${randomUUID()}`,expiresAt=new Date(Date.now()+30*60*1000).toISOString();const{data,error}=await db.rpc("iyzico_create_payment_attempt",{p_payment_request_id:paymentRequestId,p_initiated_by:userId,p_environment:environment,p_conversation_id:conversationId,p_basket_id:basketId,p_expires_at:expiresAt});if(error)throw new Error(error.message.includes("already_paid")?"PAYMENT_ALREADY_PAID":error.message.includes("cancelled")?"PAYMENT_CANCELLED":"PAYMENT_ATTEMPT_FAILED");const attempt=(Array.isArray(data)?data[0]:data) as PaymentAttempt;return{...attempt,wasCreated:attempt.conversation_id===conversationId};}
export async function claimAttemptInitialization(id:string){const{data,error}=await admin().from("studio_client_payment_attempts").update({error_code:"INITIALIZING",updated_at:new Date().toISOString()}).eq("id",id).eq("status","created").is("error_code",null).select("id").maybeSingle();if(error)throw new Error("PAYMENT_ATTEMPT_CLAIM_FAILED");return Boolean(data);}
export async function markAwaiting(attemptId:string,token:string,url:string){const{error}=await admin().from("studio_client_payment_attempts").update({status:"awaiting_payment",provider_token_hash:tokenHash(token),provider_checkout_url:url,error_code:null,updated_at:new Date().toISOString()}).eq("id",attemptId).eq("status","created");if(error)throw new Error("PAYMENT_ATTEMPT_UPDATE_FAILED");}
export async function attemptForToken(token:string){const{data,error}=await admin().from("studio_client_payment_attempts").select("id,payment_request_id,conversation_id,basket_id,amount,currency,environment,status,checkout_source,public_payment_link_id").eq("provider_token_hash",tokenHash(token)).maybeSingle();if(error)throw new Error("PAYMENT_ATTEMPT_LOOKUP_FAILED");return data as (PaymentAttempt&{payment_request_id:string})|null;}
export async function markAttemptFailed(id:string,code:string){await admin().from("studio_client_payment_attempts").update({status:"failed",error_code:code.slice(0,100),error_message:"Payment verification failed.",updated_at:new Date().toISOString()}).eq("id",id).not("status","in","(succeeded,refunded)");}
export async function finalizeAttempt(id:string,paymentId:string,amount:string,currency:string,environment:IyzicoEnvironment,metadata:VerifiedPaymentMetadata){const{data,error}=await admin().rpc("iyzico_finalize_payment_v3",{p_attempt_id:id,p_provider_payment_id:paymentId,p_amount:amount,p_paid_price:metadata.paidPrice,p_currency:currency,p_environment:environment,p_installment:metadata.installment,p_merchant_commission_rate:metadata.merchantCommissionRate,p_merchant_commission_rate_amount:metadata.merchantCommissionRateAmount,p_iyzi_commission_rate_amount:metadata.iyziCommissionRateAmount,p_iyzi_commission_fee:metadata.iyziCommissionFee,p_payment_transaction_id:metadata.paymentTransactionId,p_three_ds_status:metadata.threeDsStatus});if(error||!data)throw new Error("PAYMENT_FINALIZATION_FAILED");}
