"use client";
import {useEffect,useRef} from "react";
import type {ReactNode} from "react";
import {StudioIcon,type StudioIconName} from "@/components/studio/StudioIcons";

type Base={label?:string;help?:string;error?:string;disabled?:boolean;required?:boolean;id?:string;name?:string;className?:string};
const described=(id:string|undefined,help?:string,error?:string)=>[help?`${id}-help`:null,error?`${id}-error`:null].filter(Boolean).join(" ")||undefined;
export function StudioIconButton({icon,label,variant="default",size="md",...props}:{icon:StudioIconName;label:string;variant?:"default"|"ghost"|"subtle"|"danger";size?:"sm"|"md"|"lg"}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button type="button" title={label} aria-label={label} className={`studio-icon-button studio-icon-button--${variant} studio-icon-button--${size} ${props.className??""}`} {...props}><StudioIcon name={icon} className="h-5 w-5"/></button>}
export function StudioBadge({children,variant="neutral",icon}:{children:ReactNode;variant?:"neutral"|"info"|"success"|"warning"|"danger"|"archived"|"outline";icon?:StudioIconName}){return <span className={`studio-badge studio-badge--${variant}`}>{icon?<StudioIcon name={icon} className="h-3.5 w-3.5"/>:null}{children}</span>}
export function StudioPageHeader({eyebrow,title,description,icon,actions,back}:{eyebrow?:string;title:string;description?:string;icon?:StudioIconName;actions?:ReactNode;back?:ReactNode}){return <header className="studio-page-header">{back}{icon?<span className="studio-page-header__icon"><StudioIcon name={icon} className="h-6 w-6"/></span>:null}<div className="min-w-0 flex-1">{eyebrow?<p className="studio-eyebrow">{eyebrow}</p>:null}<h1 className="studio-page-title">{title}</h1>{description?<p className="studio-page-description">{description}</p>:null}</div>{actions?<div className="studio-page-actions">{actions}</div>:null}</header>}
export function StudioSectionHeader({title,description,icon,count,action}:{title:string;description?:string;icon?:StudioIconName;count?:ReactNode;action?:ReactNode}){return <header className="studio-section-header">{icon?<StudioIcon name={icon} className="h-5 w-5 text-[#927845]"/>:null}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2>{title}</h2>{count!==undefined?<span className="studio-count">{count}</span>:null}</div>{description?<p>{description}</p>:null}</div>{action}</header>}
export function StudioInput({label,help,error,...props}:Base&React.InputHTMLAttributes<HTMLInputElement>){return <label className="studio-control"><span>{label}{props.required?<b aria-hidden="true"> *</b>:null}</span><input {...props} aria-describedby={described(props.id,help,error)}/>{help?<small id={`${props.id}-help`}>{help}</small>:null}{error?<small id={`${props.id}-error`} role="alert">{error}</small>:null}</label>}
export function StudioTextarea({label,help,error,...props}:Base&React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <label className="studio-control"><span>{label}{props.required?<b aria-hidden="true"> *</b>:null}</span><textarea {...props} aria-describedby={described(props.id,help,error)}/>{help?<small id={`${props.id}-help`}>{help}</small>:null}{error?<small id={`${props.id}-error`} role="alert">{error}</small>:null}</label>}
export function StudioSelect({label,help,error,children,...props}:Base&React.SelectHTMLAttributes<HTMLSelectElement>){return <label className="studio-control"><span>{label}{props.required?<b aria-hidden="true"> *</b>:null}</span><select {...props} aria-describedby={described(props.id,help,error)}>{children}</select>{help?<small id={`${props.id}-help`}>{help}</small>:null}{error?<small id={`${props.id}-error`} role="alert">{error}</small>:null}</label>}
export function StudioCheckbox({label,...props}:Base&React.InputHTMLAttributes<HTMLInputElement>){return <label className="studio-checkbox"><input type="checkbox" {...props}/><span>{label}</span></label>}
export function StudioDateInput(props:Base&React.InputHTMLAttributes<HTMLInputElement>){return <StudioInput type="date" {...props}/>}
export function StudioToolbar({children,className=""}:{children:ReactNode;className?:string}){return <div className={`studio-toolbar-v2 ${className}`}>{children}</div>}
export function StudioFilterBar({children,className=""}:{children:ReactNode;className?:string}){return <div className={`studio-filter-bar ${className}`}>{children}</div>}
export function StudioSegmentedControl({items,value,onChange,ariaLabel}:{items:Array<{value:string;label:string}>;value:string;onChange?:(value:string)=>void;ariaLabel:string}){return <div className="studio-segmented" role="tablist" aria-label={ariaLabel}>{items.map(item=><button type="button" role="tab" aria-selected={value===item.value} key={item.value} onClick={()=>onChange?.(item.value)} className={value===item.value?"is-active":""}>{item.label}</button>)}</div>}
export function StudioSkeleton({className=""}:{className?:string}){return <span aria-hidden="true" className={`studio-skeleton ${className}`}/>}
export function StudioActionMenu({label="İşlemler",children}:{label?:string;children:ReactNode}){return <details className="studio-action-menu"><summary>{label}<StudioIcon name="chevron-down" className="h-4 w-4"/></summary><div>{children}</div></details>}
export function StudioModal({open,title,children,onClose,footer}:{open:boolean;title:string;children:ReactNode;onClose:()=>void;footer?:ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const handler=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};document.addEventListener("keydown",handler);ref.current?.focus();return()=>document.removeEventListener("keydown",handler);},[open,onClose]);if(!open)return null;return <div className="studio-modal-backdrop" role="presentation"><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="studio-modal-title" className="studio-modal"><header><h2 id="studio-modal-title">{title}</h2><StudioIconButton icon="close" label="Kapat" variant="ghost" onClick={onClose}/></header><div className="studio-modal__body">{children}</div>{footer?<footer>{footer}</footer>:null}</div></div>}
export function StudioDrawer({open,title,children,onClose,side="right"}:{open:boolean;title:string;children:ReactNode;onClose:()=>void;side?:"left"|"right"}){const ref=useRef<HTMLElement>(null);useEffect(()=>{if(!open)return;const handler=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};document.addEventListener("keydown",handler);ref.current?.focus();return()=>document.removeEventListener("keydown",handler);},[open,onClose]);if(!open)return null;return <div className="studio-modal-backdrop"><aside ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="studio-drawer-title" className={`studio-drawer studio-drawer--${side}`}><header><h2 id="studio-drawer-title">{title}</h2><StudioIconButton icon="close" label="Kapat" variant="ghost" onClick={onClose}/></header><div className="studio-drawer__body">{children}</div></aside></div>}
