"use client";
import {useState} from "react";
import {useActionState} from "react";
import {createStageAction} from "@/app/studio/(protected)/projects/[projectId]/stages/actions";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {ActiveStage} from "./StudioProjectStages";
import type {StudioProjectStage,NotificationActionState} from "@/lib/studio/notifications/notification-types";
type ActiveProps=React.ComponentProps<typeof ActiveStage>;const initial:NotificationActionState={success:false,message:""};
function Card({stage,...props}:{stage:StudioProjectStage}&Omit<ActiveProps,"stage">){const[open,setOpen]=useState(false);const date=(value:string|null)=>value?new Intl.DateTimeFormat("tr-TR").format(new Date(value)):"Belirtilmedi";return <><article className="flex min-h-[210px] min-w-0 flex-col rounded-xl border border-[#dedad1] bg-white p-4 shadow-[0_4px_18px_rgba(32,39,46,.035)]"><div className="flex items-start justify-between gap-3"><h3 className="min-w-0 break-words text-base font-semibold leading-6">{stage.title}</h3><button type="button" onClick={()=>setOpen(true)} className="shrink-0 rounded-lg border px-2.5 py-1.5 text-xs font-semibold" aria-label={`${stage.title} detaylarını aç`}>Detay</button></div><p className="mt-3 inline-flex w-fit rounded-full border border-[#dccda9] bg-[#f5efe2] px-2.5 py-1 text-xs font-semibold">{stage.status}</p><dl className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-[#f8f6f1] p-2"><dt className="text-[#747b78]">Başlangıç</dt><dd className="mt-1 font-semibold">{date(stage.startedAt)}</dd></div><div className="rounded-lg bg-[#f8f6f1] p-2"><dt className="text-[#747b78]">Tamamlanma</dt><dd className="mt-1 font-semibold">{date(stage.completedAt)}</dd></div></dl><p className="mt-auto pt-4 text-xs text-[#68716f]">Güncelleme: <span className="font-semibold">{date(stage.updatedAt)}</span></p></article>{open?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-0 sm:items-center sm:p-6"><div role="dialog" aria-modal="true" aria-label={`${stage.title} detayları`} className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-t-2xl bg-[#faf8f3] p-4 sm:rounded-2xl sm:p-6"><div className="mb-3 flex justify-end"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Kapat</button></div><ActiveStage stage={stage} {...props}/></div></div>:null}</>}
export default function StudioProjectStageMilestoneWorkspace({projectId,stages,attachments,files,canManage,whatsApp}:{projectId:string;stages:StudioProjectStage[];attachments:ActiveProps["attachments"];files:ActiveProps["files"];canManage:boolean;whatsApp:ActiveProps["whatsApp"]}){const[state,action,pending]=useActionState(createStageAction.bind(null,projectId),initial);const completed=stages.filter(stage=>stage.isSystem&&stage.status==="completed").length;const systems=stages.filter(stage=>stage.isSystem&&!stage.isArchived);const progress=systems.length?Math.round(completed/systems.length*100):0;return <section className="mt-6 space-y-6"><div className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Aktif Aşamalar</h2><p className="mt-1 text-sm">Sistem milestone ilerlemesi: %{progress}</p></div><div className="h-2 w-40 overflow-hidden rounded-full bg-slate-200"><span className="block h-full bg-[#9a7b40]" style={{width:`${progress}%`}}/></div></div>{canManage?<form action={action} className="mt-4 flex min-w-0 flex-col gap-3 sm:flex-row"><input name="title" required minLength={2} maxLength={180} placeholder="Yeni özel aşama" className="studio-field min-w-0 flex-1"/><button disabled={pending} className={studioButtonClass("primary","sm","shrink-0")}>Yeni Aşama Ekle</button>{state.message?<p role={state.success?"status":"alert"}>{state.message}</p>:null}</form>:null}</div><ol className="grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3">{stages.map(stage=><li key={stage.id}><Card stage={stage} projectId={projectId} attachments={attachments.filter(item=>item.stageId===stage.id)} files={files} canManage={canManage} whatsApp={whatsApp}/></li>)}</ol></section>}
