"use client";
import {useActionState} from "react";
import {createStageAction} from "@/app/studio/(protected)/projects/[projectId]/stages/actions";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {ActiveStage} from "./StudioProjectStages";
import StudioProjectStageMilestoneCard from "./StudioProjectStageMilestoneCard";
import type {StudioProjectStage,NotificationActionState} from "@/lib/studio/notifications/notification-types";
type ActiveProps=React.ComponentProps<typeof ActiveStage>;const initial:NotificationActionState={success:false,message:""};
function Card({stage,...props}:{stage:StudioProjectStage}&Omit<ActiveProps,"stage">){return <StudioProjectStageMilestoneCard stage={stage} {...props}/>;}
export default function StudioProjectStageMilestoneWorkspace({projectId,stages,attachments,files,canManage,whatsApp}:{projectId:string;stages:StudioProjectStage[];attachments:ActiveProps["attachments"];files:ActiveProps["files"];canManage:boolean;whatsApp:ActiveProps["whatsApp"]}){const[state,action,pending]=useActionState(createStageAction.bind(null,projectId),initial);const systems=stages.filter(stage=>stage.isSystem&&!stage.isArchived);const completed=systems.filter(stage=>stage.status==="completed").length;const progress=systems.length?Math.round(completed/systems.length*100):0;return <section className="mt-6 space-y-6"><div className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Aktif Aşamalar</h2><p className="mt-1 text-sm">Sistem milestone ilerlemesi: %{progress}</p></div><div className="h-2 w-40 overflow-hidden rounded-full bg-slate-200"><span className="block h-full bg-[#9a7b40]" style={{width:`${progress}%`}}/></div></div>{canManage?<form action={action} className="mt-4 flex min-w-0 flex-col gap-3 sm:flex-row"><input name="title" required minLength={2} maxLength={180} placeholder="Yeni özel aşama" className="studio-field min-w-0 flex-1"/><button disabled={pending} className={studioButtonClass("primary","sm","shrink-0")}>Yeni Aşama Ekle</button>{state.message?<p role={state.success?"status":"alert"}>{state.message}</p>:null}</form>:null}</div>{!stages.length?<div className="rounded-xl border border-dashed bg-white p-6"><p role="status" className="text-sm text-[#68716f]">Henüz proje aşaması bulunmuyor.</p>{canManage?<p className="mt-2 text-sm font-semibold">Yeni Aşama Oluştur</p>:null}</div>:<ol className="grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3">{stages.map(stage=><li key={stage.id}><Card stage={stage} projectId={projectId} attachments={attachments.filter(item=>item.stageId===stage.id)} files={files} canManage={canManage} whatsApp={whatsApp}/></li>)}</ol>}</section>}
