import "server-only";
import {createHash,randomBytes,timingSafeEqual} from "node:crypto";
import {createClient} from "@supabase/supabase-js";
import {z} from "zod";
import {getStudioContext, type StudioRole} from "@/lib/studio/auth/get-studio-context";
import type {VisualizerMachine,VisualizerMachineStatus,VisualizerRenderJob,VisualizerJobStatus,VisualizerJobDesiredState,VisualizerRenderRequest,VisualizerJobEventType,VisualizerJobActorType} from "./types";

export const VISUALIZER_HEARTBEAT_INTERVAL_SECONDS=30;
export const VISUALIZER_OFFLINE_THRESHOLD_SECONDS=90;
const machineInput=z.object({name:z.string().trim().min(1).max(120),hostname:z.string().trim().min(1).max(255),os:z.string().trim().min(1).max(80).default("unknown"),agentVersion:z.string().trim().min(1).max(80),gpuName:z.string().trim().max(255).optional().nullable(),gpuVramMb:z.number().int().min(0).max(4194304).optional().nullable(),maxConcurrentJobs:z.number().int().min(1).max(32).default(1)});
const heartbeatInput=z.object({agentVersion:z.string().trim().min(1).max(80),hostname:z.string().trim().min(1).max(255),os:z.string().trim().min(1).max(80),gpuName:z.string().trim().max(255).optional().nullable(),gpuVramMb:z.number().int().min(0).max(4194304).optional().nullable(),currentJobCount:z.number().int().min(0).max(32)});
// The project does not yet generate Supabase Database types for the additive
// Visualizer tables; keep this service boundary explicit until that generation
// is introduced rather than widening browser-facing contracts.
type Db=any;
function db():Db{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("VISUALIZER_DATABASE_NOT_CONFIGURED");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
function hash(secret:string){return createHash("sha256").update(secret,"utf8").digest("hex");}
function equalHash(a:string,b:string){const left=Buffer.from(a,"hex"),right=Buffer.from(b,"hex");return left.length===right.length&&timingSafeEqual(left,right);}
function secret(){return `arzv_${randomBytes(32).toString("base64url")}`;}
function mapMachine(row:Record<string,unknown>):VisualizerMachine{return{id:String(row.id),name:String(row.name),hostname:String(row.hostname),os:String(row.os),agentVersion:String(row.agent_version),gpuName:row.gpu_name?String(row.gpu_name):"",gpuVramMb:row.gpu_vram_mb===null?0:Number(row.gpu_vram_mb),status:String(row.status) as VisualizerMachineStatus,lastHeartbeatAt:row.last_heartbeat_at?String(row.last_heartbeat_at):undefined,maxConcurrentJobs:Number(row.max_concurrent_jobs),currentJobCount:Number(row.current_job_count)};}
async function internalContext(){const context=await getStudioContext();const role=context?.membership?.role as StudioRole|undefined;if(!context?.user||!context.membership)throw new Error("unauthorized");if(role!=="owner"&&role!=="admin")throw new Error("forbidden");return{workspaceId:context.membership.organization_id,userId:context.user.id};}
export function effectiveMachineStatus(machine:Pick<VisualizerMachine,"status"|"currentJobCount"|"lastHeartbeatAt">,now=Date.now()):VisualizerMachineStatus{if(machine.status==="disabled")return"disabled";if(!machine.lastHeartbeatAt||now-Date.parse(machine.lastHeartbeatAt)>VISUALIZER_OFFLINE_THRESHOLD_SECONDS*1000)return"offline";return machine.currentJobCount>0?"busy":"online";}
export async function registerMachine(input:unknown){const context=await internalContext(),value=machineInput.parse(input),service=db(),machineResult=await service.from("visualizer_machines").insert({workspace_id:context.workspaceId,name:value.name,hostname:value.hostname,os:value.os,agent_version:value.agentVersion,gpu_name:value.gpuName??null,gpu_vram_mb:value.gpuVramMb??null,max_concurrent_jobs:value.maxConcurrentJobs,status:"offline"}).select("*").single();if(machineResult.error||!machineResult.data)throw new Error("VISUALIZER_MACHINE_REGISTER_FAILED");const raw=secret(),credential=await service.from("visualizer_machine_credentials").insert({machine_id:machineResult.data.id,secret_hash:hash(raw)}).select("id").single();if(credential.error||!credential.data)throw new Error("VISUALIZER_CREDENTIAL_ISSUE_FAILED");await service.from("visualizer_machine_events").insert([{workspace_id:context.workspaceId,machine_id:machineResult.data.id,event_type:"registered",metadata:{}},{workspace_id:context.workspaceId,machine_id:machineResult.data.id,event_type:"credential_issued",metadata:{credentialId:credential.data.id}}]);return{machine:mapMachine(machineResult.data),credentialId:credential.data.id,agentSecret:raw};}
export async function revokeMachineCredential(machineId:string,credentialId:string){const context=await internalContext(),service=db(),machine=await service.from("visualizer_machines").select("id").eq("id",machineId).eq("workspace_id",context.workspaceId).maybeSingle();if(!machine.data)throw new Error("VISUALIZER_MACHINE_NOT_FOUND");const{data,error}=await service.from("visualizer_machine_credentials").update({revoked_at:new Date().toISOString()}).eq("id",credentialId).eq("machine_id",machineId).is("revoked_at",null).select("id").maybeSingle();if(error||!data)throw new Error("VISUALIZER_CREDENTIAL_NOT_FOUND");await service.from("visualizer_machine_events").insert({workspace_id:context.workspaceId,machine_id:machineId,event_type:"credential_revoked",metadata:{credentialId}});}
export async function issueMachineCredential(machineId:string){const context=await internalContext(),service=db(),machine=await service.from("visualizer_machines").select("id").eq("id",machineId).eq("workspace_id",context.workspaceId).maybeSingle();if(!machine.data)throw new Error("VISUALIZER_MACHINE_NOT_FOUND");const raw=secret(),credential=await service.from("visualizer_machine_credentials").insert({machine_id:machineId,secret_hash:hash(raw)}).select("id").single();if(credential.error||!credential.data)throw new Error("VISUALIZER_CREDENTIAL_ISSUE_FAILED");await service.from("visualizer_machine_events").insert({workspace_id:context.workspaceId,machine_id:machineId,event_type:"credential_issued",metadata:{credentialId:credential.data.id}});return{credentialId:credential.data.id,agentSecret:raw};}
export async function disableMachine(machineId:string,disabled:boolean){const context=await internalContext(),service=db(),{data,error}=await service.from("visualizer_machines").update({status:disabled?"disabled":"offline",disabled_at:disabled?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",machineId).eq("workspace_id",context.workspaceId).select("*").maybeSingle();if(error||!data)throw new Error("VISUALIZER_MACHINE_NOT_FOUND");await service.from("visualizer_machine_events").insert({workspace_id:context.workspaceId,machine_id:machineId,event_type:disabled?"disabled":"enabled",metadata:{}});return mapMachine(data);}
export async function authenticateAgent(token:string){if(!/^arzv_[A-Za-z0-9_-]{43}$/.test(token))return null;const service=db(),digest=hash(token),{data:credentials,error}=await service.from("visualizer_machine_credentials").select("id,machine_id,secret_hash,revoked_at").eq("secret_hash",digest).is("revoked_at",null).limit(1);if(error||!credentials?.[0])return null;const credential=credentials[0] as Record<string,unknown>;if(!equalHash(String(credential.secret_hash),digest))return null;const{data:machine}=await service.from("visualizer_machines").select("*").eq("id",credential.machine_id).maybeSingle();if(!machine||machine.disabled_at||machine.status==="disabled")return null;return{credentialId:String(credential.id),machine:mapMachine(machine),service};}
export async function heartbeatAgent(token:string,input:unknown){const auth=await authenticateAgent(token);if(!auth)throw new Error("invalid_agent_credential");const parsed=heartbeatInput.safeParse(input);if(!parsed.success)throw new Error("invalid_heartbeat_input");const value=parsed.data,now=new Date().toISOString(),status=value.currentJobCount>0?"busy":"online",result=await auth.service.from("visualizer_machines").update({agent_version:value.agentVersion,hostname:value.hostname,os:value.os,gpu_name:value.gpuName??null,gpu_vram_mb:value.gpuVramMb??null,current_job_count:value.currentJobCount,status,last_heartbeat_at:now,updated_at:now}).eq("id",auth.machine.id).is("disabled_at",null).select("*").single();if(result.error||!result.data)throw new Error("visualizer_heartbeat_failed");await auth.service.from("visualizer_machine_credentials").update({last_used_at:now}).eq("id",auth.credentialId);return{ok:true,machineId:auth.machine.id,status:status as VisualizerMachineStatus,serverTime:now};}

export const VISUALIZER_ASSIGNMENT_LEASE_SECONDS=120;
const jobStatus=z.enum(["queued","assigned","running","paused","completed","failed","cancelled"]);
const renderRequest=z.object({organizationId:z.uuid().optional(),projectId:z.uuid(),sceneId:z.uuid().optional(),cameraId:z.uuid().optional(),camera:z.unknown().optional(),quality:z.enum(["draft","standard","ultra_final"]),compute:z.enum(["auto","local","cloud"]),mode:z.enum(["interior","exterior"]),timeOfDay:z.enum(["day","golden_hour","night"]),weather:z.enum(["clear","cloudy","rain"]),prompt:z.string().trim().min(1).max(12000),negativePrompt:z.string().trim().max(12000).optional(),references:z.array(z.unknown()).max(100).optional(),settings:z.record(z.string(),z.unknown())});
const jobInput=z.object({request:renderRequest,priority:z.number().int().min(0).max(100).default(50),minimumGpuVramMb:z.number().int().min(0).max(4194304).optional(),maxAttempts:z.number().int().min(1).max(10).default(1)});
const agentUpdateInput=z.object({leaseId:z.uuid(),status:jobStatus.optional(),progressPercent:z.number().int().min(0).max(100).optional(),etaSeconds:z.number().int().min(0).nullable().optional(),errorCode:z.string().trim().max(120).optional(),errorMessage:z.string().trim().max(2000).optional()});
const transitions:Record<VisualizerJobStatus,VisualizerJobStatus[]>={queued:["assigned","cancelled"],assigned:["running","failed","cancelled"],running:["paused","completed","failed","cancelled"],paused:["running","failed","cancelled"],completed:[],failed:[],cancelled:[]};
export function canTransition(from:VisualizerJobStatus,to:VisualizerJobStatus){return transitions[from]?.includes(to)??false;}
export function effectiveJobDesiredState(status:VisualizerJobStatus,desired:VisualizerJobDesiredState):VisualizerJobDesiredState{return status==="cancelled"?"cancelled":desired;}
function mapJob(row:Record<string,unknown>):VisualizerRenderJob{return{id:String(row.id),organizationId:String(row.organization_id),projectId:String(row.project_id),createdBy:String(row.created_by),status:String(row.status) as VisualizerJobStatus,desiredState:String(row.desired_state) as VisualizerJobDesiredState,priority:Number(row.priority),quality:String(row.quality) as VisualizerRenderJob["quality"],requestedComputeMode:String(row.requested_compute_mode) as VisualizerRenderJob["requestedComputeMode"],resolvedComputeMode:row.resolved_compute_mode?String(row.resolved_compute_mode) as "local"|"cloud":undefined,renderMode:String(row.render_mode) as VisualizerRenderJob["renderMode"],timeOfDay:String(row.time_of_day) as VisualizerRenderJob["timeOfDay"],weather:String(row.weather) as VisualizerRenderJob["weather"],requestSnapshot:row.request_snapshot as VisualizerRenderRequest,assignedMachineId:row.assigned_machine_id?String(row.assigned_machine_id):undefined,assignmentLeaseId:row.assignment_lease_id?String(row.assignment_lease_id):undefined,assignmentLeaseExpiresAt:row.assignment_lease_expires_at?String(row.assignment_lease_expires_at):undefined,minimumGpuVramMb:row.minimum_gpu_vram_mb===null?undefined:Number(row.minimum_gpu_vram_mb),progressPercent:Number(row.progress_percent),etaSeconds:row.eta_seconds===null?undefined:Number(row.eta_seconds),attemptCount:Number(row.attempt_count),maxAttempts:Number(row.max_attempts),errorCode:row.error_code?String(row.error_code):undefined,errorMessage:row.error_message?String(row.error_message):undefined,queuedAt:String(row.queued_at),assignedAt:row.assigned_at?String(row.assigned_at):undefined,startedAt:row.started_at?String(row.started_at):undefined,completedAt:row.completed_at?String(row.completed_at):undefined,failedAt:row.failed_at?String(row.failed_at):undefined,cancelledAt:row.cancelled_at?String(row.cancelled_at):undefined,lastAgentUpdateAt:row.last_agent_update_at?String(row.last_agent_update_at):undefined};}
async function projectContext(projectId:string){const context=await getStudioContext();if(!context?.user||!context.membership)throw new Error("unauthorized");const service=db(),project=await service.from("studio_projects").select("id,organization_id,is_archived").eq("id",projectId).eq("organization_id",context.membership.organization_id).maybeSingle();if(project.error||!project.data||project.data.is_archived)throw new Error("project_not_found");return{service,userId:context.user.id,organizationId:context.membership.organization_id};}
async function event(service:Db,row:{organizationId:string;jobId:string;eventType:VisualizerJobEventType;fromStatus?:string;toStatus?:string;actorType:VisualizerJobActorType;actorUserId?:string;actorMachineId?:string;metadata?:Record<string,unknown>}){await service.from("visualizer_render_job_events").insert({organization_id:row.organizationId,job_id:row.jobId,event_type:row.eventType,from_status:row.fromStatus??null,to_status:row.toStatus??null,actor_type:row.actorType,actor_user_id:row.actorUserId??null,actor_machine_id:row.actorMachineId??null,metadata:row.metadata??{}});}
export async function createRenderJob(input:unknown){const value=jobInput.parse(input),request={...value.request,organizationId:undefined};const scope=await projectContext(value.request.projectId);if(value.request.compute==="cloud")throw new Error("cloud_compute_unavailable");const now=new Date().toISOString(),insert=await scope.service.from("visualizer_render_jobs").insert({organization_id:scope.organizationId,project_id:value.request.projectId,created_by:scope.userId,status:"queued",desired_state:"running",priority:value.priority,quality:value.request.quality,requested_compute_mode:value.request.compute,resolved_compute_mode:null,render_mode:value.request.mode,time_of_day:value.request.timeOfDay,weather:value.request.weather,request_snapshot:{schemaVersion:1,...request,organizationId:scope.organizationId},minimum_gpu_vram_mb:value.minimumGpuVramMb??null,max_attempts:value.maxAttempts,queued_at:now}).select("*").single();if(insert.error||!insert.data)throw new Error("visualizer_job_create_failed");await event(scope.service,{organizationId:scope.organizationId,jobId:insert.data.id,eventType:"created",toStatus:"queued",actorType:"user",actorUserId:scope.userId});return mapJob(insert.data);}
export async function claimNextRenderJob(token:string){const auth=await authenticateAgent(token);if(!auth)throw new Error("invalid_agent_credential");const result=await auth.service.rpc("visualizer_claim_next_render_job",{p_machine_id:auth.machine.id,p_now:new Date().toISOString(),p_lease_seconds:VISUALIZER_ASSIGNMENT_LEASE_SECONDS});if(result.error)throw new Error("visualizer_claim_failed");const row=(result.data??[])[0] as Record<string,unknown>|undefined;if(!row)return{job:null};await event(auth.service,{organizationId:String(row.organization_id),jobId:String(row.id),eventType:"assigned",fromStatus:"queued",toStatus:"assigned",actorType:"machine",actorMachineId:auth.machine.id});return{job:mapJob(row),leaseId:String(row.assignment_lease_id),desiredState:String(row.desired_state) as VisualizerJobDesiredState};}
export async function updateAgentJob(token:string,jobId:string,input:unknown){const auth=await authenticateAgent(token);if(!auth)throw new Error("invalid_agent_credential");const value=agentUpdateInput.parse(input),found=await auth.service.from("visualizer_render_jobs").select("*").eq("id",jobId).eq("assigned_machine_id",auth.machine.id).eq("assignment_lease_id",value.leaseId).maybeSingle();if(found.error||!found.data)throw new Error("job_lease_invalid");const current=String(found.data.status) as VisualizerJobStatus;if(value.status&&value.status!==current&&!canTransition(current,value.status))throw new Error("illegal_job_transition");if(current==="completed"||current==="cancelled")throw new Error("job_terminal");const now=new Date().toISOString(),payload:Record<string,unknown>={progress_percent:value.progressPercent??found.data.progress_percent,eta_seconds:value.etaSeconds===undefined?found.data.eta_seconds:value.etaSeconds,last_agent_update_at:now,updated_at:now};if(value.errorCode!==undefined)payload.error_code=value.errorCode;if(value.errorMessage!==undefined)payload.error_message=value.errorMessage;if(value.status){payload.status=value.status;if(value.status==="running"&&!found.data.started_at)payload.started_at=now;if(value.status==="completed")payload.completed_at=now;if(value.status==="failed")payload.failed_at=now;if(value.status==="cancelled")payload.cancelled_at=now;}const updated=await auth.service.from("visualizer_render_jobs").update(payload).eq("id",jobId).eq("assigned_machine_id",auth.machine.id).eq("assignment_lease_id",value.leaseId).select("*").single();if(updated.error||!updated.data)throw new Error("visualizer_job_update_failed");if(value.status&&value.status!==current){const eventType:VisualizerJobEventType=value.status==="running"?(current==="paused"?"resumed":"started"):value.status==="paused"?"paused":value.status==="completed"?"completed":value.status==="failed"?"failed":value.status==="cancelled"?"cancelled":"started";await event(auth.service,{organizationId:String(updated.data.organization_id),jobId,eventType,fromStatus:current,toStatus:value.status,actorType:"machine",actorMachineId:auth.machine.id});}return{ok:true,desiredState:String(updated.data.desired_state) as VisualizerJobDesiredState,job:mapJob(updated.data)};}
export async function requestJobState(jobId:string,desired:VisualizerJobDesiredState){const scope=await projectContext((await scopeJobProject(jobId,await projectContextFromUser())));const found=await scope.service.from("visualizer_render_jobs").select("*").eq("id",jobId).eq("organization_id",scope.organizationId).maybeSingle();if(found.error||!found.data)throw new Error("job_not_found");const current=String(found.data.status) as VisualizerJobStatus;if(current==="completed"||current==="cancelled"||current==="failed")throw new Error("job_terminal");const now=new Date().toISOString();if(desired==="cancelled"&&current==="queued"){const updated=await scope.service.from("visualizer_render_jobs").update({status:"cancelled",desired_state:"cancelled",cancelled_at:now,updated_at:now}).eq("id",jobId).eq("status","queued").select("*").single();if(updated.error||!updated.data)throw new Error("job_update_failed");await event(scope.service,{organizationId:scope.organizationId,jobId,eventType:"cancelled",fromStatus:"queued",toStatus:"cancelled",actorType:"user",actorUserId:scope.userId});return mapJob(updated.data);}const updated=await scope.service.from("visualizer_render_jobs").update({desired_state:desired,updated_at:now}).eq("id",jobId).eq("organization_id",scope.organizationId).select("*").single();if(updated.error||!updated.data)throw new Error("job_update_failed");await event(scope.service,{organizationId:scope.organizationId,jobId,eventType:desired==="cancelled"?"cancel_requested":desired==="paused"?"paused":"resumed",fromStatus:current,toStatus:current,actorType:"user",actorUserId:scope.userId});return mapJob(updated.data);}
async function projectContextFromUser(){const context=await getStudioContext();if(!context?.user||!context.membership)throw new Error("unauthorized");return{organizationId:context.membership.organization_id,userId:context.user.id,service:db()};}
async function scopeJobProject(jobId:string,scope:{organizationId:string;userId:string;service:Db}){const row=await scope.service.from("visualizer_render_jobs").select("project_id").eq("id",jobId).eq("organization_id",scope.organizationId).maybeSingle();if(row.error||!row.data)throw new Error("job_not_found");return row.data.project_id as string;}
export async function retryFailedJob(jobId:string){const scope=await projectContextFromUser(),found=await scope.service.from("visualizer_render_jobs").select("*").eq("id",jobId).eq("organization_id",scope.organizationId).maybeSingle();if(found.error||!found.data)throw new Error("job_not_found");if(found.data.status!=="failed")throw new Error("job_not_retryable");if(Number(found.data.attempt_count)>=Number(found.data.max_attempts))throw new Error("job_attempt_limit");const updated=await scope.service.from("visualizer_render_jobs").update({status:"queued",desired_state:"running",assigned_machine_id:null,assignment_lease_id:null,assignment_lease_expires_at:null,resolved_compute_mode:null,error_code:null,error_message:null,progress_percent:0,failed_at:null,queued_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",jobId).eq("status","failed").select("*").single();if(updated.error||!updated.data)throw new Error("job_retry_failed");await event(scope.service,{organizationId:scope.organizationId,jobId,eventType:"requeued",fromStatus:"failed",toStatus:"queued",actorType:"user",actorUserId:scope.userId});return mapJob(updated.data);}
export async function requeueExpiredAssignedJob(jobId:string){const service=db(),now=new Date().toISOString(),found=await service.from("visualizer_render_jobs").select("*").eq("id",jobId).eq("status","assigned").lt("assignment_lease_expires_at",now).maybeSingle();if(found.error||!found.data)return null;const updated=await service.from("visualizer_render_jobs").update({status:"queued",assigned_machine_id:null,assignment_lease_id:null,assignment_lease_expires_at:null,resolved_compute_mode:null,queued_at:now,updated_at:now}).eq("id",jobId).eq("status","assigned").select("*").single();if(updated.error||!updated.data)return null;await event(service,{organizationId:String(updated.data.organization_id),jobId,eventType:"lease_expired",fromStatus:"assigned",toStatus:"queued",actorType:"system"});return mapJob(updated.data);}
