import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";

const read=path=>readFileSync(path,"utf8");
const migration=read("supabase/migrations/042_client_notification_center.sql"),rollback=read("supabase/rollbacks/042_client_notification_center.rollback.sql"),route=read("app/client/(portal)/notifications/page.tsx"),repository=read("lib/client-portal/get-client-notifications.ts"),page=read("components/client-portal/ClientNotificationsPage.tsx"),list=read("components/client-portal/ClientNotificationsList.tsx"),api=read("app/api/client/notifications/read/route.ts"),navigation=read("components/client-portal/ClientPortalNavigation.tsx"),header=read("components/client-portal/ClientPortalHeader.tsx"),layout=read("app/client/(portal)/layout.tsx"),dashboard=read("components/client-portal/ClientPortalDashboard.tsx"),dashboardRepository=read("lib/client-portal/get-client-dashboard.ts"),css=read("app/client/(portal)/notifications/client-notifications.css");

test("notification route preserves canonical project selection and client context",()=>{assert.match(route,/getClientPortalContext\(selected\)/);assert.match(route,/getClientNotifications\(context\.project\.id\)/);assert.match(route,/redirect\("\/client\/login\?next=/);assert.match(route,/notFound\(\)/);assert.doesNotMatch(route,/organization_id|service.role|studio_notifications/i)});
test("list projection permits only accessible client portal notifications",()=>{assert.match(repository,/client_portal_list_notifications/);assert.doesNotMatch(repository,/\.from\(|studio_notifications|service.role/i);assert.match(migration,/studio_client_can_access_project\(auth\.uid\(\),p_project_id\)/);assert.match(migration,/n\.project_id=p_project_id and n\.channel='client_portal'/);assert.match(migration,/p\.organization_id=n\.organization_id and not p\.is_archived/)});
test("revoked passive cross-project and cross-organization access remain denied",()=>{assert.match(migration,/studio_client_can_access_project\(auth\.uid\(\),n\.project_id\)/);assert.match(migration,/n\.project_id=p_project_id/);assert.match(migration,/p\.organization_id=n\.organization_id/);assert.doesNotMatch(migration,/disable row level security|grant (select|update|insert) on (table )?public\.studio_notifications to authenticated/i)});
test("read receipts are user-specific and cannot be directly mutated",()=>{assert.match(migration,/primary key\(user_id,notification_id\)/);assert.match(migration,/user_id uuid not null references auth\.users/);assert.match(migration,/revoke all on table public\.studio_client_notification_reads from public,anon,authenticated/);assert.match(migration,/r\.user_id=auth\.uid\(\)/);assert.doesNotMatch(migration,/create policy .*studio_client_notification_reads.*(insert|update)/i)});
test("single read mutation derives organization and project only after access validation",()=>{assert.match(migration,/where n\.id=p_notification_id and n\.channel='client_portal' and public\.studio_client_can_access_project\(auth\.uid\(\),n\.project_id\)/);assert.match(migration,/values\(v_notification\.id,auth\.uid\(\),v_notification\.organization_id,v_notification\.project_id\)/);assert.match(api,/client_portal_mark_notification_read/);assert.match(api,/Bildirim bulunamadı veya erişim reddedildi/)});
test("mark all affects only accessible notifications in the selected project",()=>{assert.match(migration,/not public\.studio_client_can_access_project\(auth\.uid\(\),p_project_id\)/);assert.match(migration,/where n\.project_id=p_project_id and n\.channel='client_portal'/);assert.match(migration,/on conflict\(user_id,notification_id\) do nothing/);assert.match(api,/client_portal_mark_project_notifications_read/)});
test("header count is one safe aggregate and navigation is active",()=>{assert.match(migration,/client_portal_unread_notification_count/);assert.match(repository,/client_portal_unread_notification_count/);assert.match(layout,/getClientUnreadNotificationCount/);assert.match(header,/client-notification-badge/);assert.match(header,/unreadCount/);assert.match(header,/\/client\/notifications/);assert.match(navigation,/href:\s*"\/client\/notifications"/);assert.doesNotMatch(navigation,/label:\s*"Bildirimler"[^}]*disabled/)});
test("notification UI uses real safe fields filters drawer and existing design primitives",()=>{for(const field of["title","body","created_at","source_type","project_name","read_at"])assert.match(list,new RegExp(`item\\.${field}|selected\\.${field}`));assert.match(list,/StudioSegmentedControl/);assert.match(list,/StudioDrawer/);assert.match(list,/StudioIconSurface/);assert.match(page,/StudioPageHeader/);assert.match(page,/StudioKpiCard/);assert.match(page,/StudioEmptyState/);assert.doesNotMatch(list+page,/mock|placeholder\.com|recipient_snapshot|variables_snapshot|provider_message_id/i)});
test("dashboard notification count and activity keep the same safe projection",()=>{assert.match(dashboardRepository,/client_portal_list_\$\{name\}/);assert.match(dashboard,/data\.notifications\.data\.filter\(item=>!item\.read_at\)/);assert.match(dashboard,/data\.notifications\.data\.map/);assert.doesNotMatch(dashboard,/studio_notifications|recipient_snapshot|variables_snapshot/i)});
test("migration and rollback are balanced and Studio notifications remain intact",()=>{for(const sql of[migration,rollback]){assert.match(sql,/^begin;/);assert.match(sql,/commit;/);assert.match(sql,/notify pgrst,'reload schema'/)}assert.doesNotMatch(migration,/delete from|truncate|drop table public\.studio_notifications|alter table public\.studio_notifications disable/i);assert.match(rollback,/drop table if exists public\.studio_client_notification_reads/);assert.match(rollback,/create function public\.client_portal_list_notifications/)});
test("notification layout retains current responsive neutral portal language",()=>{for(const color of["#fff","#edf1f5","#334155"])assert.match(css,new RegExp(color));assert.match(css,/@media\(max-width:767px\)/);assert.match(css,/min-width:0/);assert.doesNotMatch(css,/cream|beige|ivory|warm sand/i)});
