import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
import test from"node:test";
import{appLoginUrl}from"../../lib/routing/app-domains.ts";

const read=path=>readFileSync(path,"utf8");
const migration=read("supabase/migrations/046_client_payment_requests.sql"),rollback=read("supabase/rollbacks/046_client_payment_requests.rollback.sql"),repository=read("lib/studio/finance/payment-request-repository.ts"),actions=read("app/studio/(protected)/projects/[projectId]/finance/actions.ts"),studioUi=read("components/studio/finance/StudioPaymentRequests.tsx"),clientRepository=read("lib/client-portal/get-client-payment-requests.ts"),clientRoute=read("app/client/(portal)/finance/page.tsx"),clientUi=read("components/client-portal/ClientPaymentRequests.tsx"),checkout=read("app/api/client/payments/[paymentRequestId]/checkout/route.ts"),publicPage=read("app/[locale]/online-odeme/page.tsx");

test("payment request schema follows the existing exact finance money model",()=>{assert.match(migration,/create table public\.studio_client_payment_requests/);assert.match(migration,/amount numeric\(16,2\) not null check\(amount>0\)/);assert.match(migration,/payment_type in\('deposit','progress_payment','final_payment','other'\)/);assert.match(migration,/status in\('pending','paid','cancelled'\)/);assert.match(migration,/paid_at timestamptz/);assert.doesNotMatch(migration,/checkout_token|card_number|cvv|iyzico_secret/i);assert.match(repository,/regex\(\/\^\\d\{1,12\}/);});

test("Studio creation is owner and project scoped",()=>{assert.match(migration,/studio_create_client_payment_request/);assert.match(migration,/studio_has_organization_role\(v_org,array\['owner'\]\)/);assert.match(migration,/p\.id=p_project_id and not p\.is_archived/);assert.match(repository,/scope\(projectId,true\)/);assert.match(repository,/p_amount:value\.amount/);assert.match(actions,/createStudioPaymentRequestAction/);assert.doesNotMatch(actions,/organizationId|createdBy|paidAt/);});

test("Studio lists requests and only pending requests can be cancelled",()=>{assert.match(repository,/studio_client_payment_requests/);assert.match(migration,/studio_cancel_client_payment_request/);assert.match(migration,/project_id=p_project_id and status='pending'/);assert.match(migration,/old\.status<>'pending'/);assert.match(studioUi,/Müşteri Ödeme Talepleri/);assert.match(studioUi,/request\.status==="pending"/);assert.match(studioUi,/Ödeme Talebi Oluştur/);});

test("client projection exposes own active project payments and hides cancelled",()=>{const projection=migration.match(/create function public\.client_portal_list_payment_requests[\s\S]*?\$\$;/)?.[0]??"";assert.match(projection,/studio_client_can_access_project\(auth\.uid\(\),r\.project_id\)/);assert.match(projection,/r\.project_id=p_project_id/);assert.match(projection,/r\.status in\('pending','paid'\)/);assert.doesNotMatch(projection,/expense|cost|margin|profitability|supplier|tax_rate|created_by/);assert.match(clientRepository,/client_portal_list_payment_requests/);assert.doesNotMatch(clientRepository,/\.from\(|service.role/i);assert.match(clientRoute,/getClientPaymentRequests\(context\.project\.id\)/);});

test("client cannot create update delete change amount or mark paid",()=>{assert.match(migration,/revoke all on table public\.studio_client_payment_requests from public,anon,authenticated/);assert.match(migration,/grant select on table public\.studio_client_payment_requests to authenticated/);assert.doesNotMatch(migration,/grant (insert|update|delete).*studio_client_payment_requests.*authenticated/i);assert.doesNotMatch(clientRepository,/\.insert\(|\.update\(|p_amount|status:\s*["']paid/i);assert.match(checkout,/CLIENT_PAYMENT_FIELDS_REJECTED/);assert.doesNotMatch(checkout,/body\.(amount|currency|projectId)/);});

test("revoked and cross-project access cannot resolve payment IDs",()=>{assert.match(migration,/studio_client_can_access_project\(auth\.uid\(\),r\.project_id\)/);assert.match(migration,/where r\.id=p_payment_request_id and r\.status='pending'/);assert.match(checkout,/authenticatedPayment/);assert.match(checkout,/PAYMENT_NOT_FOUND/);assert.doesNotMatch(checkout,/body\.(organization_id|project_id|amount|currency)/);});

test("checkout boundary accepts only the payment request ID and delegates verified payment state",()=>{assert.match(checkout,/params:Promise<\{paymentRequestId:string\}>/);assert.match(checkout,/z\.uuid\(\)/);assert.match(checkout,/initializeCheckout/);assert.match(checkout,/PAYMENT_PROVIDER_NOT_CONFIGURED/);assert.doesNotMatch(checkout,/body\.(amount|currency|projectId)|paid_at/i);assert.match(clientUi,/paymentRequestId=\{item\.id\}/);});

test("client UI distinguishes pending completed and refunded while cancelled remains absent",()=>{assert.match(clientUi,/item\.status==="pending"/);assert.match(clientUi,/\["paid","refunded"\]\.includes/);assert.match(clientUi,/ÖDEME BEKLİYOR/);assert.match(clientUi,/Ödendi/);assert.match(clientUi,/item\.projectName/);assert.doesNotMatch(clientUi,/cancelled|expense|margin|profit/i);});

test("public iyzico CTA uses canonical client login helper",()=>{const previous=process.env.NEXT_PUBLIC_CLIENT_PORTAL_URL;try{process.env.NEXT_PUBLIC_CLIENT_PORTAL_URL="http://localhost:3000/client";assert.equal(appLoginUrl("client","/client/finance"),"http://localhost:3000/client/login?next=%2Fclient%2Ffinance");process.env.NEXT_PUBLIC_CLIENT_PORTAL_URL="https://client.arzmimarlik.net";assert.equal(appLoginUrl("client","/client/finance"),"https://client.arzmimarlik.net/login?next=%2Ffinance");}finally{if(previous===undefined)delete process.env.NEXT_PUBLIC_CLIENT_PORTAL_URL;else process.env.NEXT_PUBLIC_CLIENT_PORTAL_URL=previous;}assert.match(publicPage,/appLoginUrl\("client","\/client\/finance"\)/);assert.match(publicPage,/href=\{clientFinanceHref\}/);});

test("migration and rollback are balanced without notification refactor",()=>{for(const sql of[migration,rollback]){assert.match(sql,/^begin;/);assert.match(sql,/notify pgrst,'reload schema'/);assert.match(sql,/commit;/);}assert.match(rollback,/drop table if exists public\.studio_client_payment_requests/);assert.doesNotMatch(migration,/alter table public\.studio_notifications|studio_client_notification_reads|payment_provider_token/i);});
