import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

const read=path=>readFile(new URL(path,import.meta.url),"utf8");
const[migration,rollback,repository,provider,contract,actions,downloadRoute,detail,workspace,folderActions,syncStatus]=await Promise.all([
 read("../../supabase/migrations/008_google_drive_file_operations.sql"),read("../../supabase/migrations/008_google_drive_file_operations.rollback.sql"),read("../../lib/studio/files/file-repository.ts"),read("../../lib/studio/files/storage/google-drive-provider.ts"),read("../../lib/studio/files/storage/storage-provider.ts"),read("../../app/studio/(protected)/projects/[projectId]/files/actions.ts"),read("../../app/studio/(protected)/projects/[projectId]/files/[fileId]/download/route.ts"),read("../../components/studio/files/StudioFileDetail.tsx"),read("../../components/studio/files/StudioProjectFilesPage.tsx"),read("../../components/studio/files/StudioFolderActions.tsx"),read("../../components/studio/files/StudioSyncStatus.tsx")
]);

test("migration 008 and rollback are balanced, incremental and contain no delete policy",()=>{for(const sql of[migration,rollback]){assert.match(sql,/^begin;/);assert.match(sql,/commit;\s*$/);assert.equal((sql.match(/\$\$/g)??[]).length%2,0);}for(const field of["previous_folder_id","previous_external_parent_folder_id","sync_error_code","previous_parent_folder_id"])assert.match(migration,new RegExp(field));assert.doesNotMatch(migration,/create policy|for delete/i);});
test("rollback restores both validation functions before operation fields are removed",()=>{assert.match(rollback,/create or replace function public\.studio_validate_project_file/);assert.match(rollback,/create or replace function public\.studio_validate_project_folder/);assert.ok(rollback.indexOf("studio_validate_project_folder")<rollback.indexOf("drop column if exists previous_parent_folder_id"));});
test("provider contract exposes every requested operation",()=>{for(const method of["downloadFile","renameFile","moveFile","archiveFile","restoreFile","createFolder","renameFolder","moveFolder","archiveFolder","restoreFolder","verifyFileExists","verifyFolderExists","getFileMetadata","getFolderMetadata"])assert.match(contract,new RegExp(`${method}\\(`));});
test("Drive download verifies DB-owned id, metadata, trash and parent before streaming",()=>{assert.match(repository,/fileRow\(scope,fileId\)/);assert.match(repository,/verifyFileExists/);assert.match(repository,/metadata\.trashed/);assert.match(repository,/metadata\.parents\.includes\(row\.external_parent_folder_id/);assert.match(downloadRoute,/new Response\(result\.response\.body/);assert.match(downloadRoute,/Content-Disposition/);assert.doesNotMatch(downloadRoute,/access_token|refresh_token|webViewLink|getPublicUrl/);});
test("legacy Supabase download remains a private signed redirect",()=>{assert.match(repository,/createSignedFileDownload/);assert.match(repository,/kind:"redirect"/);assert.match(downloadRoute,/NextResponse\.redirect\(result\.url/);});
test("file rename preserves extension, rejects duplicates and persists after Drive",()=>{assert.match(repository,/if\(supplied&&supplied!==extension\)/);assert.match(repository,/duplicateFile\(scope,row,row\.folder_id/);assert.ok(repository.indexOf("googleDriveStorageProvider.renameFile")<repository.indexOf('persistAfterDrive(scope,"studio_project_files",row.id,{display_name'));});
test("file move changes Drive parents without copy or re-upload",()=>{assert.match(repository,/const destination=await folderRow\(scope,folderId\)/);assert.match(provider,/addParents=.*removeParents=/);assert.match(repository,/duplicateFile\(scope,row,destination\.id/);assert.doesNotMatch(provider,/files\.copy|copyFile/);});
test("file archive and restore preserve parents and use controlled fallback",()=>{assert.match(repository,/systemFolder\(scope,"08 Arşiv"\)/);assert.match(repository,/previous_folder_id:row\.folder_id/);assert.match(repository,/previous_external_parent_folder_id:row\.external_parent_folder_id/);assert.match(repository,/systemFolder\(scope,"01 Proje"\)/);assert.match(repository,/previous_folder_id:null/);});
test("custom folders use stable appProperties identity and scoped idempotent lookup",()=>{assert.match(repository,/stableFolderId/);assert.match(repository,/logical_folder_id:id/);assert.match(provider,/pageSize=2/);assert.match(repository,/if\(error\?\.code==="23505"\)/);});
test("folder move prevents self, descendant cycles and system mutations",()=>{assert.match(repository,/if\(destination\?\.id===row\.id\)/);assert.match(repository,/while\(cursor\)/);assert.match(repository,/if\(row\.is_system\)/);assert.match(repository,/Sistem klasörleri taşınamaz/);});
test("normal archive never deletes, trashes or changes permissions",()=>{assert.doesNotMatch(provider,/method:\s*"DELETE"|trashed\s*:\s*true|permissions/);assert.match(provider,/archiveFile:move/);assert.match(provider,/archiveFolder:move/);});
test("partial failures and drift verification store safe normalized codes",()=>{assert.match(repository,/sync_status:"error",sync_error_code:code/);assert.match(repository,/metadata_persist_failed/);assert.match(repository,/external_file_missing/);assert.match(repository,/external_folder_missing/);assert.doesNotMatch(actions,/response\.json|response\.text|Google API/);});
test("organization and external identifiers are always server derived",()=>{assert.match(repository,/getStudioContext/);assert.match(repository,/if\(owner&&role!=="owner"\)/);assert.doesNotMatch(actions,/formData\.get\("organizationId"|formData\.get\("external/);assert.doesNotMatch(detail,/externalFileId|organizationId|accessToken/);assert.doesNotMatch(folderActions,/externalFolderId|organizationId/);});
test("UI includes actions, confirmations, pending state and textual sync status",()=>{for(const label of["İndir","Yeniden Adlandır","Klasöre Taşı","Arşivle","Geri Al","Drive Durumunu Doğrula"])assert.ok(detail.includes(label)||folderActions.includes(label));assert.match(folderActions,/Klasör Eşlemesini Doğrula/);assert.match(folderActions,/İçeriği silinmez/);assert.match(detail,/StudioPendingLabel/);for(const label of["Senkronize","İşlem bekliyor","Senkronizasyon hatası","İşlem gerekli"])assert.match(syncStatus,new RegExp(label));assert.match(workspace,/StudioSyncStatus/);});
test("safe download errors are normalized Turkish responses",()=>{for(const text of["Google Drive dosyası bulunamadı.","Google Drive bağlantısının yeniden yetkilendirilmesi gerekiyor.","Dosyayı indirme yetkiniz bulunmuyor.","Dosya geçici olarak indirilemiyor."])assert.ok(downloadRoute.includes(text));});
