import assert from "node:assert/strict";
import {createHmac} from "node:crypto";
import {readFileSync} from "node:fs";
import test from "node:test";
import {canonicalPrice,iyzicoAuthorization,responseSignature,verifyInitializeSignature,verifyRetrieveSignature} from "../../lib/payments/iyzico/signatures.ts";

const read=path=>readFileSync(path,"utf8");
const migration=read("supabase/migrations/047_iyzico_payment_attempts.sql"),checkout=read("app/api/client/payments/[paymentRequestId]/checkout/route.ts"),callback=read("app/api/client/payments/iyzico/callback/route.ts"),verification=read("lib/payments/iyzico/verification.ts"),client=read("lib/payments/iyzico/client.ts"),repository=read("lib/payments/iyzico/repository.ts"),button=read("components/client-portal/ClientPaymentCheckoutButton.tsx"),env=read(".env.example");

test("IYZWSv2 signs the exact serialized body and URI path",()=>{const api="api",secret="secret",random="123",path="/payment/test",body=JSON.stringify({price:75,currency:"TRY"}),expected=createHmac("sha256",secret).update(random+path+body).digest("hex"),authorization=iyzicoAuthorization(api,secret,random,path,body),decoded=Buffer.from(authorization.slice("IYZWSv2 ".length),"base64").toString("utf8");assert.equal(decoded,`apiKey:${api}&randomKey:${random}&signature:${expected}`);assert.match(client,/const body=JSON\.stringify\(payload\)/);assert.match(client,/iyzicoAuthorization\([^)]*path,body\)/);assert.match(client,/body,cache:"no-store"/);});

test("official response-signature ordering and trailing-zero contract are implemented",()=>{const secret="sandbox-qaIiLIxhjMgx3LSKIVvp6j17NunHOFtD";assert.equal(responseSignature(secret,["22416032","TRY","basketId","conversationId","10.5","10.5"]),"836c3a6c8db86c81043f2ca74edb13518b54a813f454f8dd762f0dd658610173");assert.equal(canonicalPrice("10.51050"),"10.5105");const init={conversationId:"c",token:"t"};init.signature=responseSignature(secret,["c","t"]);assert.equal(verifyInitializeSignature(secret,init),true);const result={paymentStatus:"SUCCESS",paymentId:"p",currency:"TRY",basketId:"b",conversationId:"c",paidPrice:"10.00",price:"10.0",token:"t"};result.signature=responseSignature(secret,["SUCCESS","p","TRY","b","c","10","10","t"]);assert.equal(verifyRetrieveSignature(secret,result),true);result.signature="bad";assert.equal(verifyRetrieveSignature(secret,result),false);});

test("checkout is authenticated server-authoritative and rejects client payment fields",()=>{assert.match(checkout,/runtime="nodejs"/);assert.match(checkout,/UNAUTHORIZED/);assert.match(checkout,/CLIENT_PAYMENT_FIELDS_REJECTED/);assert.match(checkout,/authenticatedPayment/);assert.match(checkout,/price=amount\(attempt\.amount\)/);assert.doesNotMatch(checkout,/body\.(amount|currency|projectId)/);assert.match(checkout,/PAYMENT_ALREADY_PAID/);assert.match(checkout,/PAYMENT_CANCELLED/);assert.match(checkout,/PAYMENT_NOT_FOUND/);assert.match(checkout,/CUSTOMER_PAYMENT_PROFILE_INCOMPLETE/);assert.match(checkout,/enabledInstallments:config\.enabledInstallments/);assert.match(checkout,/itemType:"VIRTUAL"/);});

test("attempt model is server-only concurrent and idempotent",()=>{assert.match(migration,/studio_client_payment_attempts/);assert.match(migration,/provider_token_hash/);assert.match(migration,/revoke all on table public\.studio_client_payment_attempts from public,anon,authenticated/);assert.match(migration,/studio_client_payment_attempts_one_active_idx/);assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/provider_payment_id text unique/);assert.match(repository,/claimAttemptInitialization/);assert.match(checkout,/PAYMENT_INITIALIZATION_IN_PROGRESS/);assert.match(repository,/tokenHash/);});

test("callback retrieves verifies and atomically finalizes without trusting session",()=>{assert.match(callback,/runtime="nodejs"/);assert.match(callback,/attemptForToken\(token\)/);assert.match(callback,/retrieveCheckout/);assert.match(callback,/verifyCheckoutResult/);assert.match(verification,/paymentStatus!=="SUCCESS"/);assert.match(verification,/fraudStatus\)!==1/);assert.match(callback,/finalizeAttempt/);assert.doesNotMatch(callback,/auth\.getUser/);assert.match(migration,/for update/);assert.match(migration,/studio_finance_entries/);assert.match(migration,/studio_finance_payments/);assert.match(migration,/payment_provider='iyzico'/);assert.match(migration,/if a\.status='succeeded'/);});

test("client receives only checkout URL and secrets remain server-only",()=>{assert.match(button,/window\.location\.assign\(body\.checkoutUrl\)/);assert.match(button,/if\(pending\)return/);assert.match(checkout,/\{checkoutUrl:checkout\.toString\(\)\}/);assert.doesNotMatch(checkout,/apiKey|secretKey|raw provider/i);for(const name of["IYZICO_API_KEY","IYZICO_SECRET_KEY","IYZICO_BASE_URL","IYZICO_CALLBACK_URL"])assert.match(env,new RegExp(`^${name}=`,"m"));assert.doesNotMatch(env,/NEXT_PUBLIC_IYZICO/);});

test("checkout 502 diagnostics preserve safe stage and provider metadata",()=>{for(const stage of["checkout_load_request","checkout_load_profile","checkout_claim_attempt","iyzico_initialize_request","iyzico_initialize_provider_failure","iyzico_initialize_signature","checkout_unexpected_error"])assert.match(checkout+client,new RegExp(stage));assert.match(client,/iyzico_\$\{operation\(path\)\}_http/);for(const field of["paymentRequestId","httpStatus","providerStatus","providerErrorCode","providerErrorMessage","normalizedCode","exceptionName","exceptionMessage","conversationId","attemptId"])assert.match(checkout+client,new RegExp(field));assert.match(checkout,/PAYMENT_CHECKOUT_FAILED/);});

test("diagnostics log configuration booleans but never secrets or payment identity payloads",()=>{const config=read("lib/payments/iyzico/config.ts");assert.match(config,/apiKeyConfigured:Boolean/);assert.match(config,/secretKeyConfigured:Boolean/);assert.match(config,/baseUrlConfigured:Boolean/);assert.match(config,/callbackUrlConfigured:Boolean/);assert.match(config,/hostClassification/);const logCalls=[...checkout.matchAll(/checkoutError\([^;]+/g),...client.matchAll(/logFailure\([^;]+/g)].map(match=>match[0]).join("\n");assert.doesNotMatch(logCalls,/apiKey(?!Configured)|secretKey(?!Configured)|Authorization|identityNumber|buyer_full_name|buyer_email|buyer_gsm|registrationAddress|raw request|raw provider/i);assert.doesNotMatch(logCalls,/response\.token|request\.headers|payload/);});
