import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
import test from"node:test";
import{parseIyzicoInstallments}from"../../lib/payments/iyzico/environment.ts";
import{verifyCheckoutResult}from"../../lib/payments/iyzico/verification.ts";

const read=path=>readFileSync(path,"utf8"),migration=read("supabase/migrations/051_iyzico_installments_and_refunds.sql"),checkout=read("app/api/client/payments/[paymentRequestId]/checkout/route.ts"),callback=read("app/api/client/payments/iyzico/callback/route.ts"),webhook=read("app/api/payments/iyzico/webhook/route.ts"),refund=read("lib/payments/iyzico/refund.ts"),client=read("lib/payments/iyzico/client.ts"),config=read("lib/payments/iyzico/config.ts"),studioActions=read("app/studio/(protected)/projects/[projectId]/finance/actions.ts"),studioUi=read("components/studio/finance/StudioPaymentRequests.tsx"),clientUi=read("components/client-portal/ClientPaymentRequests.tsx"),notice=read("components/client-portal/ClientPaymentResultNotice.tsx");
const attempt={conversation_id:"conversation",basket_id:"basket",amount:"100.00",currency:"TRY"};
const result={conversationId:"conversation",basketId:"basket",currency:"TRY",price:"100",paidPrice:"105",installment:6,paymentStatus:"SUCCESS",fraudStatus:1,paymentId:"payment",merchantCommissionRate:"5",merchantCommissionRateAmount:"5",iyziCommissionRateAmount:"1.25",iyziCommissionFee:"0.25",itemTransactions:[{paymentTransactionId:"transaction"}]};

test("installment configuration is allowlisted normalized and defaults safely",()=>{assert.deepEqual(parseIyzicoInstallments(undefined),[1]);assert.deepEqual(parseIyzicoInstallments("1,2,3,6,9,12"),[1,2,3,6,9,12]);assert.deepEqual(parseIyzicoInstallments("6,3,6,garbage,99,-1"),[3,6]);assert.deepEqual(parseIyzicoInstallments("garbage,99"),[1]);assert.match(checkout,/enabledInstallments:config\.enabledInstallments/);assert.doesNotMatch(checkout,/body\.(?:installment|enabledInstallments)/);});

test("live diagnostics expose only parsed installment configuration and the sent array",()=>{assert.match(config,/IYZICO_ENABLED_INSTALLMENTS/);assert.match(config,/configured:Boolean\(raw\?\.trim\(\)\)/);assert.match(config,/rawPresent:raw!==undefined/);assert.match(checkout,/console\.info\("IYZICO_INSTALLMENT_CONFIG",iyzicoInstallmentConfigStatus\(config\)\)/);assert.match(client,/console\.info\("IYZICO_INITIALIZE_INSTALLMENTS",\{enabledInstallments\}\)/);assert.match(client,/payload\.enabledInstallments/);const diagnosticCalls=[...checkout.matchAll(/console\.info\("IYZICO_INSTALLMENT_CONFIG"[^;]*/g),...client.matchAll(/console\.info\("IYZICO_INITIALIZE_INSTALLMENTS"[^;]*/g)].map(match=>match[0]).join("\n");assert.doesNotMatch(diagnosticCalls,/apiKey|secretKey|Authorization|identityNumber|buyer|token/i);});

test("retrieve keeps principal and provider charged amount separate",()=>{const metadata=verifyCheckoutResult(result,attempt);assert.equal(metadata.installment,6);assert.equal(metadata.paidPrice,"105");assert.equal(metadata.merchantCommissionRateAmount,"5");assert.equal(metadata.paymentTransactionId,"transaction");assert.throws(()=>verifyCheckoutResult({...result,price:"101"},attempt),/PAYMENT_VERIFICATION_MISMATCH/);assert.throws(()=>verifyCheckoutResult({...result,paidPrice:"99"},attempt),/PAYMENT_VERIFICATION_MISMATCH/);assert.match(migration,/paid_price numeric\(16,2\)/);assert.match(migration,/p_paid_price<p_amount/);assert.match(migration,/provider_refund_amount[\s\S]*a\.paid_price/);assert.match(migration,/studio_finance_entries[\s\S]*f\.principal_amount,f\.principal_amount/);assert.doesNotMatch(migration,/merchant_commission_rate_amount[\s\S]{0,300}studio_finance_entries/);});

test("callback and webhook share verified metadata and remain idempotent",()=>{for(const source of[callback,webhook]){assert.match(source,/verifyCheckoutResult/);assert.match(source,/finalizeAttempt/);assert.doesNotMatch(source,/sameAmount\(result\.paidPrice,attempt\.amount\)/);}assert.match(webhook,/verifyIyzicoWebhookV3/);assert.match(webhook,/attempt\.status==="succeeded"/);assert.match(migration,/iyzico_finalize_payment_v2/);assert.match(migration,/if f\.status='succeeded' then return true/);});

test("installment and reconciliation metadata are exposed without card data",()=>{assert.match(clientUi,/item\.installment/);assert.match(studioUi,/request\.installment/);assert.match(studioUi,/request\.paidPrice/);assert.match(studioUi,/iyziCommissionRateAmount/);assert.doesNotMatch(clientUi+studioUi,/binNumber|lastFourDigits|cardFamily|cardAssociation/);});

test("refund is owner claimed server authoritative and preserves original income",()=>{assert.match(migration,/studio_has_organization_role\(v_org,array\['owner'\]\)/);assert.match(refund,/studio_claim_iyzico_full_refund/);assert.match(refund,/refund\.provider_payment_id/);assert.match(refund,/refund\.provider_refund_amount/);assert.doesNotMatch(studioActions+studioUi,/providerPaymentId|provider_payment_id|refundAmount/);assert.match(studioUi,/İade Et/);assert.match(client,/REFUND_V2_PATH/);assert.match(migration,/entry_type,source_type,title[\s\S]*'expense','project','iyzico ödeme iadesi'/);assert.match(migration,/update public\.studio_client_payment_requests set status='refunded'/);assert.doesNotMatch(migration,/delete from public\.studio_finance/);});

test("duplicate and failed refunds cannot mutate the original payment twice",()=>{assert.match(migration,/payment_attempt_id uuid not null unique/);assert.match(refund,/\.eq\("status","created"\)/);assert.match(migration,/if f\.status='succeeded' then return true/);assert.match(migration,/where id=p_refund_id and status='processing'/);assert.match(migration,/if r\.id is null or r\.status<>'paid' then return false/);});

test("post-payment notice remains one-shot and drawer neutral",()=>{assert.match(notice,/history\.replaceState/);assert.doesNotMatch(notice,/router\.(?:refresh|replace)|location\.(?:reload|assign)/);});
