import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";const read=path=>readFileSync(path,"utf8"),sidebar=read("components/studio/StudioSidebar.tsx"),page=read("app/studio/(protected)/ai-usage/page.tsx"),ui=read("components/studio/ai/StudioAiUsageDashboard.tsx"),repo=read("lib/studio/ai/ai-usage-repository.ts"),migration=read("supabase/migrations/019_studio_ai_usage_tracking.sql"),admin=read("components/admin/AiUsageAdmin.tsx");
test("sidebar exposes organization AI usage with shared active route state",()=>{assert.match(sidebar,/AI Kullanımı/);assert.match(sidebar,/href: "\/studio\/ai-usage"/);assert.match(sidebar,/pathname\.startsWith/);assert.match(sidebar,/icon: "chart"/)});
test("Studio route is protected organization scoped and never accepts organization id",()=>{assert.match(page,/getStudioAiUsageDashboard/);assert.match(repo,/getStudioContext/);assert.match(repo,/membership\.organization_id/);assert.match(repo,/\.eq\("organization_id",context\.membership\.organization_id\)/);assert.doesNotMatch(page+ui,/organization_id|service_role|SUPABASE_SERVICE_ROLE_KEY/)});
test("owner sees organization while member query and RLS are own-only",()=>{assert.match(repo,/membership\.role==="owner"/);assert.match(repo,/if\(!owner\)query=query\.eq\("user_id",context\.user\.id\)/);assert.match(migration,/user_id=auth\.uid\(\) or public\.studio_has_organization_role\(organization_id,array\['owner'\]\)/);assert.match(migration,/grant select,insert.*authenticated/)});
test("dashboard has summaries breakdowns quota and safe unknown cost",()=>{for(const label of["Bu Ay AI İsteği","Toplam Token","Tahmini Maliyet","Başarılı İstek","Fallback Kullanımı","Hatalı İstek","Kullanım Bilgisi Alınamayan","Fiyatı Bilinmeyen","Modül Kırılımı","Kullanıcı Kırılımı","Kota tanımlanmamış","Henüz hesaplanamıyor"])assert.match(ui,new RegExp(label));assert.match(ui,/sm:grid-cols-2/);assert.match(ui,/xl:grid-cols-4/)});
test("filters are bounded and member has no user filter",()=>{for(const value of["from","to","module","operation","model","status","fallback","usageUnavailable","pricingUnknown"])assert.match(repo+ui,new RegExp(value));assert.match(ui,/data\.canViewOrganization\?<Select name="user"/);assert.match(repo,/\.limit\(1000\)/);assert.match(repo,/events\.slice\(0,200\)/)});
test("empty and migration missing states are safe",()=>{assert.match(repo,/42P01/);assert.match(repo,/PGRST205/);assert.match(ui,/AI kullanım takibi henüz hazırlanmadı/);assert.match(ui,/Henüz AI kullanımı bulunmuyor/);assert.doesNotMatch(ui,/PGRST|SQLSTATE|relation does not exist/)});
test("usage list excludes prompts outputs contacts and provider bodies",()=>{for(const heading of["Tarih","Modül","İşlem","Model","Input","Output","Toplam","Maliyet","Durum","Kullanıcı"])assert.match(ui,new RegExp(heading));assert.doesNotMatch(repo+ui,/prompt|response_text|customer_phone|email|request_body|providerRequestId/i)});
test("platform admin remains separate and unchanged in authority",()=>{assert.match(admin,/Studio AI kullanımı/);assert.doesNotMatch(page,/\/api\/admin\/ai-usage|isAdmin/)});
