import "server-only";
import {decryptToken,encryptToken} from "./token-encryption";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {StudioFileError} from "../file-errors";
const scope="https://www.googleapis.com/auth/drive.file";
function config(){const c=["GOOGLE_DRIVE_CLIENT_ID","GOOGLE_DRIVE_CLIENT_SECRET","GOOGLE_DRIVE_REDIRECT_URI"] as const;for(const k of c)if(!process.env[k])throw new StudioFileError("storage",`${k} yapılandırılmamış.`);return{clientId:process.env.GOOGLE_DRIVE_CLIENT_ID!,clientSecret:process.env.GOOGLE_DRIVE_CLIENT_SECRET!,redirectUri:process.env.GOOGLE_DRIVE_REDIRECT_URI!};}
export function googleDriveAuthorizationUrl(state:string){const c=config();const q=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:"code",access_type:"offline",prompt:"consent",scope,state});return `https://accounts.google.com/o/oauth2/v2/auth?${q}`;}
export async function exchangeGoogleCode(code:string){const c=config();const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,grant_type:"authorization_code"})});if(!response.ok)throw new StudioFileError("storage","Google Drive yetkilendirmesi tamamlanamadı.");return response.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>;}
export async function getGoogleAccessToken(organizationId:string){const supabase=await createStudioServerClient();const {data}=await supabase.from("studio_storage_connections").select("id,encrypted_access_token,encrypted_refresh_token,access_token_expires_at,status").eq("organization_id",organizationId).eq("provider","google_drive").maybeSingle();if(!data?.encrypted_refresh_token)throw new StudioFileError("storage","Google Drive bağlantısı gerekli.");if(data.access_token_expires_at&&new Date(data.access_token_expires_at).getTime()>Date.now()+60000)return decryptToken(data.encrypted_access_token);const c=config();const token=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:decryptToken(data.encrypted_refresh_token),grant_type:"refresh_token"})});if(!token.ok){await supabase.from("studio_storage_connections").update({status:"reauthorization_required",last_error_code:"token_refresh_failed"}).eq("id",data.id);throw new StudioFileError("storage","Google Drive bağlantısı yeniden yetkilendirilmeli.");}const body=await token.json() as {access_token:string;expires_in:number};await supabase.from("studio_storage_connections").update({encrypted_access_token:encryptToken(body.access_token),access_token_expires_at:new Date(Date.now()+body.expires_in*1000).toISOString(),status:"connected",last_verified_at:new Date().toISOString()}).eq("id",data.id);return body.access_token;}
