import "server-only";
import {getGoogleAccessToken} from "./google-drive-auth";
import {StudioFileError} from "../file-errors";
async function drive(org:string,path:string,init:RequestInit={}){const token=await getGoogleAccessToken(org);const response=await fetch(`https://www.googleapis.com/drive/v3/${path}`,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});if(!response.ok)throw new StudioFileError("storage","Google Drive işlemi başarısız oldu.");return response;}
export async function createDriveFolder(organizationId:string,name:string,parentId:string|undefined,properties:Record<string,string>={}){const response=await drive(organizationId,"files",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,mimeType:"application/vnd.google-apps.folder",parents:parentId?[parentId]:undefined,appProperties:properties})});return response.json() as Promise<{id:string,name:string,parents?:string[],appProperties?:Record<string,string>}>;}
export async function findDriveFolder(organizationId:string,parentId:string,properties:Record<string,string>){const q=[`'${parentId}' in parents`,`mimeType='application/vnd.google-apps.folder'`,`trashed=false`,...Object.entries(properties).map(([k,v])=>`appProperties has { key='${k}' and value='${v.replace(/'/g,"\\'")}' }`)].join(" and ");const response=await drive(organizationId,`files?spaces=drive&fields=files(id,name,parents,appProperties)&q=${encodeURIComponent(q)}`);const body=await response.json() as {files?:Array<{id:string;name:string;parents?:string[];appProperties?:Record<string,string>}>};if((body.files??[]).length>1)throw new StudioFileError("storage","Google Drive klasör eşlemesi belirsiz.");return body.files?.[0]??null;}
export async function createDriveResumableSession(organizationId:string,metadata:{name:string;mimeType:string;size:number;parentId:string;appProperties?:Record<string,string>}){const token=await getGoogleAccessToken(organizationId);const response=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","X-Upload-Content-Type":metadata.mimeType,"X-Upload-Content-Length":String(metadata.size)},body:JSON.stringify({name:metadata.name,parents:[metadata.parentId],appProperties:metadata.appProperties})});if(!response.ok)throw new StudioFileError("storage","Google Drive yükleme oturumu oluşturulamadı.");const location=response.headers.get("location");if(!location)throw new StudioFileError("storage","Google Drive yükleme adresi alınamadı.");return location;}
export async function downloadDriveFile(organizationId:string,fileId:string){return drive(organizationId,`files/${encodeURIComponent(fileId)}?alt=media`);}
export async function getDriveFileMetadata(organizationId:string,fileId:string){const response=await drive(organizationId,`files/${encodeURIComponent(fileId)}?fields=id,name,mimeType,size,parents,md5Checksum,version,webViewLink,trashed`);return response.json() as Promise<{id:string;name:string;mimeType?:string;size?:string;parents?:string[];md5Checksum?:string;version?:string;webViewLink?:string;trashed?:boolean}>;}
export async function updateDriveFile(organizationId:string,fileId:string,body:Record<string,unknown>){return (await drive(organizationId,`files/${encodeURIComponent(fileId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)})).json();}
export {getGoogleAccessToken};
