"use server";
import {revalidatePath} from "next/cache";
import {createProjectExpense,createVisualizationRevision,createVisualizationTimeEntry,saveProjectFinanceProfile} from "@/lib/studio/finance/project-finance-repository";
import {cancelStudioPaymentRequest,createStudioPaymentRequest}from"@/lib/studio/finance/payment-request-repository";
import{refundStudioPaymentRequest}from"@/lib/payments/iyzico/refund";
const value=(form:FormData,key:string)=>String(form.get(key)??"");
const refresh=(projectId:string)=>{revalidatePath(`/studio/projects/${projectId}/finance`);revalidatePath("/studio/finance");revalidatePath("/studio");revalidatePath("/studio/finance/profitability");};
export async function saveProjectFinanceProfileAction(projectId:string,form:FormData){try{await saveProjectFinanceProfile(projectId,{agreedAmount:value(form,"agreedAmount"),currency:value(form,"currency")||"TRY",contractDate:value(form,"contractDate"),description:value(form,"description"),contractFileId:value(form,"contractFileId"),includedRevisionCount:value(form,"includedRevisionCount")||"0",extraRevisionUnitPrice:value(form,"extraRevisionUnitPrice")||"0"});refresh(projectId);return{success:true,message:"Proje finans profili kaydedildi."};}catch{return{success:false,message:"Proje finans profili kaydedilemedi."};}}
export async function createProjectExpenseAction(projectId:string,form:FormData){try{await createProjectExpense(projectId,{category:value(form,"category"),amount:value(form,"amount"),paidAmount:value(form,"paidAmount")||"0",status:value(form,"status")||"waiting",entryDate:value(form,"entryDate"),description:value(form,"description"),documentFileId:value(form,"documentFileId"),receiptFileId:value(form,"receiptFileId"),invoiceFileId:value(form,"invoiceFileId")});refresh(projectId);return{success:true,message:"Proje gideri kaydedildi."};}catch{return{success:false,message:"Proje gideri kaydedilemedi."};}}
export async function createStudioPaymentRequestAction(projectId:string,form:FormData){try{await createStudioPaymentRequest(projectId,{title:value(form,"title"),paymentType:value(form,"paymentType"),amount:value(form,"amount"),currency:value(form,"currency")||"TRY",description:value(form,"description"),dueDate:value(form,"dueDate")});refresh(projectId);return{success:true,message:"Ödeme talebi oluşturuldu."};}catch{return{success:false,message:"Ödeme talebi oluşturulamadı."};}}
export async function cancelStudioPaymentRequestAction(projectId:string,paymentRequestId:string){try{await cancelStudioPaymentRequest(projectId,paymentRequestId);refresh(projectId);return{success:true,message:"Ödeme talebi iptal edildi."};}catch{return{success:false,message:"Ödeme talebi iptal edilemedi."};}}
export async function refundStudioPaymentRequestAction(projectId:string,paymentRequestId:string){try{const result=await refundStudioPaymentRequest(projectId,paymentRequestId);refresh(projectId);return{success:true,message:result==="already_refunded"?"Ödeme daha önce iade edildi.":"Ödeme başarıyla iade edildi."};}catch(error){const code=error instanceof Error?error.message:"";return{success:false,message:code==="REFUND_FORBIDDEN"?"Bu işlem için yetkiniz yok.":code==="REFUND_ALREADY_PROCESSING"?"İade işlemi zaten işleniyor.":"İade işlemi tamamlanamadı."};}}
export async function createVisualizationTimeEntryAction(projectId:string,form:FormData){try{await createVisualizationTimeEntry(projectId,{workType:value(form,"workType"),durationMinutes:value(form,"durationMinutes"),workDate:value(form,"workDate"),description:value(form,"description"),renderId:value(form,"renderId")});refresh(projectId);return{success:true,message:"Çalışma süresi kaydedildi."};}catch{return{success:false,message:"Çalışma süresi kaydedilemedi."};}}
export async function createVisualizationRevisionAction(projectId:string,form:FormData){try{await createVisualizationRevision(projectId,{revisionNumber:value(form,"revisionNumber"),requestedAt:value(form,"requestedAt"),description:value(form,"description"),isIncluded:value(form,"isIncluded")==="true",amount:value(form,"amount")||"0",status:value(form,"status")||"requested",renderId:value(form,"renderId"),fileVersionId:value(form,"fileVersionId")});refresh(projectId);return{success:true,message:"Revize kaydedildi."};}catch{return{success:false,message:"Revize kaydedilemedi."};}}
