import 'server-only';
import {OpenAIRequestError} from '@/lib/ai-project';

const seo={type:'object',additionalProperties:false,required:['metaTitle','metaDescription','keywords','openGraphDescription'],properties:{metaTitle:{type:'string'},metaDescription:{type:'string'},keywords:{type:'array',items:{type:'string'}},openGraphDescription:{type:'string'}}};
const post={type:'object',additionalProperties:false,required:['title','excerpt','content','slug','seo'],properties:{title:{type:'string'},excerpt:{type:'string'},content:{type:'string'},slug:{type:'string'},seo}};
async function structured<T>(name:string,schema:object,instructions:string,input:unknown,max=5000,imageUrl?:string):Promise<T>{
 const key=process.env.OPENAI_API_KEY;if(!key)throw new OpenAIRequestError('OPENAI_API_KEY tanımlı değil.',503,'missing key');
 for(let attempt=1;attempt<=2;attempt++){let response:Response;try{response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_PROJECT_MODEL||'gpt-5-mini',instructions,input:imageUrl?[{role:'user',content:[{type:'input_text',text:JSON.stringify(input)},{type:'input_image',image_url:imageUrl,detail:'high'}]}]:JSON.stringify(input),max_output_tokens:max,text:{format:{type:'json_schema',name,strict:true,schema}}}),signal:AbortSignal.timeout(180000)});}catch(e){if(e instanceof Error&&(e.name==='TimeoutError'||e.name==='AbortError'))throw new OpenAIRequestError('AI isteği zaman aşımına uğradı. Lütfen tekrar deneyin.',504,e.message);throw e;}if(!response.ok){const detail=(await response.text()).slice(0,2000);throw new OpenAIRequestError(`OpenAI isteği başarısız (${response.status}).`,response.status,detail);}const data=await response.json() as {output_text?:string;output?:Array<{content?:Array<{type?:string;text?:string}>}>};const text=data.output_text??data.output?.flatMap(x=>x.content??[]).find(x=>x.type==='output_text')?.text;try{if(!text)throw new Error('boş çıktı');return JSON.parse(text) as T;}catch(e){console.error('CMS AI JSON validation failed',{attempt,name,error:e instanceof Error?e.message:String(e)});if(attempt===2)throw new OpenAIRequestError('AI yanıtı bozuk geldi ve tekrar deneme başarısız oldu.',502,String(e));}}
 throw new OpenAIRequestError('AI yanıtı işlenemedi.',502,'retry state');
}
export function generateBlog(draft:{title:string;notes:string}){return structured<{title:string;excerpt:string;content:string;slug:string;seo:Record<string,unknown>}>('blog_tr',post,'ARZ Mimarlık için Türkçe mimarlık blog yazısı taslağı üret. Yalnızca verilen gerçekleri kullan. İçerik HTML paragraf ve başlık etiketleri içerebilir. Slug Latin küçük harf olsun.',draft,6000);}
export function translateBlog(source:unknown,locales:string[]){const props=Object.fromEntries(locales.map(l=>[l,post]));return structured<Record<string,unknown>>(`blog_${locales.join('_')}`,{type:'object',additionalProperties:false,required:locales,properties:props},`Türkçe blog yazısını şu dillere doğal biçimde çevir: ${locales.join(',')}. Her slug Latin karakterli ve doğal olsun.`,source,7000);}
export function generateAltText(imageUrl:string){return structured<{alt:string}>('media_alt_tr',{type:'object',additionalProperties:false,required:['alt'],properties:{alt:{type:'string'}}},'Görsel için kısa, doğal, erişilebilir Türkçe alt metin yaz. Mimari tür, cephe, malzeme, mekân ve ışığı yalnızca açıkça görünüyorsa belirt. Anahtar kelime doldurma yapma.',{},1000,imageUrl);}
export function translateStrings(source:Record<string,string>,locales:string[]){const language={type:'object',additionalProperties:false,required:Object.keys(source),properties:Object.fromEntries(Object.keys(source).map(k=>[k,{type:'string'}]))};return structured<Record<string,Record<string,string>>>('site_strings',{type:'object',additionalProperties:false,required:locales,properties:Object.fromEntries(locales.map(l=>[l,language]))},`Türkçe site metinlerini şu dillere doğal ve kısa biçimde çevir: ${locales.join(',')}.`,source,5000);}
