import "server-only";
import {getStudioContext} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import type {StudioFavoriteEntityType,StudioQuickAccessData,StudioQuickAccessItem,StudioRecentEntityType} from "./quick-access-types";

type Scope={organizationId:string;userId:string;supabase:Awaited<ReturnType<typeof createStudioServerClient>>};
async function scope():Promise<Scope>{const context=await getStudioContext();if(!context?.membership)throw new Error("Oturum gerekli.");return{organizationId:context.membership.organization_id,userId:context.user.id,supabase:await createStudioServerClient()};}
function unavailable(error:{code?:string}|null){return error?.code==="42P01"||error?.code==="PGRST205";}
export function favoriteKey(type:string,id:string){return`${type}:${id}`;}

export async function listUserFavoriteKeys(){const s=await scope();const{data,error}=await s.supabase.from("studio_user_favorites").select("entity_type,entity_id").eq("organization_id",s.organizationId).eq("user_id",s.userId).is("archived_at",null);if(error){if(unavailable(error))return new Set<string>();throw new Error("Favoriler yüklenemedi.");}return new Set((data??[]).map(row=>favoriteKey(row.entity_type,row.entity_id)));}
export async function addFavorite(entityType:StudioFavoriteEntityType,entityId:string){const s=await scope();const{data}=await s.supabase.from("studio_user_favorites").select("id").eq("organization_id",s.organizationId).eq("user_id",s.userId).eq("entity_type",entityType).eq("entity_id",entityId).maybeSingle();const query=data?.id?s.supabase.from("studio_user_favorites").update({archived_at:null}).eq("id",data.id):s.supabase.from("studio_user_favorites").insert({organization_id:s.organizationId,user_id:s.userId,entity_type:entityType,entity_id:entityId});const{error}=await query;if(error)throw new Error("Kayıt favorilere eklenemedi.");}
export async function removeFavorite(entityType:StudioFavoriteEntityType,entityId:string){const s=await scope();const{error}=await s.supabase.from("studio_user_favorites").update({archived_at:new Date().toISOString()}).eq("organization_id",s.organizationId).eq("user_id",s.userId).eq("entity_type",entityType).eq("entity_id",entityId).is("archived_at",null);if(error)throw new Error("Kayıt favorilerden çıkarılamadı.");}
export async function recordRecentItem(entityType:StudioRecentEntityType,entityId:string){const s=await scope();const{error}=await s.supabase.from("studio_user_recent_items").upsert({organization_id:s.organizationId,user_id:s.userId,entity_type:entityType,entity_id:entityId,last_opened_at:new Date().toISOString()},{onConflict:"organization_id,user_id,entity_type,entity_id"});if(error&&!unavailable(error))throw new Error("Son açılan kayıt güncellenemedi.");}

type Ref={entity_type:StudioFavoriteEntityType;entity_id:string;created_at?:string;last_opened_at?:string};
async function hydrate(s:Scope,refs:Ref[],favoriteKeys:Set<string>):Promise<StudioQuickAccessItem[]>{
 const byType=new Map<StudioFavoriteEntityType,string[]>();for(const ref of refs){const ids=byType.get(ref.entity_type)??[];ids.push(ref.entity_id);byType.set(ref.entity_type,ids);}
 const values=new Map<string,{title:string;subtitle:string;url:string}>();
 await Promise.all([...byType].map(async([type,ids])=>{let query;
  if(type==="project")query=s.supabase.from("studio_projects").select("id,name,code").in("id",ids).eq("organization_id",s.organizationId);
  else if(type==="crm_lead")query=s.supabase.from("studio_leads").select("id,first_name,last_name,company_name").in("id",ids).eq("organization_id",s.organizationId);
  else if(type==="quote")query=s.supabase.from("studio_quotes").select("id,title,quote_number").in("id",ids).eq("organization_id",s.organizationId);
  else if(type==="folder")query=s.supabase.from("studio_project_folders").select("id,name,project_id").in("id",ids).eq("organization_id",s.organizationId);
  else if(type==="file")query=s.supabase.from("studio_project_files").select("id,display_name,project_id,extension").in("id",ids).eq("organization_id",s.organizationId);
  else query=s.supabase.from("studio_project_file_versions").select("id,file_id,project_id,version_number,original_file_name").in("id",ids).eq("organization_id",s.organizationId);
  const{data}=await query;for(const raw of data??[]){const row=raw as Record<string,unknown>,id=String(row.id);if(type==="project")values.set(favoriteKey(type,id),{title:String(row.name),subtitle:String(row.code),url:`/studio/projects/${id}`});else if(type==="crm_lead")values.set(favoriteKey(type,id),{title:`${String(row.first_name??"")} ${String(row.last_name??"")}`.trim(),subtitle:String(row.company_name||"CRM kaydı"),url:`/studio/crm/${id}`});else if(type==="quote")values.set(favoriteKey(type,id),{title:String(row.title),subtitle:String(row.quote_number),url:`/studio/quotes/${id}`});else if(type==="folder")values.set(favoriteKey(type,id),{title:String(row.name),subtitle:"Proje klasörü",url:`/studio/projects/${String(row.project_id)}/files?folder=${id}`});else if(type==="file")values.set(favoriteKey(type,id),{title:String(row.display_name),subtitle:String(row.extension).toUpperCase(),url:`/studio/projects/${String(row.project_id)}/files/${id}`});else values.set(favoriteKey(type,id),{title:String(row.original_file_name),subtitle:`V${String(row.version_number)}`,url:`/studio/projects/${String(row.project_id)}/files/${String(row.file_id)}/versions/${id}`});}}
 ));
 return refs.flatMap(ref=>{const key=favoriteKey(ref.entity_type,ref.entity_id),value=values.get(key);return value?[{key,entityType:ref.entity_type,entityId:ref.entity_id,...value,isFavorite:favoriteKeys.has(key),lastOpenedAt:ref.last_opened_at}]:[];});
}
export async function getQuickAccessData(limit=20):Promise<StudioQuickAccessData>{const s=await scope();const[favoritesResult,recentResult]=await Promise.all([s.supabase.from("studio_user_favorites").select("entity_type,entity_id,created_at").eq("organization_id",s.organizationId).eq("user_id",s.userId).is("archived_at",null).order("created_at",{ascending:false}).limit(100),s.supabase.from("studio_user_recent_items").select("entity_type,entity_id,last_opened_at").eq("organization_id",s.organizationId).eq("user_id",s.userId).order("last_opened_at",{ascending:false}).limit(Math.min(limit,20))]);if(favoritesResult.error||recentResult.error){if(unavailable(favoritesResult.error)||unavailable(recentResult.error))return{available:false,favorites:[],recent:[]};throw new Error("Hızlı erişim kayıtları yüklenemedi.");}const refs=favoritesResult.data as Ref[];const keys=new Set(refs.map(ref=>favoriteKey(ref.entity_type,ref.entity_id)));const[favorites,recent]=await Promise.all([hydrate(s,refs,keys),hydrate(s,recentResult.data as Ref[],keys)]);return{available:true,favorites,recent};}
