import Link from "next/link";
import {notFound} from "next/navigation";
import {studioButtonClass} from "@/components/studio/StudioButton";
import StudioSyncStatus from "@/components/studio/files/StudioSyncStatus";
import StudioVersionPromoteButton from "@/components/studio/files/StudioVersionPromoteButton";
import {getStudioProjectFileById} from "@/lib/studio/files/file-repository";
import {getStudioFileVersionById} from "@/lib/studio/files/versions/version-repository";
import {STUDIO_REVISION_REASON_LABELS} from "@/lib/studio/files/versions/version-types";
export const dynamic="force-dynamic";
export default async function VersionDetailPage({params}:{params:Promise<{projectId:string;fileId:string;versionId:string}>}){const{projectId,fileId,versionId}=await params;const[fileResult,version]=await Promise.all([getStudioProjectFileById(projectId,fileId),getStudioFileVersionById(projectId,fileId,versionId).catch(()=>null)]);if(!fileResult||!version)notFound();const item=(label:string,value:React.ReactNode)=><div><dt className="text-sm font-semibold text-[#707674]">{label}</dt><dd className="mt-1 break-words text-[15px] leading-6">{value||"—"}</dd></div>;return <section className="mx-auto max-w-4xl px-4 py-7 sm:px-6 lg:px-8"><Link href={`/studio/projects/${projectId}/files/${fileId}`} className="text-sm font-semibold text-[#8e784d]">← Dosyaya Dön</Link><header className="mt-4 rounded-xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-[#69716f]">{fileResult.file.displayName}</p><h1 className="mt-2 text-3xl font-semibold">V{version.versionNumber}{version.revisionCode?` · ${version.revisionCode}`:""}</h1><p className="mt-2 text-[15px]">{version.revisionTitle||STUDIO_REVISION_REASON_LABELS[version.revisionReason]}</p></div><div className="flex flex-wrap gap-2">{version.isCurrent?<span className="rounded-full border border-[#b9d2c3] bg-[#edf6f0] px-3 py-2 text-sm font-semibold text-[#315c45]">✓ Güncel sürüm</span>:null}<StudioSyncStatus status={version.syncStatus}/></div></div><div className="mt-5 flex flex-wrap gap-2"><a href={`/studio/projects/${projectId}/files/${fileId}/versions/${versionId}/download`} className={studioButtonClass("primary")}>V{version.versionNumber} Sürümünü İndir</a>{fileResult.file.canManage&&!version.isCurrent?<StudioVersionPromoteButton projectId={projectId} fileId={fileId} versionId={versionId} versionNumber={version.versionNumber}/>:null}</div></header><section className="mt-5 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Revizyon Bilgileri</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{item("Revizyon nedeni",STUDIO_REVISION_REASON_LABELS[version.revisionReason])}{item("Revizyon kodu",version.revisionCode)}{item("Fiziksel dosya",version.originalFileName)}{item("Boyut",version.fileSizeLabel)}{item("MIME",version.mimeType)}{item("Yükleyen",version.uploadedBy.name)}{item("Oluşturulma",version.createdAtLabel)}{item("Drive modified",version.externalModifiedAt?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(version.externalModifiedAt)):"")}{item("Checksum",version.checksum)}{item("Provider version",version.providerVersion)}</dl><div className="mt-6 border-t pt-5"><h3 className="text-lg font-semibold">Revizyon Notu</h3><p className="mt-2 whitespace-pre-wrap break-words text-[15px] leading-7 text-[#596260]">{version.revisionNote||"Revizyon notu eklenmemiş."}</p></div></section></section>;}
