import Image from "next/image";
import Link from "next/link";
import ClientInvitationForm from "@/components/client-portal/ClientInvitationForm";
import {StudioBadge,StudioCard,StudioEmptyState,StudioIconSurface} from "@/components/studio/ui";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {getInvitationPreview} from "@/lib/client-portal/auth";
export const dynamic="force-dynamic";
const copy={expired:["Davet süresi doldu","Yeni bir davet bağlantısı için ARZ Mimarlık ile iletişime geçin."],accepted:["Davet daha önce kabul edildi","Hesabınızla müşteri portalına giriş yapabilirsiniz."],revoked:["Davet iptal edildi","Bu bağlantı artık kullanılamıyor."],invalid:["Davet bulunamadı","Bağlantı geçersiz veya artık kullanılamıyor."],unavailable:["Davet şu anda doğrulanamıyor","Lütfen kısa bir süre sonra tekrar deneyin."]} as const;
export default async function ClientInvitePage({params}:{params:Promise<{token:string}>}){
 const{token}=await params;const preview=await getInvitationPreview(token).catch(()=>({state:"unavailable" as const}));
 return <main className="flex min-h-screen items-center justify-center bg-[#F7F9FC] p-5 text-[#17232e]"><StudioCard className="w-full max-w-[520px] border border-[#e4eaf0] bg-white p-7 shadow-[0_24px_70px_rgba(31,48,65,.09)] sm:p-10"><div className="flex items-center justify-between"><Image src="/arz-logo-final.png" alt="ARZ Mimarlık" width={116} height={38} priority/><StudioIconSurface icon="messages" tone="blue" size="lg"/></div>{preview.state==="valid"?<><div className="mt-9 flex items-center gap-2"><StudioBadge variant="success">Geçerli davet</StudioBadge><span className="text-xs text-[#82909a]">ARZ Mimarlık</span></div><h1 className="mt-3 text-3xl font-semibold tracking-[-.035em]">Müşteri Portalı daveti</h1><p className="mt-3 text-sm leading-6 text-[#64748b]"><strong className="text-[#334155]">{preview.projectName}</strong> projesine güvenli erişiminizi etkinleştirin.</p><dl className="mt-6 grid gap-3 rounded-2xl bg-[#F7F9FC] p-4 text-sm"><div className="flex justify-between gap-4"><dt className="text-[#82909a]">Davet edilen</dt><dd className="text-right font-semibold text-[#334155]">{preview.email}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#82909a]">Geçerlilik</dt><dd className="text-right font-semibold text-[#334155]">{new Intl.DateTimeFormat("tr-TR",{dateStyle:"long",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(preview.expiresAt!))}</dd></div></dl><ClientInvitationForm token={token} email={preview.email!}/></>:<div className="mt-8"><StudioEmptyState icon="warning" title={copy[preview.state][0]} description={copy[preview.state][1]} action={preview.state==="accepted"?<Link href="/client/login" className={studioButtonClass("primary")}>Müşteri Girişi</Link>:undefined}/></div>}</StudioCard></main>;
}
