"use client";
import {QUOTE_UNITS,QUOTE_UNIT_LABELS} from "@/lib/studio/quotes/quote-constants";
import {calculateQuoteTotals} from "@/lib/studio/quotes/quote-calculations";
import type {QuoteDiscountType,QuoteUnit} from "@/lib/studio/quotes/quote-types";
export type EditableQuoteItem={serviceName:string;description:string;quantity:string;unit:QuoteUnit;unitPrice:string};
const blankItem:EditableQuoteItem={serviceName:"",description:"",quantity:"1",unit:"Piece",unitPrice:"0"};
export default function StudioQuoteItemsEditor({items,onChange,currency,discountType,discountValue,taxRate,error}:{items:EditableQuoteItem[];onChange:(items:EditableQuoteItem[])=>void;currency:string;discountType:QuoteDiscountType;discountValue:string;taxRate:string;error?:string}){
 function update(index:number,key:keyof EditableQuoteItem,value:string){onChange(items.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));}
 let totals;try{totals=calculateQuoteTotals({items,discountType,discountValue,taxRate});}catch{totals={subtotal:"0.00",discountTotal:"0.00",taxTotal:"0.00",grandTotal:"0.00",lineTotals:items.map(()=>"0.00")};}
 return <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-4 border-b border-[#ece9e3] pb-4"><div><h2 className="text-[13px] font-semibold text-[#2d353b]">Hizmet Kalemleri</h2><p className="mt-1 text-[9px] text-[#989994]">Toplamlar server tarafından yeniden hesaplanır.</p></div><button type="button" onClick={()=>onChange([...items,{...blankItem}])} className="h-9 rounded-lg border border-[#d5d0c6] px-3 text-[9px] text-[#5d6465] outline-none focus-visible:ring-2 focus-visible:ring-[#9e8452]/30">Kalem Ekle</button></div>
  {error?<p role="alert" className="mt-3 text-[9px] text-[#9b5d48]">{error}</p>:null}<div className="mt-4 space-y-4">{items.map((item,index)=><article key={index} className="grid min-w-0 gap-3 rounded-lg border border-[#e6e2da] bg-[#fbfaf7] p-4 md:grid-cols-12">
   <label className="min-w-0 md:col-span-4"><span className="text-[8px] uppercase tracking-[.1em] text-[#777a75]">Hizmet Adı</span><input aria-label={`${index+1}. kalem hizmet adı`} value={item.serviceName} onChange={event=>update(index,"serviceName",event.target.value)} className="mt-1.5 h-10 w-full min-w-0 rounded-md border border-[#ddd8ce] bg-white px-3 text-[10px] outline-none focus:border-[#a58a56]"/></label>
   <label className="min-w-0 md:col-span-8"><span className="text-[8px] uppercase tracking-[.1em] text-[#777a75]">Açıklama</span><input aria-label={`${index+1}. kalem açıklaması`} value={item.description} onChange={event=>update(index,"description",event.target.value)} className="mt-1.5 h-10 w-full min-w-0 rounded-md border border-[#ddd8ce] bg-white px-3 text-[10px] outline-none focus:border-[#a58a56]"/></label>
   <label className="min-w-0 md:col-span-2"><span className="text-[8px] uppercase tracking-[.1em] text-[#777a75]">Miktar</span><input aria-label={`${index+1}. kalem miktarı`} inputMode="decimal" value={item.quantity} onChange={event=>update(index,"quantity",event.target.value)} className="mt-1.5 h-10 w-full min-w-0 rounded-md border border-[#ddd8ce] bg-white px-3 text-[10px]"/></label>
   <label className="min-w-0 md:col-span-2"><span className="text-[8px] uppercase tracking-[.1em] text-[#777a75]">Birim</span><select aria-label={`${index+1}. kalem birimi`} value={item.unit} onChange={event=>update(index,"unit",event.target.value)} className="mt-1.5 h-10 w-full min-w-0 rounded-md border border-[#ddd8ce] bg-white px-2 text-[10px]">{QUOTE_UNITS.map(unit=><option key={unit} value={unit}>{QUOTE_UNIT_LABELS[unit]}</option>)}</select></label>
   <label className="min-w-0 md:col-span-3"><span className="text-[8px] uppercase tracking-[.1em] text-[#777a75]">Birim Fiyat</span><input aria-label={`${index+1}. kalem birim fiyatı`} inputMode="decimal" value={item.unitPrice} onChange={event=>update(index,"unitPrice",event.target.value)} className="mt-1.5 h-10 w-full min-w-0 rounded-md border border-[#ddd8ce] bg-white px-3 text-[10px]"/></label>
   <div className="min-w-0 md:col-span-3"><span className="text-[8px] uppercase tracking-[.1em] text-[#777a75]">Satır Toplamı</span><p className="mt-1.5 break-words text-[11px] font-semibold text-[#30393f]">{totals.lineTotals[index]} {currency}</p></div>
   <div className="flex items-end md:col-span-2"><button type="button" aria-label={`${index+1}. hizmet kalemini kaldır`} disabled={items.length===1} onClick={()=>onChange(items.filter((_,itemIndex)=>itemIndex!==index))} className="h-9 rounded-md border border-[#decfc7] px-3 text-[9px] text-[#8a5f50] disabled:cursor-not-allowed disabled:opacity-40">Kaldır</button></div>
  </article>)}</div>
  <dl className="ml-auto mt-5 grid max-w-sm grid-cols-2 gap-x-5 gap-y-2 border-t border-[#e6e2da] pt-4 text-[10px]"><dt>Ara Toplam</dt><dd className="text-right">{totals.subtotal} {currency}</dd><dt>İndirim</dt><dd className="text-right">-{totals.discountTotal} {currency}</dd><dt>Vergi</dt><dd className="text-right">{totals.taxTotal} {currency}</dd><dt className="font-semibold">Genel Toplam</dt><dd className="text-right font-semibold">{totals.grandTotal} {currency}</dd></dl>
 </section>;
}
