import Link from "next/link";
import StudioQuoteActions from "./StudioQuoteActions";
import StudioQuoteArchiveControl from "./StudioQuoteArchiveControl";
import StudioQuoteBadge from "./StudioQuoteBadge";
import StudioQuoteConversionForm from "./StudioQuoteConversionForm";
import {QUOTE_UNIT_LABELS} from "@/lib/studio/quotes/quote-constants";
import type {StudioProjectMember} from "@/lib/studio/projects/project-types";
import type {StudioQuote} from "@/lib/studio/quotes/quote-types";
function money(value:string,currency:string){return new Intl.NumberFormat("tr-TR",{style:"currency",currency}).format(Number(value));}
export default function StudioQuoteDetail({quote,members}:{quote:StudioQuote;members:StudioProjectMember[]}){return <section className="mx-auto min-w-0 max-w-[1280px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8 lg:py-9">
 <header className="rounded-xl border border-[#d9d4ca] bg-white p-5 shadow-[0_5px_24px_rgba(30,38,45,.04)] sm:p-7"><Link href="/studio/quotes" className="text-[9px] font-medium uppercase tracking-[.14em] text-[#8e784d]">← Tekliflere Dön</Link><div className="mt-5 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="min-w-0"><div className="flex flex-wrap gap-2"><StudioQuoteBadge status={quote.status}/>{quote.isPastValidity?<span className="rounded-full border border-[#dec9bd] bg-[#f8efea] px-2.5 py-1 text-[9px] text-[#8b5f4d]">Geçerlilik tarihi geçti</span>:null}{quote.isArchived?<span className="rounded-full border px-2.5 py-1 text-[9px]">Arşiv</span>:null}</div><p className="mt-4 text-[9px] font-semibold uppercase tracking-[.13em] text-[#9a8253]">{quote.quoteNumber}</p><h1 className="mt-2 break-words text-[28px] font-semibold tracking-[-.04em] text-[#1f2930]">{quote.title}</h1><p className="mt-2 text-[11px] text-[#777b78]">{quote.client.name}{quote.client.company?` · ${quote.client.company}`:""}</p></div><div className="flex flex-wrap gap-2"><a href={`/studio/quotes/${quote.id}/pdf`} target="_blank" rel="noreferrer" className="grid h-10 place-items-center rounded-lg border border-[#d5d0c6] px-4 text-[9px] text-[#525b5e]">PDF Önizle / İndir</a>{quote.canManage&&quote.status==="Draft"&&!quote.isArchived?<Link href={`/studio/quotes/${quote.id}/edit`} className="grid h-10 place-items-center rounded-lg bg-[var(--studio-action-primary)] hover:bg-[var(--studio-action-primary-hover)] active:bg-[var(--studio-action-primary-pressed)] px-4 text-[9px] font-semibold text-white">Düzenle</Link>:null}{quote.canManage?<StudioQuoteArchiveControl quoteId={quote.id} archived={quote.isArchived}/>:null}</div></div>{quote.canManage&&!quote.isArchived?<div className="mt-5 border-t border-[#ece9e3] pt-5"><StudioQuoteActions quoteId={quote.id} status={quote.status}/></div>:null}</header>
 <div className="mt-5 grid min-w-0 gap-5 lg:grid-cols-3"><section className="rounded-xl border border-[#dedad1] bg-white p-5 lg:col-span-2"><h2 className="text-[13px] font-semibold text-[#2d353b]">Hizmet Kalemleri</h2><div className="mt-4 space-y-3">{quote.items.map((item,index)=><article key={item.id} className="grid gap-3 rounded-lg border border-[#e7e3dc] p-4 sm:grid-cols-[28px_minmax(0,1fr)_auto]"><span className="text-[9px] text-[#aaa79f]">{index+1}</span><div className="min-w-0"><h3 className="break-words text-[11px] font-medium text-[#30393f]">{item.serviceName}</h3><p className="mt-1 break-words text-[9px] leading-4 text-[#858783]">{item.description||"Açıklama yok"}</p><p className="mt-2 text-[9px] text-[#6e7473]">{item.quantity} {QUOTE_UNIT_LABELS[item.unit]} × {money(item.unitPrice,quote.currency)}</p></div><p className="text-[10px] font-semibold text-[#394246]">{money(item.lineTotal,quote.currency)}</p></article>)}</div></section>
 <aside className="rounded-xl border border-[#d8cfbd] bg-[#faf8f3] p-5"><h2 className="text-[13px] font-semibold text-[#2d353b]">Finansal Özet</h2><dl className="mt-5 space-y-3 text-[10px]"><div className="flex justify-between gap-4"><dt>Ara Toplam</dt><dd>{money(quote.subtotal,quote.currency)}</dd></div><div className="flex justify-between gap-4"><dt>İndirim</dt><dd>-{money(quote.discountTotal,quote.currency)}</dd></div><div className="flex justify-between gap-4"><dt>KDV (%{quote.taxRate})</dt><dd>{money(quote.taxTotal,quote.currency)}</dd></div><div className="flex justify-between gap-4 border-t border-[#d8d1c5] pt-3 text-[12px] font-semibold"><dt>Genel Toplam</dt><dd>{money(quote.grandTotal,quote.currency)}</dd></div></dl></aside>
 <section className="rounded-xl border border-[#dedad1] bg-white p-5"><h2 className="text-[13px] font-semibold">Müşteri Snapshot</h2><div className="mt-4 space-y-2 break-words text-[10px] text-[#646b6c]"><p>{quote.client.name}</p><p>{quote.client.company||"Firma belirtilmedi"}</p><p>{quote.client.phone}</p><p>{quote.client.email||"E-posta belirtilmedi"}</p><p>{[quote.client.city,quote.client.district].filter(Boolean).join(" / ")||"Konum belirtilmedi"}</p><Link href={`/studio/crm/${quote.leadId}`} className="mt-3 inline-block text-[#806b45]">CRM kaydına git →</Link></div></section>
 <section className="rounded-xl border border-[#dedad1] bg-white p-5"><h2 className="text-[13px] font-semibold">Ödeme Koşulları</h2><p className="mt-4 whitespace-pre-wrap break-words text-[10px] leading-5 text-[#646b6c]">{quote.paymentTerms||"Belirtilmedi"}</p></section><section className="rounded-xl border border-[#dedad1] bg-white p-5"><h2 className="text-[13px] font-semibold">Notlar</h2><p className="mt-4 whitespace-pre-wrap break-words text-[10px] leading-5 text-[#646b6c]">{quote.notes||"Not bulunmuyor."}</p></section>
 <section className="rounded-xl border border-[#dedad1] bg-white p-5 lg:col-span-3"><h2 className="text-[13px] font-semibold">Durum Bilgileri</h2><dl className="mt-4 grid gap-4 sm:grid-cols-4"><div><dt className="text-[8px] uppercase text-[#aaa79f]">Oluşturuldu</dt><dd className="mt-1 text-[10px]">{quote.createdAtLabel}</dd></div><div><dt className="text-[8px] uppercase text-[#aaa79f]">Gönderildi</dt><dd className="mt-1 text-[10px]">{quote.sentAt?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(quote.sentAt)):"—"}</dd></div><div><dt className="text-[8px] uppercase text-[#aaa79f]">Onaylandı</dt><dd className="mt-1 text-[10px]">{quote.approvedAt?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(quote.approvedAt)):"—"}</dd></div><div><dt className="text-[8px] uppercase text-[#aaa79f]">Proje</dt><dd className="mt-1 text-[10px]">{quote.project?<Link href={`/studio/projects/${quote.project.id}`} className="text-[#806b45]">{quote.project.code} · {quote.project.name}</Link>:"—"}</dd></div></dl></section>
 </div>{quote.canManage&&quote.status==="Approved"&&!quote.isArchived&&!quote.project?<div className="mt-5"><StudioQuoteConversionForm quote={quote} members={members}/></div>:null}
 </section>;}
