"use client";
import Link from "next/link";
import {useActionState,useState} from "react";
import StudioQuoteItemsEditor,{type EditableQuoteItem} from "./StudioQuoteItemsEditor";
import {DEFAULT_QUOTE_VALUES,QUOTE_CURRENCIES,QUOTE_DISCOUNT_TYPES} from "@/lib/studio/quotes/quote-constants";
import type {QuoteDiscountType,QuoteFormState,QuoteFormValues,StudioQuoteLead} from "@/lib/studio/quotes/quote-types";
import {StudioPendingLabel,studioButtonClass} from "@/components/studio/StudioButton";
import StudioAiWritingDialog from "@/components/studio/ai/StudioAiWritingDialog";
type Action=(state:QuoteFormState,data:FormData)=>Promise<QuoteFormState>;
const blankItem:EditableQuoteItem={serviceName:"",description:"",quantity:"1",unit:"Piece",unitPrice:"0"};
const defaults:QuoteFormValues={leadId:"",title:"",currency:DEFAULT_QUOTE_VALUES.currency,discountType:DEFAULT_QUOTE_VALUES.discountType,discountValue:"0",taxRate:DEFAULT_QUOTE_VALUES.taxRate,validUntil:"",notes:"",paymentTerms:"",items:JSON.stringify([blankItem])};
const inputClass="mt-2 h-11 w-full min-w-0 rounded-lg border border-[#ddd8ce] bg-[#fbfaf7] px-3 text-[11px] text-[#343b40] outline-none focus:border-[#a58a56] focus:ring-2 focus:ring-[#a58a56]/15 aria-[invalid=true]:border-[#a56650]";
export default function StudioQuoteForm({action,leads,initialValues,mode,quoteId}:{action:Action;leads:StudioQuoteLead[];initialValues?:QuoteFormValues;mode:"create"|"edit";quoteId?:string}){
 const[state,formAction,pending]=useActionState(action,{success:false,values:initialValues??defaults});const values=state.values??initialValues??defaults;
 const[items,setItems]=useState<EditableQuoteItem[]>(()=>{try{return JSON.parse(values.items) as EditableQuoteItem[];}catch{return[{...blankItem}];}});
 const[currency,setCurrency]=useState(values.currency);const[discountType,setDiscountType]=useState<QuoteDiscountType>(values.discountType as QuoteDiscountType);
 const[discountValue,setDiscountValue]=useState(values.discountValue);const[taxRate,setTaxRate]=useState(values.taxRate);
 const[notes,setNotes]=useState(values.notes);
 function error(name:keyof QuoteFormValues){return state.fieldErrors?.[name]?.[0];}
 return <form action={formAction} className="space-y-5"><input type="hidden" name="items" value={JSON.stringify(items)}/>
  {state.message?<div role="alert" className="rounded-lg border border-[#decfc7] bg-[#f8f1ee] px-4 py-3 text-[10px] text-[#875b4b]">{state.message}</div>:null}
  <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><div className="border-b border-[#ece9e3] pb-4"><h2 className="text-[13px] font-semibold text-[#2d353b]">Genel Bilgiler</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2">
   <label className="min-w-0"><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">CRM Lead *</span><select name="leadId" required defaultValue={values.leadId} aria-invalid={Boolean(error("leadId"))} aria-describedby={error("leadId")?"leadId-error":undefined} className={inputClass}><option value="">Lead seçin</option>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.name}{lead.company?` · ${lead.company}`:""}</option>)}</select>{error("leadId")?<span id="leadId-error" className="mt-1.5 block text-[9px] text-[#9b5d48]">{error("leadId")}</span>:null}</label>
   <label className="min-w-0"><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">Teklif Başlığı *</span><input name="title" required defaultValue={values.title} aria-invalid={Boolean(error("title"))} aria-describedby={error("title")?"title-error":undefined} className={inputClass}/>{error("title")?<span id="title-error" className="mt-1.5 block text-[9px] text-[#9b5d48]">{error("title")}</span>:null}</label>
   <label><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">Para Birimi</span><select name="currency" value={currency} onChange={event=>setCurrency(event.target.value)} className={inputClass}>{QUOTE_CURRENCIES.map(value=><option key={value}>{value}</option>)}</select></label>
   <label><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">Geçerlilik Tarihi</span><input name="validUntil" type="date" defaultValue={values.validUntil} className={inputClass}/></label>
   <label><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">İndirim Tipi</span><select name="discountType" value={discountType} onChange={event=>setDiscountType(event.target.value as QuoteDiscountType)} className={inputClass}>{QUOTE_DISCOUNT_TYPES.map(value=><option key={value} value={value}>{value==="None"?"İndirim Yok":value==="Fixed"?"Sabit Tutar":"Yüzde"}</option>)}</select></label>
   <label><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">İndirim Değeri</span><input name="discountValue" inputMode="decimal" value={discountValue} onChange={event=>setDiscountValue(event.target.value)} className={inputClass}/>{error("discountValue")?<span className="mt-1.5 block text-[9px] text-[#9b5d48]">{error("discountValue")}</span>:null}</label>
   <label><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">KDV Oranı (%)</span><input name="taxRate" inputMode="decimal" value={taxRate} onChange={event=>setTaxRate(event.target.value)} className={inputClass}/>{error("taxRate")?<span className="mt-1.5 block text-[9px] text-[#9b5d48]">{error("taxRate")}</span>:null}</label>
  </div></section>
  <StudioQuoteItemsEditor items={items} onChange={setItems} currency={currency} discountType={discountType} discountValue={discountValue} taxRate={taxRate} error={error("items")}/>
  <section className="rounded-xl border border-[#dedad1] bg-white p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-2"><label><span className="text-[9px] font-semibold uppercase tracking-[.1em] text-[#777a75]">Ödeme Koşulları</span><textarea name="paymentTerms" rows={5} maxLength={5000} defaultValue={values.paymentTerms} className="mt-2 w-full resize-y rounded-lg border border-[#ddd8ce] bg-[#fbfaf7] px-3 py-3 text-[15px] outline-none focus:border-[#a58a56]"/></label><div><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-sm font-semibold uppercase tracking-[.08em] text-[#777a75]">Teklif Açıklaması</span><StudioAiWritingDialog operation="proposal_ai_description" title="AI Teklif Açıklaması" triggerLabel="AI ile Teklif Açıklaması Oluştur" currentText={notes} context={{projectName:values.title,services:items.map(item=>item.serviceName).filter(Boolean),customerType:leads.find(lead=>lead.id===values.leadId)?.company?"kurumsal":"bireysel",currency}} onUse={setNotes}/></div><label className="mt-3 block"><span className="sr-only">Teklif açıklaması</span><textarea name="notes" rows={5} maxLength={10000} value={notes} onChange={event=>setNotes(event.target.value)} className="mt-2 w-full resize-y rounded-lg border border-[#ddd8ce] bg-[#fbfaf7] px-3 py-3 text-[15px] leading-6 outline-none focus:border-[#a58a56]"/></label></div></div></section>
  <div className="flex flex-col-reverse gap-3 border-t border-[#dcd7cd] pt-5 sm:flex-row sm:justify-end"><Link href={quoteId?`/studio/quotes/${quoteId}`:"/studio/quotes"} className={studioButtonClass("outline")}>Vazgeç</Link><button type="submit" disabled={pending} aria-busy={pending} className={studioButtonClass("primary")}><StudioPendingLabel pending={pending} pendingLabel={mode==="create"?"Teklif Oluşturuluyor...":"Değişiklikler Kaydediliyor..."}>{mode==="create"?"Teklif Oluştur":"Değişiklikleri Kaydet"}</StudioPendingLabel></button></div>
 </form>;
}
