/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase relation rows are mapped at this boundary. */
import"server-only";
import{getStudioContext}from"@/lib/studio/auth/get-studio-context";import{createStudioServerClient}from"@/lib/studio/supabase/server";import{formatBytes}from"@/lib/studio/files/file-mappers";import{renderAspectRatio,renderCategorySchema,renderMetadataSchema}from"./render-validation";import type{StudioRenderArchive,StudioRenderFilters}from"./render-types";
async function scope(owner=false){const c=await getStudioContext();if(!c?.user||!c.membership)throw new Error("unauthorized");if(owner&&c.membership.role!=="owner")throw new Error("forbidden");return{organizationId:c.membership.organization_id,userId:c.user.id,canManage:c.membership.role==="owner",db:await createStudioServerClient()};}
async function projectScope(projectId:string,owner=false){const s=await scope(owner);const{data,error}=await s.db.from("studio_projects").select("id,code,name").eq("id",projectId).eq("organization_id",s.organizationId).maybeSingle();if(error||!data)throw new Error("project_not_found");return{...s,project:data};}
const categorySelect="id,name,sort_order,is_system,is_archived";
export async function initializeRenderCategories(projectId:string){const s=await projectScope(projectId,true);const{error}=await s.db.rpc("studio_initialize_render_categories",{target_project:projectId,target_user:s.userId});if(error)throw error;}
export async function getRenderArchive(projectId:string,filters:StudioRenderFilters={}):Promise<StudioRenderArchive>{const s=await projectScope(projectId);const[{data:categories,error:categoryError},{data:rows,error:renderError},{data:files,error:fileError},{data:favorites},{data:tagRows}]=await Promise.all([
 s.db.from("studio_render_categories").select(categorySelect).eq("organization_id",s.organizationId).eq("project_id",projectId).order("sort_order"),
 s.db.from("studio_project_renders").select("id,project_id,logical_file_id,category_id,title,description,width,height,aspect_ratio,is_hero,is_client_visible,presented_at,archived_at,category:studio_render_categories(name),file:studio_project_files!inner(display_name,extension,mime_type,file_size,current_version_id,latest_version_number,version_count,revision_code,uploaded_by,created_at,is_archived,status,uploader:profiles!studio_project_files_uploaded_by_fkey(full_name))").eq("organization_id",s.organizationId).eq("project_id",projectId).is("archived_at",null),
 s.db.from("studio_project_files").select("id,display_name,extension").eq("organization_id",s.organizationId).eq("project_id",projectId).eq("status","ready").eq("is_archived",false).in("category",["render","image"]).order("created_at",{ascending:false}),
 s.db.from("studio_user_favorites").select("entity_id").eq("organization_id",s.organizationId).eq("user_id",s.userId).eq("entity_type","file").is("archived_at",null),
 s.db.from("studio_tag_assignments").select("entity_id,tag:studio_tags(name)").eq("organization_id",s.organizationId).eq("entity_type","file").eq("is_active",true),
 ]);if(categoryError||renderError||fileError)throw categoryError||renderError||fileError;const favoriteIds=new Set((favorites??[]).map(x=>x.entity_id));const tags=new Map<string,string[]>();for(const row of tagRows??[]){const tag=Array.isArray(row.tag)?row.tag[0]:row.tag;if(tag){const values=tags.get(row.entity_id)??[];values.push(String((tag as{ name:string}).name));tags.set(row.entity_id,values);}}
 let renders=(rows??[]).map((raw:any)=>{const file=Array.isArray(raw.file)?raw.file[0]:raw.file,category=Array.isArray(raw.category)?raw.category[0]:raw.category,uploader=Array.isArray(file.uploader)?file.uploader[0]:file.uploader;return{id:raw.id,projectId:raw.project_id,fileId:raw.logical_file_id,title:raw.title,description:raw.description??"",categoryId:raw.category_id,categoryName:category?.name??"Diğer",isHero:raw.is_hero,isClientVisible:raw.is_client_visible,presentedAt:raw.presented_at,archivedAt:raw.archived_at,width:raw.width,height:raw.height,aspectRatio:raw.aspect_ratio??renderAspectRatio(raw.width,raw.height),file:{displayName:file.display_name,extension:file.extension,mimeType:file.mime_type,fileSize:Number(file.file_size),fileSizeLabel:formatBytes(Number(file.file_size)),versionNumber:file.latest_version_number||1,versionCount:file.version_count||1,revisionCode:file.revision_code??"",currentVersionId:file.current_version_id,uploadedByName:uploader?.full_name??"Studio kullanıcısı",createdAt:file.created_at},tags:tags.get(raw.logical_file_id)??[],canManage:s.canManage,thumbnailUrl:`/studio/projects/${projectId}/files/${raw.logical_file_id}/thumbnail?version=${file.current_version_id}`};});
 renders=renders.map(render=>({...render,isFavorite:favoriteIds.has(render.fileId)}));if(filters.category)renders=renders.filter(x=>x.categoryId===filters.category);if(filters.favoritesOnly)renders=renders.filter(x=>favoriteIds.has(x.fileId));if(filters.presented!==undefined)renders=renders.filter(x=>Boolean(x.presentedAt)===filters.presented);if(filters.hero)renders=renders.filter(x=>x.isHero);if(filters.uploader)renders=renders.filter(x=>x.file.uploadedByName===filters.uploader);if(filters.dateFrom)renders=renders.filter(x=>x.file.createdAt>=filters.dateFrom!);if(filters.dateTo)renders=renders.filter(x=>x.file.createdAt<=`${filters.dateTo}T23:59:59.999Z`);if(filters.tagIds?.length){const selected=new Set(filters.tagIds);renders=renders.filter(x=>x.tags.some(tag=>selected.has(tag)));}
 const linked=new Set((rows??[]).map((r:any)=>r.logical_file_id));return{project:s.project,categories:(categories??[]).map((c:any)=>({id:c.id,name:c.name,sortOrder:c.sort_order,isSystem:c.is_system,isArchived:c.is_archived})),renders,attachableFiles:(files??[]).filter(f=>!linked.has(f.id)).map(f=>({id:f.id,name:f.display_name,extension:f.extension})),canManage:s.canManage};}
async function event(s:Awaited<ReturnType<typeof projectScope>>,renderId:string,type:string,title:string){await s.db.from("studio_render_events").insert({organization_id:s.organizationId,project_id:s.project.id,render_id:renderId,event_type:type,title,created_by:s.userId});}
export async function createRenderCategory(projectId:string,name:string){const s=await projectScope(projectId,true),clean=renderCategorySchema.parse(name);const{error}=await s.db.from("studio_render_categories").insert({organization_id:s.organizationId,project_id:projectId,name:clean,normalized_name:clean.toLocaleLowerCase("tr-TR"),sort_order:999,created_by:s.userId,updated_by:s.userId});if(error)throw error;}
export async function updateRenderCategory(projectId:string,id:string,name:string,archived:boolean){const s=await projectScope(projectId,true),clean=renderCategorySchema.parse(name);const{error}=await s.db.from("studio_render_categories").update({name:clean,normalized_name:clean.toLocaleLowerCase("tr-TR"),is_archived:archived,updated_by:s.userId}).eq("id",id).eq("organization_id",s.organizationId).eq("project_id",projectId);if(error)throw error;}
export async function attachRenderFile(projectId:string,fileId:string,categoryId:string|null){const s=await projectScope(projectId,true);const{data:file}=await s.db.from("studio_project_files").select("id,display_name").eq("id",fileId).eq("project_id",projectId).eq("organization_id",s.organizationId).eq("status","ready").eq("is_archived",false).in("category",["render","image"]).maybeSingle();if(!file)throw new Error("render_file_invalid");const{data,error}=await s.db.from("studio_project_renders").insert({organization_id:s.organizationId,project_id:projectId,logical_file_id:fileId,category_id:categoryId,title:file.display_name,created_by:s.userId,updated_by:s.userId}).select("id").single();if(error)throw error;await event(s,data.id,"created","Render arşive eklendi");}
export async function updateRender(projectId:string,id:string,input:unknown){const s=await projectScope(projectId,true),value=renderMetadataSchema.parse(input);const ratio=renderAspectRatio(value.width,value.height);const{error}=await s.db.from("studio_project_renders").update({title:value.title,description:value.description||null,category_id:value.categoryId,width:value.width,height:value.height,aspect_ratio:ratio,updated_by:s.userId}).eq("id",id).eq("organization_id",s.organizationId).eq("project_id",projectId).is("archived_at",null);if(error)throw error;await event(s,id,"updated","Render bilgileri güncellendi");}
export async function setHeroRender(projectId:string,id:string){const s=await projectScope(projectId,true);const{error}=await s.db.rpc("studio_set_hero_render",{target_project:projectId,target_render:id,target_user:s.userId});if(error)throw error;await event(s,id,"hero_selected","Kapak renderı seçildi");}
export async function setRenderFlags(projectId:string,ids:string[],input:{clientVisible?:boolean;presented?:boolean;archived?:boolean}){const s=await projectScope(projectId,true),safe=[...new Set(ids)].filter(x=>/^[0-9a-f-]{36}$/i.test(x)).slice(0,50);if(!safe.length)throw new Error("render_selection_empty");const values:Record<string,unknown>={updated_by:s.userId};if(input.clientVisible!==undefined)values.is_client_visible=input.clientVisible;if(input.presented!==undefined)values.presented_at=input.presented?new Date().toISOString():null;if(input.archived!==undefined){values.archived_at=input.archived?new Date().toISOString():null;values.archived_by=input.archived?s.userId:null;values.is_hero=false;}const{error}=await s.db.from("studio_project_renders").update(values).eq("organization_id",s.organizationId).eq("project_id",projectId).in("id",safe);if(error)throw error;}
export async function getRenderForNotification(projectId:string,id:string){const s=await projectScope(projectId,true);const{data,error}=await s.db.from("studio_project_renders").select("id,title,description,logical_file_id,archived_at,file:studio_project_files!inner(mime_type)").eq("id",id).eq("organization_id",s.organizationId).eq("project_id",projectId).maybeSingle();if(error||!data||data.archived_at)throw new Error("render_not_found");return{...s,render:data};}
