import "server-only";
import {logSafeServerDiagnostic} from "@/lib/studio/observability/safe-server-logger";
export type RenderArchiveErrorKind="schema_missing"|"schema_cache"|"permission"|"network"|"repository"|"mapper";
export type RenderArchiveLoadError={kind:RenderArchiveErrorKind;operation:string;sqlState:string|null;postgrestCode:string|null;relation:string|null;function:string|null;constraint:string|null;sanitizedMessage:string};
type ErrorLike={code?:unknown;message?:unknown;details?:unknown;hint?:unknown;cause?:unknown;name?:unknown};
const text=(value:unknown)=>typeof value==="string"&&value.trim()?value.trim():null;
function flatten(error:unknown):ErrorLike{if(error instanceof Error)return{message:error.message,name:error.name,cause:error.cause};if(typeof error==="string")return{message:error};if(error&&typeof error==="object")return error as ErrorLike;return{};}
export function classifyRenderArchiveError(error:unknown,operation:string):RenderArchiveLoadError{const value=flatten(error);const cause=value.cause?flatten(value.cause):{};const code=text(value.code)??text(cause.code);const message=text(value.message)??text(cause.message)??"";const lower=message.toLowerCase();let kind:RenderArchiveErrorKind="repository";if(code==="42P01"||code==="42703"||(lower.includes("does not exist")&&(lower.includes("relation")||lower.includes("column"))))kind="schema_missing";else if(code==="PGRST205"||code==="PGRST204")kind="schema_cache";else if(code==="42501"||code==="PGRST301"||lower.includes("permission denied")||lower==="forbidden"||lower==="unauthorized")kind="permission";else if(lower.includes("fetch")||lower.includes("network")||lower.includes("timeout"))kind="network";else if(lower.includes("cannot read")||lower.includes("undefined")||lower.includes("mapper"))kind="mapper";const safe={schema_missing:"Render Archive schema is not prepared.",schema_cache:"Render Archive schema is outside the API schema cache.",permission:"Render Archive access could not be verified.",network:"Render Archive request could not be completed.",mapper:"Render Archive response could not be read.",repository:"Render Archive repository operation failed."}[kind];return{kind,operation,sqlState:code?.match(/^\d[A-Z0-9]{4}$/)?code:null,postgrestCode:code?.startsWith("PGRST")?code:null,relation:message.match(/relation ["']?([\w.]+)["']? does not exist/i)?.[1]??null,function:message.match(/function ["']?([\w.]+)["']?/i)?.[1]??null,constraint:message.match(/constraint ["']?([\w.-]+)["']?/i)?.[1]??null,sanitizedMessage:safe};}
export function logRenderArchiveError(error:RenderArchiveLoadError){if(process.env.NODE_ENV!=="production")logSafeServerDiagnostic("STUDIO_RENDER_ARCHIVE_LOAD_ERROR",{operation:error.operation,kind:error.kind,relation:error.relation,function:error.function,constraint:error.constraint,sqlState:error.sqlState,postgrestCode:error.postgrestCode,sanitizedMessage:error.sanitizedMessage});}
export function renderArchiveUserMessage(error:RenderArchiveLoadError){switch(error.kind){case"schema_missing":return"Render Arşivi veritabanı şeması henüz hazırlanmadı.";case"schema_cache":return"Render Arşivi şeması mevcut ancak API önbelleği yenilenmelidir.";case"permission":return"Render Arşivi erişim yetkisi doğrulanamadı.";default:return"Render Arşivi şu anda yüklenemedi.";}}
