/* eslint-disable @typescript-eslint/no-explicit-any */
import"server-only";import{getStudioContext}from"@/lib/studio/auth/get-studio-context";import{createStudioServerClient}from"@/lib/studio/supabase/server";
async function scope(owner=false){const c=await getStudioContext();if(!c?.user||!c.membership)throw new Error("unauthorized");if(owner&&c.membership.role!=="owner")throw new Error("forbidden");return{userId:c.user.id,organizationId:c.membership.organization_id,db:await createStudioServerClient()}}
async function stage(id:string,owner=false){const s=await scope(owner);const{data,error}=await s.db.from("studio_project_stages").select("id,project_id,organization_id,title").eq("id",id).eq("organization_id",s.organizationId).single();if(error||!data)throw new Error("stage_not_found");return{...s,row:data}}
export async function listStageFiles(projectId:string){const s=await scope();const{data,error}=await s.db.from("studio_project_stage_files").select("id,stage_id,file_id,version_id,attachment_role,is_customer_visible,file:studio_project_files!inner(display_name,extension)").eq("organization_id",s.organizationId).eq("project_id",projectId).is("archived_at",null);if(error)throw error;return(data??[]).map((r:any)=>{const f=Array.isArray(r.file)?r.file[0]:r.file;return{id:r.id,stageId:r.stage_id,fileId:r.file_id,versionId:r.version_id,role:r.attachment_role,customerVisible:r.is_customer_visible,name:f.display_name,extension:f.extension}})}
export async function listAttachableStageFiles(projectId:string){const s=await scope();const{data,error}=await s.db.from("studio_project_files").select("id,display_name,extension").eq("organization_id",s.organizationId).eq("project_id",projectId).eq("status","ready").eq("is_archived",false).in("extension",["pdf","dwg"]).order("display_name");if(error)throw error;return(data??[]).map(r=>({id:r.id,name:r.display_name,extension:r.extension}))}
export async function updateFlexibleStage(id:string,input:Record<string,string|boolean>){const s=await stage(id,true),title=String(input.title).normalize("NFC").trim();if(title.length<2||title.length>180)throw new Error("invalid_title");const status=String(input.status);if(!["waiting","in_progress","completed","cancelled"].includes(status))throw new Error("invalid_status");const{error}=await s.db.from("studio_project_stages").update({title,description:String(input.description).trim()||null,status,started_at:String(input.startedAt)||null,completed_at:status==="completed"?(String(input.completedAt)||new Date().toISOString()):null,responsible_user_id:String(input.responsibleUserId)||null,note:String(input.note).trim()||null,is_active:Boolean(input.isActive),is_client_visible:Boolean(input.isClientVisible),updated_by:s.userId}).eq("id",id).eq("organization_id",s.organizationId);if(error)throw error}
export async function duplicateStage(id:string){const s=await stage(id,true);const{data:max}=await s.db.from("studio_project_stages").select("sort_order").eq("project_id",s.row.project_id).order("sort_order",{ascending:false}).limit(1);const{error}=await s.db.from("studio_project_stages").insert({organization_id:s.organizationId,project_id:s.row.project_id,title:`${s.row.title} (Kopya)`,sort_order:(max?.[0]?.sort_order??0)+1,created_by:s.userId,updated_by:s.userId});if(error)throw error}
export async function archiveStage(id:string,archived:boolean){const s=await stage(id,true);const{error}=await s.db.from("studio_project_stages").update({is_archived:archived,archived_at:archived?new Date().toISOString():null,archived_by:archived?s.userId:null,updated_by:s.userId}).eq("id",id);if(error)throw error}
export async function reorderStage(id:string,direction:-1|1){const s=await stage(id,true);const{error}=await s.db.rpc("studio_reorder_project_stage",{target_stage:id,direction});if(error)throw error}
export async function attachStageFile(stageId:string,fileId:string,role:string,visible:boolean){const s=await stage(stageId,true);if(!["approval_document","drawing","report","submission","other"].includes(role))throw new Error("invalid_role");const{error}=await s.db.from("studio_project_stage_files").insert({organization_id:s.organizationId,project_id:s.row.project_id,stage_id:stageId,file_id:fileId,attachment_role:role,is_customer_visible:visible,created_by:s.userId});if(error)throw error}
export async function updateStageFile(id:string,remove:boolean,visible:boolean){const s=await scope(true);const{error}=await s.db.from("studio_project_stage_files").update(remove?{archived_at:new Date().toISOString(),archived_by:s.userId}:{is_customer_visible:visible}).eq("id",id).eq("organization_id",s.organizationId);if(error)throw error}
