import "server-only";

import {createHash} from "node:crypto";
import {getStudioContext,type StudioRole} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {STUDIO_FILES_BUCKET} from "./file-constants";
import {normalizeFileError,normalizeFileReservationError,StudioFileError} from "./file-errors";
import {formatBytes,mapFile,mapFolder,type FileRow,type FolderRow} from "./file-mappers";
import {buildStudioFilePath,safeDownloadName} from "./file-paths";
import {cleanupStorageObject,createSignedFileDownload,createSignedFileUpload} from "./file-storage";
import {createDriveResumableSession,findDriveFolder,getDriveFileMetadata,googleDriveStorageProvider} from "./storage/google-drive-provider";
import type {ExternalObjectMetadata} from "./storage/storage-provider";
import type {FileMetadataInput,FileReservationInput,FolderInput,StudioFileQuery} from "./file-types";
import {fileExtension,isStudioFileId} from "./file-validation";
import {physicalVersionName} from "./versions/version-naming";

const folderSelect="id,project_id,parent_folder_id,name,sort_order,is_system,is_archived,created_at,updated_at,storage_provider,external_folder_id,external_parent_folder_id,sync_status,last_synced_at,sync_error_code,previous_parent_folder_id,previous_external_parent_folder_id";
const fileSelect="id,project_id,folder_id,display_name,original_file_name,extension,mime_type,file_size,description,category,status,is_archived,uploaded_by,created_at,updated_at,storage_provider,external_file_id,external_parent_folder_id,sync_status,last_synced_at,sync_error_code,previous_folder_id,previous_external_parent_folder_id,current_version_id,version_count,latest_version_number,current_version:studio_project_file_versions!studio_project_files_current_version_fkey(revision_code),uploader:profiles!studio_project_files_uploaded_by_fkey(id,full_name)";
type Client=Awaited<ReturnType<typeof createStudioServerClient>>;
type ProjectContext={ctx:{userId:string;organizationId:string;canManage:boolean};supabase:Client;project:{id:string;code:string;name:string;storage_provider?:string;external_project_folder_id?:string|null}};
type DbFile=FileRow&{organization_id:string;storage_path:string;external_parent_folder_id:string|null;sync_error_code?:string|null;previous_folder_id?:string|null;previous_external_parent_folder_id?:string|null};
type DbFolder=FolderRow&{organization_id:string;storage_provider?:string;external_folder_id?:string|null;external_parent_folder_id?:string|null;sync_error_code?:string|null;previous_parent_folder_id?:string|null;previous_external_parent_folder_id?:string|null};

async function context(owner=false){const value=await getStudioContext();if(!value?.user||!value.membership)throw new StudioFileError("unauthorized","Oturum gerekli.");const role=value.membership.role as StudioRole;if(owner&&role!=="owner")throw new StudioFileError("forbidden","Bu işlem yalnızca Studio sahibi tarafından yapılabilir.");return{userId:value.user.id,organizationId:value.membership.organization_id,canManage:role==="owner"};}
async function project(projectId:string,owner=false):Promise<ProjectContext>{if(!isStudioFileId(projectId))throw new StudioFileError("not_found","Proje bulunamadı.");const ctx=await context(owner);const supabase=await createStudioServerClient();const{data,error}=await supabase.from("studio_projects").select("id,code,name,storage_provider,external_project_folder_id").eq("id",projectId).eq("organization_id",ctx.organizationId).maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Proje bulunamadı.");return{ctx,supabase,project:data};}
async function folderRow(scope:ProjectContext,folderId:string,allowRoot:true):Promise<DbFolder|null>;
async function folderRow(scope:ProjectContext,folderId:string,allowRoot?:false):Promise<DbFolder>;
async function folderRow(scope:ProjectContext,folderId:string,allowRoot=false):Promise<DbFolder|null>{if(!folderId&&allowRoot)return null;if(!isStudioFileId(folderId))throw new StudioFileError("invalid_folder","Klasör bulunamadı.");const{data,error}=await scope.supabase.from("studio_project_folders").select(folderSelect+",organization_id").eq("id",folderId).eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id).maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("invalid_folder","Klasör bulunamadı.");return data as unknown as DbFolder;}
async function fileRow(scope:ProjectContext,fileId:string){if(!isStudioFileId(fileId))throw new StudioFileError("not_found","Dosya bulunamadı.");const{data,error}=await scope.supabase.from("studio_project_files").select(fileSelect+",organization_id,storage_path").eq("id",fileId).eq("project_id",scope.project.id).eq("organization_id",scope.ctx.organizationId).maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Dosya bulunamadı.");return data as unknown as DbFile;}
function requireDriveFile(row:DbFile){if(row.storage_provider!=="google_drive"||!row.external_file_id||!row.external_parent_folder_id)throw new StudioFileError("storage","Google Drive dosya eşlemesi hazır değil.");}
function requireDriveFolder(row:DbFolder|null,scope:ProjectContext){const externalId=row?.external_folder_id??scope.project.external_project_folder_id;if((row&&row.storage_provider!=="google_drive")||!externalId)throw new StudioFileError("storage","Google Drive klasör eşlemesi hazır değil.");return externalId;}
async function systemFolder(scope:ProjectContext,name:string){const{data}=await scope.supabase.from("studio_project_folders").select(folderSelect+",organization_id").eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id).eq("is_system",true).eq("name",name).maybeSingle();if(!data)throw new StudioFileError("storage",`${name} sistem klasörü hazır değil.`);const row=data as unknown as DbFolder;requireDriveFolder(row,scope);return row;}
async function markFileError(scope:ProjectContext,id:string,code:string){await scope.supabase.from("studio_project_files").update({sync_status:"error",sync_error_code:code}).eq("id",id).eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id);}
async function markFolderError(scope:ProjectContext,id:string,code:string){await scope.supabase.from("studio_project_folders").update({sync_status:"error",sync_error_code:code}).eq("id",id).eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id);}
async function persistAfterDrive(scope:ProjectContext,table:"studio_project_files"|"studio_project_folders",id:string,values:Record<string,unknown>){const{data,error}=await scope.supabase.from(table).update({...values,sync_status:"synced",sync_error_code:null,last_synced_at:new Date().toISOString(),updated_by:scope.ctx.userId}).eq("id",id).eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id).select("id").maybeSingle();if(error||!data){if(table==="studio_project_files")await markFileError(scope,id,"metadata_persist_failed");else await markFolderError(scope,id,"metadata_persist_failed");throw new StudioFileError("partial_sync","Drive işlemi tamamlandı ancak Studio kaydı senkronize edilemedi. Durumu doğrulayıp yeniden deneyin.");}}
function normalized(value:string){return value.trim().replace(/\s+/g," ").toLocaleLowerCase("tr-TR");}
function stableFolderId(value:string){const hex=createHash("sha256").update(value).digest("hex").slice(0,32).split("");hex[12]="5";hex[16]=((Number.parseInt(hex[16],16)&3)|8).toString(16);const joined=hex.join("");return`${joined.slice(0,8)}-${joined.slice(8,12)}-${joined.slice(12,16)}-${joined.slice(16,20)}-${joined.slice(20)}`;}
async function duplicateFile(scope:ProjectContext,row:DbFile,folderId:string,name:string){let query=scope.supabase.from("studio_project_files").select("id").eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id).eq("normalized_file_name",normalized(name)).eq("is_archived",false).in("status",["uploading","ready"]).neq("id",row.id);query=folderId?query.eq("folder_id",folderId):query.is("folder_id",null);const{data}=await query.maybeSingle();if(data)throw new StudioFileError("duplicate","Hedef klasörde aynı ada sahip bir dosya bulunuyor.");}
async function duplicateFolder(scope:ProjectContext,rowId:string,parentId:string,name:string){let query=scope.supabase.from("studio_project_folders").select("id").eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id).eq("normalized_name",normalized(name)).eq("is_archived",false).neq("id",rowId);query=parentId?query.eq("parent_folder_id",parentId):query.is("parent_folder_id",null);const{data}=await query.maybeSingle();if(data)throw new StudioFileError("duplicate","Hedef konumda aynı ada sahip bir klasör bulunuyor.");}
function desiredFileName(input:string,extension:string){const value=input.trim().replace(/[\\/\r\n]/g,"-");if(!value||value.length>240)throw new StudioFileError("invalid_file","Geçerli bir dosya adı girin.");const supplied=fileExtension(value);if(supplied&&supplied!==extension)throw new StudioFileError("invalid_file","Dosya uzantısı değiştirilemez.");const name=supplied?value:`${value}.${extension}`;if(name.length>240)throw new StudioFileError("invalid_file","Dosya adı çok uzun.");return name;}
function syncValues(value:ExternalObjectMetadata){return{provider_checksum:value.checksum??null,provider_version:value.version??null,external_modified_at:value.modifiedTime??null};}

export async function getStudioFileAccess(){const ctx=await context();return{canManage:ctx.canManage};}
export async function reserveGoogleDriveProjectFile(input:FileReservationInput&{extension:string;mimeType:string}){const scope=await project(input.projectId,true);const folder=await folderRow(scope,input.folderId);const parentId=requireDriveFolder(folder,scope);const normalizedName=normalized(input.originalFileName);const{data:duplicate}=await scope.supabase.from("studio_project_files").select("id").eq("organization_id",scope.ctx.organizationId).eq("project_id",input.projectId).eq("folder_id",input.folderId).eq("normalized_file_name",normalizedName).eq("is_archived",false).in("status",["uploading","ready"]).maybeSingle();if(duplicate)throw new StudioFileError("duplicate","Bu klasörde aynı ada sahip bir dosya bulunuyor.");const id=crypto.randomUUID();const reservation=await scope.supabase.from("studio_project_files").insert({id,organization_id:scope.ctx.organizationId,project_id:input.projectId,folder_id:input.folderId,display_name:input.originalFileName,original_file_name:input.originalFileName,normalized_file_name:normalizedName,extension:input.extension,mime_type:input.mimeType,file_size:input.fileSize,storage_provider:"google_drive",storage_bucket:STUDIO_FILES_BUCKET,storage_path:`google-drive://${id}`,external_parent_folder_id:parentId,category:input.category,status:"uploading",uploaded_by:scope.ctx.userId,updated_by:scope.ctx.userId,sync_status:"pending"});if(reservation.error)throw normalizeFileReservationError(reservation.error);try{const sessionUrl=await createDriveResumableSession(scope.ctx.organizationId,{name:input.originalFileName,mimeType:input.mimeType,size:input.fileSize,parentId,appProperties:{arz_entity_type:"file",organization_id:scope.ctx.organizationId,project_id:input.projectId,reservation_id:id}});return{id,sessionUrl,expected:{name:input.originalFileName,mimeType:input.mimeType,size:input.fileSize,parentId}};}catch(error){await markFileError(scope,id,"upload_session_failed");await scope.supabase.from("studio_project_files").update({status:"failed"}).eq("id",id);throw error;}}
export async function finalizeGoogleDriveProjectFile(projectId:string,fileId:string,externalFileId:string){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);if(row.status==="ready")return row;if(row.storage_provider!=="google_drive"||row.status!=="uploading")throw new StudioFileError("storage","Yükleme durumu finalize edilemez.");const value=await getDriveFileMetadata(scope.ctx.organizationId,externalFileId).catch(()=>null);if(!value||value.id!==externalFileId||value.trashed||value.name!==row.original_file_name||value.mimeType!==row.mime_type||Number(value.size??-1)!==Number(row.file_size)||!value.parents.includes(row.external_parent_folder_id??"")){await scope.supabase.from("studio_project_files").update({status:"failed",sync_status:"error",sync_error_code:"upload_verification_failed"}).eq("id",fileId);throw new StudioFileError("storage","Google Drive dosya doğrulaması başarısız oldu.");}const{error}=await scope.supabase.from("studio_project_files").update({status:"ready",sync_status:"synced",sync_error_code:null,external_file_id:externalFileId,...syncValues(value),last_synced_at:new Date().toISOString()}).eq("id",fileId).eq("status","uploading");if(error)throw normalizeFileError(error);return row;}
export async function initializeStudioProjectFolders(projectId:string){const scope=await project(projectId);const{error}=await scope.supabase.rpc("studio_initialize_project_folders",{target_project_id:projectId});if(error)throw normalizeFileError(error);}
export async function getStudioProjectFolders(projectId:string,archive:StudioFileQuery["archive"]="active"){const scope=await project(projectId);let query=scope.supabase.from("studio_project_folders").select(folderSelect).eq("organization_id",scope.ctx.organizationId).eq("project_id",projectId).order("sort_order").order("name");if(archive!=="all")query=query.eq("is_archived",archive==="archived");const{data,error}=await query;if(error)throw normalizeFileError(error);return(data as unknown as FolderRow[]).map(row=>mapFolder(row,scope.ctx.canManage));}
export async function getStudioProjectFiles(projectId:string,filters:StudioFileQuery={}){const scope=await project(projectId);let query=scope.supabase.from("studio_project_files").select(fileSelect).eq("organization_id",scope.ctx.organizationId).eq("project_id",projectId).order("created_at",{ascending:false});if(filters.archive!=="all")query=query.eq("is_archived",filters.archive==="archived");if(filters.folderId)query=query.eq("folder_id",filters.folderId);else if(filters.archive!=="archived")query=query.is("folder_id",null);if(filters.category)query=query.eq("category",filters.category);if(filters.extension)query=query.eq("extension",filters.extension);if(filters.query){const safe=filters.query.replace(/[,%()"'*:]/g," ").trim();if(safe)query=query.ilike("display_name",`%${safe}%`);}const{data,error}=await query;if(error)throw normalizeFileError(error);return(data as unknown as FileRow[]).map(row=>mapFile(row,scope.ctx.canManage));}
export async function getStudioProjectFileSummary(projectId:string){const scope=await project(projectId);const[{data:files,error:fileError},{count:folderCount,error:folderError}]=await Promise.all([scope.supabase.from("studio_project_files").select("file_size").eq("organization_id",scope.ctx.organizationId).eq("project_id",projectId).eq("is_archived",false).eq("status","ready"),scope.supabase.from("studio_project_folders").select("id",{count:"exact",head:true}).eq("organization_id",scope.ctx.organizationId).eq("project_id",projectId).eq("is_archived",false)]);if(fileError)throw normalizeFileError(fileError);if(folderError)throw normalizeFileError(folderError);const bytes=(files??[]).reduce((sum,row)=>sum+Number(row.file_size),0);return{fileCount:files?.length??0,folderCount:folderCount??0,storageBytes:bytes,storageLabel:formatBytes(bytes)};}
export async function getStudioProjectFileWorkspace(projectId:string,filters:StudioFileQuery={}){await initializeStudioProjectFolders(projectId);const scope=await project(projectId);const[folders,files,activeFolders,summary]=await Promise.all([getStudioProjectFolders(projectId,filters.archive),getStudioProjectFiles(projectId,filters),getStudioProjectFolders(projectId,"active"),getStudioProjectFileSummary(projectId)]);let currentFolder=null;if(filters.folderId){currentFolder=folders.find(folder=>folder.id===filters.folderId)??null;if(!currentFolder)throw new StudioFileError("not_found","Klasör bulunamadı.");}const byId=new Map(activeFolders.concat(folders).map(folder=>[folder.id,folder]));const breadcrumbs=[];let cursor=currentFolder;while(cursor){breadcrumbs.unshift(cursor);cursor=cursor.parentFolderId?byId.get(cursor.parentFolderId)??null:null;}return{project:scope.project,folders:filters.archive==="archived"&&!filters.folderId?folders:folders.filter(folder=>folder.parentFolderId===(filters.folderId??"")),availableFolders:activeFolders,files,currentFolder,breadcrumbs,summary,canManage:scope.ctx.canManage};}

export async function createStudioProjectFolder(projectId:string,input:FolderInput){const scope=await project(projectId,true);const parent=await folderRow(scope,input.parentFolderId,true);const parentExternalId=requireDriveFolder(parent,scope);const identity=`${scope.ctx.organizationId}:${projectId}:${input.parentFolderId||"root"}:${normalized(input.name)}`;const id=stableFolderId(identity);await duplicateFolder(scope,id,input.parentFolderId,input.name);const props={arz_entity_type:"custom_folder",organization_id:scope.ctx.organizationId,project_id:projectId,logical_folder_id:id};let external=await findDriveFolder(scope.ctx.organizationId,parentExternalId,{logical_folder_id:id});if(!external)external=await googleDriveStorageProvider.createFolder(scope.ctx.organizationId,input.name,parentExternalId,props);const{error}=await scope.supabase.from("studio_project_folders").insert({id,organization_id:scope.ctx.organizationId,project_id:projectId,parent_folder_id:input.parentFolderId||null,name:input.name,normalized_name:normalized(input.name),created_by:scope.ctx.userId,updated_by:scope.ctx.userId,storage_provider:"google_drive",external_folder_id:external.id,external_parent_folder_id:parentExternalId,sync_status:"synced",sync_error_code:null,last_synced_at:new Date().toISOString()});if(error?.code==="23505"){const{data}=await scope.supabase.from("studio_project_folders").select("id,external_folder_id").eq("id",id).eq("external_folder_id",external.id).maybeSingle();if(data)return;}if(error)throw new StudioFileError("partial_sync","Drive klasörü oluşturuldu ancak Studio eşlemesi kaydedilemedi. Aynı adla yeniden deneyin.");}
export async function renameStudioProjectFolder(projectId:string,folderId:string,name:string){const scope=await project(projectId,true);const row=await folderRow(scope,folderId);if(row.is_system)throw new StudioFileError("forbidden","Sistem klasörleri yeniden adlandırılamaz.");const externalId=requireDriveFolder(row,scope);await duplicateFolder(scope,row.id,row.parent_folder_id??"",name);const external=await googleDriveStorageProvider.renameFolder(scope.ctx.organizationId,externalId,name);await persistAfterDrive(scope,"studio_project_folders",row.id,{name,normalized_name:normalized(name),external_parent_folder_id:external.parents[0]??row.external_parent_folder_id});}
export async function moveStudioProjectFolder(projectId:string,folderId:string,parentFolderId:string){const scope=await project(projectId,true);const row=await folderRow(scope,folderId);if(row.is_system)throw new StudioFileError("forbidden","Sistem klasörleri taşınamaz.");const destination=await folderRow(scope,parentFolderId,true);if(destination?.id===row.id)throw new StudioFileError("invalid_folder","Klasör kendi altına taşınamaz.");let cursor=destination;while(cursor){if(cursor.id===row.id)throw new StudioFileError("invalid_folder","Klasör kendi alt klasörüne taşınamaz.");cursor=cursor.parent_folder_id?await folderRow(scope,cursor.parent_folder_id):null;}await duplicateFolder(scope,row.id,parentFolderId,row.name);const externalId=requireDriveFolder(row,scope);const destinationExternalId=requireDriveFolder(destination,scope);const external=await googleDriveStorageProvider.moveFolder(scope.ctx.organizationId,externalId,row.external_parent_folder_id??"",destinationExternalId);await persistAfterDrive(scope,"studio_project_folders",row.id,{parent_folder_id:parentFolderId||null,external_parent_folder_id:external.parents[0]??destinationExternalId});}
export async function setStudioProjectFolderArchived(projectId:string,folderId:string,archived:boolean){const scope=await project(projectId,true);const row=await folderRow(scope,folderId);if(row.is_system)throw new StudioFileError("forbidden","Sistem klasörleri arşivlenemez.");const externalId=requireDriveFolder(row,scope);if(archived){const archive=await systemFolder(scope,"08 Arşiv");const archiveExternal=requireDriveFolder(archive,scope);const external=await googleDriveStorageProvider.archiveFolder(scope.ctx.organizationId,externalId,row.external_parent_folder_id??"",archiveExternal);await persistAfterDrive(scope,"studio_project_folders",row.id,{is_archived:true,previous_parent_folder_id:row.parent_folder_id,previous_external_parent_folder_id:row.external_parent_folder_id,parent_folder_id:archive.id,external_parent_folder_id:external.parents[0]??archiveExternal});return;}let destination:DbFolder|null=null;if(row.previous_parent_folder_id)destination=await folderRow(scope,row.previous_parent_folder_id,true).catch(()=>null);if(destination?.is_archived)destination=null;const destinationExternal=requireDriveFolder(destination,scope);const verified=destination?await googleDriveStorageProvider.verifyFolderExists(scope.ctx.organizationId,destinationExternal):{exists:true};if(!verified.exists){destination=await systemFolder(scope,"01 Proje");}const finalExternal=requireDriveFolder(destination,scope);await duplicateFolder(scope,row.id,destination?.id??"",row.name);const external=await googleDriveStorageProvider.restoreFolder(scope.ctx.organizationId,externalId,row.external_parent_folder_id??"",finalExternal);await persistAfterDrive(scope,"studio_project_folders",row.id,{is_archived:false,parent_folder_id:destination?.id??null,external_parent_folder_id:external.parents[0]??finalExternal,previous_parent_folder_id:null,previous_external_parent_folder_id:null});}

export async function reserveStudioProjectFile(input:FileReservationInput&{extension:string;mimeType:string}){const scope=await project(input.projectId,true);await folderRow(scope,input.folderId,true);const id=crypto.randomUUID();const path=buildStudioFilePath(scope.ctx.organizationId,input.projectId,id,input.originalFileName);const{error}=await scope.supabase.from("studio_project_files").insert({id,organization_id:scope.ctx.organizationId,project_id:input.projectId,folder_id:input.folderId||null,display_name:input.originalFileName,original_file_name:input.originalFileName,normalized_file_name:normalized(input.originalFileName),extension:input.extension,mime_type:input.mimeType,file_size:input.fileSize,storage_bucket:STUDIO_FILES_BUCKET,storage_path:path,category:input.category,status:"uploading",uploaded_by:scope.ctx.userId,updated_by:scope.ctx.userId});if(error)throw normalizeFileError(error);try{return{id,...await createSignedFileUpload(path)};}catch(error){await scope.supabase.from("studio_project_files").update({status:"failed"}).eq("id",id);throw error;}}
export async function finalizeStudioProjectFile(projectId:string,fileId:string){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);if(row.storage_provider==="google_drive")throw new StudioFileError("storage","Google Drive yüklemesi güvenli finalize action ile tamamlanmalıdır.");const{data,error}=await scope.supabase.from("studio_project_files").update({status:"ready"}).eq("id",fileId).eq("status","uploading").select("id").maybeSingle();if(error||!data){await cleanupStorageObject(row.storage_path);throw normalizeFileError(error??new Error("finalize"));}}
export async function markStudioProjectFileFailed(projectId:string,fileId:string){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);await scope.supabase.from("studio_project_files").update({status:"failed",sync_status:"error",sync_error_code:"upload_failed"}).eq("id",fileId);if(row.storage_provider==="supabase")await cleanupStorageObject(row.storage_path);}
export async function getStudioProjectFileById(projectId:string,fileId:string){if(!isStudioFileId(fileId))return null;const scope=await project(projectId);const{data,error}=await scope.supabase.from("studio_project_files").select(fileSelect+",organization_id,storage_path").eq("id",fileId).eq("project_id",projectId).eq("organization_id",scope.ctx.organizationId).maybeSingle();if(error)throw normalizeFileError(error);if(!data)return null;const row=data as unknown as DbFile;return{file:mapFile(row,scope.ctx.canManage),storagePath:row.storage_path,provider:row.storage_provider??"supabase",externalFileId:row.external_file_id??null};}
export async function updateStudioProjectFileMetadata(projectId:string,fileId:string,input:FileMetadataInput){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);const{data,error}=await scope.supabase.from("studio_project_files").update({description:input.description||null,category:input.category}).eq("id",row.id).select("id").maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Dosya bulunamadı.");}
async function readyDriveVersions(scope:ProjectContext,fileId:string){const{data,error}=await scope.supabase.from("studio_project_file_versions").select("id,version_number,revision_code,external_file_id,external_parent_folder_id").eq("organization_id",scope.ctx.organizationId).eq("project_id",scope.project.id).eq("file_id",fileId).eq("status","ready").eq("storage_provider","google_drive").order("version_number");if(error)throw normalizeFileError(error);return data??[];}
async function markVersionBatchError(scope:ProjectContext,fileId:string,code:string){await scope.supabase.from("studio_project_files").update({sync_status:"action_required",sync_error_code:code}).eq("id",fileId).eq("organization_id",scope.ctx.organizationId);}
async function moveHistoricalVersions(scope:ProjectContext,row:DbFile,destinationExternal:string){const versions=await readyDriveVersions(scope,row.id);for(const version of versions){if(!version.external_file_id||version.external_file_id===row.external_file_id||version.external_parent_folder_id===destinationExternal)continue;await googleDriveStorageProvider.moveFile(scope.ctx.organizationId,version.external_file_id,version.external_parent_folder_id??row.external_parent_folder_id!,destinationExternal);}const{error}=await scope.supabase.from("studio_project_file_versions").update({external_parent_folder_id:destinationExternal,sync_status:"synced",sync_error_code:null,updated_at:new Date().toISOString()}).eq("file_id",row.id).eq("status","ready");if(error)throw error;}
export async function renameStudioProjectFile(projectId:string,fileId:string,name:string){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);requireDriveFile(row);const desired=desiredFileName(name,row.extension);await duplicateFile(scope,row,row.folder_id??"",desired);const versions=await readyDriveVersions(scope,fileId);try{for(const version of versions){if(!version.external_file_id)continue;const physical=physicalVersionName(desired,version.version_number,version.revision_code);await googleDriveStorageProvider.renameFile(scope.ctx.organizationId,version.external_file_id,physical);}const{error}=await scope.supabase.from("studio_project_file_versions").update({sync_status:"synced",sync_error_code:null,updated_at:new Date().toISOString()}).eq("file_id",fileId).eq("status","ready");if(error)throw error;const external=await getDriveFileMetadata(scope.ctx.organizationId,row.external_file_id!);await persistAfterDrive(scope,"studio_project_files",row.id,{display_name:desired,normalized_file_name:normalized(desired),...syncValues(external)});}catch{await markVersionBatchError(scope,fileId,"version_rename_partial");throw new StudioFileError("partial_sync","Bazı sürümler yeniden adlandırıldı; eşitleme onarımı gerekiyor.");}}
export async function moveStudioProjectFile(projectId:string,fileId:string,folderId:string){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);requireDriveFile(row);const destination=await folderRow(scope,folderId);if(destination.is_archived)throw new StudioFileError("invalid_folder","Arşivlenmiş klasöre normal taşıma yapılamaz.");const destinationExternal=requireDriveFolder(destination,scope);await duplicateFile(scope,row,destination.id,row.display_name);const versions=await readyDriveVersions(scope,fileId);try{for(const version of versions){if(!version.external_file_id||version.external_parent_folder_id===destinationExternal)continue;await googleDriveStorageProvider.moveFile(scope.ctx.organizationId,version.external_file_id,version.external_parent_folder_id??row.external_parent_folder_id!,destinationExternal);}const{error}=await scope.supabase.from("studio_project_file_versions").update({external_parent_folder_id:destinationExternal,sync_status:"synced",sync_error_code:null,updated_at:new Date().toISOString()}).eq("file_id",fileId).eq("status","ready");if(error)throw error;const external=await getDriveFileMetadata(scope.ctx.organizationId,row.external_file_id!);await persistAfterDrive(scope,"studio_project_files",row.id,{folder_id:destination.id,external_parent_folder_id:destinationExternal,...syncValues(external)});}catch{await markVersionBatchError(scope,fileId,"version_move_partial");throw new StudioFileError("partial_sync","Bazı sürümler taşındı; eşitleme onarımı gerekiyor.");}}
export async function setStudioProjectFileArchived(projectId:string,fileId:string,archived:boolean){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);if(row.storage_provider!=="google_drive"){const{error}=await scope.supabase.from("studio_project_files").update({is_archived:archived}).eq("id",row.id);if(error)throw normalizeFileError(error);return;}requireDriveFile(row);try{if(archived){const archive=await systemFolder(scope,"08 Arşiv");const archiveExternal=requireDriveFolder(archive,scope);await moveHistoricalVersions(scope,row,archiveExternal);const external=await googleDriveStorageProvider.archiveFile(scope.ctx.organizationId,row.external_file_id!,row.external_parent_folder_id!,archiveExternal);await persistAfterDrive(scope,"studio_project_files",row.id,{is_archived:true,previous_folder_id:row.folder_id,previous_external_parent_folder_id:row.external_parent_folder_id,folder_id:archive.id,external_parent_folder_id:external.parents[0]??archiveExternal,...syncValues(external)});return;}let destination:DbFolder|null=null;if(row.previous_folder_id)destination=await folderRow(scope,row.previous_folder_id,true).catch(()=>null);if(!destination||destination.is_archived||!destination.external_folder_id||(await googleDriveStorageProvider.verifyFolderExists(scope.ctx.organizationId,destination.external_folder_id)).exists===false)destination=await systemFolder(scope,"01 Proje");const destinationExternal=requireDriveFolder(destination,scope);await duplicateFile(scope,row,destination.id,row.display_name);const fallbackUsed=destination.id!==row.previous_folder_id;await moveHistoricalVersions(scope,row,destinationExternal);const external=await googleDriveStorageProvider.restoreFile(scope.ctx.organizationId,row.external_file_id!,row.external_parent_folder_id!,destinationExternal);await persistAfterDrive(scope,"studio_project_files",row.id,{is_archived:false,folder_id:destination.id,external_parent_folder_id:external.parents[0]??destinationExternal,previous_folder_id:null,previous_external_parent_folder_id:null,...syncValues(external)});return{fallbackUsed};}catch(error){await markVersionBatchError(scope,fileId,archived?"version_archive_partial":"version_restore_partial");if(error instanceof StudioFileError)throw error;throw new StudioFileError("partial_sync","Bazı sürümler taşındı; eşitleme onarımı gerekiyor.");}}

export async function verifyStudioProjectFile(projectId:string,fileId:string){const scope=await project(projectId,true);const row=await fileRow(scope,fileId);requireDriveFile(row);const verification=await googleDriveStorageProvider.verifyFileExists(scope.ctx.organizationId,row.external_file_id!);if(!verification.exists||!verification.metadata){await markFileError(scope,row.id,"external_file_missing");throw new StudioFileError("not_found","Google Drive dosyası bulunamadı.");}const value=verification.metadata;const correctParent=value.parents.includes(row.external_parent_folder_id!);if(!correctParent){await markFileError(scope,row.id,"external_parent_mismatch");throw new StudioFileError("storage","Dosyanın Google Drive klasör konumu Studio kaydıyla eşleşmiyor.");}await persistAfterDrive(scope,"studio_project_files",row.id,{display_name:value.name,original_file_name:value.name,normalized_file_name:normalized(value.name),...syncValues(value)});return value;}
export async function verifyStudioProjectFolder(projectId:string,folderId:string){const scope=await project(projectId,true);const row=await folderRow(scope,folderId);const externalId=requireDriveFolder(row,scope);const verification=await googleDriveStorageProvider.verifyFolderExists(scope.ctx.organizationId,externalId);if(!verification.exists||!verification.metadata){await markFolderError(scope,row.id,"external_folder_missing");throw new StudioFileError("not_found","Google Drive klasörü bulunamadı.");}const value=verification.metadata;const identityOk=row.is_system?value.appProperties.logical_folder_id===row.id:value.appProperties.organization_id===scope.ctx.organizationId&&value.appProperties.project_id===scope.project.id;if(!value.parents.includes(row.external_parent_folder_id??"")||!identityOk){await markFolderError(scope,row.id,!identityOk?"external_identity_mismatch":"external_parent_mismatch");throw new StudioFileError("storage","Google Drive klasör eşlemesi Studio kaydıyla eşleşmiyor.");}await persistAfterDrive(scope,"studio_project_folders",row.id,{name:value.name,normalized_name:normalized(value.name),external_parent_folder_id:value.parents[0]??row.external_parent_folder_id});return value;}

export async function createStudioProjectFileDownload(projectId:string,fileId:string){const scope=await project(projectId);const row=await fileRow(scope,fileId);if(row.status!=="ready")throw new StudioFileError("not_found","Dosya indirilmeye hazır değil.");const fileName=safeDownloadName(row.original_file_name);if(row.storage_provider==="google_drive"){requireDriveFile(row);const verification=await googleDriveStorageProvider.verifyFileExists(scope.ctx.organizationId,row.external_file_id!);if(!verification.exists||!verification.metadata||verification.metadata.trashed)throw new StudioFileError("not_found","Google Drive dosyası bulunamadı.");if(!verification.metadata.parents.includes(row.external_parent_folder_id!))throw new StudioFileError("forbidden","Dosyayı indirme yetkiniz bulunmuyor.");return{kind:"stream" as const,response:await googleDriveStorageProvider.downloadFile(scope.ctx.organizationId,row.external_file_id!),fileName};}return{kind:"redirect" as const,url:await createSignedFileDownload(row.storage_path,fileName),fileName};}
