import "server-only";
import {getStudioContext,type StudioRole} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {buildStudioFilePath,safeDownloadName} from "./file-paths";
import {normalizeFileError,StudioFileError} from "./file-errors";
import {mapFile,mapFolder,formatBytes,type FileRow,type FolderRow} from "./file-mappers";
import {createSignedFileDownload,createSignedFileUpload,cleanupStorageObject} from "./file-storage";
import {downloadDriveFile} from "./storage/google-drive-provider";
import {STUDIO_FILES_BUCKET} from "./file-constants";
import type {FileMetadataInput,FileReservationInput,FolderInput,StudioFileQuery} from "./file-types";
import {isStudioFileId} from "./file-validation";

const folderSelect="id,project_id,parent_folder_id,name,sort_order,is_system,is_archived,created_at,updated_at";
const fileSelect="id,project_id,folder_id,display_name,original_file_name,extension,mime_type,file_size,description,category,status,is_archived,uploaded_by,created_at,updated_at,storage_provider,external_file_id,uploader:profiles!studio_project_files_uploaded_by_fkey(id,full_name)";
async function context(owner=false){const value=await getStudioContext();if(!value?.user||!value.membership)throw new StudioFileError("unauthorized","Oturum gerekli.");const role=value.membership.role as StudioRole;if(owner&&role!=="owner")throw new StudioFileError("forbidden","Bu işlem yalnızca Studio sahibi tarafından yapılabilir.");return{userId:value.user.id,organizationId:value.membership.organization_id,canManage:role==="owner"};}
async function project(projectId:string,owner=false){if(!isStudioFileId(projectId))throw new StudioFileError("not_found","Proje bulunamadı.");const ctx=await context(owner);const supabase=await createStudioServerClient();const{data,error}=await supabase.from("studio_projects").select("id,code,name").eq("id",projectId).eq("organization_id",ctx.organizationId).maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Proje bulunamadı.");return{ctx,supabase,project:data};}
async function assertFolder(supabase:Awaited<ReturnType<typeof createStudioServerClient>>,organizationId:string,projectId:string,folderId:string){if(!folderId)return null;if(!isStudioFileId(folderId))throw new StudioFileError("invalid_folder","Klasör bulunamadı.");const{data}=await supabase.from("studio_project_folders").select("id").eq("id",folderId).eq("organization_id",organizationId).eq("project_id",projectId).maybeSingle();if(!data)throw new StudioFileError("invalid_folder","Klasör bulunamadı.");return data.id as string;}
export async function getStudioFileAccess(){const ctx=await context();return{canManage:ctx.canManage};}
export async function initializeStudioProjectFolders(projectId:string){const{ctx,supabase}=await project(projectId);const{error}=await supabase.rpc("studio_initialize_project_folders",{target_project_id:projectId});if(error){console.error("Studio folders initialization failed",{code:error.code,organizationId:ctx.organizationId});throw normalizeFileError(error);}}
export async function getStudioProjectFolders(projectId:string,archive:StudioFileQuery["archive"]="active"){const{ctx,supabase}=await project(projectId);let query=supabase.from("studio_project_folders").select(folderSelect).eq("organization_id",ctx.organizationId).eq("project_id",projectId).order("sort_order").order("name");if(archive!=="all")query=query.eq("is_archived",archive==="archived");const{data,error}=await query;if(error)throw normalizeFileError(error);return(data as FolderRow[]).map(row=>mapFolder(row,ctx.canManage));}
export async function getStudioProjectFiles(projectId:string,filters:StudioFileQuery={}){const{ctx,supabase}=await project(projectId);let query=supabase.from("studio_project_files").select(fileSelect).eq("organization_id",ctx.organizationId).eq("project_id",projectId).order("created_at",{ascending:false});if(filters.archive!=="all")query=query.eq("is_archived",filters.archive==="archived");if(filters.folderId)query=query.eq("folder_id",filters.folderId);else query=query.is("folder_id",null);if(filters.category)query=query.eq("category",filters.category);if(filters.extension)query=query.eq("extension",filters.extension);if(filters.query){const safe=filters.query.replace(/[,%()"'*:]/g," ").trim();if(safe)query=query.ilike("display_name",`%${safe}%`);}const{data,error}=await query;if(error)throw normalizeFileError(error);return(data as unknown as FileRow[]).map(row=>mapFile(row,ctx.canManage));}
export async function getStudioProjectFileSummary(projectId:string){const{ctx,supabase}=await project(projectId);const[{data:files,error:fileError},{count:folderCount,error:folderError}]=await Promise.all([supabase.from("studio_project_files").select("file_size").eq("organization_id",ctx.organizationId).eq("project_id",projectId).eq("is_archived",false).eq("status","ready"),supabase.from("studio_project_folders").select("id",{count:"exact",head:true}).eq("organization_id",ctx.organizationId).eq("project_id",projectId).eq("is_archived",false)]);if(fileError)throw normalizeFileError(fileError);if(folderError)throw normalizeFileError(folderError);const bytes=(files??[]).reduce((sum,row)=>sum+Number(row.file_size),0);return{fileCount:files?.length??0,folderCount:folderCount??0,storageBytes:bytes,storageLabel:formatBytes(bytes)};}
export async function getStudioProjectFileWorkspace(projectId:string,filters:StudioFileQuery={}){await initializeStudioProjectFolders(projectId);const{ctx,project:projectRow}=await project(projectId);const[folders,files,activeFolders,summary]=await Promise.all([getStudioProjectFolders(projectId,filters.archive),getStudioProjectFiles(projectId,filters),getStudioProjectFolders(projectId,"active"),getStudioProjectFileSummary(projectId)]);let currentFolder=null;if(filters.folderId){currentFolder=folders.find(folder=>folder.id===filters.folderId)??null;if(!currentFolder)throw new StudioFileError("not_found","Klasör bulunamadı.");}return{project:projectRow,folders:folders.filter(folder=>folder.parentFolderId===(filters.folderId??"")),availableFolders:activeFolders,files,currentFolder,breadcrumbs:currentFolder?[currentFolder]:[],summary,canManage:ctx.canManage};}
export async function createStudioProjectFolder(projectId:string,input:FolderInput){const{ctx,supabase}=await project(projectId,true);await assertFolder(supabase,ctx.organizationId,projectId,input.parentFolderId);const{error}=await supabase.from("studio_project_folders").insert({organization_id:ctx.organizationId,project_id:projectId,parent_folder_id:input.parentFolderId||null,name:input.name,normalized_name:input.name.toLocaleLowerCase("tr-TR"),created_by:ctx.userId,updated_by:ctx.userId});if(error)throw normalizeFileError(error);}
export async function renameStudioProjectFolder(projectId:string,folderId:string,name:string){const{ctx,supabase}=await project(projectId,true);const{data,error}=await supabase.from("studio_project_folders").update({name,normalized_name:name.toLocaleLowerCase("tr-TR")}).eq("id",folderId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).eq("is_system",false).select("id").maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Klasör bulunamadı veya sistem klasörü değiştirilemez.");}
export async function moveStudioProjectFolder(projectId:string,folderId:string,parentFolderId:string){const{ctx,supabase}=await project(projectId,true);await assertFolder(supabase,ctx.organizationId,projectId,parentFolderId);const{data,error}=await supabase.from("studio_project_folders").update({parent_folder_id:parentFolderId||null}).eq("id",folderId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).eq("is_system",false).select("id").maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Klasör bulunamadı.");}
export async function setStudioProjectFolderArchived(projectId:string,folderId:string,archived:boolean){const{ctx,supabase}=await project(projectId,true);const{data,error}=await supabase.from("studio_project_folders").update({is_archived:archived}).eq("id",folderId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).eq("is_system",false).select("id").maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Klasör bulunamadı veya sistem klasörü arşivlenemez.");}
export async function reserveStudioProjectFile(input:FileReservationInput&{extension:string;mimeType:string}){const{ctx,supabase}=await project(input.projectId,true);await assertFolder(supabase,ctx.organizationId,input.projectId,input.folderId);const id=crypto.randomUUID();const path=buildStudioFilePath(ctx.organizationId,input.projectId,id,input.originalFileName);const{error}=await supabase.from("studio_project_files").insert({id,organization_id:ctx.organizationId,project_id:input.projectId,folder_id:input.folderId||null,display_name:input.originalFileName,original_file_name:input.originalFileName,normalized_file_name:input.originalFileName.toLocaleLowerCase("tr-TR"),extension:input.extension,mime_type:input.mimeType,file_size:input.fileSize,storage_bucket:STUDIO_FILES_BUCKET,storage_path:path,category:input.category,status:"uploading",uploaded_by:ctx.userId,updated_by:ctx.userId});if(error)throw normalizeFileError(error);try{return{id,...await createSignedFileUpload(path)};}catch(error){await supabase.from("studio_project_files").update({status:"failed"}).eq("id",id).eq("organization_id",ctx.organizationId);throw error;}}
export async function finalizeStudioProjectFile(projectId:string,fileId:string){const{ctx,supabase}=await project(projectId,true);const{data:reservation}=await supabase.from("studio_project_files").select("storage_path").eq("id",fileId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).eq("status","uploading").maybeSingle();if(!reservation)throw new StudioFileError("not_found","Yükleme kaydı bulunamadı.");const{data,error}=await supabase.from("studio_project_files").update({status:"ready"}).eq("id",fileId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).eq("status","uploading").select("id").maybeSingle();if(error||!data){await cleanupStorageObject(reservation.storage_path);await supabase.from("studio_project_files").update({status:"failed"}).eq("id",fileId).eq("organization_id",ctx.organizationId);throw normalizeFileError(error??new Error("finalize"));}}
export async function markStudioProjectFileFailed(projectId:string,fileId:string){const{ctx,supabase}=await project(projectId,true);const{data}=await supabase.from("studio_project_files").update({status:"failed"}).eq("id",fileId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).select("storage_path").maybeSingle();if(data?.storage_path)await cleanupStorageObject(data.storage_path);}
export async function getStudioProjectFileById(projectId:string,fileId:string){if(!isStudioFileId(fileId))return null;const{ctx,supabase}=await project(projectId);const{data,error}=await supabase.from("studio_project_files").select(fileSelect+",storage_path").eq("id",fileId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).maybeSingle();if(error)throw normalizeFileError(error);return data?{file:mapFile(data as unknown as FileRow,ctx.canManage),storagePath:(data as unknown as {storage_path:string}).storage_path,provider:(data as unknown as FileRow).storage_provider??"supabase",externalFileId:(data as unknown as FileRow).external_file_id??null}:null;}
export async function updateStudioProjectFileMetadata(projectId:string,fileId:string,input:FileMetadataInput){const{ctx,supabase}=await project(projectId,true);await assertFolder(supabase,ctx.organizationId,projectId,input.folderId);const{data,error}=await supabase.from("studio_project_files").update({display_name:input.displayName,normalized_file_name:input.displayName.toLocaleLowerCase("tr-TR"),description:input.description||null,category:input.category,folder_id:input.folderId||null}).eq("id",fileId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).select("id").maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Dosya bulunamadı.");}
export async function setStudioProjectFileArchived(projectId:string,fileId:string,archived:boolean){const{ctx,supabase}=await project(projectId,true);const{data,error}=await supabase.from("studio_project_files").update({is_archived:archived}).eq("id",fileId).eq("project_id",projectId).eq("organization_id",ctx.organizationId).select("id").maybeSingle();if(error)throw normalizeFileError(error);if(!data)throw new StudioFileError("not_found","Dosya bulunamadı.");}
export async function createStudioProjectFileDownload(projectId:string,fileId:string){const result=await getStudioProjectFileById(projectId,fileId);if(!result||result.file.status!=="ready")throw new StudioFileError("not_found","Dosya indirilmeye hazır değil.");if(result.provider==="google_drive"&&result.externalFileId){const {ctx}=await project(projectId);return downloadDriveFile(ctx.organizationId,result.externalFileId);}return createSignedFileDownload(result.storagePath,safeDownloadName(result.file.originalFileName));}
