'use client';
import {useEffect,useMemo,useState} from 'react';
import Image from 'next/image';

type Img={src:string;alt:string;contain?:boolean};
type Project={slug:string;title:string;titleLines:string[];category:string;location:string;year:string;services:string[];cover:string;coverAlt:string;description:string;detailParagraphs:string[];images:Img[]};
type Managed={id:string;slugTr:string;slugEn:string;published:boolean;order:number;tr:Project;en:Project};
const blankProject=():Project=>({slug:'',title:'',titleLines:[''],category:'',location:'',year:new Date().getFullYear().toString(),services:[],cover:'',coverAlt:'',description:'',detailParagraphs:[''],images:[]});
const blankManaged=():Managed=>({id:crypto.randomUUID(),slugTr:'',slugEn:'',published:true,order:999,tr:blankProject(),en:blankProject()});
function slugify(v:string){return v.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
export default function AdminDashboard(){const [items,setItems]=useState<Managed[]>([]);const [selected,setSelected]=useState<Managed|null>(null);const [tab,setTab]=useState<'tr'|'en'>('tr');const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);
async function load(){setLoading(true);const r=await fetch('/api/admin/projects');if(r.ok)setItems(await r.json());setLoading(false)}useEffect(()=>{load()},[]);
const p=selected?.[tab]; const changed=useMemo(()=>selected,[selected]);
function updateRoot<K extends keyof Managed>(key:K,value:Managed[K]){setSelected(s=>s?{...s,[key]:value}:s)}
function update<K extends keyof Project>(key:K,value:Project[K]){setSelected(s=>s?{...s,[tab]:{...s[tab],[key]:value}}:s)}
async function save(){if(!selected)return;const slugTr=selected.slugTr||slugify(selected.tr.title);const slugEn=selected.slugEn||slugify(selected.en.title||selected.tr.title);const payload={...selected,slugTr,slugEn,tr:{...selected.tr,slug:slugTr,titleLines:selected.tr.titleLines.filter(Boolean),services:selected.tr.services.filter(Boolean),detailParagraphs:selected.tr.detailParagraphs.filter(Boolean)},en:{...selected.en,slug:slugEn,titleLines:selected.en.titleLines.filter(Boolean),services:selected.en.services.filter(Boolean),detailParagraphs:selected.en.detailParagraphs.filter(Boolean)}};setStatus('Kaydediliyor…');const r=await fetch('/api/admin/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});setStatus(r.ok?'Kaydedildi.':'Kaydetme hatası');if(r.ok){setSelected(payload);await load()}}
async function remove(){if(!selected||!confirm('Bu projeyi silmek istediğine emin misin?'))return;await fetch('/api/admin/projects',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id})});setSelected(null);await load()}
async function upload(file:File,kind:'cover'|'gallery'){if(!selected)return;setStatus('Görsel yükleniyor…');const fd=new FormData();fd.append('file',file);fd.append('slug',selected.slugTr||slugify(selected.tr.title)||'project');const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const data=await r.json();if(!r.ok){setStatus(data.error||'Yükleme hatası');return}if(kind==='cover')update('cover',data.url);else update('images',[...(p?.images||[]),{src:data.url,alt:p?.title||'Project image'}]);setStatus('Görsel yüklendi.')}
async function downloadBackup(){setStatus('Yedek hazırlanıyor…');const r=await fetch('/api/admin/backup');if(!r.ok){setStatus('Yedek alınamadı');return}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ARZ-Backup-${new Date().toISOString().slice(0,10)}.zip`;a.click();URL.revokeObjectURL(url);setStatus('Yedek indirildi. Güvenli bir yerde saklayın.');}
async function restoreBackup(file:File){if(!confirm('Bu yedek mevcut admin proje verilerini ve yüklenen görselleri değiştirecek. Devam edilsin mi?'))return;setStatus('Yedek geri yükleniyor…');const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/backup',{method:'POST',body:fd});const data=await r.json();if(!r.ok){setStatus(data.error||'Yedek geri yüklenemedi');return}setSelected(null);await load();setStatus(`Yedek geri yüklendi: ${data.projects ?? 0} admin kaydı, ${data.images ?? 0} görsel, ${data.files} dosya. data/projects.ts de geri yüklendi.`);}
async function logout(){await fetch('/api/admin/logout',{method:'POST'});location.reload()}
return <div className="min-h-screen lg:grid lg:grid-cols-[320px_1fr]">
<aside className="border-r border-white/10 bg-black/40 p-5 lg:min-h-screen"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[.35em] text-white/35">ARZ Mimarlık</p><h1 className="mt-2 text-2xl font-light">Projeler</h1></div><button onClick={logout} className="text-xs text-white/45 hover:text-white">Çıkış</button></div><button onClick={()=>{setSelected(blankManaged());setTab('tr')}} className="mt-8 w-full border border-white/20 px-4 py-3 text-sm hover:bg-white hover:text-black">+ Yeni proje</button><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={downloadBackup} className="border border-white/15 px-3 py-2 text-xs text-white/70 hover:bg-white/10">Yedek indir</button><label className="cursor-pointer border border-white/15 px-3 py-2 text-center text-xs text-white/70 hover:bg-white/10">Yedek yükle<input type="file" accept=".zip,application/zip" hidden onChange={e=>{const f=e.target.files?.[0];if(f)restoreBackup(f);e.currentTarget.value=''}}/></label></div><p className="mt-2 text-[10px] leading-4 text-amber-100/40">Yedek; proje verilerini, otomatik oluşturulan data/projects.ts dosyasını, public/images altındaki tüm proje görsellerini, eski yüklemeleri ve 2FA anahtarını içerir. Gizli tutun.</p><div className="mt-6 space-y-1">{loading?<p className="text-sm text-white/35">Yükleniyor…</p>:items.map(x=><button key={x.id} onClick={()=>setSelected(structuredClone(x))} className={`w-full border-l px-4 py-3 text-left ${selected?.id===x.id?'border-white bg-white/10':'border-white/10 hover:bg-white/5'}`}><span className="block text-sm">{x.tr.title}</span><span className="mt-1 block text-[10px] text-white/35">{x.tr.location} · {x.tr.year}</span></button>)}</div></aside>
<section className="p-5 md:p-10">{!selected?<div className="flex min-h-[60vh] items-center justify-center text-center text-white/35"><p>Bir proje seç veya yeni proje oluştur.</p></div>:<div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-5"><div><p className="text-[9px] uppercase tracking-[.35em] text-white/35">Proje düzenleyici</p><h2 className="mt-2 text-3xl font-light">{selected.tr.title||'Yeni proje'}</h2></div><div className="flex gap-2"><button onClick={remove} className="border border-red-400/30 px-4 py-2 text-sm text-red-300">Sil</button><button onClick={save} className="bg-white px-5 py-2 text-sm text-black">Kaydet</button></div></div>{status&&<p className="mt-4 text-sm text-white/55">{status}</p>}
<div className="mt-8 grid gap-5 md:grid-cols-3"><label className="text-xs text-white/50">Sıra<input type="number" value={selected.order} onChange={e=>updateRoot('order',Number(e.target.value))} className="field"/></label><label className="text-xs text-white/50">Türkçe slug<input value={selected.slugTr} onChange={e=>updateRoot('slugTr',slugify(e.target.value))} className="field"/></label><label className="text-xs text-white/50">İngilizce slug<input value={selected.slugEn} onChange={e=>updateRoot('slugEn',slugify(e.target.value))} className="field"/></label></div><label className="mt-5 flex items-center gap-3 text-sm"><input type="checkbox" checked={selected.published} onChange={e=>updateRoot('published',e.target.checked)}/> Yayında</label>
<div className="mt-10 flex border-b border-white/10"><button onClick={()=>setTab('tr')} className={`px-6 py-3 text-sm ${tab==='tr'?'border-b border-white text-white':'text-white/40'}`}>Türkçe</button><button onClick={()=>setTab('en')} className={`px-6 py-3 text-sm ${tab==='en'?'border-b border-white text-white':'text-white/40'}`}>English</button></div>
{p&&<div className="mt-8 space-y-7"><div className="grid gap-5 md:grid-cols-2"><Field label="Başlık" value={p.title} onChange={v=>update('title',v)}/><Field label="Başlık satırları (her satır ayrı)" value={p.titleLines.join('\n')} area onChange={v=>update('titleLines',v.split('\n'))}/><Field label="Kategori" value={p.category} onChange={v=>update('category',v)}/><Field label="Konum" value={p.location} onChange={v=>update('location',v)}/><Field label="Yıl" value={p.year} onChange={v=>update('year',v)}/><Field label="Hizmetler (her satır ayrı)" value={p.services.join('\n')} area onChange={v=>update('services',v.split('\n'))}/></div><Field label="Kısa açıklama" value={p.description} area onChange={v=>update('description',v)}/><Field label="Detay paragrafları (her paragraf ayrı satır)" value={p.detailParagraphs.join('\n')} area onChange={v=>update('detailParagraphs',v.split('\n'))}/>
<div className="border border-white/10 p-5"><h3 className="text-lg">Kapak görseli</h3>{p.cover&&<div className="relative mt-4 aspect-[16/9] max-w-xl overflow-hidden bg-white/5"><Image src={p.cover} alt={p.coverAlt||''} fill className="object-cover" unoptimized/></div>}<div className="mt-4 flex flex-wrap gap-3"><label className="cursor-pointer border border-white/20 px-4 py-2 text-sm">Görsel yükle<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'cover')}/></label><input value={p.cover} onChange={e=>update('cover',e.target.value)} placeholder="veya /images/... yolu" className="min-w-[280px] flex-1 border border-white/15 bg-transparent px-3 py-2 text-sm"/></div><Field label="Kapak alt metni" value={p.coverAlt} onChange={v=>update('coverAlt',v)}/></div>
<div className="border border-white/10 p-5"><div className="flex items-center justify-between"><h3 className="text-lg">Galeri</h3><label className="cursor-pointer border border-white/20 px-4 py-2 text-sm">Görsel ekle<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'gallery')}/></label></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{p.images.map((img,i)=><div key={`${img.src}-${i}`} className="border border-white/10 p-3"><div className="relative aspect-[4/3] overflow-hidden bg-white/5"><Image src={img.src} alt={img.alt} fill className="object-cover" unoptimized/></div><input value={img.alt} onChange={e=>{const a=[...p.images];a[i]={...a[i],alt:e.target.value};update('images',a)}} className="mt-3 w-full border border-white/10 bg-transparent px-2 py-2 text-xs"/><button onClick={()=>update('images',p.images.filter((_,n)=>n!==i))} className="mt-2 text-xs text-red-300">Kaldır</button></div>)}</div></div></div>}</div>}</section></div>}
function Field({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label className="block text-xs text-white/50">{label}{area?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className="field resize-y"/>:<input value={value} onChange={e=>onChange(e.target.value)} className="field"/>}</label>}
