"use client";
import {useState} from "react";
import {StudioBadge,StudioDrawer} from "@/components/studio/ui/StudioUiPrimitives";
import {StudioIconSurface} from "@/components/studio/ui/StudioIconSurface";
import type {ClientStage} from "@/lib/client-portal/get-client-dashboard";
const workLabels:Record<string,string>={waiting:"Bekliyor",in_progress:"Devam Ediyor",completed:"Tamamlandı",cancelled:"İptal"};
const municipalityLabels:Record<string,string>={waiting:"Bekleniyor",reviewing:"İnceleniyor",approved:"Onaylandı",revision_requested:"Revize İstendi",rejected:"Reddedildi"};
const variant=(value:string)=>value==="completed"?"success" as const:value==="in_progress"?"info" as const:value==="cancelled"?"danger" as const:"neutral" as const;
const municipalityVariant=(value:string)=>value==="approved"?"success" as const:value==="rejected"?"danger" as const:value==="revision_requested"?"warning" as const:value==="reviewing"?"info" as const:"neutral" as const;
const date=(value:string|null)=>value?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric",timeZone:"Europe/Istanbul"}).format(new Date(value)):"Belirtilmedi";
export default function ClientStagesTimeline({stages,currentId,nextId}:{stages:ClientStage[];currentId?:string;nextId?:string}){const[selected,setSelected]=useState<ClientStage|null>(null);return <><ol className="client-stage-grid">{stages.map((stage,index)=>{const isCurrent=stage.id===currentId,isNext=stage.id===nextId,completed=stage.status==="completed";return <li key={stage.id} className={`client-stage-item ${isCurrent?"is-current":""} ${completed?"is-completed":""}`}><button type="button" onClick={()=>setSelected(stage)} aria-label={`${stage.title} aşama detayını aç`}><span className="client-stage-order">{index+1}</span><StudioIconSurface icon={completed?"check":isCurrent?"activity":"clock"} tone={completed?"green":isCurrent?"blue":"slate"} size="lg"/><span className="client-stage-card-content"><span className="client-stage-card-top"><strong>{stage.title}</strong>{isCurrent?<StudioBadge variant="info">Şu anki aşama</StudioBadge>:isNext?<StudioBadge variant="outline">Sıradaki</StudioBadge>:null}</span><span className="client-stage-badges"><StudioBadge variant={variant(stage.status)}>{workLabels[stage.status]??stage.status}</StudioBadge>{stage.municipality_status?<StudioBadge variant={municipalityVariant(stage.municipality_status)}>Belediye: {municipalityLabels[stage.municipality_status]??stage.municipality_status}</StudioBadge>:null}</span>{stage.description?<span className="client-stage-description">{stage.description}</span>:null}<span className="client-stage-date">Son güncelleme: {date(stage.updated_at)}</span></span></button></li>})}</ol><StudioDrawer open={Boolean(selected)} title={selected?.title??"Aşama Detayı"} onClose={()=>setSelected(null)}>{selected?<div className="client-stage-detail"><div className="client-stage-detail__badges"><StudioBadge variant={variant(selected.status)}>{workLabels[selected.status]??selected.status}</StudioBadge>{selected.municipality_status?<StudioBadge variant={municipalityVariant(selected.municipality_status)}>Belediye: {municipalityLabels[selected.municipality_status]??selected.municipality_status}</StudioBadge>:null}</div>{selected.description?<section><h3>Açıklama</h3><p>{selected.description}</p></section>:null}<dl><div><dt>Başlangıç</dt><dd>{date(selected.started_at)}</dd></div><div><dt>Tamamlanma</dt><dd>{date(selected.completed_at)}</dd></div><div><dt>Son güncelleme</dt><dd>{date(selected.updated_at)}</dd></div></dl><p className="client-stage-detail__notice">Bu alanda yalnızca müşteriye açılmış aşama bilgileri gösterilir.</p></div>:null}</StudioDrawer></>}
