import{StudioCard,StudioEmptyState,StudioKpiCard}from"@/components/studio/StudioDesignSystem";
import{StudioBadge,StudioPageHeader,StudioSectionHeader}from"@/components/studio/ui/StudioUiPrimitives";
import type{ClientFinance}from"@/lib/client-portal/get-client-dashboard";
import type{ClientPortalProject}from"@/lib/client-portal/get-client-portal-context";
import type{ClientPaymentRequest}from"@/lib/payments/payment-request-types";
import ClientFinanceList from"./ClientFinanceList";
import ClientPaymentRequests from"./ClientPaymentRequests";

const terminal=new Set(["collected","paid","cancelled"]);
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric",timeZone:"Europe/Istanbul"}).format(new Date(value)):"Belirtilmedi";
const totals=(entries:ClientFinance[])=>Object.entries(entries.reduce<Record<string,number>>((sum,item)=>{sum[item.currency]=(sum[item.currency]??0)+Number(item.amount);return sum;},{})).map(([currency,amount])=>new Intl.NumberFormat("tr-TR",{style:"currency",currency,maximumFractionDigits:0}).format(amount)).join(" · ")||"—";

export default function ClientFinancePage({project,entries,paymentRequests,downloadableFileIds,today}:{project:ClientPortalProject;entries:ClientFinance[];paymentRequests:ClientPaymentRequest[];downloadableFileIds:string[];today:string}){const active=entries.filter(item=>item.status!=="cancelled"),paid=active.filter(item=>["collected","paid"].includes(item.status)),pending=active.filter(item=>!terminal.has(item.status)),overdue=pending.filter(item=>item.due_date&&item.due_date<today),next=pending.filter(item=>item.due_date&&item.due_date>=today).toSorted((a,b)=>String(a.due_date).localeCompare(String(b.due_date)))[0],latest=entries.toSorted((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at))[0];return <div className="client-finance-page"><StudioPageHeader eyebrow={project.name} title="Finans / Ödemeler" description="Projenize ait ödeme planını ve güncel ödeme durumlarını takip edin." icon="payments" actions={<div className="client-finance-header-meta"><StudioBadge variant="info">{entries.length} kayıt</StudioBadge><span>Son güncelleme <strong>{date(latest?.created_at)}</strong></span><span>Sıradaki vade <strong>{date(next?.due_date)}</strong></span></div>}/><ClientPaymentRequests requests={paymentRequests}/>{entries.length?<><section className="client-finance-summary" aria-label="Ödeme özeti"><StudioKpiCard label="Toplam Planlanan" value={totals(active)} detail="İptal edilmemiş kayıtlar" icon="wallet" tone="blue"/><StudioKpiCard label="Ödenen" value={totals(paid)} detail="Tamamlanmış ödeme kayıtları" icon="check" tone="green"/><StudioKpiCard label="Bekleyen" value={pending.length} detail="Kısmi kayıtlar dahil" icon="clock" tone="slate"/><StudioKpiCard label="Geciken" value={overdue.length} detail="Vadesi geçmiş açık kayıtlar" icon="warning" tone="red"/></section><StudioCard className="client-finance-surface"><StudioSectionHeader title="Ödeme Planı" description="Müşteriye açılmış ödeme ve tahsilat kayıtları." icon="payments" count={entries.length}/><ClientFinanceList projectName={project.name} entries={entries} downloadableFileIds={downloadableFileIds} today={today}/></StudioCard></>:paymentRequests.length?null:<StudioCard className="client-finance-empty"><StudioEmptyState icon="payments" title="Henüz paylaşılmış ödeme kaydı bulunmuyor." description="Ödeme planınız güncellendiğinde burada görüntülenecektir."/></StudioCard>}</div>}
