"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {StudioEmptyState,StudioToolbar} from "@/components/studio/StudioDesignSystem";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioBadge,StudioDrawer,StudioSegmentedControl} from "@/components/studio/ui/StudioUiPrimitives";
import {StudioIconSurface} from "@/components/studio/ui/StudioIconSurface";
import type {ClientNotification} from "@/lib/client-portal/get-client-dashboard";

const typeLabels:Record<string,string>={project_stage:"Proje Aşaması",official_process:"Resmî Süreç",fee:"Harç",document_ready:"Evrak",payment_reminder:"Ödeme",custom:"Bilgilendirme"};
const target=(item:ClientNotification)=>item.source_type==="project_stage"?"/client/stages":["official_process","fee","document_ready"].includes(item.source_type)?"/client/documents":item.source_type==="payment_reminder"?"/client/finance":null;
const date=(value:string)=>new Intl.DateTimeFormat("tr-TR",{dateStyle:"long",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(new Date(value));

export default function ClientNotificationsList({projectId,notifications}:{projectId:string;notifications:ClientNotification[]}){const router=useRouter(),[items,setItems]=useState(notifications),[selected,setSelected]=useState<ClientNotification|null>(null),[filter,setFilter]=useState("all"),[pending,setPending]=useState(false),[message,setMessage]=useState("");const visible=useMemo(()=>items.filter(item=>filter==="all"||!item.read_at),[filter,items]),unread=items.filter(item=>!item.read_at).length;
 async function markOne(item:ClientNotification){setSelected(item);if(item.read_at)return;setMessage("");const now=new Date().toISOString();setItems(current=>current.map(value=>value.id===item.id?{...value,read_at:now}:value));setSelected({...item,read_at:now});try{const response=await fetch("/api/client/notifications/read",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({notificationId:item.id})});if(!response.ok)throw new Error();router.refresh();}catch{setItems(current=>current.map(value=>value.id===item.id?item:value));setSelected(item);setMessage("Bildirim okundu olarak işaretlenemedi.");}}
 async function markAll(){if(!unread||pending)return;setPending(true);setMessage("");const previous=items,now=new Date().toISOString();setItems(current=>current.map(item=>item.read_at?item:{...item,read_at:now}));try{const response=await fetch("/api/client/notifications/read",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,all:true})});if(!response.ok)throw new Error();router.refresh();}catch{setItems(previous);setMessage("Bildirimler okundu olarak işaretlenemedi.");}finally{setPending(false);}}
 return <><StudioToolbar className="client-notification-toolbar"><StudioSegmentedControl ariaLabel="Bildirim görünümü" value={filter} onChange={setFilter} items={[{value:"all",label:"Tümü"},{value:"unread",label:`Okunmamış (${unread})`}]}/><button type="button" className={studioButtonClass("outline","sm")} disabled={!unread||pending} onClick={markAll}>{pending?"İşaretleniyor…":"Tümünü Okundu İşaretle"}</button><span className="client-notification-toolbar__count" aria-live="polite">{visible.length} bildirim</span></StudioToolbar>{message?<p className="client-notification-message" role="alert">{message}</p>:null}{visible.length?<ul className="client-notification-list">{visible.map(item=><li key={item.id} className={item.read_at?"is-read":"is-unread"}><StudioIconSurface icon={item.source_type==="payment_reminder"?"payments":item.source_type==="document_ready"?"file-text":"notifications"} tone={item.read_at?"slate":"blue"} size="md"/><button type="button" onClick={()=>markOne(item)} aria-label={`${item.title} bildirim detayını aç`}><span className="client-notification-title"><strong>{item.title}</strong>{!item.read_at?<span aria-label="Okunmamış bildirim"/>:null}</span><span>{item.body}</span></button><div className="client-notification-meta"><StudioBadge variant={item.read_at?"neutral":"info"}>{item.read_at?"Okundu":"Okunmamış"}</StudioBadge><span>{typeLabels[item.source_type]??item.source_type}</span><time dateTime={item.created_at}>{date(item.created_at)}</time></div></li>)}</ul>:<StudioEmptyState icon="notifications" title="Okunmamış bildiriminiz yok." description="Yeni bildirimler bu görünümde listelenecektir."/>}<StudioDrawer open={Boolean(selected)} title={selected?.title??"Bildirim Detayı"} onClose={()=>setSelected(null)}>{selected?<div className="client-notification-detail"><div><StudioBadge variant={selected.read_at?"neutral":"info"}>{selected.read_at?"Okundu":"Okunmamış"}</StudioBadge><StudioBadge variant="outline">{typeLabels[selected.source_type]??selected.source_type}</StudioBadge></div><p>{selected.body}</p><dl><div><dt>Proje</dt><dd>{selected.project_name}</dd></div><div><dt>Tarih</dt><dd>{date(selected.created_at)}</dd></div></dl>{target(selected)?<Link className={studioButtonClass("outline","sm")} href={`${target(selected)}?project=${encodeURIComponent(projectId)}`}>İlgili Bölüme Git</Link>:null}</div>:null}</StudioDrawer></>;}
