"use client";
import {useMemo,useState} from "react";
import {StudioToolbar} from "@/components/studio/StudioDesignSystem";
import {StudioBadge,StudioModal,StudioSelect} from "@/components/studio/ui/StudioUiPrimitives";
import {StudioIconSurface} from "@/components/studio/ui/StudioIconSurface";
import type {ClientRender} from "@/lib/client-portal/get-client-dashboard";
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"long",year:"numeric",timeZone:"Europe/Istanbul"}).format(new Date(value)):"Belirtilmedi";
const timestamp=(render:ClientRender)=>new Date(render.presented_at||render.created_at).getTime();
export default function ClientRenderGallery({projectName,renders}:{projectName:string;renders:ClientRender[]}){const[selected,setSelected]=useState<ClientRender|null>(null),[category,setCategory]=useState("all"),[order,setOrder]=useState("newest");const categories=useMemo(()=>Array.from(new Set(renders.map(render=>render.category).filter((value):value is string=>Boolean(value)))).sort((a,b)=>a.localeCompare(b,"tr")),[renders]);const visible=useMemo(()=>renders.filter(render=>category==="all"||render.category===category).toSorted((a,b)=>order==="newest"?timestamp(b)-timestamp(a):timestamp(a)-timestamp(b)),[category,order,renders]);return <><StudioToolbar className="client-render-toolbar"><StudioSelect label="Kategori" value={category} onChange={event=>setCategory(event.target.value)}><option value="all">Tümü</option>{categories.map(item=><option key={item} value={item}>{item}</option>)}</StudioSelect><StudioSelect label="Sıralama" value={order} onChange={event=>setOrder(event.target.value)}><option value="newest">En Yeni</option><option value="oldest">En Eski</option></StudioSelect><span className="client-render-toolbar__count" aria-live="polite">{visible.length} render</span></StudioToolbar><div className="client-render-gallery">{visible.map(render=><article key={render.id} className="client-render-gallery-card"><button type="button" onClick={()=>setSelected(render)} aria-label={`${render.title} renderını görüntüle`}><span className="client-render-gallery-preview" aria-hidden="true"><StudioIconSurface icon="render" tone="purple" size="xl"/><span>Güvenli önizleme hazırlanmadı</span></span><span className="client-render-gallery-body"><span className="client-render-gallery-top"><span>{render.category||"Render"}</span><StudioBadge variant="success">Paylaşıldı</StudioBadge></span><strong>{render.title}</strong><span className="client-render-gallery-date">{date(render.presented_at||render.created_at)}</span><span className="client-render-gallery-link">Görüntüle</span></span></button></article>)}</div><StudioModal open={Boolean(selected)} title={selected?.title??"Render Detayı"} onClose={()=>setSelected(null)}>{selected?<div className="client-render-detail"><div className="client-render-detail-preview"><StudioIconSurface icon="render" tone="purple" size="xl"/><strong>Güvenli önizleme mevcut değil</strong><p>Render dosyasına ait client-safe preview bağlantısı paylaşılmadı.</p></div><div className="client-render-detail-badges"><StudioBadge variant="success">Paylaşıldı</StudioBadge>{selected.category?<StudioBadge variant="outline">{selected.category}</StudioBadge>:null}</div>{selected.description?<section><h3>Açıklama</h3><p>{selected.description}</p></section>:null}<dl><div><dt>Proje</dt><dd>{projectName}</dd></div><div><dt>Yayın tarihi</dt><dd>{date(selected.presented_at||selected.created_at)}</dd></div></dl></div>:null}</StudioModal></>;}
