import Link from "next/link";
import {StudioCard,StudioEmptyState,StudioKpiCard} from "@/components/studio/StudioDesignSystem";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioIcon} from "@/components/studio/StudioIcons";
import {StudioBadge,StudioPageHeader,StudioSectionHeader} from "@/components/studio/ui/StudioUiPrimitives";
import {StudioIconSurface} from "@/components/studio/ui/StudioIconSurface";
import type {ClientPortalProject} from "@/lib/client-portal/get-client-portal-context";
import type {ClientDashboardData,ClientFinance,ClientNotification,ClientStage} from "@/lib/client-portal/get-client-dashboard";
import ClientProjectSelector from "./ClientProjectSelector";

const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric",timeZone:"Europe/Istanbul"}).format(new Date(value)):"Belirtilmedi";
const money=(value:number,currency:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:currency||"TRY",maximumFractionDigits:0}).format(Number(value));
const status=(value:string)=>({waiting:"Bekliyor",partial:"Kısmi",collected:"Tahsil Edildi",paid:"Ödendi",issued:"Düzenlendi",cancelled:"İptal",pending:"Bekliyor",sent:"Gönderildi",delivered:"Teslim Edildi",read:"Okundu",completed:"Tamamlandı",active:"Devam Ediyor"}[value]??value.replaceAll("_"," "));
const badge=(value:string):"neutral"|"info"|"success"|"warning"|"danger"=>["collected","paid","completed","delivered","read"].includes(value)?"success":["cancelled","rejected","failed"].includes(value)?"danger":["waiting","partial","pending"].includes(value)?"warning":"info";
function PanelError(){return <StudioEmptyState icon="warning" title="Bu bölüm yüklenemedi" description="Diğer proje bilgileriniz güvenle görüntülenmeye devam ediyor."/>}
function currentStage(stages:ClientStage[]){return stages.find(item=>!["completed","cancelled"].includes(item.status))??stages.at(-1)}

export default function ClientPortalDashboard({project,projects,userName,data}:{project:ClientPortalProject;projects:ClientPortalProject[];userName:string;data:ClientDashboardData}){
 const stage=currentStage(data.stages.data),pendingPayments=data.finance.data.filter(item=>["waiting","partial","issued"].includes(item.status)),unread=data.notifications.data.filter(item=>!item.read_at),latestRenders=data.renders.data.slice(0,3),latestFiles=data.files.data.slice(0,5),latestFinance=data.finance.data.slice(0,4);
 const activities=[...data.notifications.data.map(item=>({id:`n-${item.id}`,title:notificationTitle(item),date:item.created_at,icon:"notifications" as const})),...data.stages.data.map(item=>({id:`s-${item.id}`,title:`${item.title} aşaması güncellendi`,date:item.updated_at,icon:"activity" as const})),...data.processes.data.map(item=>({id:`p-${item.id}`,title:`${item.title} süreci güncellendi`,date:item.updated_at,icon:"file-text" as const}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).slice(0,5);
 return <div className="client-dashboard"><StudioPageHeader eyebrow="Proje takip merkezi" title={`Hoş geldiniz, ${userName}`} description={`${project.name} projenizin güncel durumunu buradan takip edebilirsiniz.`} actions={<div className="client-welcome-meta"><span>Son güncelleme <strong>{date(project.updated_at)}</strong></span>{projects.length>1?<ClientProjectSelector projects={projects}/>:null}</div>}/>
 <StudioCard className="client-progress-card"><StudioSectionHeader title="Proje İlerleme Özeti" description="Güncel aşama ve sıradaki proje adımı" icon="activity" action={<span className="client-muted-action" aria-disabled="true">Tüm Aşamalar Yakında</span>}/><div className="client-progress-layout"><div><div className="client-progress-title"><div><p>{project.code}</p><h2>{project.name}</h2></div><StudioBadge variant="info">{project.status}</StudioBadge></div><dl className="client-project-facts"><div><dt>Proje türü</dt><dd>{project.category||"Belirtilmedi"}</dd></div><div><dt>Konum</dt><dd>{project.location||"Belirtilmedi"}</dd></div><div><dt>Güncel aşama</dt><dd>{stage?.title||project.current_phase||project.stage||"Planlanıyor"}</dd></div><div><dt>Hedef tarih</dt><dd>{date(project.target_date)}</dd></div></dl></div><div className="client-progress-meter"><div><span>Genel ilerleme</span><strong>%{Math.max(0,Math.min(100,Number(project.progress)||0))}</strong></div><div role="progressbar" aria-label="Proje ilerlemesi" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.max(0,Math.min(100,Number(project.progress)||0))}><span style={{width:`${Math.max(0,Math.min(100,Number(project.progress)||0))}%`}}/></div><p>Sonraki adım <strong>{project.next_milestone||"Henüz planlanmadı"}</strong>{project.next_milestone_date?` · ${date(project.next_milestone_date)}`:""}</p></div></div></StudioCard>
 <section aria-labelledby="client-actions"><StudioSectionHeader title="Sizin İçin Öne Çıkanlar" description="Güvenli proje kayıtlarından hesaplanan güncel özet" icon="star"/><div id="client-actions" className="client-action-grid"><StudioKpiCard label="Bekleyen Ödeme" value={pendingPayments.length} detail={pendingPayments[0]?.due_date?`En yakın vade ${date(pendingPayments[0].due_date)}`:"Güncel ödeme kaydı"} icon="payments" tone="orange"/><StudioKpiCard label="Yeni Bildirim" value={unread.length} detail="Client Portal bildirimleri" icon="notifications" tone="blue"/><StudioKpiCard label="Paylaşılan Dosya" value={data.files.data.length} detail="İndirmeye açık güvenli dosyalar" icon="files" tone="green"/><StudioKpiCard label="Yaklaşan Adım" value={project.next_milestone_date?date(project.next_milestone_date):"—"} detail={project.next_milestone||"Henüz planlanmadı"} icon="calendar" tone="purple"/></div></section>
 <div className="client-content-grid"><StudioCard className="client-panel client-panel--renders"><StudioSectionHeader title="Son Renderlar" description="Müşteri görünürlüğü açılmış sunumlar" icon="render" count={data.renders.data.length}/>{data.renders.error?<PanelError/>:latestRenders.length?<div className="client-render-grid">{latestRenders.map(item=><article key={item.id} className="client-render-card"><div className="client-render-preview"><StudioIconSurface icon="render" tone="purple" size="xl"/><StudioBadge variant="success">Yayınlandı</StudioBadge></div><div><p>{item.category||"Render"}</p><h3>{item.title}</h3><span>{date(item.presented_at||item.created_at)}</span></div></article>)}</div>:<StudioEmptyState icon="render" title="Henüz paylaşılan render yok" description="Müşteriye açılan renderlar burada görüntülenecek."/>}</StudioCard>
 <StudioCard className="client-panel"><StudioSectionHeader title="Son Dosyalar ve Evraklar" description="Müşteri paylaşımına açılmış belgeler" icon="files" count={data.files.data.length}/>{data.files.error?<PanelError/>:latestFiles.length?<ul className="client-operation-list">{latestFiles.map(file=><li key={file.id}><StudioIconSurface icon={file.mime_type.startsWith("image/")?"image":"file-text"} tone="blue" size="sm"/><div><strong>{file.display_name}</strong><span>{file.category} · {date(file.created_at)}</span></div><StudioBadge variant="outline">{file.extension.toUpperCase()}</StudioBadge><Link className={studioButtonClass("ghost","sm")} href={`/client/files/${file.id}/download`}><StudioIcon name="download" className="h-4 w-4"/>İndir</Link></li>)}</ul>:<StudioEmptyState icon="files" title="Paylaşılan dosya yok" description="Müşteriye açılan hazır dosyalar burada listelenecek."/>}</StudioCard>
 <StudioCard className="client-panel"><StudioSectionHeader title="Finans / Ödemeler" description="Yalnız müşteri görünürlüğü açılmış ödeme kayıtları" icon="payments" count={data.finance.data.length}/>{data.finance.error?<PanelError/>:latestFinance.length?<ul className="client-operation-list">{latestFinance.map(item=><FinanceRow key={item.id} item={item}/>)}</ul>:<StudioEmptyState icon="payments" title="Görüntülenecek ödeme kaydı yok" description="Paylaşılan ödeme ve vade bilgileri burada görünecek."/>}</StudioCard>
 <StudioCard className="client-panel"><StudioSectionHeader title="Son Aktiviteler" description="Projenizde müşteriye açık son güncellemeler" icon="activity"/>{data.notifications.error&&data.stages.error&&data.processes.error?<PanelError/>:activities.length?<ul className="client-activity-list">{activities.map(item=><li key={item.id}><StudioIconSurface icon={item.icon} tone="slate" size="sm"/><div><strong>{item.title}</strong><span>{date(item.date)}</span></div></li>)}</ul>:<StudioEmptyState icon="activity" title="Henüz aktivite yok" description="Müşteriye açık proje güncellemeleri burada gösterilecek."/>}</StudioCard></div>
 </div>;
}
function FinanceRow({item}:{item:ClientFinance}){return <li><StudioIconSurface icon="payments" tone="green" size="sm"/><div><strong>{item.title}</strong><span>{item.due_date?`Vade ${date(item.due_date)}`:"Vade belirtilmedi"}</span></div><div className="client-finance-value"><strong>{money(item.amount,item.currency)}</strong><StudioBadge variant={badge(item.status)}>{status(item.status)}</StudioBadge></div></li>}
function notificationTitle(item:ClientNotification){return item.source_type==="render"?"Yeni render yayınlandı":item.source_type==="file"?"Yeni dosya paylaşıldı":item.source_type==="finance"?"Ödeme kaydı güncellendi":item.template_name.replaceAll("_"," ")||"Yeni bildirim"}
