begin;
drop policy if exists studio_storage_connection_owner_update on public.studio_storage_connections;
drop policy if exists studio_storage_connection_owner_write on public.studio_storage_connections;
drop policy if exists studio_storage_connection_read on public.studio_storage_connections;
drop table if exists public.studio_storage_connections;
alter table public.studio_project_files drop column if exists last_synced_at;
alter table public.studio_project_files drop column if exists sync_status;
alter table public.studio_project_files drop column if exists provider_version;
alter table public.studio_project_files drop column if exists provider_checksum;
alter table public.studio_project_files drop column if exists external_web_view_link;
alter table public.studio_project_files drop column if exists external_parent_folder_id;
alter table public.studio_project_files drop column if exists external_file_id;
alter table public.studio_project_files drop column if exists storage_provider;
alter table public.studio_project_folders drop column if exists last_synced_at;
alter table public.studio_project_folders drop column if exists sync_status;
alter table public.studio_project_folders drop column if exists external_parent_folder_id;
alter table public.studio_project_folders drop column if exists external_folder_id;
alter table public.studio_project_folders drop column if exists storage_provider;
alter table public.studio_projects drop column if exists storage_last_synced_at;
alter table public.studio_projects drop column if exists storage_sync_status;
alter table public.studio_projects drop column if exists external_project_folder_id;
alter table public.studio_projects drop column if exists storage_provider;
commit;
