"use server";
import {cookies} from "next/headers";
import {redirect} from "next/navigation";
import {randomBytes} from "node:crypto";
import {getStudioContext} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {googleDriveAuthorizationUrl,exchangeGoogleCode} from "@/lib/studio/files/storage/google-drive-auth";
import {encryptToken} from "@/lib/studio/files/storage/token-encryption";
export async function connectGoogleDrive(){const ctx=await getStudioContext();if(!ctx?.membership||ctx.membership.role!=="owner")throw new Error("Yalnızca Studio sahibi bağlayabilir.");const state=randomBytes(24).toString("base64url");(await cookies()).set("studio_google_oauth_state",state,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:600,path:"/"});redirect(googleDriveAuthorizationUrl(state));}
export async function disconnectGoogleDrive(){const ctx=await getStudioContext();if(!ctx?.membership||ctx.membership.role!=="owner")throw new Error("Yetkiniz yok.");const supabase=await createStudioServerClient();await supabase.from("studio_storage_connections").update({status:"disconnected",encrypted_access_token:null,encrypted_refresh_token:null,updated_by:ctx.user.id}).eq("organization_id",ctx.membership.organization_id).eq("provider","google_drive");}
export async function saveGoogleConnection(code:string){const ctx=await getStudioContext();if(!ctx?.membership||ctx.membership.role!=="owner")throw new Error("Yetkiniz yok.");const token=await exchangeGoogleCode(code);if(!token.refresh_token)throw new Error("Google yenileme tokenı alınamadı. Lütfen yeniden yetkilendirin.");const supabase=await createStudioServerClient();await supabase.from("studio_storage_connections").upsert({organization_id:ctx.membership.organization_id,provider:"google_drive",encrypted_access_token:encryptToken(token.access_token),encrypted_refresh_token:encryptToken(token.refresh_token),access_token_expires_at:new Date(Date.now()+token.expires_in*1000).toISOString(),status:"connected",last_connected_at:new Date().toISOString(),last_verified_at:new Date().toISOString(),created_by:ctx.user.id,updated_by:ctx.user.id},{onConflict:"organization_id,provider"});}
