/* eslint-disable @next/next/no-html-link-for-pages -- report exports require native download navigation. */
"use client";
import {useState} from "react";
import {archiveFinanceEntryAction,createFinanceEntryAction,createFinancePaymentAction,sendFinanceWhatsAppAction} from "@/app/studio/(protected)/finance/actions";
import StudioAiWritingDialog from "@/components/studio/ai/StudioAiWritingDialog";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {money} from "@/lib/studio/finance/finance-validation";
import type {FinanceDashboard,FinanceEntry,FinanceType} from "@/lib/studio/finance/finance-types";
import {StudioKpiCard} from "@/components/studio/ui";

function Metric({label,value}:{label:string;value:string}){return <StudioKpiCard label={label} value={value} icon="wallet"/>}

const labels:Record<FinanceType,string>={income:"Gelir",expense:"Gider",progress_payment:"Hakediş",invoice:"Fatura"};
const categories=[['project_fee','Proje Geliri'],['municipal_fee','Belediye Harcı'],['building_inspection','Yapı Denetim'],['personnel','Personel'],['office','Ofis'],['software','Yazılım'],['advertising','Reklam'],['tax','Vergi'],['social_security','SGK'],['electricity','Elektrik'],['water','Su'],['internet','İnternet'],['vehicle','Araç'],['fuel','Yakıt'],['other','Diğer'],['progress_payment','Hakediş'],['invoice','Fatura']] as const;

function EntryForm({data,type}:{data:FinanceDashboard;type:FinanceType}){
 const[result,setResult]=useState(""),[description,setDescription]=useState(""),[source,setSource]=useState("manual");
 const operation=type==="progress_payment"?"progress_payment":type==="invoice"?"invoice_description":"finance_summary";
 return <form action={async form=>setResult((await createFinanceEntryAction(type,form)).message)} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2 xl:grid-cols-4">
  <h2 className="text-xl font-semibold md:col-span-2 xl:col-span-4">Yeni {labels[type]}</h2>
  <label className="text-sm font-semibold">Kaynak<select name="sourceType" value={source} onChange={e=>setSource(e.target.value)} className="studio-field mt-1 w-full"><option value="manual">Manuel</option><option value="project">Proje</option><option value="quote">Teklif</option></select></label>
  <label className="text-sm font-semibold">Başlık<input name="title" required minLength={2} className="studio-field mt-1 w-full"/></label>
  <label className="text-sm font-semibold">Müşteri<select name="crmLeadId" className="studio-field mt-1 w-full"><option value="">Müşteri seçilmedi</option>{data.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  {source==="quote"?<label className="text-sm font-semibold">Teklif<select name="quoteId" required className="studio-field mt-1 w-full"><option value="">Teklif seçin</option>{data.quotes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>:<label className="text-sm font-semibold">Proje<select name="projectId" required={source==="project"} className="studio-field mt-1 w-full"><option value="">Projesiz</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
  <label className="text-sm font-semibold">Kategori<select name="category" defaultValue={type==='expense'?'other':type==='progress_payment'?'progress_payment':type==='invoice'?'invoice':'project_fee'} className="studio-field mt-1 w-full">{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
  <label className="text-sm font-semibold">Tutar<input name="amount" type="number" min="0.01" step="0.01" required className="studio-field mt-1 w-full"/></label>
  {type==='expense'?<><label className="text-sm font-semibold">Ödenen Gider<input name="paidAmount" type="number" min="0" step="0.01" defaultValue="0" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Gider Durumu<select name="status" defaultValue="waiting" className="studio-field mt-1 w-full"><option value="waiting">Bekliyor</option><option value="partial">Kısmi Ödendi</option><option value="paid">Ödendi</option><option value="cancelled">İptal</option></select></label></>:null}
  <label className="text-sm font-semibold">KDV %<input name="taxRate" type="number" min="0" max="100" step="0.01" defaultValue="20" className="studio-field mt-1 w-full"/></label>
  <label className="text-sm font-semibold">Para Birimi<select name="currency" className="studio-field mt-1 w-full"><option>TRY</option><option>USD</option><option>EUR</option><option>GBP</option></select></label>
  <label className="text-sm font-semibold">Tarih<input name="entryDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className="studio-field mt-1 w-full"/></label>
  <label className="text-sm font-semibold">Son Tarih<input name="dueDate" type="date" className="studio-field mt-1 w-full"/></label>
  {type==='invoice'?<label className="text-sm font-semibold">Fatura No<input name="invoiceNumber" maxLength={80} className="studio-field mt-1 w-full"/></label>:null}
  <label className="text-sm font-semibold">PDF / Fatura / Dekont<select name="documentFileId" className="studio-field mt-1 w-full"><option value="">Belge yok</option>{data.files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
  <label className="text-sm font-semibold md:col-span-2"><span className="flex flex-wrap items-center justify-between gap-2">Açıklama<StudioAiWritingDialog operation={operation} title={`AI ${labels[type]} Açıklaması`} triggerLabel="AI ile Oluştur" currentText={description} context={{recordType:labels[type]}} onUse={setDescription}/></span><textarea name="description" value={description} onChange={e=>setDescription(e.target.value)} maxLength={4000} className="studio-field mt-1 min-h-24 w-full"/></label>
  <label className="flex items-center gap-2 text-sm"><input name="clientVisible" value="1" type="checkbox"/>Client Portal’da görünür</label><button className={studioButtonClass("primary","md")}>Kaydet</button>{result?<p role="status" className="text-sm md:col-span-2 xl:col-span-4">{result}</p>:null}
 </form>;
}

function PaymentForm({data}:{data:FinanceDashboard}){const[result,setResult]=useState("");const incomes=data.entries.filter(x=>(x.type==='income'||x.type==='progress_payment')&&x.remaining>0);return <form action={async form=>setResult((await createFinancePaymentAction(form)).message)} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2 xl:grid-cols-4"><h2 className="text-xl font-semibold md:col-span-2 xl:col-span-4">Yeni Tahsilat</h2><label className="text-sm font-semibold xl:col-span-2">Gelir / Hakediş<select name="incomeId" required className="studio-field mt-1 w-full"><option value="">Kayıt seçin</option>{incomes.map(x=><option key={x.id} value={x.id}>{x.title} · kalan {money(x.remaining,x.currency)}</option>)}</select></label><label className="text-sm font-semibold">Tutar<input name="amount" type="number" min="0.01" step="0.01" required className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Tarih<input name="paymentDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)} className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Yöntem<select name="method" className="studio-field mt-1 w-full"><option value="bank_transfer">Havale/EFT</option><option value="cash">Nakit</option><option value="credit_card">Kredi Kartı</option><option value="other">Diğer</option></select></label><label className="text-sm font-semibold">Dekont<select name="receiptFileId" className="studio-field mt-1 w-full"><option value="">Dekont yok</option>{data.files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="text-sm font-semibold xl:col-span-2">Not<input name="note" maxLength={1000} className="studio-field mt-1 w-full"/></label><button className={studioButtonClass("primary","md")}>Tahsilatı Kaydet</button>{result?<p role="status">{result}</p>:null}</form>}

function FinanceRow({entry,canManage}:{entry:FinanceEntry;canManage:boolean}){const[result,setResult]=useState(""),[message,setMessage]=useState(entry.description);return <article className="grid gap-3 border-b p-4 text-sm last:border-0 sm:grid-cols-[minmax(0,2fr)_1fr_1fr]"><div className="min-w-0"><h3 className="break-words font-semibold">{entry.title}</h3><p className="mt-1 text-[#68706f]">{entry.projectName??'Projesiz'} · {labels[entry.type]} · {entry.entryDate}</p></div><span>{entry.status}</span><div><strong>{money(entry.amount,entry.currency)}</strong>{entry.remaining>0&&entry.type!=='expense'?<p className="text-xs">Kalan {money(entry.remaining,entry.currency)}</p>:null}{canManage?<div className="mt-2 flex flex-wrap gap-2"><button onClick={async()=>setResult((await archiveFinanceEntryAction(entry.id)).message)} className="text-xs underline">Arşivle</button>{entry.documentFileId?<><StudioAiWritingDialog operation="payment_reminder" title="AI Ödeme Mesajı" triggerLabel="AI Mesaj" currentText={message} context={{title:entry.title,amount:money(entry.remaining,entry.currency),dueDate:entry.dueDate??""}} onUse={setMessage}/><button onClick={async()=>setResult((await sendFinanceWhatsAppAction(entry.id,message)).message)} className="text-xs font-semibold underline">WhatsApp ile Gönder</button></>:null}</div>:null}{result?<p role="status" className="mt-2 text-xs">{result}</p>:null}</div></article>}

export default function StudioFinanceDashboardView({data,section}:{data:FinanceDashboard;section:string}){
 if(!data.available)return <p role="status" className="rounded-xl border border-dashed p-6">Finans modülü henüz hazırlanmadı.</p>;
 const type=section==='incomes'?'income':section==='expenses'?'expense':section==='progress-payments'?'progress_payment':section==='invoices'?'invoice':null,filtered=type?data.entries.filter(x=>x.type===type):data.entries;
 return <div className="mt-6 space-y-6">{section==='overview'?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Toplam Gelir',data.summary.income],['Toplam Gider',data.summary.expense],['Bekleyen Tahsilat',data.summary.outstanding],['Bu Ay Tahsilat',data.summary.monthCollected],['Net Karlılık',data.summary.profit],['Nakit',data.summary.cash],['Bekleyen Hakediş',data.summary.pendingProgress]].map(([l,v])=><div key={String(l)} className="rounded-xl border bg-white p-5"><p className="text-sm text-[#68706f]">{l}</p><p className="mt-2 text-2xl font-semibold">{money(Number(v))}</p></div>)}<div className="rounded-xl border bg-white p-5"><p className="text-sm text-[#68706f]">En Karlı Proje</p><p className="mt-2 text-lg font-semibold">{data.summary.bestProject??'Henüz yok'}</p></div></div>:null}
 {section==='overview'?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Toplam Anlaşılan Proje Bedeli" value={money(data.summary.totalExpected)}/><Metric label="Toplam Tahsil Edilen" value={money(data.summary.totalCollected)}/><Metric label="Toplam Kalan Tahsilat" value={money(data.summary.totalOutstanding)}/><Metric label="Toplam Proje Gideri" value={money(data.summary.totalExpense)}/><Metric label="Ödenmiş Giderler" value={money(data.summary.paidExpense)}/><Metric label="Bekleyen Giderler" value={money(data.summary.pendingExpense)}/><Metric label="Toplam Brüt Kâr" value={money(data.summary.grossProfit)}/><Metric label="Ortalama Kâr Marjı" value={data.summary.averageMargin===null?'Henüz hesaplanamıyor':`%${data.summary.averageMargin.toFixed(1)}`}/><Metric label="Bu Ay Proje Gideri" value={money(data.summary.monthExpense)}/><Metric label="Bu Ay Tahsilat" value={money(data.summary.monthCollected)}/></div>:null}{data.canManage&&type?<EntryForm data={data} type={type}/>:null}{data.canManage&&section==='payments'?<PaymentForm data={data}/>:null}
 {section==='profitability'?<div className="grid gap-4 lg:grid-cols-2">{data.profitability.map(p=><article key={p.projectId} className="rounded-xl border bg-white p-5"><h3 className="text-lg font-semibold">{p.projectName}</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt>Beklenen Gelir</dt><dd>{money(p.expected)}</dd></div><div><dt>Gerçekleşen Gelir</dt><dd>{money(p.income)}</dd></div><div><dt>Toplam Gider + Harç</dt><dd>{money(p.expense)}</dd></div><div><dt>Kalan Tahsilat</dt><dd>{money(p.remaining)}</dd></div><div><dt>Net Karlılık</dt><dd>{money(p.profit)}</dd></div><div><dt>ROI</dt><dd>{p.roi===null?'—':`%${p.roi.toFixed(1)}`}</dd></div></dl></article>)}</div>:section==='cash-flow'?<div className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Nakit Akışı</h2><p className="mt-2 text-[15px]">Tahsilat {money(data.summary.collected)} · Gider {money(data.summary.expense)} · Net {money(data.summary.cash)}</p></div>:section==='reports'?<div className="flex flex-wrap gap-3 rounded-xl border bg-white p-5"><a href="/studio/finance/reports/export?format=pdf" className={studioButtonClass("outline","md")}>PDF</a><a href="/studio/finance/reports/export?format=xls" className={studioButtonClass("outline","md")}>Excel</a><a href="/studio/finance/reports/export?format=csv" className={studioButtonClass("outline","md")}>CSV</a></div>:<div className="overflow-hidden rounded-xl border bg-white"><div className="hidden grid-cols-[minmax(0,2fr)_1fr_1fr] gap-3 border-b bg-[#f7f4ee] p-4 text-sm font-semibold sm:grid"><span>Kayıt</span><span>Durum</span><span>Tutar</span></div>{filtered.length?filtered.map(x=><FinanceRow key={x.id} entry={x} canManage={data.canManage}/>):<p className="p-8 text-center">Bu bölümde henüz kayıt bulunmuyor.</p>}</div>}
 </div>;
}
