"use client";

import {useState} from "react";
import {cancelStudioPaymentRequestAction,createPublicPaymentLinkAction,createStudioPaymentRequestAction,reconcilePublicPaymentAction,refundStudioPaymentRequestAction,revokePublicPaymentLinkAction} from "@/app/studio/(protected)/projects/[projectId]/finance/actions";
import {studioButtonClass} from "@/components/studio/StudioButton";
import {StudioBadge,StudioCard,StudioEmptyState,StudioModal,StudioSectionHeader} from "@/components/studio/ui";
import type {StudioPaymentRequest} from "@/lib/payments/payment-request-types";
import type{StudioPublicPaymentLink}from"@/lib/payments/public-links";

const typeLabels={deposit:"Ön Ödeme",progress_payment:"Hakediş",final_payment:"Final Ödemesi",other:"Diğer"} as const;
const statusLabels={pending:"Bekliyor",paid:"Ödendi",cancelled:"İptal",refunded:"İade Edildi"} as const;
const statusVariant=(status:string)=>status==="paid"?"success" as const:status==="cancelled"?"danger" as const:"warning" as const;
const money=(amount:string,currency:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency}).format(Number(amount));
const date=(value:string|null)=>value?new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Istanbul"}).format(new Date(`${value}T12:00:00Z`)):"Belirtilmedi";
const paymentFormId="studio-payment-request-form";

export default function StudioPaymentRequests({projectId,canManage,requests,publicLinks}:{projectId:string;canManage:boolean;requests:StudioPaymentRequest[];publicLinks:StudioPublicPaymentLink[]}){
  const [open,setOpen]=useState(false);
  const [message,setMessage]=useState("");
  const[selected,setSelected]=useState<StudioPaymentRequest|null>(null),[knownUrls,setKnownUrls]=useState<Record<string,string>>({});
  const links=new Map(publicLinks.map(link=>[link.paymentRequestId,link]));
  const linkLabels={active:"Aktif",paid:"Ödendi",expired:"Süresi Doldu",revoked:"İptal Edildi"}as const;

  return <StudioCard className="mt-4 overflow-hidden p-0">
    <div className="p-4"><StudioSectionHeader title="Müşteri Ödeme Talepleri" description="Client Portal’da gösterilecek, proje kapsamlı ödeme talepleri" icon="payments" count={requests.length} action={canManage?<button type="button" onClick={()=>setOpen(true)} className={studioButtonClass("primary","sm")}>Ödeme Talebi Oluştur</button>:undefined}/></div>
    <div className="border-t border-[#edf0f2]">{requests.length?requests.map(request=><article key={request.id} className="grid min-w-0 items-center gap-3 border-b border-[#edf0f2] px-4 py-3 last:border-0 md:grid-cols-[minmax(0,1fr)_auto_auto_auto]">
      <div className="min-w-0"><h3 className="truncate text-[13px] font-semibold">{request.title}</h3><p className="mt-1 line-clamp-2 text-[11px] text-[#89939a]">{typeLabels[request.paymentType]} · Son ödeme: {date(request.dueDate)}</p>{request.description?<p className="mt-1 line-clamp-2 text-[11px] text-[#89939a]">{request.description}</p>:null}</div>
      <strong className="text-sm">{money(request.amount,request.currency)}</strong>
      <div className="flex flex-wrap items-center gap-2"><StudioBadge variant={statusVariant(request.status)}>{statusLabels[request.status]}</StudioBadge>{request.paymentProvider==="iyzico"?<span className="text-[11px] text-[#64748b]">iyzico ile tahsil edildi{request.installment&&request.installment>1?` · ${request.installment} taksit`:""}</span>:null}{request.paidPrice&&request.paidPrice!==request.amount?<span className="text-[11px] text-[#64748b]">Karttan çekilen: {money(request.paidPrice,request.currency)}</span>:null}{request.iyziCommissionRateAmount||request.iyziCommissionFee?<span className="text-[11px] text-[#64748b]">iyzico komisyonu: {money(String(Number(request.iyziCommissionRateAmount??0)+Number(request.iyziCommissionFee??0)),request.currency)}</span>:null}</div>
      <div className="flex flex-wrap justify-end gap-2">{links.get(request.id)?<StudioBadge variant={links.get(request.id)?.status==="active"?"success":links.get(request.id)?.status==="revoked"?"danger":"warning"}>{linkLabels[links.get(request.id)!.status]}</StudioBadge>:null}{canManage&&request.status==="pending"?<>{request.canReconcile?<button type="button" onClick={async()=>{const result=await reconcilePublicPaymentAction(projectId,request.id);setMessage(result.message)}} className={studioButtonClass("secondary","sm")}>Ödemeyi Doğrula</button>:null}{links.get(request.id)?.status==="active"&&knownUrls[request.id]?<button type="button" className={studioButtonClass("secondary","sm")} onClick={()=>navigator.clipboard.writeText(knownUrls[request.id])}>Ödeme Linkini Kopyala</button>:null}{links.get(request.id)?.status==="active"&&knownUrls[request.id]?<a className={studioButtonClass("secondary","sm")} target="_blank" rel="noreferrer" href={`https://wa.me/?text=${encodeURIComponent(`Merhaba,\nARZ Mimarlık ödeme bağlantınız:\n${knownUrls[request.id]}\n\nÖdeme tutarı:\n${money(request.amount,request.currency)}`)}`}>WhatsApp'ta Paylaş</a>:null}<button type="button" onClick={()=>setSelected(request)} className={studioButtonClass("primary","sm")}>{links.get(request.id)?.status==="active"?"Linki Yenile":"Ödeme Linki Oluştur"}</button>{links.get(request.id)?.status==="active"?<button type="button" onClick={async()=>{const result=await revokePublicPaymentLinkAction(projectId,request.id);setMessage(result.message)}} className={studioButtonClass("danger","sm")}>Linki İptal Et</button>:null}<form action={async()=>{const result=await cancelStudioPaymentRequestAction(projectId,request.id);setMessage(result.message)}}><button className={studioButtonClass("danger","sm")}>İptal Et</button></form></>:canManage&&request.status==="paid"&&request.paymentProvider==="iyzico"?<form action={async()=>{const result=await refundStudioPaymentRequestAction(projectId,request.id);setMessage(result.message)}}><button className={studioButtonClass("danger","sm")}>İade Et</button></form>:null}</div>
    </article>):<StudioEmptyState icon="payments" title="Ödeme talebi yok" description="Müşteri için henüz bir ödeme talebi oluşturulmadı."/>}</div>
    {message?<p role="status" className="border-t border-[#edf0f2] px-4 py-3 text-sm">{message}</p>:null}
    <StudioModal open={open} title="Ödeme Talebi Oluştur" onClose={()=>setOpen(false)} footer={<><button type="button" onClick={()=>setOpen(false)} className={studioButtonClass("secondary","md")}>Vazgeç</button><button type="submit" form={paymentFormId} className={studioButtonClass("primary","md")}>Kaydet</button></>}>
      <form id={paymentFormId} action={async form=>{const result=await createStudioPaymentRequestAction(projectId,form);setMessage(result.message);if(result.success)setOpen(false)}} className="grid gap-4 sm:grid-cols-2">
        <label className="text-sm font-semibold sm:col-span-2">Ödeme Başlığı<input name="title" required minLength={2} maxLength={180} className="studio-field mt-1 w-full" placeholder="2. Hakediş"/></label>
        <label className="text-sm font-semibold">Ödeme Türü<select name="paymentType" defaultValue="progress_payment" className="studio-field mt-1 w-full"><option value="deposit">Ön Ödeme</option><option value="progress_payment">Hakediş</option><option value="final_payment">Final Ödemesi</option><option value="other">Diğer</option></select></label>
        <label className="text-sm font-semibold">Tutar<input name="amount" required inputMode="decimal" pattern="[0-9]+([,.][0-9]{1,2})?" className="studio-field mt-1 w-full" placeholder="75000,00"/></label>
        <label className="text-sm font-semibold">Para Birimi<select name="currency" defaultValue="TRY" className="studio-field mt-1 w-full"><option value="TRY">TRY</option></select></label>
        <label className="text-sm font-semibold">Son Ödeme Tarihi<input name="dueDate" type="date" className="studio-field mt-1 w-full"/></label>
        <label className="text-sm font-semibold sm:col-span-2">Açıklama<textarea name="description" maxLength={4000} className="studio-field mt-1 min-h-24 w-full" placeholder="Mimari proje 2. hakediş ödemesi"/></label>
      </form>
    </StudioModal>
    <StudioModal open={Boolean(selected)} title="Ödeme Linki Oluştur" onClose={()=>setSelected(null)} footer={null}>{selected?<form action={async form=>{const result=await createPublicPaymentLinkAction(projectId,form);setMessage(result.message);if(result.success&&result.url){setKnownUrls(current=>({...current,[selected.id]:result.url!}));await navigator.clipboard.writeText(result.url).catch(()=>undefined);setSelected(null)}}} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="paymentRequestId" value={selected.id}/><div className="sm:col-span-2 rounded-xl bg-[#f4f6f7] p-3 text-sm"><strong>{selected.title}</strong><p>{money(selected.amount,selected.currency)}</p></div><label className="text-sm font-semibold">Ad<input required name="firstName" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Soyad<input required name="lastName" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Email<input required type="email" name="email" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Telefon<input required name="gsmNumber" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">TCKN / Kimlik No<input required inputMode="numeric" pattern="[0-9]{11}" name="identityNumber" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Son kullanım tarihi<input required type="date" name="expiresAt" defaultValue={new Date(Date.now()+30*86400000).toISOString().slice(0,10)} className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold sm:col-span-2">Adres<input required name="registrationAddress" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Şehir<input required name="city" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Ülke<input required name="country" defaultValue="Turkey" className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Posta kodu<input name="zipCode" className="studio-field mt-1 w-full"/></label><div className="flex justify-end sm:col-span-2"><button className={studioButtonClass("primary","md")}>Bağlantıyı Oluştur ve Kopyala</button></div></form>:null}</StudioModal>
  </StudioCard>;
}
