/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-html-link-for-pages -- server projection boundary and existing project navigation style. */
"use client";
import {useState} from "react";
import {createVisualizationRevisionAction,createVisualizationTimeEntryAction,saveProjectFinanceProfileAction} from "@/app/studio/(protected)/projects/[projectId]/finance/actions";
import StudioAiWritingDialog from "@/components/studio/ai/StudioAiWritingDialog";
import {studioButtonClass} from "@/components/studio/StudioButton";

const workTypes=["Modelleme","Kaplama / Materyal","Işıklandırma","Render Ayarları","Render Süresi","Photoshop / Post-prodüksiyon","Animasyon","Video Montaj","Revize","Toplantı","Diğer"];
const money=(n:number,currency:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency}).format(n);

export default function StudioVisualizationFinanceProfile({data}:{data:any}){
 const visual=data.visualization??{times:[],revisions:[],renders:[],totalHours:0,deliveredRenders:0,renderCount:0,renderVersionCount:0,usedRevisionCount:0,remainingIncludedRevisions:0,hourlyEarnings:null,costPerDeliveredRender:null,netProfit:0};
 const [message,setMessage]=useState(""); const [aiText,setAiText]=useState(""); const profile=data.profile; const currency=profile.currency;
 const cards:[string,number|string][]=[
  ["Anlaşılan Bedel",data.summary.agreedAmount],["Tahsil Edilen",data.summary.collected],["Kalan Tahsilat",data.summary.remainingCollection],["Toplam Görselleştirme Gideri",data.summary.totalExpense],["Ödenmiş Gider",data.summary.paidExpense],["Bekleyen Gider",data.summary.pendingExpense],["Net Kâr",visual.netProfit],["Kâr Marjı",data.summary.margin===null?"Henüz hesaplanamıyor":`%${data.summary.margin.toFixed(1)}`],["Toplam Çalışma Süresi",`${visual.totalHours.toFixed(1)} saat`],["Saatlik Kazanç",visual.hourlyEarnings===null?"Henüz hesaplanamıyor":money(visual.hourlyEarnings,currency)],["Teslim Edilen Render",visual.deliveredRenders],["Render Başına Maliyet",visual.costPerDeliveredRender===null?"Henüz hesaplanamıyor":money(visual.costPerDeliveredRender,currency)],
 ];
 const moneyLabels=new Set(["Anlaşılan Bedel","Tahsil Edilen","Kalan Tahsilat","Toplam Görselleştirme Gideri","Ödenmiş Gider","Bekleyen Gider","Net Kâr"]);
 return <div className="mt-6 space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><span className="rounded-full border border-[#b99654]/40 bg-[#fbf5e9] px-3 py-1 text-sm font-semibold text-[#765820]">Görselleştirme Finans Profili</span><a href="/studio/finance" className={studioButtonClass("secondary","sm")}>Tüm Şirket Finansını Aç</a></div>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Anlaşılan Bedel ve Sözleşme PDF</h2>{data.canManage?<form action={async f=>setMessage((await saveProjectFinanceProfileAction(data.project.id,f)).message)} className="mt-4 grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-semibold">Manuel proje bedeli<input name="agreedAmount" type="number" min="0" step="0.01" defaultValue={profile.agreedAmount||""} className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Para birimi<select name="currency" defaultValue={currency} className="studio-field mt-1 w-full"><option>TRY</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><label className="text-sm font-semibold">Sözleşme tarihi<input name="contractDate" type="date" defaultValue={profile.contractDate??""} className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Sözleşme PDF<select name="contractFileId" defaultValue={profile.contractFileId??""} className="studio-field mt-1 w-full"><option value="">Bağlanmadı</option>{data.files.filter((f:any)=>String(f.extension).toLowerCase()==="pdf").map((f:any)=><option key={f.id} value={f.id}>{f.display_name}</option>)}</select></label><label className="text-sm font-semibold sm:col-span-2 lg:col-span-4">Açıklama<textarea name="description" defaultValue={profile.description} maxLength={4000} className="studio-field mt-1 min-h-20 w-full"/></label><label className="text-sm font-semibold">Sözleşmeye dahil revize<input name="includedRevisionCount" type="number" min="0" defaultValue={profile.includedRevisionCount} className="studio-field mt-1 w-full"/></label><label className="text-sm font-semibold">Ek revize birim ücreti<input name="extraRevisionUnitPrice" type="number" min="0" step="0.01" defaultValue={profile.extraRevisionUnitPrice} className="studio-field mt-1 w-full"/></label><button className={studioButtonClass("primary","md")}>Bedel Kaydet</button></form>:<p className="mt-3">{money(profile.agreedAmount,currency)} · {profile.contractFileId?"Sözleşme PDF bağlı":"Sözleşme PDF bağlı değil"}</p>}{message?<p role="status" className="mt-3 text-sm">{message}</p>:null}</section>
  <section className="grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{cards.map(([label,value])=><article key={label} className="min-w-0 rounded-xl border bg-white p-4"><p className="text-sm text-[#68706f]">{label}</p><p className={`mt-2 break-words text-xl font-semibold ${typeof value==="number"&&value<0?"text-red-700":""}`}>{typeof value==="number"&&moneyLabels.has(label)?money(value,currency):value}</p></article>)}</section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Revize Durumu</h2><p className="mt-1 text-sm text-[#68706f]">{profile.includedRevisionCount} revize dahil · {visual.usedRevisionCount} kullanıldı · {visual.remainingIncludedRevisions?`${visual.remainingIncludedRevisions} ücretsiz revize kaldı`:"Sonraki revize ücretli"}</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b"><th className="py-2">No</th><th>Açıklama</th><th>Durum</th><th>Ücretsiz</th><th>Tutar</th></tr></thead><tbody>{visual.revisions.map((r:any)=><tr key={r.id} className="border-b"><td className="py-2">R{r.revision_number}</td><td>{r.description}</td><td>{r.status}</td><td>{r.is_included?"Evet":"Hayır"}</td><td>{money(Number(r.amount),currency)}</td></tr>)}</tbody></table></div>{data.canManage?<form action={async f=>setMessage((await createVisualizationRevisionAction(data.project.id,f)).message)} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input name="revisionNumber" required type="number" min="1" placeholder="Revize no" className="studio-field"/><input name="requestedAt" required type="date" className="studio-field"/><input name="description" required placeholder="Açıklama" className="studio-field lg:col-span-2"/><select name="isIncluded" defaultValue="true" className="studio-field"><option value="true">Ücretsiz</option><option value="false">Ücretli</option></select><input name="amount" type="number" min="0" step="0.01" placeholder="Tutar" className="studio-field"/><select name="status" defaultValue="requested" className="studio-field"><option value="requested">Bekliyor</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal</option></select><button className={studioButtonClass("primary","md")}>Revize Kaydet</button></form>:null}</section>
  <section className="grid min-w-0 gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Görselleştirme Giderleri</h2><p className="mt-3 text-sm text-[#68706f]">Toplam: {money(data.summary.totalExpense,currency)} · Ödenmiş: {money(data.summary.paidExpense,currency)}</p><div className="mt-3 divide-y">{data.expenses.map((e:any)=><p key={e.id} className="break-words py-3">{e.entryDate} · {e.category} · {money(e.amount,currency)}</p>)}</div>{data.canManage?<p className="mt-3 text-sm text-[#68706f]">Yeni gider mevcut Proje Finans gider akışı üzerinden eklenebilir.</p>:null}</section><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Çalışma Süresi</h2><p className="mt-3">Toplam: {visual.totalHours.toFixed(1)} saat</p>{data.canManage?<form action={async f=>setMessage((await createVisualizationTimeEntryAction(data.project.id,f)).message)} className="mt-3 grid gap-3 sm:grid-cols-2"><select name="workType" className="studio-field">{workTypes.map(x=><option key={x}>{x}</option>)}</select><input name="durationMinutes" required type="number" min="1" max="1440" placeholder="Dakika" className="studio-field"/><input name="workDate" required type="date" className="studio-field"/><input name="description" placeholder="Açıklama" className="studio-field"/><button className={studioButtonClass("primary","md")}>Süre Ekle</button></form>:null}<div className="mt-3 divide-y">{visual.times.map((t:any)=><p key={t.id} className="py-2 text-sm">{t.work_date} · {t.work_type} · {(Number(t.duration_minutes)/60).toFixed(1)} saat</p>)}</div></section></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Render Metrikleri</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><p>Arşiv: <strong>{visual.renderCount}</strong></p><p>Teslim: <strong>{visual.deliveredRenders}</strong></p><p>Versiyon: <strong>{visual.renderVersionCount}</strong></p><p>Müşteriye açık: <strong>{visual.renders.filter((r:any)=>r.is_client_visible).length}</strong></p></div></section>
  <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">AI Finans Özeti</h2><StudioAiWritingDialog operation="visualization_finance_summary" title="Görselleştirme finans özeti" triggerLabel="AI Özeti Oluştur" context={{projectName:data.project.name,agreedAmount:String(profile.agreedAmount),totalExpense:String(data.summary.totalExpense),totalHours:String(visual.totalHours),deliveredRenders:String(visual.deliveredRenders),margin:String(data.summary.margin??"")}} onUse={setAiText}/></div>{aiText?<p className="mt-3 whitespace-pre-wrap text-sm">{aiText}</p>:<p className="mt-2 text-sm text-[#68706f]">AI çıktısını oluşturmak için butonu kullanın.</p>}</section>
 </div>;
}
