import "server-only";
import {getStudioContext} from "@/lib/studio/auth/get-studio-context";
import {createStudioServerClient} from "@/lib/studio/supabase/server";
import {StudioFileError} from "../file-errors";
import {getDriveFileMetadata,getGoogleAccessToken} from "../storage/google-drive-provider";
import {finalizeInitialStudioFileVersion} from "../versions/version-repository";

type RawDriveFile={id:string;name:string;mimeType:string;size?:string;parents?:string[];trashed?:boolean;appProperties?:Record<string,string>};
const fields="id,name,mimeType,size,parents,trashed,appProperties";
const escapeDriveQuery=(value:string)=>value.replace(/['\\]/g,char=>`\\${char}`);

async function matchingReservationFiles(organizationId:string,parentId:string,reservationId:string){const token=await getGoogleAccessToken(organizationId);const query=[`'${escapeDriveQuery(parentId)}' in parents`,`trashed=false`,`appProperties has { key='reservation_id' and value='${escapeDriveQuery(reservationId)}' }`].join(" and ");const response=await fetch(`https://www.googleapis.com/drive/v3/files?spaces=drive&pageSize=3&fields=${encodeURIComponent(`files(${fields})`)}&q=${encodeURIComponent(query)}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok)throw new StudioFileError(response.status===401?"reauthorization_required":"storage","Google Drive yükleme doğrulaması tamamlanamadı.");return((await response.json()) as {files?:RawDriveFile[]}).files??[];}

export async function recoverInitialGoogleDriveUpload(projectId:string,fileId:string){const context=await getStudioContext();if(!context?.user||!context.membership)throw new StudioFileError("unauthorized","Oturum gerekli.");if(context.membership.role!=="owner")throw new StudioFileError("forbidden","Bu işlem yalnızca Studio sahibi tarafından yapılabilir.");const organizationId=context.membership.organization_id;const supabase=await createStudioServerClient();const{data:row,error}=await supabase.from("studio_project_files").select("id,project_id,organization_id,status,current_version_id,display_name,mime_type,file_size,external_file_id,external_parent_folder_id").eq("id",fileId).eq("project_id",projectId).eq("organization_id",organizationId).maybeSingle();if(error||!row)throw new StudioFileError("not_found","Yükleme rezervasyonu bulunamadı.");if(row.current_version_id&&row.status==="ready")return{completed:true as const};if(!row.external_parent_folder_id)throw new StudioFileError("storage","Yükleme hedef klasörü doğrulanamadı.");let candidates:RawDriveFile[]=[];if(row.external_file_id){const known=await getDriveFileMetadata(organizationId,row.external_file_id);candidates=[{id:known.id,name:known.name,mimeType:known.mimeType??"",size:String(known.size??0),parents:known.parents,trashed:known.trashed,appProperties:known.appProperties}];}else candidates=await matchingReservationFiles(organizationId,row.external_parent_folder_id,fileId);if(candidates.length!==1){await supabase.from("studio_project_files").update({sync_status:"action_required",sync_error_code:candidates.length?"upload_recovery_ambiguous":"upload_recovery_not_found"}).eq("id",fileId).eq("organization_id",organizationId);throw new StudioFileError("partial_sync",candidates.length?"Birden fazla Drive dosyası eşleşti. Otomatik tamamlama durduruldu.":"Drive dosyası henüz doğrulanamadı. Aynı yüklemeyi yeniden göndermeyin.");}const candidate=candidates[0];const valid=!candidate.trashed&&candidate.name===row.display_name&&candidate.mimeType===row.mime_type&&Number(candidate.size)===Number(row.file_size)&&candidate.parents?.includes(row.external_parent_folder_id)&&candidate.appProperties?.reservation_id===fileId&&candidate.appProperties?.organization_id===organizationId&&candidate.appProperties?.project_id===projectId;if(!valid){await supabase.from("studio_project_files").update({sync_status:"action_required",sync_error_code:"upload_recovery_metadata_mismatch"}).eq("id",fileId);throw new StudioFileError("partial_sync","Drive dosyası bulundu ancak yükleme bilgileri eşleşmedi.");}await finalizeInitialStudioFileVersion(projectId,fileId,candidate.id);return{completed:true as const};}
