"use client";
export type UploadProgress={uploaded:number;total:number};
export type DriveUploadMetadata={id:string};
const CHUNK_SIZE=8*1024*1024;
export class GoogleDriveUploadUncertainError extends Error{readonly status?:number;constructor(status?:number){super("Dosya Google Drive’a aktarılmış olabilir ancak ARZ Studio işlemi tamamlayamadı.");this.name="GoogleDriveUploadUncertainError";this.status=status;}}
function diagnostic(operation:string,value:{status?:number;responseReadable:boolean;externalFileId:boolean}){if(process.env.NODE_ENV==="development")console.info("STUDIO_DRIVE_UPLOAD_DIAGNOSTIC",{operation,...value,finalizeStarted:false});}
function uploadedOffset(response:Response,fallback=0){const match=response.headers.get("range")?.match(/-(\d+)$/);return match?Number(match[1])+1:fallback;}
async function readableMetadata(response:Response,operation:string){try{const value=await response.json() as Partial<DriveUploadMetadata>;diagnostic(operation,{status:response.status,responseReadable:true,externalFileId:Boolean(value.id)});return value.id?value as DriveUploadMetadata:null;}catch{diagnostic(operation,{status:response.status,responseReadable:false,externalFileId:false});return null;}}
export async function queryGoogleDriveUploadStatus(sessionUrl:string,totalSize:number,signal?:AbortSignal){try{const response=await fetch(sessionUrl,{method:"PUT",headers:{"Content-Length":"0","Content-Range":`bytes */${totalSize}`},signal});if(response.status===200||response.status===201)return{kind:"complete" as const,metadata:await readableMetadata(response,"resumable_status_complete")};if(response.status===308){diagnostic("resumable_status_incomplete",{status:308,responseReadable:true,externalFileId:false});return{kind:"incomplete" as const,offset:uploadedOffset(response)};}if(response.status===404||response.status===410)return{kind:"expired" as const,status:response.status};if(response.status===401||response.status===403)return{kind:"authorization" as const,status:response.status};return{kind:"error" as const,status:response.status};}catch{diagnostic("resumable_status_network_error",{responseReadable:false,externalFileId:false});return{kind:"network" as const};}}
export async function uploadToGoogleDriveSession(file:File,sessionUrl:string,onProgress:(progress:UploadProgress)=>void,signal?:AbortSignal,startWithStatusCheck=false){let offset=0;if(startWithStatusCheck){const status=await queryGoogleDriveUploadStatus(sessionUrl,file.size,signal);if(status.kind==="complete"){if(status.metadata)return status.metadata;throw new GoogleDriveUploadUncertainError(200);}if(status.kind==="incomplete")offset=status.offset;if(status.kind==="expired")throw new Error("Google Drive yükleme oturumunun süresi doldu. Yeni bir kontrollü yükleme başlatın.");if(status.kind==="authorization")throw new Error("Google Drive bağlantısının yeniden yetkilendirilmesi gerekiyor.");if(status.kind==="network")throw new GoogleDriveUploadUncertainError();}while(offset<file.size){if(signal?.aborted)throw new DOMException("İptal edildi","AbortError");const end=Math.min(offset+CHUNK_SIZE,file.size);const chunk=file.slice(offset,end);let response:Response;try{response=await fetch(sessionUrl,{method:"PUT",headers:{"Content-Length":String(chunk.size),"Content-Range":`bytes ${offset}-${end-1}/${file.size}`},body:chunk,signal});}catch{diagnostic("resumable_put_network_error",{responseReadable:false,externalFileId:false});const status=await queryGoogleDriveUploadStatus(sessionUrl,file.size,signal);if(status.kind==="complete"){if(status.metadata)return status.metadata;throw new GoogleDriveUploadUncertainError(200);}if(status.kind==="incomplete"){offset=status.offset;onProgress({uploaded:offset,total:file.size});continue;}throw new GoogleDriveUploadUncertainError("status" in status?status.status:undefined);}if(response.status===308){offset=uploadedOffset(response,end);onProgress({uploaded:offset,total:file.size});continue;}if(response.status===200||response.status===201){onProgress({uploaded:file.size,total:file.size});const metadata=await readableMetadata(response,"resumable_put_complete");if(metadata)return metadata;throw new GoogleDriveUploadUncertainError(response.status);}diagnostic("resumable_put_rejected",{status:response.status,responseReadable:true,externalFileId:false});if(response.status===401||response.status===403)throw new Error("Google Drive bağlantısının yeniden yetkilendirilmesi gerekiyor.");if(response.status===404||response.status===410)throw new Error("Google Drive yükleme oturumunun süresi doldu. Yeni bir kontrollü yükleme başlatın.");throw new Error("Google Drive yüklemesi geçici olarak tamamlanamadı.");}throw new GoogleDriveUploadUncertainError();}
